import {sealComponentManifest,validateAdapterContract,validateComponentManifest,type AdapterContract,type BlackBoxConformanceProvider,type ComponentManifestV2,type ConformanceLevel,type MigrationEdge,type NativeLiftAdapter,type NativeObservation,type StableCompilerPass} from '@open-autonomy/core';
export {createCompilerArtifact,runConformanceTck,runStableCompiler} from '@open-autonomy/core';
export type {AdapterContract,CompilerArtifact,ComponentManifestV2,ConformanceTestManifest,MigrationEdge,NativeLiftAdapter,NativeObservation,StableCompilerPass} from '@open-autonomy/core';

export interface ProviderHealthContract {check:string;healthyWhen:string;timeoutMs:number;intervalMs:number}
export interface ProviderLifecycleContract {provision:string;upgrade:string;rollback:string;teardown:string;upgradePrecondition:string;rollbackCriterion:string;teardownCriterion:string}
export interface OperationResult {status:'succeeded'|'failed'|'not-needed';criterion:string;evidence:Record<string,string>;recoveryRequired:boolean}
export interface ProviderOperations {provision(input:unknown):Promise<OperationResult>;health():Promise<OperationResult>;upgrade(input:unknown):Promise<OperationResult>;rollback(input:unknown):Promise<OperationResult>;teardown(input:unknown):Promise<OperationResult>}
export interface CredentialRequest {principal:string;scopes:string[];audience:string;ttlSeconds:number}
export interface CredentialLease {reference:string;principal:string;scopes:string[];audience:string;expiresAt:string}
export interface CredentialBroker {issue(request:Readonly<CredentialRequest>):Promise<CredentialLease>;revoke(reference:string):Promise<void>}
export interface ProviderConformanceHook {levels:ConformanceLevel[];operations:string[];invoke(operation:string,input:unknown):Promise<{output:unknown;evidence?:Record<string,string>}>}
export interface SubstrateProviderDefinition {id:string;version:string;manifest:ComponentManifestV2;adapters:AdapterContract[];passes:StableCompilerPass[];lifters:NativeLiftAdapter[];migrations:MigrationEdge[];health:ProviderHealthContract;lifecycle:ProviderLifecycleContract;operations:ProviderOperations;conformance:ProviderConformanceHook}

export function defineComponentManifest(value:ComponentManifestV2):Readonly<ComponentManifestV2>{const sealed=sealComponentManifest(value);const checked=validateComponentManifest(sealed);if(checked.errors.length)throw new Error(checked.errors.join('; '));return freeze(sealed);}
export function defineAdapter(value:AdapterContract,registry:Record<string,AdapterContract>={}):Readonly<AdapterContract>{const checked=validateAdapterContract(value,registry);if(checked.errors.length)throw new Error(checked.errors.join('; '));return freeze(structuredClone(value));}
export function defineProvider(value:SubstrateProviderDefinition):Readonly<SubstrateProviderDefinition>{
  if(value.id!==value.manifest.id||value.version!==value.manifest.version)throw new Error('provider identity must equal manifest identity');
  if(!value.health.healthyWhen||value.health.timeoutMs<=0||value.health.intervalMs<=0)throw new Error('provider requires a bounded positive health criterion and interval');
  for(const field of ['upgrade','rollback','teardown','upgradePrecondition','rollbackCriterion','teardownCriterion'] as const)if(!value.lifecycle[field])throw new Error(`provider lifecycle.${field} is required`);
  defineComponentManifest(value.manifest);for(const adapter of value.adapters)defineAdapter(adapter,Object.fromEntries(value.adapters.map(item=>[item.id,item])));
  if(!value.conformance.levels.includes('substrate'))throw new Error('provider conformance must include substrate level');
  for(const operation of ['provision','health','upgrade','rollback','teardown'] as const)if(typeof value.operations[operation]!=='function')throw new Error(`provider operation.${operation} is required`);
  for(const pass of value.passes)if(!validatedPasses.has(pass))throw new Error(`provider pass '${pass.id}' was not built by defineLoweringPass`);
  for(const lifter of value.lifters)if(!validatedLifters.has(lifter))throw new Error(`provider lifter '${lifter.id}' was not built by createNativeLifter`);
  for(const migration of value.migrations)if(!validatedMigrations.has(migration))throw new Error(`provider migration '${migration.id}' was not built by defineMigration`);
  const operations=Object.fromEntries((['provision','health','upgrade','rollback','teardown'] as const).map(operation=>{const raw=value.operations[operation];const expected=operation==='health'||operation==='provision'?value.health.healthyWhen:operation==='upgrade'?value.lifecycle.upgradePrecondition:operation==='rollback'?value.lifecycle.rollbackCriterion:value.lifecycle.teardownCriterion;return[operation,async(input?:unknown)=>validateOperationResult(operation,expected,await (raw as any)(structuredClone(input)))];})) as unknown as ProviderOperations;
  return freeze({...value,operations,manifest:structuredClone(value.manifest),adapters:structuredClone(value.adapters),passes:structuredClone(value.passes),migrations:[...value.migrations],lifters:[...value.lifters],health:structuredClone(value.health),lifecycle:structuredClone(value.lifecycle)});
}
export function conformanceProvider(definition:Readonly<SubstrateProviderDefinition>):BlackBoxConformanceProvider{return{id:definition.id,implementationVersion:definition.version,languageVersion:'2.0.0',levels:[...definition.conformance.levels],operations:[...definition.conformance.operations],async invoke(request){const result=await definition.conformance.invoke(request.operation,structuredClone(request.input));return{correlation:request.correlation,output:result.output,evidence:result.evidence};}};}
export async function executeProviderOperation(provider:Readonly<SubstrateProviderDefinition>,operation:keyof ProviderOperations,input?:unknown):Promise<OperationResult>{return provider.operations[operation](structuredClone(input));}
function validateOperationResult(operation:keyof ProviderOperations,expected:string,result:OperationResult):OperationResult{if(!result.criterion||result.criterion!==expected)throw new Error(`${operation} result criterion must equal '${expected}'`);if(!Object.keys(result.evidence).length)throw new Error(`${operation} result requires evidence`);if(result.status==='failed'&&!result.recoveryRequired)throw new Error(`${operation} failure must require recovery`);return freeze(structuredClone(result)) as OperationResult;}
export interface ScheduledFault {at:number;kind:'timeout'|'error'|'partition'|'duplicate'|'reorder';target:string;detail?:string}
export class DeterministicFaultScheduler {readonly #faults:ScheduledFault[];constructor(faults:ScheduledFault[]){this.#faults=structuredClone(faults).sort((a,b)=>a.at-b.at||a.target.localeCompare(b.target));}at(tick:number,target:string){return this.#faults.filter(x=>x.at===tick&&x.target===target).map(value=>structuredClone(value));}}
export interface TraceEntry {sequence:number;kind:string;correlation:string;value:unknown}
export class TraceRecorder {readonly #entries:TraceEntry[]=[];#bytes=0;truncated=false;constructor(readonly maxEntries=1000,readonly maxBytes=1_048_576){}record(kind:string,correlation:string,value:unknown){if(this.#entries.length>=this.maxEntries||!fits(value,this.maxBytes-this.#bytes)){this.truncated=true;return false;}try{const entry={sequence:this.#entries.length,kind,correlation,value:structuredClone(value)};const encoded=JSON.stringify(entry);if(encoded===undefined){this.truncated=true;return false;}const size=Buffer.byteLength(encoded);if(this.#bytes+size>this.maxBytes){this.truncated=true;return false;}this.#bytes+=size;this.#entries.push(freeze(entry) as TraceEntry);return true;}catch{this.truncated=true;return false;}}snapshot(){return freeze({entries:structuredClone(this.#entries),truncated:this.truncated,bytes:this.#bytes});}}
export class MemoryCredentialBroker implements CredentialBroker {readonly #leases=new Map<string,CredentialLease>();#nextReference=0;constructor(readonly now=()=>Date.now()){}async issue(request:Readonly<CredentialRequest>){if(request.ttlSeconds<=0)throw new Error('credential TTL must be positive');const reference=`credential:${this.#nextReference++}`;const lease={reference,...structuredClone(request),expiresAt:new Date(this.now()+request.ttlSeconds*1000).toISOString()};delete (lease as any).ttlSeconds;this.#leases.set(reference,lease);return structuredClone(lease);}async revoke(reference:string){this.#leases.delete(reference);}has(reference:string){return this.#leases.has(reference);}}
const validatedLifters=new WeakSet<object>(),validatedPasses=new WeakSet<object>(),validatedMigrations=new WeakSet<object>();
export function createNativeLifter(config:{id:string;provider:string;schema:string;version:string;portableTypes:string[];map(observation:NativeObservation):ReturnType<NativeLiftAdapter['lift']>}):NativeLiftAdapter{const {id,provider,schema,version,map}=config;const portableTypes=Object.freeze([...config.portableTypes]);const lifter=freeze<NativeLiftAdapter>({id,provider,nativeSchema:schema,nativeVersion:version,portableTypes:[...portableTypes],lift(observation){if(observation.provider!==provider||observation.schema!==schema||observation.version!==version)return undefined;const event=map(structuredClone(observation));if(!event||event.schema!=='autonomy.event.v2'||!portableTypes.includes(event.type)||!event.provenance?.some(item=>item.uri===observation.provenance.uri))throw new Error('lifter returned an undeclared event or discarded provenance');return event;}}) as NativeLiftAdapter;validatedLifters.add(lifter);return lifter;}
export function defineLoweringPass(value:StableCompilerPass,accounting:{sourceObligations:string[];losses:string[]}):Readonly<StableCompilerPass>{if(!['organization.lower','organization.emit'].includes(value.implementation))throw new Error('SDK lowering pass must use an audited lowering implementation');if(value.implementation==='organization.lower'&&!['organization-to-control','control-to-execution','execution-to-v1'].includes(String((value.configuration as any)?.phase)))throw new Error('organization.lower requires a supported configuration.phase');if(!accounting.sourceObligations.length)throw new Error('lowering pass requires source-obligation accounting');const pass=freeze({...structuredClone(value),accounting:structuredClone(accounting)}) as StableCompilerPass;validatedPasses.add(pass);return pass;}
export function defineMigration(value:MigrationEdge):Readonly<MigrationEdge>{if(!value.id||value.from===value.to)throw new Error('migration requires distinct versioned endpoints');const original=value.migrate;const edge=freeze({...value,migrate(document:Readonly<unknown>){const result=original(document);if(!result.dispositions.length)throw new Error('migration requires field dispositions');for(const pointer of removedPointers(document,result.document))if(!result.dispositions.some(item=>pointer===item.source||pointer.startsWith(`${item.source}/`)))throw new Error(`migration drops unaccounted field '${pointer}'`);return result;}}) as MigrationEdge;validatedMigrations.add(edge);return edge;}
export function compatibilityManifest(provider:Readonly<SubstrateProviderDefinition>){return freeze({schema:'autonomy.sdk-compatibility.v1',provider:provider.id,version:provider.version,levels:[...provider.conformance.levels].sort(),operations:[...provider.conformance.operations].sort(),facets:Object.values(provider.manifest.facets).map(x=>x.facet).sort(),adapters:provider.adapters.map(x=>x.id).sort(),migrations:provider.migrations.map(x=>x.id).sort()});}
export class ScriptedProviderDouble {readonly calls:Array<{operation:string;input:unknown}>=[];constructor(readonly responses:Record<string,unknown>={}){}async invoke(operation:string,input:unknown){this.calls.push({operation,input:structuredClone(input)});if(!(operation in this.responses))throw new Error(`unscripted operation '${operation}'`);return structuredClone(this.responses[operation]);}}
function freeze<T>(value:T):Readonly<T>{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.freeze(value);for(const child of Object.values(value as any))freeze(child);}return value;}
function removedPointers(before:unknown,after:unknown,path=''):string[]{if(JSON.stringify(before)===JSON.stringify(after))return[];if(Array.isArray(before)){if(!Array.isArray(after))return[path||'/'];return before.flatMap((value,index)=>index<after.length?removedPointers(value,after[index],`${path}/${index}`):[`${path}/${index}`]);}if(before&&typeof before==='object'){if(!after||typeof after!=='object'||Array.isArray(after))return[path||'/'];return Object.entries(before as Record<string,unknown>).flatMap(([key,value])=>{const pointer=`${path}/${key.replace(/~/g,'~0').replace(/\//g,'~1')}`;return key in (after as Record<string,unknown>)?removedPointers(value,(after as any)[key],pointer):[pointer];});}return[path||'/'];}
function fits(value:unknown,limit:number){let used=0;const active=new Set<object>();const visit=(item:unknown,depth:number):boolean=>{used+=8;if(used>limit||depth>100)return false;const primitive=typeof item;if(primitive==='string'){used+=Buffer.byteLength(item as string);return used<=limit;}if(primitive==='bigint'||primitive==='function'||primitive==='symbol'||primitive==='undefined'||(primitive==='number'&&!Number.isFinite(item)))return false;if(!item||primitive!=='object')return true;if(active.has(item))return false;active.add(item);const entries=Array.isArray(item)?item.map((child,index)=>[String(index),child] as const):Object.entries(item);for(const [key,child] of entries){used+=Buffer.byteLength(key);if(used>limit||!visit(child,depth+1)){active.delete(item);return false;}}active.delete(item);return true;};return visit(value,0);}
