import {describe,expect,test} from 'bun:test';
import {readFileSync} from 'node:fs';
import {HERMES_COMPONENT} from '@open-autonomy/core';
import {DeterministicFaultScheduler,MemoryCredentialBroker,ScriptedProviderDouble,TraceRecorder,compatibilityManifest,conformanceProvider,createNativeLifter,defineMigration,defineProvider,executeProviderOperation,type SubstrateProviderDefinition} from './index';

const toy=():SubstrateProviderDefinition=>({
  id:'toy-substrate',version:'1.0.0',manifest:{...structuredClone(HERMES_COMPONENT),id:'toy-substrate',version:'1.0.0',digest:undefined,signatures:undefined},adapters:[],passes:[],lifters:[],migrations:[],
  health:{check:'toy.health',healthyWhen:'response.ok == true',timeoutMs:1000,intervalMs:5000},
  lifecycle:{provision:'toy.provision',upgrade:'toy.upgrade',rollback:'toy.rollback',teardown:'toy.teardown',upgradePrecondition:'healthy',rollbackCriterion:'upgrade fails health',teardownCriterion:'no durable handles remain'},
  operations:{async provision(){return{status:'succeeded',criterion:'response.ok == true',evidence:{probe:'ok'},recoveryRequired:false};},async health(){return{status:'succeeded',criterion:'response.ok == true',evidence:{probe:'ok'},recoveryRequired:false};},async upgrade(){return{status:'succeeded',criterion:'healthy',evidence:{version:'2'},recoveryRequired:false};},async rollback(){return{status:'not-needed',criterion:'upgrade fails health',evidence:{reason:'healthy'},recoveryRequired:false};},async teardown(){return{status:'succeeded',criterion:'no durable handles remain',evidence:{handles:'0'},recoveryRequired:false};}},
  conformance:{levels:['component','substrate','live-runtime'],operations:['health','create','read','upgrade','rollback','teardown'],async invoke(operation,input){return{output:{operation,input,ok:true},evidence:{toy:'observed'}};}},
});
describe('R6 substrate SDK',()=>{
  test('builds an immutable nontrivial provider and deterministic compatibility declaration',async()=>{const provider=defineProvider(toy());expect(Object.isFrozen(provider)).toBe(true);expect(compatibilityManifest(provider)).toEqual(compatibilityManifest(provider));const observation=await conformanceProvider(provider).invoke({test:'health',operation:'health',correlation:'c',input:{}});expect(observation).toMatchObject({correlation:'c',output:{ok:true}});});
  test('requires recovery, rollback, teardown, and substrate conformance contracts',()=>{const invalid=toy();invalid.lifecycle.rollbackCriterion='';expect(()=>defineProvider(invalid)).toThrow('rollbackCriterion');invalid.lifecycle.rollbackCriterion='x';invalid.conformance.levels=[];expect(()=>defineProvider(invalid)).toThrow('substrate level');const interval=toy();interval.health.intervalMs=-1;expect(()=>defineProvider(interval)).toThrow('positive health');});
  test('validates executable lifecycle results and forbids bypassing registered migrations/lifters',async()=>{const invalid=toy();invalid.operations.upgrade=async()=>({status:'failed',criterion:'',evidence:{},recoveryRequired:false});const provider=defineProvider(invalid);await expect(provider.operations.upgrade({})).rejects.toThrow('criterion');const bypass=toy();bypass.migrations=[{id:'x',kind:'organization',from:'1',to:'2',migrate:()=>({document:{},dispositions:[]})}];expect(()=>defineProvider(bypass)).toThrow('defineMigration');const migration=defineMigration({id:'x',kind:'organization',from:'1',to:'2',migrate:()=>({document:{schema:'2',actors:[]},dispositions:[{source:'/schema',target:'/schema',disposition:'transformed'}]})});expect(()=>migration.migrate({schema:'1',actors:['a','b']})).toThrow('/actors/0');const lifter=createNativeLifter({id:'l',provider:'toy',schema:'native',version:'1',portableTypes:['work.started'],map:o=>({schema:'autonomy.event.v2',reducer:'r',id:o.id,type:'work.started',at:o.at,issuer:'toy',parents:[],epistemic:'observation',provenance:[o.provenance]})});expect(Object.isFrozen(lifter)).toBe(true);expect(()=>{(lifter as any).lift=()=>({schema:'evil'});}).toThrow();expect(lifter.lift({provider:'other',schema:'native',version:'1',id:'1',at:'x',data:{},provenance:{uri:'n'},authenticated:true})).toBeUndefined();});
  test('provides deterministic faults, bounded traces, doubles, and nonexpired opaque credentials',async()=>{const faults=new DeterministicFaultScheduler([{at:2,kind:'timeout',target:'read'},{at:1,kind:'error',target:'write'}]);expect(faults.at(2,'read')[0]?.kind).toBe('timeout');const trace=new TraceRecorder(1,1000);trace.record('request','c',{x:1});trace.record('response','c',{x:2});expect(trace.snapshot().entries[0]).toMatchObject({sequence:0,correlation:'c'});expect(trace.snapshot().truncated).toBe(true);const cyclic:any={};cyclic.self=cyclic;const cycleTrace=new TraceRecorder();expect(cycleTrace.record('cycle','c',cyclic)).toBe(false);expect(cycleTrace.record('bigint','c',1n)).toBe(false);expect(cycleTrace.snapshot().truncated).toBe(true);const double=new ScriptedProviderDouble({read:{value:1}});expect(await double.invoke('read',{})).toEqual({value:1});const broker=new MemoryCredentialBroker(()=>1_000_000);const lease=await broker.issue({principal:'worker',scopes:['repo:read'],audience:'toy',ttlSeconds:60});expect(Date.parse(lease.expiresAt)).toBe(1_060_000);expect(JSON.stringify(lease)).not.toContain('secret');await broker.revoke(lease.reference);expect(broker.has(lease.reference)).toBe(false);const replacement=await broker.issue({principal:'other',scopes:['repo:read'],audience:'toy',ttlSeconds:60});expect(replacement.reference).not.toBe(lease.reference);});
  test('snapshots caller-owned lifter and lifecycle definitions',async()=>{const config={id:'fixed',provider:'toy',schema:'native',version:'1',portableTypes:['work.started'],map:(o:any)=>({schema:'autonomy.event.v2' as const,reducer:'r',id:o.id,type:'work.started',at:o.at,issuer:'toy',parents:[],epistemic:'observation' as const,provenance:[o.provenance]})};const lifter=createNativeLifter(config);config.provider='evil';expect(lifter.lift({provider:'evil',schema:'native',version:'1',id:'1',at:'x',data:{},provenance:{uri:'n'},authenticated:true})).toBeUndefined();const source=toy();const provider=defineProvider(source);source.operations.upgrade=async()=>({status:'succeeded',criterion:'changed',evidence:{x:'x'},recoveryRequired:false});source.lifecycle.upgradePrecondition='changed';expect((await provider.operations.upgrade({})).criterion).toBe('healthy');});
  test('keeps dependency direction core <- SDK <- provider',()=>{for(const file of new Bun.Glob('packages/core/src/*.ts').scanSync('.')){const text=readFileSync(file,'utf8');expect(text).not.toMatch(/@open-autonomy\/sdk|packages\/sdk/);}expect(readFileSync('packages/sdk/package.json','utf8')).toContain('@open-autonomy/core');});
});
