#!/usr/bin/env bun
import{existsSync,readFileSync}from"node:fs";
import{acceptR21Collection,acceptR21CollectorIntent,acceptR21Evidence,acceptR21Registration,assembleR21,createR21State,expectedR21Cells,issueR21Collection,issueR21CollectorIntent,issueR21Evidence,issueR21Registration,loadR21State,saveR21Json,saveR21State,type R21Category,type R21Response}from"./r21-acquisition";
const COMMANDS=["init","status","issue-registration","accept-registration","issue-evidence","accept-evidence","issue-collector-intent","accept-collector-intent","issue-collection","accept-collection","assemble"]as const;type Command=typeof COMMANDS[number];
function parse(argv:string[]){const command=argv.shift()as Command,flags=new Map<string,string>();if(!(COMMANDS as readonly string[]).includes(command))throw Error(`usage: r21-acquire <${COMMANDS.join("|")}> [options]`);while(argv.length){const k=argv.shift()!,v=argv.shift();if(!k.startsWith("--")||v===undefined||flags.has(k))throw Error("R21 acquisition arguments invalid");flags.set(k,v)}const required=(k:string)=>{const v=flags.get(k);if(!v)throw Error(`R21 acquisition ${k} required`);return v};return{command,required}}
const json=(p:string)=>JSON.parse(readFileSync(p,"utf8"));
export async function runR21AcquisitionCli(argv:string[]){const{command,required}=parse([...argv]),statePath=required("--state");if(command==="init"){if(existsSync(statePath))throw Error("R21 acquisition state already exists");const s=createR21State(json(required("--registry")));saveR21State(statePath,s);return{campaignId:s.campaignId,manifestDigest:s.manifestDigest}}
  const s=loadR21State(statePath);if(command==="status"){let requiredCells:null|Record<string,number>=null;try{requiredCells=Object.fromEntries(Object.entries(expectedR21Cells(s)).map(([k,v])=>[k,v.length]))}catch{}return{campaignId:s.campaignId,registration:!!s.registration?.response,required:requiredCells,accepted:Object.fromEntries(Object.entries(s.evidence).map(([k,v])=>[k,Object.values(v).filter(x=>x.response).length])),collectorIntent:!!s.collectorIntent?.response,collection:!!s.collection?.response,assembledBundleDigest:s.assembledBundleDigest}}
  const response=()=>json(required("--response"))as R21Response,durable=(v:unknown)=>{saveR21State(statePath,s);saveR21Json(required("--out"),v)};let result:unknown;
  if(command==="issue-registration"){const v=issueR21Registration(s);durable(v);result={action:v.action}}else if(command==="accept-registration")result={responseDigest:acceptR21Registration(s,response())}
  else if(command==="issue-evidence"){const c=required("--category")as R21Category,id=required("--cell"),v=issueR21Evidence(s,c,id);durable(v);result={category:c,cell:id,ordinal:v.ordinal}}else if(command==="accept-evidence"){const c=required("--category")as R21Category,id=required("--cell");result={responseDigest:acceptR21Evidence(s,c,id,response())}}
  else if(command==="issue-collector-intent"){const v=issueR21CollectorIntent(s);durable(v);result={action:v.action}}else if(command==="accept-collector-intent")result={responseDigest:acceptR21CollectorIntent(s,response())}
  else if(command==="issue-collection"){const v=issueR21Collection(s);durable(v);result={candidateDigest:v.candidateDigest}}else if(command==="accept-collection")result={responseDigest:acceptR21Collection(s,response())}
  else{const c=assembleR21(s);durable(c);result={bundleDigest:s.assembledBundleDigest}}saveR21State(statePath,s);return result}
if(import.meta.main)runR21AcquisitionCli(process.argv.slice(2)).then(x=>console.log(JSON.stringify(x))).catch(e=>{console.error(e instanceof Error?e.message:e);process.exitCode=1});
