import { afterEach, describe, expect, test } from "bun:test";
import { createHash, generateKeyPairSync, sign } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { canonicalSemanticJson, signableR21Operator } from "@open-autonomy/core";
import { acceptR21Evidence, acceptR21Registration, createR21State, expectedR21Cells, issueR21CollectorIntent, issueR21Evidence,
  issueR21Registration, loadR21State, saveR21State, type R21Category, type R21Request, type R21Response, type R21State } from "./r21-acquisition";
import{runR21AcquisitionCli}from"./r21-acquisition-cli";

const dirs:string[]=[];afterEach(()=>{for(const d of dirs.splice(0))rmSync(d,{recursive:true,force:true})});
const hash=(x:unknown)=>`sha256:${createHash("sha256").update(canonicalSemanticJson(x)).digest("hex")}`as const;
function fixture(){const names=["reg","collector","telemetry","fault","lifecycle","custodian","billing-a","billing-b","operator"]as const,keys=Object.fromEntries(names.map(n=>[n,generateKeyPairSync("ed25519")]))as Record<typeof names[number],ReturnType<typeof generateKeyPairSync>>,
  publicKeys=Object.fromEntries(names.map(n=>[n,keys[n].publicKey.export({type:"spki",format:"pem"}).toString()])),state=createR21State({campaignId:"r21",createdAt:"2026-01-01T00:00:00Z",registrationKeyId:"reg",collectorKeyId:"collector",telemetryKeyId:"telemetry",faultKeyId:"fault",lifecycleKeyId:"lifecycle",custodianKeyId:"custodian",billingKeyIds:{a:"billing-a",b:"billing-b"},billingAssignments:{api:"a",worker:"b"},operatorKeyIds:{human:"operator"},publicKeys}),
  registration:any={campaignId:"r21",topologyDigest:hash("topology"),services:["api","worker"],regions:["east"],faults:["process"],lifecycle:["upgrade"],rampConcurrency:[1,2],minimumDistinctBillingAuthorities:2,minimumUnfamiliarOperators:1,registrationAuthority:{publicKeyPem:publicKeys.reg}},
  keyId=(q:R21Request)=>q.category==="services"?"telemetry":q.category==="faults"?"fault":q.category==="lifecycle"?"lifecycle":q.category==="billing"?({a:"billing-a",b:"billing-b"}as any)[q.signerId]:q.category==="operators"?"custodian":q.cellId==="registration"?"reg":"collector",
  respond=(q:R21Request,fragment:unknown):R21Response=>{const signerKeyId=keyId(q),body={schema:"open-autonomy.bench-r21-acquisition-response.v1"as const,requestDigest:hash(q),fragmentDigest:hash(fragment),signerKeyId,signedAt:"2026-01-02T00:00:00Z"};return{...body,signature:sign(null,Buffer.from(canonicalSemanticJson(body)),keys[signerKeyId as keyof typeof keys].privateKey).toString("base64"),fragment}};
  return{state,keys,registration,respond,publicKeys}}
function register(f:ReturnType<typeof fixture>){const q=issueR21Registration(f.state);acceptR21Registration(f.state,f.respond(q,f.registration))}
function row(f:ReturnType<typeof fixture>,c:R21Category,id:string):any{const parts=id.split("/").map(decodeURIComponent),base={campaignId:"r21",topologyDigest:f.registration.topologyDigest};if(c==="services")return{...base,service:parts[0],region:parts[1],phase:parts[2],concurrency:Number(parts[3])};if(c==="faults")return{...base,fault:parts[0],region:parts[1]};if(c==="lifecycle")return{...base,operation:parts[0],service:parts[1]};if(c==="billing")return{campaignId:"r21",service:parts[0],authority:f.state.billingAssignments[parts[0]!]};
  const op:any={campaignId:"r21",operatorId:parts[0],operatorSignature:{publicKeyPem:f.publicKeys.operator,signature:""},custodianSignature:{publicKeyPem:f.publicKeys.custodian,signature:""}};op.operatorSignature.signature=sign(null,Buffer.from(canonicalSemanticJson(signableR21Operator(op,"operatorSignature"))),f.keys.operator.privateKey).toString("base64");op.custodianSignature.signature=sign(null,Buffer.from(canonicalSemanticJson(signableR21Operator(op,"custodianSignature"))),f.keys.custodian.privateKey).toString("base64");return op}
function acceptAll(f:ReturnType<typeof fixture>,skip?:[R21Category,string]){const cells=expectedR21Cells(f.state);for(const c of Object.keys(cells)as R21Category[])for(const id of cells[c])if(!skip||skip[0]!==c||skip[1]!==id){const q=issueR21Evidence(f.state,c,id);acceptR21Evidence(f.state,c,id,f.respond(q,row(f,c,id)))}}

describe("R21 exact-cell external acquisition",()=>{
  test("derives every category domain and refuses incomplete final collection",()=>{const f=fixture();register(f);const cells=expectedR21Cells(f.state);expect(cells.services).toHaveLength(6);expect(cells.faults).toHaveLength(1);expect(cells.lifecycle).toHaveLength(2);expect(cells.billing).toHaveLength(2);expect(cells.operators).toEqual(["human"]);acceptAll(f,["faults",cells.faults[0]!]);expect(()=>issueR21CollectorIntent(f.state)).toThrow(/faults/)});
  test("rejects cell substitution, wrong authority, forgery, and equivocation",()=>{const f=fixture();register(f);const id=expectedR21Cells(f.state).services[0]!,q=issueR21Evidence(f.state,"services",id),valid=f.respond(q,row(f,"services",id));const changed:any=structuredClone(valid);changed.fragment.region="west";expect(()=>acceptR21Evidence(f.state,"services",id,changed)).toThrow(/substitution|binding/);expect(()=>acceptR21Evidence(f.state,"services",id,{...valid,signerKeyId:"fault"})).toThrow(/binding/);expect(()=>acceptR21Evidence(f.state,"services",id,{...valid,signature:Buffer.alloc(64).toString("base64")})).toThrow(/signature/);acceptR21Evidence(f.state,"services",id,valid);expect(()=>acceptR21Evidence(f.state,"services",id,f.respond(q,row(f,"services",id)))).not.toThrow()});
  test("revalidates pending exact-cell requests after restart",()=>{const f=fixture();register(f);const id=expectedR21Cells(f.state).billing[0]!,dir=mkdtempSync(join(tmpdir(),"oa-r21-"));dirs.push(dir);const path=join(dir,"state.json");issueR21Evidence(f.state,"billing",id);saveR21State(path,f.state);const resumed=loadR21State(path);resumed.evidence.billing[id]!.request.ordinal=99;expect(()=>saveR21State(path,resumed)).toThrow(/request drift/)});
  test("rejects renamed duplicate authority keys",()=>{const f=fixture();f.state.publicKeys.fault=f.state.publicKeys.telemetry!;expect(()=>createR21State({campaignId:"x",createdAt:f.state.createdAt,registrationKeyId:f.state.registrationKeyId,collectorKeyId:f.state.collectorKeyId,telemetryKeyId:f.state.telemetryKeyId,faultKeyId:f.state.faultKeyId,lifecycleKeyId:f.state.lifecycleKeyId,custodianKeyId:f.state.custodianKeyId,billingKeyIds:f.state.billingKeyIds,billingAssignments:f.state.billingAssignments,operatorKeyIds:f.state.operatorKeyIds,publicKeys:f.state.publicKeys})).toThrow(/cryptographically distinct/)});
  test("CLI persists registration issuance before request exposure",async()=>{const f=fixture(),dir=mkdtempSync(join(tmpdir(),"oa-r21-cli-"));dirs.push(dir);const statePath=join(dir,"state.json"),registryPath=join(dir,"registry.json"),out=join(dir,"request.json"),{schema:_,checkpoint:__,manifestDigest:___,evidence:____,assembledBundleDigest:_____,...registry}=f.state;writeFileSync(registryPath,JSON.stringify(registry));await runR21AcquisitionCli(["init","--state",statePath,"--registry",registryPath]);await runR21AcquisitionCli(["issue-registration","--state",statePath,"--out",out]);expect(JSON.parse(readFileSync(out,"utf8")).action).toBe("registration");expect(loadR21State(statePath).registration).toBeDefined()});
});
