import{createHash,createPublicKey,verify}from"node:crypto";import{closeSync,fsyncSync,openSync,readFileSync,renameSync,writeFileSync}from"node:fs";import{dirname,resolve}from"node:path";
import{canonicalSemanticJson,R22_COST_DIMENSIONS,R22_CUSTODY_ATTACKS,signableR22Campaign,signableR22Cost,signableR22Criterion,signableR22Enrollment,signableR22Rating,type R22Analysis,type R22Campaign,type R22Cost,type R22CriterionAttestation,type R22CustodyAttack,type R22Enrollment,type R22Rating,type R22Registration,type R22TrialObservation}from"@open-autonomy/core";
type D=`sha256:${string}`;export type R22Kind="criteria"|"enrollments"|"trials"|"attacks"|"ratings"|"costs";type Role="workload"|"environment"|"scorer"|"privacy"|"cost";const KINDS:R22Kind[]=["criteria","enrollments","trials","attacks","ratings","costs"],ROLES:Role[]=["workload","environment","scorer","privacy","cost"],h=(x:unknown):D=>`sha256:${createHash("sha256").update(canonicalSemanticJson(x)).digest("hex")}`,fp=(p:string)=>createHash("sha256").update(createPublicKey(p).export({type:"spki",format:"der"})).digest("hex"),cell=(...x:string[])=>x.map(encodeURIComponent).join("/"),parts=(x:string)=>x.split("/").map(decodeURIComponent),MANIFEST={version:1,order:["registration","criteria","enrollments","trials-and-attacks","ratings-and-costs","analysis","collector-intent","collection"]};
const exact=(x:object,k:string[],n:string)=>{if(Object.keys(x).sort().join("\0")!==[...k].sort().join("\0"))throw Error(`R22 acquisition ${n} schema invalid`)};
export type R22Request={schema:"open-autonomy.bench-r22-acquisition-request.v1";checkpoint:"R22";campaignId:string;action:"registration"|"evidence"|"analysis"|"collector-intent"|"collection";kind:R22Kind|null;cellId:string;signerId:string;manifestDigest:D;ordinal:number;descriptorDigest:D|null;prerequisiteDigests:D[];candidateDigest:D|null};
export type R22Response={schema:"open-autonomy.bench-r22-acquisition-response.v1";requestDigest:D;fragmentDigest:D;signerKeyId:string;signedAt:string;signature:string;fragment:unknown};type X={request:R22Request;response?:R22Response};
export type R22State={schema:"open-autonomy.bench-r22-acquisition-state.v1";checkpoint:"R22";campaignId:string;createdAt:string;manifestDigest:D;registrationKeyId:string;collectorKeyId:string;criterionKeyIds:Record<Role,string>;raterKeyIds:Record<string,string>;trialCustodianKeyId:string;attackCustodianKeyId:string;publicKeys:Record<string,string>;registration?:X;evidence:Record<R22Kind,Record<string,X>>;analysis?:X;collectorIntent?:X;collection?:X;assembledBundleDigest:D|null};
function registry(s:Pick<R22State,"registrationKeyId"|"collectorKeyId"|"criterionKeyIds"|"raterKeyIds"|"trialCustodianKeyId"|"attackCustodianKeyId"|"publicKeys">){if(Object.keys(s.criterionKeyIds).sort().join()!==[...ROLES].sort().join()||!Object.keys(s.raterKeyIds).length)throw Error("R22 acquisition authority registry incomplete");const ids=[s.registrationKeyId,s.collectorKeyId,...Object.values(s.criterionKeyIds),...Object.values(s.raterKeyIds),s.trialCustodianKeyId,s.attackCustodianKeyId];if(ids.some(i=>!i||!s.publicKeys[i])||new Set(ids).size!==ids.length)throw Error("R22 acquisition authority keys aliased or missing");let f:string[];try{f=ids.map(i=>fp(s.publicKeys[i]!))}catch{throw Error("R22 acquisition public key invalid")}if(new Set(f).size!==f.length)throw Error("R22 acquisition public keys must be cryptographically distinct")}
const accepted=(x:X|undefined,n:string)=>{if(!x?.response)throw Error(`R22 acquisition ${n} response missing`);return x.response},registration=(s:R22State)=>accepted(s.registration,"registration").fragment as R22Registration;
function key(s:R22State,q:R22Request){if(q.action==="registration")return s.registrationKeyId;if(q.action==="collector-intent"||q.action==="collection")return s.collectorKeyId;if(q.action==="analysis")return s.criterionKeyIds.scorer;if(q.kind==="criteria")return s.criterionKeyIds[q.signerId as Role];if(q.kind==="enrollments")return s.criterionKeyIds.privacy;if(q.kind==="ratings")return s.raterKeyIds[q.signerId];if(q.kind==="costs")return s.criterionKeyIds.cost;if(q.kind==="trials")return s.trialCustodianKeyId;return s.attackCustodianKeyId}
const request=(s:R22State,x:Omit<R22Request,"schema"|"checkpoint"|"campaignId"|"manifestDigest">):R22Request=>({schema:"open-autonomy.bench-r22-acquisition-request.v1",checkpoint:"R22",campaignId:s.campaignId,manifestDigest:s.manifestDigest,...x});
function checkReq(s:R22State,q:R22Request){exact(q,["schema","checkpoint","campaignId","action","kind","cellId","signerId","manifestDigest","ordinal","descriptorDigest","prerequisiteDigests","candidateDigest"],"request");if(q.schema!=="open-autonomy.bench-r22-acquisition-request.v1"||q.checkpoint!=="R22"||q.campaignId!==s.campaignId||q.manifestDigest!==s.manifestDigest||!q.signerId||!Number.isSafeInteger(q.ordinal)||q.ordinal<0||!q.prerequisiteDigests.every(x=>/^sha256:[a-f0-9]{64}$/.test(x))||(q.descriptorDigest!==null&&!/^sha256:[a-f0-9]{64}$/.test(q.descriptorDigest))||(q.candidateDigest!==null&&!/^sha256:[a-f0-9]{64}$/.test(q.candidateDigest))||!key(s,q))throw Error("R22 acquisition request invalid")}
function checkRes(s:R22State,x:X){const r=x.response;if(!r)return;exact(r,["schema","requestDigest","fragmentDigest","signerKeyId","signedAt","signature","fragment"],"response");const kid=key(s,x.request);if(r.schema!=="open-autonomy.bench-r22-acquisition-response.v1"||r.requestDigest!==h(x.request)||r.fragmentDigest!==h(r.fragment)||r.signerKeyId!==kid||!Number.isFinite(Date.parse(r.signedAt))||Date.parse(r.signedAt)<Date.parse(s.createdAt))throw Error("R22 acquisition response binding invalid");const b={schema:r.schema,requestDigest:r.requestDigest,fragmentDigest:r.fragmentDigest,signerKeyId:r.signerKeyId,signedAt:r.signedAt};if(!verify(null,Buffer.from(canonicalSemanticJson(b)),s.publicKeys[kid]!,Buffer.from(r.signature,"base64")))throw Error("R22 acquisition response signature invalid")}
function accept(s:R22State,x:X,r:R22Response){if(s.assembledBundleDigest)throw Error("R22 acquisition already assembled");if(x.response&&canonicalSemanticJson(x.response)!==canonicalSemanticJson(r))throw Error("R22 acquisition equivocation rejected");checkRes(s,{request:x.request,response:r});x.response=r;return h(r)}
function live(s:R22State){if(s.schema!=="open-autonomy.bench-r22-acquisition-state.v1"||s.checkpoint!=="R22"||s.manifestDigest!==h(MANIFEST)||s.assembledBundleDigest)throw Error("R22 acquisition state is not mutable")}
export function createR22State(i:Omit<R22State,"schema"|"checkpoint"|"manifestDigest"|"registration"|"evidence"|"analysis"|"collectorIntent"|"collection"|"assembledBundleDigest">):R22State{if(!i.campaignId||!Number.isFinite(Date.parse(i.createdAt)))throw Error("R22 acquisition identity invalid");registry(i);return{...i,schema:"open-autonomy.bench-r22-acquisition-state.v1",checkpoint:"R22",manifestDigest:h(MANIFEST),evidence:{criteria:{},enrollments:{},trials:{},attacks:{},ratings:{},costs:{}},assembledBundleDigest:null}}
export function issueR22Registration(s:R22State){live(s);const q=request(s,{action:"registration",kind:null,cellId:"registration",signerId:"registration",ordinal:0,descriptorDigest:null,prerequisiteDigests:[],candidateDigest:null});s.registration??={request:q};return s.registration.request}
function validRegistration(s:R22State,r:R22Registration){if(!r||r.campaignId!==s.campaignId||r.authority?.publicKeyPem!==s.publicKeys[s.registrationKeyId]||canonicalSemanticJson([...r.raterIds].sort())!==canonicalSemanticJson(Object.keys(s.raterKeyIds).sort()))throw Error("R22 acquisition registration fragment invalid")}
export function acceptR22Registration(s:R22State,r:R22Response){live(s);if(!s.registration)throw Error("R22 acquisition registration request missing");validRegistration(s,r.fragment as R22Registration);return accept(s,s.registration,r)}
export function expectedR22Cells(s:R22State,r=registration(s)):Record<R22Kind,string[]>{return{criteria:ROLES.map(x=>cell(x)),enrollments:r.raterIds.map(x=>cell(x)),trials:r.trials.map(x=>cell(x.trialId)),attacks:[...R22_CUSTODY_ATTACKS].map(x=>cell(x)),ratings:r.raterIds.flatMap(a=>r.itemIds.map(b=>cell(a,b))),costs:r.trials.flatMap(t=>R22_COST_DIMENSIONS.map(d=>cell(t.trialId,d)))}}
function desc(s:R22State,k:R22Kind,id:string,r=registration(s)):any{const p=parts(id);if(k==="criteria")return{role:p[0]};if(k==="enrollments")return{raterId:p[0]};if(k==="trials")return r.trials.find(x=>x.trialId===p[0]);if(k==="attacks")return{attack:p[0]};if(k==="ratings")return{raterId:p[0],itemId:p[1]};return{trialId:p[0],dimension:p[1]}}
function prereqs(s:R22State,k:R22Kind,d:any):D[]{const rr=h(accepted(s.registration,"registration"));if(k==="criteria")return[rr];if(k==="enrollments")return[rr,h(accepted(s.evidence.criteria[cell("privacy")],"privacy criterion"))];if(k==="trials"||k==="attacks")return[rr,...ROLES.map(x=>h(accepted(s.evidence.criteria[cell(x)],`${x} criterion`)))];if(k==="ratings")return[rr,h(accepted(s.evidence.enrollments[cell(d.raterId)],`enrollment ${d.raterId}`))];return[rr,h(accepted(s.evidence.criteria[cell("cost")],"cost criterion")),h(accepted(s.evidence.trials[cell(d.trialId)],`trial ${d.trialId}`))]}
function signerId(k:R22Kind,d:any){return k==="criteria"?d.role:k==="enrollments"?"privacy":k==="ratings"?d.raterId:k==="costs"?"cost":k==="trials"?"trial-custodian":"attack-custodian"}
export function issueR22Evidence(s:R22State,k:R22Kind,id:string){live(s);const cells=expectedR22Cells(s),ordinal=cells[k].indexOf(id);if(ordinal<0)throw Error("R22 acquisition cell is not preregistered");const d=desc(s,k,id),q=request(s,{action:"evidence",kind:k,cellId:id,signerId:signerId(k,d),ordinal:ordinal+1,descriptorDigest:h(d),prerequisiteDigests:prereqs(s,k,d),candidateDigest:null}),old=s.evidence[k][id];if(old&&canonicalSemanticJson(old.request)!==canonicalSemanticJson(q))throw Error("R22 acquisition evidence request drift");s.evidence[k][id]??={request:q};return s.evidence[k][id]!.request}
function embedded(body:unknown,pem:string,signature:string){return verify(null,Buffer.from(canonicalSemanticJson(body)),pem,Buffer.from(signature,"base64"))}
function validEvidence(s:R22State,k:R22Kind,id:string,x:any){const d=desc(s,k,id);if(!x)throw Error("R22 acquisition evidence fragment invalid");if(k==="criteria"){if(x.role!==d.role||x.signature?.publicKeyPem!==s.publicKeys[s.criterionKeyIds[d.role as Role]]||!embedded(signableR22Criterion(x),x.signature.publicKeyPem,x.signature.signature))throw Error("R22 acquisition criterion invalid")}else if(k==="enrollments"){if(x.raterId!==d.raterId||x.signature?.publicKeyPem!==s.publicKeys[s.criterionKeyIds.privacy]||!embedded(signableR22Enrollment(x),x.signature.publicKeyPem,x.signature.signature))throw Error("R22 acquisition enrollment invalid")}else if(k==="trials"){if(x.campaignId!==s.campaignId||x.trialId!==d.trialId||x.blockId!==d.blockId||x.itemId!==d.itemId||x.arm!==d.arm)throw Error("R22 acquisition trial substitution")}else if(k==="attacks"){if(x.campaignId!==s.campaignId||x.attack!==d.attack)throw Error("R22 acquisition attack substitution")}else if(k==="ratings"){const pem=s.publicKeys[s.raterKeyIds[d.raterId]];if(x.campaignId!==s.campaignId||x.raterId!==d.raterId||x.itemId!==d.itemId||x.signature?.publicKeyPem!==pem||!embedded(signableR22Rating(x),pem!,x.signature.signature))throw Error("R22 acquisition rating invalid")}else{const pem=s.publicKeys[s.criterionKeyIds.cost];if(x.trialId!==d.trialId||x.dimension!==d.dimension||x.signature?.publicKeyPem!==pem||!embedded(signableR22Cost(x),pem!,x.signature.signature))throw Error("R22 acquisition cost invalid")}}
export function acceptR22Evidence(s:R22State,k:R22Kind,id:string,r:R22Response){live(s);const x=s.evidence[k]?.[id];if(!x)throw Error("R22 acquisition evidence request missing");validEvidence(s,k,id,r.fragment);return accept(s,x,r)}
function rows<T>(s:R22State,k:R22Kind){return expectedR22Cells(s)[k].map(id=>accepted(s.evidence[k][id],`${k} ${id}`).fragment as T)}
type Summary=Omit<R22Analysis,"costs">;function allDigests(s:R22State){return KINDS.flatMap(k=>expectedR22Cells(s)[k].map(id=>h(accepted(s.evidence[k][id],`${k} ${id}`))))}
export function issueR22Analysis(s:R22State){live(s);const q=request(s,{action:"analysis",kind:null,cellId:"analysis",signerId:"scorer",ordinal:0,descriptorDigest:null,prerequisiteDigests:allDigests(s),candidateDigest:null});s.analysis??={request:q};return s.analysis.request}
function validSummary(x:Summary){if(!x||Object.keys(x).sort().join()!=="blockEffects,ci95,costTotals,estimand,simulatorScores,transferRmse,variance")throw Error("R22 acquisition analysis summary invalid")}
export function acceptR22Analysis(s:R22State,r:R22Response){live(s);if(!s.analysis)throw Error("R22 acquisition analysis request missing");validSummary(r.fragment as Summary);return accept(s,s.analysis,r)}
type Intent=Omit<R22Campaign["collector"],"signature">;export function issueR22CollectorIntent(s:R22State){live(s);const q=request(s,{action:"collector-intent",kind:null,cellId:"collector-intent",signerId:"collector",ordinal:0,descriptorDigest:null,prerequisiteDigests:[h(accepted(s.analysis,"analysis"))],candidateDigest:null});s.collectorIntent??={request:q};return s.collectorIntent.request}
function validIntent(s:R22State,x:Intent){if(!x||Object.keys(x).sort().join()!=="publicKeyPem,signedAt,signerId"||x.publicKeyPem!==s.publicKeys[s.collectorKeyId]||!x.signerId||!Number.isFinite(Date.parse(x.signedAt)))throw Error("R22 acquisition collector intent invalid")}
export function acceptR22CollectorIntent(s:R22State,r:R22Response){live(s);if(!s.collectorIntent)throw Error("R22 acquisition collector intent missing");validIntent(s,r.fragment as Intent);return accept(s,s.collectorIntent,r)}
function draft(s:R22State,signature:string):R22Campaign{const summary=accepted(s.analysis,"analysis").fragment as Summary;return{schema:"autonomy.r22-external-campaign.v1",closureClaim:true,registration:registration(s),criterionAttestations:rows<R22CriterionAttestation>(s,"criteria"),enrollments:rows<R22Enrollment>(s,"enrollments"),trials:rows<R22TrialObservation>(s,"trials"),custodyAttacks:rows<R22CustodyAttack>(s,"attacks"),ratings:rows<R22Rating>(s,"ratings"),analysis:{...summary,costs:rows<R22Cost>(s,"costs")},collector:{...(accepted(s.collectorIntent,"collector intent").fragment as Intent),signature}}}
export function issueR22Collection(s:R22State){live(s);const q=request(s,{action:"collection",kind:null,cellId:"collection",signerId:"collector",ordinal:0,descriptorDigest:null,prerequisiteDigests:[h(accepted(s.collectorIntent,"collector intent"))],candidateDigest:h(signableR22Campaign(draft(s,"")))});s.collection??={request:q};return s.collection.request}
function validCollection(s:R22State,x:any){const c=draft(s,x?.campaignSignature??""),pem=s.publicKeys[s.collectorKeyId]!;if(!x||Object.keys(x).join()!=="campaignSignature"||!embedded(signableR22Campaign(c),pem,x.campaignSignature??""))throw Error("R22 acquisition campaign signature invalid")}
export function acceptR22Collection(s:R22State,r:R22Response){live(s);if(!s.collection)throw Error("R22 acquisition collection missing");validCollection(s,r.fragment);return accept(s,s.collection,r)}
export function assembleR22(s:R22State){assertR22State(s);const sig=(accepted(s.collection,"collection").fragment as any).campaignSignature,c=draft(s,sig),d=h(c);if(s.assembledBundleDigest&&s.assembledBundleDigest!==d)throw Error("R22 acquisition assembly drift");s.assembledBundleDigest=d;return c}
export function assertR22State(s:R22State){exact(s,["schema","checkpoint","campaignId","createdAt","manifestDigest","registrationKeyId","collectorKeyId","criterionKeyIds","raterKeyIds","trialCustodianKeyId","attackCustodianKeyId","publicKeys","registration","evidence","analysis","collectorIntent","collection","assembledBundleDigest"].filter(x=>x in s),"state");if(s.schema!=="open-autonomy.bench-r22-acquisition-state.v1"||s.checkpoint!=="R22"||!s.campaignId||!Number.isFinite(Date.parse(s.createdAt))||s.manifestDigest!==h(MANIFEST))throw Error("R22 acquisition state invalid");registry(s);if(Object.keys(s.evidence).sort().join()!==[...KINDS].sort().join())throw Error("R22 acquisition evidence registry invalid");const check=(x:X|undefined)=>{if(!x)return;checkReq(s,x.request);checkRes(s,x)};check(s.registration);for(const k of KINDS)Object.values(s.evidence[k]).forEach(check);check(s.analysis);check(s.collectorIntent);check(s.collection);
  if(s.registration){const er=request(s,{action:"registration",kind:null,cellId:"registration",signerId:"registration",ordinal:0,descriptorDigest:null,prerequisiteDigests:[],candidateDigest:null});if(canonicalSemanticJson(er)!==canonicalSemanticJson(s.registration.request))throw Error("R22 acquisition registration request drift");if(s.registration.response){validRegistration(s,s.registration.response.fragment as R22Registration);const cells=expectedR22Cells(s);for(const k of KINDS)for(const[id,x]of Object.entries(s.evidence[k])){const ordinal=cells[k].indexOf(id),d=desc(s,k,id);if(ordinal<0)throw Error("R22 acquisition unregistered stored cell");const q=request(s,{action:"evidence",kind:k,cellId:id,signerId:signerId(k,d),ordinal:ordinal+1,descriptorDigest:h(d),prerequisiteDigests:prereqs(s,k,d),candidateDigest:null});if(canonicalSemanticJson(q)!==canonicalSemanticJson(x.request))throw Error("R22 acquisition evidence request drift");if(x.response)validEvidence(s,k,id,x.response.fragment)}}else if(KINDS.some(k=>Object.keys(s.evidence[k]).length))throw Error("R22 acquisition evidence before registration")}
  if(s.analysis){const q=request(s,{action:"analysis",kind:null,cellId:"analysis",signerId:"scorer",ordinal:0,descriptorDigest:null,prerequisiteDigests:allDigests(s),candidateDigest:null});if(canonicalSemanticJson(q)!==canonicalSemanticJson(s.analysis.request))throw Error("R22 acquisition analysis request drift");if(s.analysis.response)validSummary(s.analysis.response.fragment as Summary)}if(s.collectorIntent){const q=request(s,{action:"collector-intent",kind:null,cellId:"collector-intent",signerId:"collector",ordinal:0,descriptorDigest:null,prerequisiteDigests:[h(accepted(s.analysis,"analysis"))],candidateDigest:null});if(canonicalSemanticJson(q)!==canonicalSemanticJson(s.collectorIntent.request))throw Error("R22 acquisition collector intent drift");if(s.collectorIntent.response)validIntent(s,s.collectorIntent.response.fragment as Intent)}if(s.collection){const q=request(s,{action:"collection",kind:null,cellId:"collection",signerId:"collector",ordinal:0,descriptorDigest:null,prerequisiteDigests:[h(accepted(s.collectorIntent,"collector intent"))],candidateDigest:h(signableR22Campaign(draft(s,"")))});if(canonicalSemanticJson(q)!==canonicalSemanticJson(s.collection.request))throw Error("R22 acquisition collection request drift");if(s.collection.response)validCollection(s,s.collection.response.fragment)}if(s.assembledBundleDigest!==null){const sig=(accepted(s.collection,"collection").fragment as any).campaignSignature;if(s.assembledBundleDigest!==h(draft(s,sig)))throw Error("R22 acquisition assembled state invalid")}return s}
export function saveR22State(path:string,s:R22State){assertR22State(s);saveR22Json(path,s)}export function saveR22Json(path:string,v:unknown){const t=resolve(path),tmp=`${t}.tmp-${process.pid}`;writeFileSync(tmp,`${canonicalSemanticJson(v)}\n`,{flag:"wx",mode:0o600});const f=openSync(tmp,"r");try{fsyncSync(f)}finally{closeSync(f)}renameSync(tmp,t);const d=openSync(dirname(t),"r");try{fsyncSync(d)}finally{closeSync(d)}}export function loadR22State(path:string){return assertR22State(JSON.parse(readFileSync(path,"utf8"))as R22State)}
