#!/usr/bin/env bun
import{existsSync,readFileSync}from"node:fs";
import{acceptR22Analysis,acceptR22Collection,acceptR22CollectorIntent,acceptR22Evidence,acceptR22Registration,assembleR22,createR22State,expectedR22Cells,issueR22Analysis,issueR22Collection,issueR22CollectorIntent,issueR22Evidence,issueR22Registration,loadR22State,saveR22Json,saveR22State,type R22Kind,type R22Response}from"./r22-acquisition";
const COMMANDS=["init","status","issue-registration","accept-registration","issue-evidence","accept-evidence","issue-analysis","accept-analysis","issue-collector-intent","accept-collector-intent","issue-collection","accept-collection","assemble"]as const;type Command=typeof COMMANDS[number];
function parse(argv:string[]){const command=argv.shift()as Command,flags=new Map<string,string>();if(!(COMMANDS as readonly string[]).includes(command))throw Error(`usage: r22-acquire <${COMMANDS.join("|")}> [options]`);while(argv.length){const k=argv.shift()!,v=argv.shift();if(!k.startsWith("--")||v===undefined||flags.has(k))throw Error("R22 acquisition arguments invalid");flags.set(k,v)}const required=(k:string)=>{const v=flags.get(k);if(!v)throw Error(`R22 acquisition ${k} required`);return v};return{command,required}}
const json=(p:string)=>JSON.parse(readFileSync(p,"utf8"));
export async function runR22AcquisitionCli(argv:string[]){const{command,required}=parse([...argv]),statePath=required("--state");if(command==="init"){if(existsSync(statePath))throw Error("R22 acquisition state already exists");const s=createR22State(json(required("--registry")));saveR22State(statePath,s);return{campaignId:s.campaignId,manifestDigest:s.manifestDigest}}
  const s=loadR22State(statePath);if(command==="status"){let requiredCells:null|Record<string,number>=null;try{requiredCells=Object.fromEntries(Object.entries(expectedR22Cells(s)).map(([k,v])=>[k,v.length]))}catch{}return{campaignId:s.campaignId,registration:!!s.registration?.response,required:requiredCells,accepted:Object.fromEntries(Object.entries(s.evidence).map(([k,v])=>[k,Object.values(v).filter(x=>x.response).length])),analysis:!!s.analysis?.response,collectorIntent:!!s.collectorIntent?.response,collection:!!s.collection?.response,assembledBundleDigest:s.assembledBundleDigest}}
  const response=()=>json(required("--response"))as R22Response,durable=(v:unknown)=>{saveR22State(statePath,s);saveR22Json(required("--out"),v)};let result:unknown;
  if(command==="issue-registration"){const v=issueR22Registration(s);durable(v);result={action:v.action}}else if(command==="accept-registration")result={responseDigest:acceptR22Registration(s,response())}
  else if(command==="issue-evidence"){const k=required("--kind")as R22Kind,id=required("--cell"),v=issueR22Evidence(s,k,id);durable(v);result={kind:k,cell:id,ordinal:v.ordinal}}else if(command==="accept-evidence"){const k=required("--kind")as R22Kind,id=required("--cell");result={responseDigest:acceptR22Evidence(s,k,id,response())}}
  else if(command==="issue-analysis"){const v=issueR22Analysis(s);durable(v);result={prerequisites:v.prerequisiteDigests.length}}else if(command==="accept-analysis")result={responseDigest:acceptR22Analysis(s,response())}
  else if(command==="issue-collector-intent"){const v=issueR22CollectorIntent(s);durable(v);result={action:v.action}}else if(command==="accept-collector-intent")result={responseDigest:acceptR22CollectorIntent(s,response())}
  else if(command==="issue-collection"){const v=issueR22Collection(s);durable(v);result={candidateDigest:v.candidateDigest}}else if(command==="accept-collection")result={responseDigest:acceptR22Collection(s,response())}
  else{const c=assembleR22(s);durable(c);result={bundleDigest:s.assembledBundleDigest}}saveR22State(statePath,s);return result}
if(import.meta.main)runR22AcquisitionCli(process.argv.slice(2)).then(x=>console.log(JSON.stringify(x))).catch(e=>{console.error(e instanceof Error?e.message:e);process.exitCode=1});
