import{afterEach,describe,expect,test}from"bun:test";import{createHash,generateKeyPairSync,sign}from"node:crypto";import{mkdtempSync,readFileSync,rmSync,writeFileSync}from"node:fs";import{tmpdir}from"node:os";import{join}from"node:path";
import{canonicalSemanticJson,signableR22Criterion}from"@open-autonomy/core";import{acceptR22Evidence,acceptR22Registration,createR22State,issueR22Analysis,issueR22Evidence,issueR22Registration,loadR22State,saveR22State,type R22Request,type R22Response}from"./r22-acquisition";import{runR22AcquisitionCli}from"./r22-acquisition-cli";
const dirs:string[]=[];afterEach(()=>dirs.splice(0).forEach(d=>rmSync(d,{recursive:true,force:true})));const hash=(x:unknown)=>`sha256:${createHash("sha256").update(canonicalSemanticJson(x)).digest("hex")}`as const;
function fixture(){const ids=["registration","collector","workload","environment","scorer","privacy","cost","rater","trial","attack"],keys=Object.fromEntries(ids.map(id=>[id,generateKeyPairSync("ed25519")]))as Record<string,ReturnType<typeof generateKeyPairSync>>,publicKeys=Object.fromEntries(ids.map(id=>[id,keys[id]!.publicKey.export({type:"spki",format:"pem"}).toString()])),state=createR22State({campaignId:"r22",createdAt:"2026-01-01T00:00:00Z",registrationKeyId:"registration",collectorKeyId:"collector",criterionKeyIds:{workload:"workload",environment:"environment",scorer:"scorer",privacy:"privacy",cost:"cost"},raterKeyIds:{alice:"rater"},trialCustodianKeyId:"trial",attackCustodianKeyId:"attack",publicKeys}),respond=(q:R22Request,fragment:unknown):R22Response=>{const body={schema:"open-autonomy.bench-r22-acquisition-response.v1"as const,requestDigest:hash(q),fragmentDigest:hash(fragment),signerKeyId:q.action==="registration"?"registration":q.action==="analysis"?"scorer":q.signerId==="trial-custodian"?"trial":q.signerId==="attack-custodian"?"attack":q.signerId==="alice"?"rater":q.signerId,signedAt:"2026-01-02T00:00:00Z"};return{...body,signature:sign(null,Buffer.from(canonicalSemanticJson(body)),keys[body.signerKeyId]!.privateKey).toString("base64"),fragment}},registration:any={campaignId:"r22",raterIds:["alice"],itemIds:["item/1"],trials:[],authority:{publicKeyPem:publicKeys.registration}};return{state,keys,publicKeys,respond,registration}}
function register(f:ReturnType<typeof fixture>){const q=issueR22Registration(f.state);acceptR22Registration(f.state,f.respond(q,f.registration))}function criterion(f:ReturnType<typeof fixture>,role:"workload"|"environment"|"scorer"|"privacy"|"cost"){const x:any={role,digest:hash(role),signature:{signerId:role,publicKeyPem:f.publicKeys[role],signedAt:"2026-01-02T00:00:00Z",signature:""}};x.signature.signature=sign(null,Buffer.from(canonicalSemanticJson(signableR22Criterion(x))),f.keys[role]!.privateKey).toString("base64");return x}
describe("R22 causally ordered external acquisition",()=>{
 test("enforces prerequisites and matrix completeness",()=>{const f=fixture();register(f);expect(()=>issueR22Evidence(f.state,"enrollments","alice")).toThrow(/privacy criterion/);expect(()=>issueR22Analysis(f.state)).toThrow(/criteria/);for(const role of["workload","environment","scorer","privacy","cost"]as const){const q=issueR22Evidence(f.state,"criteria",role);acceptR22Evidence(f.state,"criteria",role,f.respond(q,criterion(f,role)))}expect(()=>issueR22Analysis(f.state)).toThrow(/enrollments/) });
 test("rejects substitution, wrong signer, forgery, and equivocation",()=>{const f=fixture();register(f);const q=issueR22Evidence(f.state,"criteria","workload"),valid=f.respond(q,criterion(f,"workload")),changed:any=structuredClone(valid);changed.fragment.role="privacy";expect(()=>acceptR22Evidence(f.state,"criteria","workload",changed)).toThrow(/criterion|binding/);expect(()=>acceptR22Evidence(f.state,"criteria","workload",{...valid,signerKeyId:"privacy"})).toThrow(/binding/);expect(()=>acceptR22Evidence(f.state,"criteria","workload",{...valid,signature:Buffer.alloc(64).toString("base64")})).toThrow(/signature/);acceptR22Evidence(f.state,"criteria","workload",valid);const other:any=structuredClone(valid);other.signedAt="2026-01-03T00:00:00Z";expect(()=>acceptR22Evidence(f.state,"criteria","workload",other)).toThrow(/equivocation/) });
 test("revalidates pending causal requests after restart",()=>{const f=fixture();register(f);const dir=mkdtempSync(join(tmpdir(),"oa-r22-"));dirs.push(dir);const path=join(dir,"state.json");issueR22Evidence(f.state,"criteria","privacy");saveR22State(path,f.state);const resumed=loadR22State(path);resumed.evidence.criteria.privacy!.request.ordinal=99;expect(()=>saveR22State(path,resumed)).toThrow(/request drift/) });
 test("rejects renamed duplicate cryptographic authorities",()=>{const f=fixture(),bad={...f.state.publicKeys,attack:f.state.publicKeys.trial!};expect(()=>createR22State({campaignId:"x",createdAt:f.state.createdAt,registrationKeyId:"registration",collectorKeyId:"collector",criterionKeyIds:f.state.criterionKeyIds,raterKeyIds:f.state.raterKeyIds,trialCustodianKeyId:"trial",attackCustodianKeyId:"attack",publicKeys:bad})).toThrow(/cryptographically distinct/) });
 test("CLI persists issuance before exposing a request",async()=>{const f=fixture(),dir=mkdtempSync(join(tmpdir(),"oa-r22-cli-"));dirs.push(dir);const statePath=join(dir,"state.json"),registryPath=join(dir,"registry.json"),out=join(dir,"request.json"),{schema:_,checkpoint:__,manifestDigest:___,evidence:____,assembledBundleDigest:_____,...registry}=f.state;writeFileSync(registryPath,JSON.stringify(registry));await runR22AcquisitionCli(["init","--state",statePath,"--registry",registryPath]);await runR22AcquisitionCli(["issue-registration","--state",statePath,"--out",out]);expect(JSON.parse(readFileSync(out,"utf8")).action).toBe("registration");expect(loadR22State(statePath).registration).toBeDefined() });
});
