import { afterEach, describe, expect, test } from "bun:test";
import { createHash, generateKeyPairSync, sign } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os"; import { join } from "node:path";
import { canonicalSemanticJson, signableR23Normalization, signableR23Registration } from "@open-autonomy/core";
import { acceptR23Evidence, acceptR23Registration, createR23State, issueR23Evidence, issueR23Registration, issueR23Summary, loadR23State, saveR23State, type R23Request, type R23Response } from "./r23-acquisition";
import { runR23AcquisitionCli } from "./r23-acquisition-cli";
const dirs: string[] = []; afterEach(() => dirs.splice(0).forEach((d) => rmSync(d, { recursive: true, force: true })));
const hash = (x: unknown) => `sha256:${createHash("sha256").update(canonicalSemanticJson(x)).digest("hex")}` as const;
function fixture() { const ids = ["registration", "collector", "privacy", "event", "normalization", "p1", "p2", "h1", "h2"], keys = Object.fromEntries(ids.map((id) => [id, generateKeyPairSync("ed25519")])) as Record<string, ReturnType<typeof generateKeyPairSync>>, publicKeys = Object.fromEntries(ids.map((id) => [id, keys[id]!.publicKey.export({ type: "spki", format: "pem" }).toString()])), state = createR23State({ campaignId: "r23", createdAt: "2026-01-01T00:00:00Z", registrationKeyId: "registration", collectorKeyId: "collector", privacyKeyId: "privacy", eventKeyId: "event", normalizationKeyId: "normalization", providerKeyIds: { p1: "p1", p2: "p2" }, humanKeyIds: { h1: "h1", h2: "h2" }, publicKeys }), registration: any = { schema: "autonomy.r23-external-registration.v1", campaignId: "r23", dependencies: { R18: hash("18"), R20: hash("20"), R22: hash("22") }, workIds: ["w"], workValues: { w: 1 }, analysisPlan: { minimumTerminalWork: 2, studentTDegreesFreedom: 1, studentTCritical95: 12.706, transferDegreesFreedom: 3, transferTCritical95: 3.182 }, simulatorTimings: { "w:t": 1 }, providerIds: ["p1", "p2"], humanIds: ["h1", "h2"], taskIds: ["t"], attemptsPerWork: 1, horizon: { startsAt: "2026-01-01T00:00:01Z", endsAt: "2026-01-01T00:00:09Z" }, workloadDigest: hash("work"), normalizationDigest: hash([]), privacyDigest: hash("privacy"), authority: { signerId: "registration", publicKeyPem: publicKeys.registration, signedAt: "2026-01-01T00:00:00Z", signature: "" } };
  registration.authority.signature = sign(null, Buffer.from(canonicalSemanticJson(signableR23Registration(registration))), keys.registration!.privateKey).toString("base64");
  const respond = (q: R23Request, fragment: unknown, override?: string): R23Response => { const signerKeyId = override ?? (q.action === "registration" ? "registration" : q.kind === "normalization" ? "normalization" : q.signerId === "event" ? "event" : q.signerId), body = { schema: "open-autonomy.bench-r23-acquisition-response.v1" as const, requestDigest: hash(q), fragmentDigest: hash(fragment), signerKeyId, signedAt: "2026-01-01T00:00:09Z" }; return { ...body, signature: sign(null, Buffer.from(canonicalSemanticJson(body)), keys[signerKeyId]!.privateKey).toString("base64"), fragment }; };
  return { state, keys, publicKeys, registration, respond }; }
function register(f: ReturnType<typeof fixture>) { const q = issueR23Registration(f.state); acceptR23Registration(f.state, f.respond(q, f.registration)); }
function normalization(f: ReturnType<typeof fixture>) { const x: any = { schema: "autonomy.r23-normalization-registry.v1", entries: [], digest: hash([]), signature: { signerId: "normalization", publicKeyPem: f.publicKeys.normalization, signedAt: "2026-01-01T00:00:00Z", signature: "" } }; x.signature.signature = sign(null, Buffer.from(canonicalSemanticJson(signableR23Normalization(x))), f.keys.normalization!.privateKey).toString("base64"); return x; }
describe("R23 exact accounting-product acquisition", () => {
  test("requires registered provider selection and causal predecessors", () => { const f = fixture(); register(f); expect(() => issueR23Evidence(f.state, "attempts", "w/0")).toThrow(/provider required/); expect(() => issueR23Evidence(f.state, "attempts", "w/0", "unknown")).toThrow(/provider required/); expect(() => issueR23Evidence(f.state, "works", "w")).toThrow(/attempts/); expect(() => issueR23Evidence(f.state, "usage", "w/0/p1/tokens")).toThrow(/normalization/); expect(() => issueR23Summary(f.state)).toThrow(/normalization/); });
  test("rejects substitution, authority changes, forgery, and equivocation", () => { const f = fixture(); register(f); const q = issueR23Evidence(f.state, "normalization", "registry"), valid = f.respond(q, normalization(f)), changed: any = structuredClone(valid); changed.fragment.digest = hash("other"); expect(() => acceptR23Evidence(f.state, "normalization", "registry", changed)).toThrow(/binding|signature|normalization/); expect(() => acceptR23Evidence(f.state, "normalization", "registry", { ...valid, signerKeyId: "p1" })).toThrow(/binding/); expect(() => acceptR23Evidence(f.state, "normalization", "registry", { ...valid, signature: Buffer.alloc(64).toString("base64") })).toThrow(/signature/); acceptR23Evidence(f.state, "normalization", "registry", valid); const other: any = structuredClone(valid); other.signedAt = "2026-01-01T00:00:08Z"; expect(() => acceptR23Evidence(f.state, "normalization", "registry", other)).toThrow(/equivocation/); });
  test("revalidates immutable provider assignment after restart", () => { const f = fixture(); register(f); const dir = mkdtempSync(join(tmpdir(), "oa-r23-")); dirs.push(dir); const path = join(dir, "state.json"); issueR23Evidence(f.state, "attempts", "w/0", "p1"); saveR23State(path, f.state); const resumed = loadR23State(path); resumed.evidence.attempts["w/0"]!.request.signerId = "p2"; expect(() => saveR23State(path, resumed)).toThrow(/request drift/); });
  test("rejects renamed duplicate cryptographic identities", () => { const f = fixture(), bad = { ...f.state.publicKeys, p2: f.state.publicKeys.p1! }; expect(() => createR23State({ campaignId: "x", createdAt: f.state.createdAt, registrationKeyId: "registration", collectorKeyId: "collector", privacyKeyId: "privacy", eventKeyId: "event", normalizationKeyId: "normalization", providerKeyIds: { p1: "p1", p2: "p2" }, humanKeyIds: { h1: "h1", h2: "h2" }, publicKeys: bad })).toThrow(/cryptographically distinct/); });
  test("CLI persists issuance before exposing its request", async () => { const f = fixture(), dir = mkdtempSync(join(tmpdir(), "oa-r23-cli-")); dirs.push(dir); const statePath = join(dir, "state.json"), registryPath = join(dir, "registry.json"), out = join(dir, "request.json"), { schema: _, checkpoint: __, manifestDigest: ___, evidence: ____, assembledBundleDigest: _____, ...registry } = f.state; writeFileSync(registryPath, JSON.stringify(registry)); await runR23AcquisitionCli(["init", "--state", statePath, "--registry", registryPath]); await runR23AcquisitionCli(["issue-registration", "--state", statePath, "--out", out]); expect(JSON.parse(readFileSync(out, "utf8")).action).toBe("registration"); expect(loadR23State(statePath).registration).toBeDefined(); });
});
