#!/usr/bin/env bun
import { existsSync, readFileSync } from "node:fs";
import { acceptR23Collection, acceptR23CollectorIntent, acceptR23Evidence, acceptR23Registration, acceptR23Summary, assembleR23, createR23State, expectedR23Cells, issueR23Collection, issueR23CollectorIntent, issueR23Evidence, issueR23Registration, issueR23Summary, loadR23State, saveR23Json, saveR23State, type R23Kind, type R23Response } from "./r23-acquisition";
const COMMANDS = ["init", "status", "issue-registration", "accept-registration", "issue-evidence", "accept-evidence", "issue-summary", "accept-summary", "issue-collector-intent", "accept-collector-intent", "issue-collection", "accept-collection", "assemble"] as const;
type Command = typeof COMMANDS[number];
function parse(argv: string[]) { const command = argv.shift() as Command, flags = new Map<string, string>(); if (!(COMMANDS as readonly string[]).includes(command)) throw Error(`usage: r23-acquire <${COMMANDS.join("|")}> [options]`); while (argv.length) { const k = argv.shift()!, v = argv.shift(); if (!k.startsWith("--") || v === undefined || flags.has(k)) throw Error("R23 acquisition arguments invalid"); flags.set(k, v); } const required = (k: string) => { const v = flags.get(k); if (!v) throw Error(`R23 acquisition ${k} required`); return v; }; return { command, required, optional: (k: string) => flags.get(k) }; }
const json = (path: string) => JSON.parse(readFileSync(path, "utf8"));
export async function runR23AcquisitionCli(argv: string[]) { const { command, required, optional } = parse([...argv]), statePath = required("--state"); if (command === "init") { if (existsSync(statePath)) throw Error("R23 acquisition state already exists"); const s = createR23State(json(required("--registry"))); saveR23State(statePath, s); return { campaignId: s.campaignId, manifestDigest: s.manifestDigest }; }
  const s = loadR23State(statePath); if (command === "status") { let requiredCells: null | Record<string, number> = null; try { requiredCells = Object.fromEntries(Object.entries(expectedR23Cells(s)).map(([k, v]) => [k, v.length])); } catch {} return { campaignId: s.campaignId, registration: !!s.registration?.response, required: requiredCells, accepted: Object.fromEntries(Object.entries(s.evidence).map(([k, v]) => [k, Object.values(v).filter((x) => x.response).length])), summary: !!s.summary?.response, collectorIntent: !!s.collectorIntent?.response, collection: !!s.collection?.response, assembledBundleDigest: s.assembledBundleDigest }; }
  const response = () => json(required("--response")) as R23Response, durable = (value: unknown) => { saveR23State(statePath, s); saveR23Json(required("--out"), value); }; let result: unknown;
  if (command === "issue-registration") { const q = issueR23Registration(s); durable(q); result = { action: q.action }; } else if (command === "accept-registration") result = { responseDigest: acceptR23Registration(s, response()) };
  else if (command === "issue-evidence") { const kind = required("--kind") as R23Kind, id = required("--cell"), q = issueR23Evidence(s, kind, id, optional("--provider")); durable(q); result = { kind, cell: id, ordinal: q.ordinal, signerId: q.signerId }; } else if (command === "accept-evidence") { const kind = required("--kind") as R23Kind, id = required("--cell"); result = { responseDigest: acceptR23Evidence(s, kind, id, response()) }; }
  else if (command === "issue-summary") { const q = issueR23Summary(s); durable(q); result = { prerequisites: q.prerequisiteDigests.length }; } else if (command === "accept-summary") result = { responseDigest: acceptR23Summary(s, response()) };
  else if (command === "issue-collector-intent") { const q = issueR23CollectorIntent(s); durable(q); result = { action: q.action }; } else if (command === "accept-collector-intent") result = { responseDigest: acceptR23CollectorIntent(s, response()) };
  else if (command === "issue-collection") { const q = issueR23Collection(s); durable(q); result = { candidateDigest: q.candidateDigest }; } else if (command === "accept-collection") result = { responseDigest: acceptR23Collection(s, response()) };
  else { const campaign = assembleR23(s); durable(campaign); result = { bundleDigest: s.assembledBundleDigest }; } saveR23State(statePath, s); return result;
}
if (import.meta.main) runR23AcquisitionCli(process.argv.slice(2)).then((x) => console.log(JSON.stringify(x))).catch((e) => { console.error(e instanceof Error ? e.message : e); process.exitCode = 1; });
