import { createHash, createPublicKey, verify } from "node:crypto";
import { closeSync, fsyncSync, openSync, readFileSync, renameSync, writeFileSync } from "node:fs"; import { dirname, resolve } from "node:path";
import { canonicalSemanticJson, deriveR24DifferenceInventory, type ClosureSigned, type R24ExternalCampaign, type R24PreregistrationBody } from "@open-autonomy/core";
type V5MatchedBundle = R24ExternalCampaign["bundle"];
type D = `sha256:${string}`; export type R24Kind = "equivalence" | "triage" | "dependencies"; const KINDS: R24Kind[] = ["equivalence", "triage", "dependencies"], DEPENDENCIES = ["R15", "R16", "R21", "R22", "R23"] as const, LOCK_PATHS = ["isolation", "credential-scope", "provider-revision", "provider-config", "provider-command"];
const hash = (x: unknown): D => `sha256:${createHash("sha256").update(canonicalSemanticJson(x)).digest("hex")}`, fingerprint = (pem: string) => createHash("sha256").update(createPublicKey(pem).export({ type: "spki", format: "der" })).digest("hex"), cell = (...xs: string[]) => xs.map(encodeURIComponent).join("/"), parts = (x: string) => x.split("/").map(decodeURIComponent), MANIFEST = { version: 1, order: ["preregistration", "bundle", "equivalence-and-dependencies", "triage", "closure"] };
export type R24Request = { schema: "open-autonomy.bench-r24-acquisition-request.v1"; checkpoint: "R24"; campaignId: string; action: "preregistration" | "bundle" | "evidence" | "closure"; kind: R24Kind | null; cellId: string; signerId: string; manifestDigest: D; ordinal: number; descriptorDigest: D | null; prerequisiteDigests: D[]; candidateDigest: D | null };
export type R24Response = { schema: "open-autonomy.bench-r24-acquisition-response.v1"; requestDigest: D; fragmentDigest: D; signerKeyId: string; signedAt: string; signature: string; fragment: unknown }; type Exchange = { request: R24Request; response?: R24Response };
export type R24State = { schema: "open-autonomy.bench-r24-acquisition-state.v1"; checkpoint: "R24"; campaignId: string; createdAt: string; manifestDigest: D; preregistrationKeyId: string; bundleKeyId: string; equivalenceKeyId: string; triageKeyId: string; closureKeyId: string; dependencyKeyIds: Record<(typeof DEPENDENCIES)[number], string>; publicKeys: Record<string, string>; preregistration?: Exchange; bundle?: Exchange; domains: Record<R24Kind, string[]> | null; evidence: Record<R24Kind, Record<string, Exchange>>; closure?: Exchange; closureGeneratedAt: string | null; assembledBundleDigest: D | null };
function registry(s: Pick<R24State, "preregistrationKeyId" | "bundleKeyId" | "equivalenceKeyId" | "triageKeyId" | "closureKeyId" | "dependencyKeyIds" | "publicKeys">) { if (Object.keys(s.dependencyKeyIds).sort().join() !== [...DEPENDENCIES].sort().join()) throw Error("R24 acquisition dependency registry incomplete"); const ids = [s.preregistrationKeyId, s.bundleKeyId, s.equivalenceKeyId, s.triageKeyId, s.closureKeyId, ...Object.values(s.dependencyKeyIds)]; if (ids.some((id) => !id || !s.publicKeys[id]) || new Set(ids).size !== ids.length) throw Error("R24 acquisition authority keys aliased or missing"); let fps: string[]; try { fps = ids.map((id) => fingerprint(s.publicKeys[id]!)); } catch { throw Error("R24 acquisition public key invalid"); } if (new Set(fps).size !== fps.length) throw Error("R24 acquisition public keys must be cryptographically distinct"); }
const accepted = (x: Exchange | undefined, name: string) => { if (!x?.response) throw Error(`R24 acquisition ${name} response missing`); return x.response; }, preregistration = (s: R24State) => accepted(s.preregistration, "preregistration").fragment as ClosureSigned<R24PreregistrationBody>, bundle = (s: R24State) => accepted(s.bundle, "bundle").fragment as V5MatchedBundle;
const responseDigest = (r: R24Response) => hash({ requestDigest: r.requestDigest, fragmentDigest: r.fragmentDigest, signerKeyId: r.signerKeyId, signedAt: r.signedAt, signature: r.signature });
function key(s: R24State, q: R24Request) { if (q.action === "preregistration") return s.preregistrationKeyId; if (q.action === "bundle") return s.bundleKeyId; if (q.action === "closure") return s.closureKeyId; if (q.kind === "equivalence") return s.equivalenceKeyId; if (q.kind === "triage") return s.triageKeyId; return s.dependencyKeyIds[q.signerId as keyof typeof s.dependencyKeyIds]; }
const request = (s: R24State, x: Omit<R24Request, "schema" | "checkpoint" | "campaignId" | "manifestDigest">): R24Request => ({ schema: "open-autonomy.bench-r24-acquisition-request.v1", checkpoint: "R24", campaignId: s.campaignId, manifestDigest: s.manifestDigest, ...x });
function checkRequest(s: R24State, q: R24Request) { if (q.schema !== "open-autonomy.bench-r24-acquisition-request.v1" || q.checkpoint !== "R24" || q.campaignId !== s.campaignId || q.manifestDigest !== s.manifestDigest || !q.signerId || !Number.isSafeInteger(q.ordinal) || q.ordinal < 0 || !key(s, q)) throw Error("R24 acquisition request invalid"); }
function checkResponse(s: R24State, x: Exchange) { if (!x.response) return; const r = x.response, kid = key(s, x.request); if (r.schema !== "open-autonomy.bench-r24-acquisition-response.v1" || r.requestDigest !== hash(x.request) || r.fragmentDigest !== hash(r.fragment) || r.signerKeyId !== kid || !Number.isFinite(Date.parse(r.signedAt)) || Date.parse(r.signedAt) < Date.parse(s.createdAt)) throw Error("R24 acquisition response binding invalid"); const body = { schema: r.schema, requestDigest: r.requestDigest, fragmentDigest: r.fragmentDigest, signerKeyId: r.signerKeyId, signedAt: r.signedAt }; if (!verify(null, Buffer.from(canonicalSemanticJson(body)), s.publicKeys[kid]!, Buffer.from(r.signature, "base64"))) throw Error("R24 acquisition response signature invalid"); }
function live(s: R24State) { if (s.schema !== "open-autonomy.bench-r24-acquisition-state.v1" || s.checkpoint !== "R24" || s.manifestDigest !== hash(MANIFEST) || s.assembledBundleDigest) throw Error("R24 acquisition state is not mutable"); }
function accept(s: R24State, x: Exchange, r: R24Response) { live(s); if (x.response && canonicalSemanticJson(x.response) !== canonicalSemanticJson(r)) throw Error("R24 acquisition equivocation rejected"); checkResponse(s, { request: x.request, response: r }); x.response = r; return hash(r); }
export function createR24State(i: Omit<R24State, "schema" | "checkpoint" | "manifestDigest" | "preregistration" | "bundle" | "domains" | "evidence" | "closure" | "closureGeneratedAt" | "assembledBundleDigest">): R24State { if (!i.campaignId || !Number.isFinite(Date.parse(i.createdAt))) throw Error("R24 acquisition identity invalid"); registry(i); return { ...i, schema: "open-autonomy.bench-r24-acquisition-state.v1", checkpoint: "R24", manifestDigest: hash(MANIFEST), domains: null, evidence: { equivalence: {}, triage: {}, dependencies: {} }, closureGeneratedAt: null, assembledBundleDigest: null }; }
export function issueR24Preregistration(s: R24State) { live(s); const q = request(s, { action: "preregistration", kind: null, cellId: "preregistration", signerId: "preregistration", ordinal: 0, descriptorDigest: null, prerequisiteDigests: [], candidateDigest: null }); s.preregistration ??= { request: q }; return s.preregistration.request; }
function validSigned(x: any, keyId: string, label: string) { if (!x || x.digest !== hash(x.body) || x.keyId !== keyId || !Number.isFinite(Date.parse(x.signedAt)) || !x.signature) throw Error(`R24 acquisition ${label} signed fragment invalid`); }
export function acceptR24Preregistration(s: R24State, r: R24Response) { live(s); if (!s.preregistration) throw Error("R24 acquisition preregistration request missing"); validSigned(r.fragment, s.preregistrationKeyId, "preregistration"); return accept(s, s.preregistration, r); }
export function issueR24Bundle(s: R24State) { live(s); const pre = preregistration(s), q = request(s, { action: "bundle", kind: null, cellId: "bundle", signerId: "bundle", ordinal: 0, descriptorDigest: hash({ planDigest: pre.body.planDigest, designDigest: pre.body.designDigest }), prerequisiteDigests: [responseDigest(accepted(s.preregistration, "preregistration"))], candidateDigest: null }); s.bundle ??= { request: q }; return s.bundle.request; }
function validBundle(s: R24State, x: any) { const pre = preregistration(s); if (!x || x.digest !== hash((({ digest: _, ...body }) => body)(x)) || hash(x.artifact?.plan) !== pre.body.planDigest || x.artifact?.plan?.designDigest !== pre.body.designDigest) throw Error("R24 acquisition matched bundle invalid"); }
function deriveDomains(b: V5MatchedBundle): Record<R24Kind, string[]> { return { equivalence: b.artifact.plan.pairSummaries.flatMap((x) => LOCK_PATHS.map((path) => cell(x.pairId, path))), triage: deriveR24DifferenceInventory(b).map((x) => cell(x.id)), dependencies: DEPENDENCIES.map((x) => cell(x)) }; }
export function acceptR24Bundle(s: R24State, r: R24Response) { live(s); if (!s.bundle) throw Error("R24 acquisition bundle request missing"); validBundle(s, r.fragment); const digest = accept(s, s.bundle, r), domains = deriveDomains(r.fragment as V5MatchedBundle); if (s.domains && canonicalSemanticJson(s.domains) !== canonicalSemanticJson(domains)) throw Error("R24 acquisition domain drift"); s.domains = domains; return digest; }
export function expectedR24Cells(s: R24State): Record<R24Kind, string[]> { if (!s.domains) throw Error("R24 acquisition bundle domains missing"); return s.domains; }
function descriptor(s: R24State, k: R24Kind, id: string) { const p = parts(id), b = bundle(s); if (k === "dependencies") return { checkpoint: p[0] }; if (k === "triage") return expectedR24Cells(s).triage.includes(id) ? { differenceId: p[0] } : null; const h = b.artifact.cells.find((x) => x.pairId === p[0] && x.substrate === "hermes"), pc = b.artifact.cells.find((x) => x.pairId === p[0] && x.substrate === "paperclip"); return h && pc ? { pairId: p[0], path: p[1], hermesDigest: h.locks.find((x) => x.path === p[1])?.digest, paperclipDigest: pc.locks.find((x) => x.path === p[1])?.digest } : null; }
function prerequisites(s: R24State, k: R24Kind) { const base = [responseDigest(accepted(s.preregistration, "preregistration")), responseDigest(accepted(s.bundle, "bundle"))]; return k === "triage" ? [...base, ...expectedR24Cells(s).equivalence.map((id) => responseDigest(accepted(s.evidence.equivalence[id], `equivalence ${id}`)))] : base; }
function signer(k: R24Kind, d: any) { return k === "dependencies" ? d.checkpoint : k; }
export function issueR24Evidence(s: R24State, k: R24Kind, id: string) { live(s); const cells = expectedR24Cells(s), ordinal = cells[k].indexOf(id), d = descriptor(s, k, id); if (ordinal < 0 || !d) throw Error("R24 acquisition cell is not registered"); const q = request(s, { action: "evidence", kind: k, cellId: id, signerId: signer(k, d), ordinal: ordinal + 1, descriptorDigest: hash(d), prerequisiteDigests: prerequisites(s, k), candidateDigest: null }), old = s.evidence[k][id]; if (old && canonicalSemanticJson(old.request) !== canonicalSemanticJson(q)) throw Error("R24 acquisition evidence request drift"); s.evidence[k][id] ??= { request: q }; return s.evidence[k][id]!.request; }
function validEvidence(s: R24State, k: R24Kind, id: string, x: any) { const d: any = descriptor(s, k, id); if (!x || !d) throw Error("R24 acquisition evidence invalid"); if (k === "equivalence") { validSigned(x, s.equivalenceKeyId, "equivalence"); if (x.body.pairId !== d.pairId || x.body.path !== d.path || x.body.hermesDigest !== d.hermesDigest || x.body.paperclipDigest !== d.paperclipDigest || x.body.equivalent !== true || !/^sha256:[a-f0-9]{64}$/.test(x.body.evidenceDigest)) throw Error("R24 acquisition equivalence substitution"); } else if (k === "triage") { validSigned(x, s.triageKeyId, "triage"); if (x.body.differenceId !== d.differenceId || !x.body.rationale || !x.body.evidenceDigests?.length) throw Error("R24 acquisition triage substitution"); } else { const checkpoint = d.checkpoint as keyof R24State["dependencyKeyIds"]; if (x.checkpoint !== checkpoint || x.keyId !== s.dependencyKeyIds[checkpoint] || x.artifactDigest !== hash(x.artifact) || !x.signature) throw Error("R24 acquisition dependency substitution"); } }
export function acceptR24Evidence(s: R24State, k: R24Kind, id: string, r: R24Response) { live(s); const x = s.evidence[k]?.[id]; if (!x) throw Error("R24 acquisition evidence request missing"); validEvidence(s, k, id, r.fragment); return accept(s, x, r); }
function rows<T>(s: R24State, k: R24Kind) { return expectedR24Cells(s)[k].map((id) => accepted(s.evidence[k][id], `${k} ${id}`).fragment as T); }
function body(s: R24State, generatedAt: string) { const b = bundle(s); return { schema: "autonomy.r24-external-closure.v2" as const, closureClaim: true as const, bundle: b, bundleDigest: b.digest, preregistration: preregistration(s), equivalence: rows(s, "equivalence"), triage: rows(s, "triage"), dependencies: rows(s, "dependencies"), generatedAt }; }
export function issueR24Closure(s: R24State, generatedAt: string) { live(s); if (!Number.isFinite(Date.parse(generatedAt))) throw Error("R24 acquisition closure timestamp invalid"); if (s.closureGeneratedAt && s.closureGeneratedAt !== generatedAt) throw Error("R24 acquisition closure timestamp drift"); s.closureGeneratedAt ??= generatedAt; const q = request(s, { action: "closure", kind: null, cellId: "closure", signerId: "closure", ordinal: 0, descriptorDigest: hash({ generatedAt }), prerequisiteDigests: KINDS.flatMap((k) => expectedR24Cells(s)[k].map((id) => responseDigest(accepted(s.evidence[k][id], `${k} ${id}`)))), candidateDigest: hash(body(s, generatedAt)) }); s.closure ??= { request: q }; return s.closure.request; }
function validClosure(s: R24State, x: any) { const generatedAt = s.closureGeneratedAt; if (!x || Object.keys(x).sort().join() !== "digest,generatedAt,signature,signerKeyId" || x.signerKeyId !== s.closureKeyId || x.generatedAt !== generatedAt || !generatedAt || !Number.isFinite(Date.parse(generatedAt)) || x.digest !== hash(body(s, generatedAt)) || !x.signature) throw Error("R24 acquisition closure fragment invalid"); }
export function acceptR24Closure(s: R24State, r: R24Response) { live(s); if (!s.closure) throw Error("R24 acquisition closure request missing"); validClosure(s, r.fragment); return accept(s, s.closure, r); }
export function assembleR24(s: R24State) { assertR24State(s); const x: any = accepted(s.closure, "closure").fragment, campaign = { ...body(s, x.generatedAt), signerKeyId: x.signerKeyId, digest: x.digest, signature: x.signature } as R24ExternalCampaign, digest = hash(campaign); if (s.assembledBundleDigest && s.assembledBundleDigest !== digest) throw Error("R24 acquisition assembly drift"); s.assembledBundleDigest = digest; return campaign; }
export function assertR24State(s: R24State) { if (s.schema !== "open-autonomy.bench-r24-acquisition-state.v1" || s.checkpoint !== "R24" || !s.campaignId || !Number.isFinite(Date.parse(s.createdAt)) || s.manifestDigest !== hash(MANIFEST)) throw Error("R24 acquisition state invalid"); registry(s); if (Object.keys(s.evidence).sort().join() !== [...KINDS].sort().join()) throw Error("R24 acquisition evidence registry invalid"); const check = (x: Exchange | undefined) => { if (!x) return; checkRequest(s, x.request); checkResponse(s, x); }; check(s.preregistration); check(s.bundle); for (const k of KINDS) Object.values(s.evidence[k]).forEach(check); check(s.closure);
  if (s.preregistration) { const q = request(s, { action: "preregistration", kind: null, cellId: "preregistration", signerId: "preregistration", ordinal: 0, descriptorDigest: null, prerequisiteDigests: [], candidateDigest: null }); if (canonicalSemanticJson(q) !== canonicalSemanticJson(s.preregistration.request)) throw Error("R24 acquisition preregistration request drift"); if (s.preregistration.response) validSigned(s.preregistration.response.fragment, s.preregistrationKeyId, "preregistration"); }
  if (s.bundle) { const pre = preregistration(s), q = request(s, { action: "bundle", kind: null, cellId: "bundle", signerId: "bundle", ordinal: 0, descriptorDigest: hash({ planDigest: pre.body.planDigest, designDigest: pre.body.designDigest }), prerequisiteDigests: [responseDigest(accepted(s.preregistration, "preregistration"))], candidateDigest: null }); if (canonicalSemanticJson(q) !== canonicalSemanticJson(s.bundle.request)) throw Error("R24 acquisition bundle request drift"); if (s.bundle.response) { validBundle(s, s.bundle.response.fragment); if (canonicalSemanticJson(deriveDomains(s.bundle.response.fragment as V5MatchedBundle)) !== canonicalSemanticJson(s.domains)) throw Error("R24 acquisition domain drift"); const cells = expectedR24Cells(s); for (const k of KINDS) for (const [id, x] of Object.entries(s.evidence[k])) { const ordinal = cells[k].indexOf(id), d = descriptor(s, k, id); if (ordinal < 0 || !d) throw Error("R24 acquisition unregistered stored cell"); const q = request(s, { action: "evidence", kind: k, cellId: id, signerId: signer(k, d), ordinal: ordinal + 1, descriptorDigest: hash(d), prerequisiteDigests: prerequisites(s, k), candidateDigest: null }); if (canonicalSemanticJson(q) !== canonicalSemanticJson(x.request)) throw Error("R24 acquisition evidence request drift"); if (x.response) validEvidence(s, k, id, x.response.fragment); } } }
  if (s.closure) { if (!s.closureGeneratedAt) throw Error("R24 acquisition closure timestamp missing"); const q = request(s, { action: "closure", kind: null, cellId: "closure", signerId: "closure", ordinal: 0, descriptorDigest: hash({ generatedAt: s.closureGeneratedAt }), prerequisiteDigests: KINDS.flatMap((k) => expectedR24Cells(s)[k].map((id) => responseDigest(accepted(s.evidence[k][id], `${k} ${id}`)))), candidateDigest: hash(body(s, s.closureGeneratedAt)) }); if (canonicalSemanticJson(q) !== canonicalSemanticJson(s.closure.request)) throw Error("R24 acquisition closure request drift"); if (s.closure.response) validClosure(s, s.closure.response.fragment); } else if (s.closureGeneratedAt !== null) throw Error("R24 acquisition orphan closure timestamp");
  if (s.assembledBundleDigest !== null) { const x: any = accepted(s.closure, "closure").fragment, campaign = { ...body(s, x.generatedAt), signerKeyId: x.signerKeyId, digest: x.digest, signature: x.signature }; if (s.assembledBundleDigest !== hash(campaign)) throw Error("R24 acquisition assembled state invalid"); } return s; }
export function saveR24State(path: string, s: R24State) { assertR24State(s); saveR24Json(path, s); } export function saveR24Json(path: string, value: unknown) { const target = resolve(path), temporary = `${target}.tmp-${process.pid}`; writeFileSync(temporary, `${canonicalSemanticJson(value)}\n`, { flag: "wx", mode: 0o600 }); const file = openSync(temporary, "r"); try { fsyncSync(file); } finally { closeSync(file); } renameSync(temporary, target); const directory = openSync(dirname(target), "r"); try { fsyncSync(directory); } finally { closeSync(directory); } } export function loadR24State(path: string) { return assertR24State(JSON.parse(readFileSync(path, "utf8")) as R24State); }
