#!/usr/bin/env bun
import { existsSync, readFileSync } from "node:fs"; import { acceptR24Bundle, acceptR24Closure, acceptR24Evidence, acceptR24Preregistration, assembleR24, createR24State, expectedR24Cells, issueR24Bundle, issueR24Closure, issueR24Evidence, issueR24Preregistration, loadR24State, saveR24Json, saveR24State, type R24Kind, type R24Response } from "./r24-acquisition";
const COMMANDS = ["init", "status", "issue-preregistration", "accept-preregistration", "issue-bundle", "accept-bundle", "issue-evidence", "accept-evidence", "issue-closure", "accept-closure", "assemble"] as const; type Command = typeof COMMANDS[number];
function parse(argv: string[]) { const command = argv.shift() as Command, flags = new Map<string, string>(); if (!(COMMANDS as readonly string[]).includes(command)) throw Error(`usage: r24-acquire <${COMMANDS.join("|")}> [options]`); while (argv.length) { const k = argv.shift()!, v = argv.shift(); if (!k.startsWith("--") || v === undefined || flags.has(k)) throw Error("R24 acquisition arguments invalid"); flags.set(k, v); } const required = (k: string) => { const v = flags.get(k); if (!v) throw Error(`R24 acquisition ${k} required`); return v; }; return { command, required }; } const json = (path: string) => JSON.parse(readFileSync(path, "utf8"));
export async function runR24AcquisitionCli(argv: string[]) { const { command, required } = parse([...argv]), statePath = required("--state"); if (command === "init") { if (existsSync(statePath)) throw Error("R24 acquisition state already exists"); const s = createR24State(json(required("--registry"))); saveR24State(statePath, s); return { campaignId: s.campaignId, manifestDigest: s.manifestDigest }; } const s = loadR24State(statePath); if (command === "status") return { campaignId: s.campaignId, preregistration: !!s.preregistration?.response, bundle: !!s.bundle?.response, required: s.domains && Object.fromEntries(Object.entries(expectedR24Cells(s)).map(([k, v]) => [k, v.length])), accepted: Object.fromEntries(Object.entries(s.evidence).map(([k, v]) => [k, Object.values(v).filter((x) => x.response).length])), closure: !!s.closure?.response, assembledBundleDigest: s.assembledBundleDigest };
  const response = () => json(required("--response")) as R24Response, durable = (value: unknown) => { saveR24State(statePath, s); saveR24Json(required("--out"), value); }; let result: unknown;
  if (command === "issue-preregistration") { const q = issueR24Preregistration(s); durable(q); result = { action: q.action }; } else if (command === "accept-preregistration") result = { responseDigest: acceptR24Preregistration(s, response()) };
  else if (command === "issue-bundle") { const q = issueR24Bundle(s); durable(q); result = { descriptorDigest: q.descriptorDigest }; } else if (command === "accept-bundle") result = { responseDigest: acceptR24Bundle(s, response()) };
  else if (command === "issue-evidence") { const kind = required("--kind") as R24Kind, id = required("--cell"), q = issueR24Evidence(s, kind, id); durable(q); result = { kind, cell: id, ordinal: q.ordinal }; } else if (command === "accept-evidence") { const kind = required("--kind") as R24Kind, id = required("--cell"); result = { responseDigest: acceptR24Evidence(s, kind, id, response()) }; }
  else if (command === "issue-closure") { const q = issueR24Closure(s, required("--generated-at")); durable(q); result = { candidateDigest: q.candidateDigest }; } else if (command === "accept-closure") result = { responseDigest: acceptR24Closure(s, response()) };
  else { const campaign = assembleR24(s); durable(campaign); result = { bundleDigest: s.assembledBundleDigest }; } saveR24State(statePath, s); return result;
}
if (import.meta.main) runR24AcquisitionCli(process.argv.slice(2)).then((x) => console.log(JSON.stringify(x))).catch((e) => { console.error(e instanceof Error ? e.message : e); process.exitCode = 1; });
