import { createHash, createPublicKey, verify } from "node:crypto"; import { closeSync, fsyncSync, openSync, readFileSync, renameSync, writeFileSync } from "node:fs"; import { dirname, resolve } from "node:path";
import { canonicalSemanticJson, twinDigest, type R25Calibration, type R25Signed } from "@open-autonomy/core";
type D = `sha256:${string}`; export type R25Kind = "dependencies" | "train-sources" | "cases" | "ledger" | "held-sources" | "predictions" | "outcomes"; const KINDS: R25Kind[] = ["dependencies", "train-sources", "cases", "ledger", "held-sources", "predictions", "outcomes"], DEPS = ["R19", "R23", "R24"] as const;
const hash = (x: unknown): D => `sha256:${createHash("sha256").update(canonicalSemanticJson(x)).digest("hex")}`, fp = (pem: string) => createHash("sha256").update(createPublicKey(pem).export({ type: "spki", format: "der" })).digest("hex"), enc = (x: string) => encodeURIComponent(x), dec = (x: string) => decodeURIComponent(x), MANIFEST_VERSION = 1;
export type R25Request = { schema: "open-autonomy.bench-r25-acquisition-request.v1"; checkpoint: "R25"; campaignId: string; action: "evidence" | "specification" | "sensitivity" | "preregistration" | "analysis" | "disposition"; kind: R25Kind | null; cellId: string; signerId: string; manifestDigest: D; ordinal: number; descriptorDigest: D | null; prerequisiteDigests: D[]; candidateDigest: D | null };
export type R25Response = { schema: "open-autonomy.bench-r25-acquisition-response.v1"; requestDigest: D; fragmentDigest: D; signerKeyId: string; signedAt: string; signature: string; fragment: unknown }; type X = { request: R25Request; response?: R25Response };
type Dep = (typeof DEPS)[number]; export type R25State = { schema: "open-autonomy.bench-r25-acquisition-state.v1"; checkpoint: "R25"; campaignId: string; createdAt: string; manifestDigest: D; trainSourceIds: string[]; heldSourceIds: string[]; caseIds: string[]; parameterPaths: string[]; dependencyKeyIds: Record<Dep, string>; modelKeyId: string; trainSourceKeyId: string; caseKeyId: string; identifiabilityKeyId: string; preregistrationKeyId: string; predictionKeyId: string; heldSourceKeyId: string; outcomeKeyId: string; analysisKeyId: string; dispositionKeyId: string; publicKeys: Record<string, string>; evidence: Record<R25Kind, Record<string, X>>; specification?: X; sensitivity?: X; preregistration?: X; analysis?: X; disposition?: X; assembledBundleDigest: D | null };
function registry(s: Pick<R25State, "trainSourceIds" | "heldSourceIds" | "caseIds" | "parameterPaths" | "dependencyKeyIds" | "modelKeyId" | "trainSourceKeyId" | "caseKeyId" | "identifiabilityKeyId" | "preregistrationKeyId" | "predictionKeyId" | "heldSourceKeyId" | "outcomeKeyId" | "analysisKeyId" | "dispositionKeyId" | "publicKeys">) { for (const [name, xs] of [["train sources", s.trainSourceIds], ["held sources", s.heldSourceIds], ["cases", s.caseIds], ["parameters", s.parameterPaths]] as const) if (!xs.length || new Set(xs).size !== xs.length || xs.some((x) => !x)) throw Error(`R25 acquisition ${name} registry invalid`); if (Object.keys(s.dependencyKeyIds).sort().join() !== [...DEPS].sort().join()) throw Error("R25 acquisition dependency registry invalid"); const ids = [...Object.values(s.dependencyKeyIds), s.modelKeyId, s.trainSourceKeyId, s.caseKeyId, s.identifiabilityKeyId, s.preregistrationKeyId, s.predictionKeyId, s.heldSourceKeyId, s.outcomeKeyId, s.analysisKeyId, s.dispositionKeyId]; if (ids.some((id) => !id || !s.publicKeys[id]) || new Set(ids).size !== ids.length) throw Error("R25 acquisition authority keys aliased or missing"); let fps: string[]; try { fps = ids.map((id) => fp(s.publicKeys[id]!)); } catch { throw Error("R25 acquisition public key invalid"); } if (new Set(fps).size !== fps.length) throw Error("R25 acquisition public keys must be cryptographically distinct"); }
const manifest = (s: Pick<R25State, "trainSourceIds" | "heldSourceIds" | "caseIds" | "parameterPaths">) => ({ version: MANIFEST_VERSION, trainSourceIds: s.trainSourceIds, heldSourceIds: s.heldSourceIds, caseIds: s.caseIds, parameterPaths: s.parameterPaths, order: ["frozen-inputs", "identifiability", "preregistration", "predictions", "held-out-observation", "analysis", "disposition"] }), accepted = (x: X | undefined, n: string) => { if (!x?.response) throw Error(`R25 acquisition ${n} response missing`); return x.response; };
function key(s: R25State, q: R25Request) { if (q.action === "specification") return s.modelKeyId; if (q.action === "sensitivity") return s.identifiabilityKeyId; if (q.action === "preregistration") return s.preregistrationKeyId; if (q.action === "analysis") return s.analysisKeyId; if (q.action === "disposition") return s.dispositionKeyId; if (q.kind === "dependencies") return s.dependencyKeyIds[q.signerId as Dep]; if (q.kind === "train-sources") return s.trainSourceKeyId; if (q.kind === "cases") return s.caseKeyId; if (q.kind === "ledger") return s.modelKeyId; if (q.kind === "held-sources") return s.heldSourceKeyId; if (q.kind === "predictions") return s.predictionKeyId; return s.outcomeKeyId; }
const request = (s: R25State, x: Omit<R25Request, "schema" | "checkpoint" | "campaignId" | "manifestDigest">): R25Request => ({ schema: "open-autonomy.bench-r25-acquisition-request.v1", checkpoint: "R25", campaignId: s.campaignId, manifestDigest: s.manifestDigest, ...x }), rd = (r: R25Response) => hash({ requestDigest: r.requestDigest, fragmentDigest: r.fragmentDigest, signerKeyId: r.signerKeyId, signedAt: r.signedAt, signature: r.signature });
function checkRequest(s: R25State, q: R25Request) { if (q.schema !== "open-autonomy.bench-r25-acquisition-request.v1" || q.checkpoint !== "R25" || q.campaignId !== s.campaignId || q.manifestDigest !== s.manifestDigest || !q.signerId || !Number.isSafeInteger(q.ordinal) || q.ordinal < 0 || !key(s, q)) throw Error("R25 acquisition request invalid"); }
function checkResponse(s: R25State, x: X) { if (!x.response) return; const r = x.response, kid = key(s, x.request); if (r.schema !== "open-autonomy.bench-r25-acquisition-response.v1" || r.requestDigest !== hash(x.request) || r.fragmentDigest !== hash(r.fragment) || r.signerKeyId !== kid || !Number.isFinite(Date.parse(r.signedAt)) || Date.parse(r.signedAt) < Date.parse(s.createdAt)) throw Error("R25 acquisition response binding invalid"); const body = { schema: r.schema, requestDigest: r.requestDigest, fragmentDigest: r.fragmentDigest, signerKeyId: r.signerKeyId, signedAt: r.signedAt }; if (!verify(null, Buffer.from(canonicalSemanticJson(body)), s.publicKeys[kid]!, Buffer.from(r.signature, "base64"))) throw Error("R25 acquisition response signature invalid"); }
function live(s: R25State) { if (s.schema !== "open-autonomy.bench-r25-acquisition-state.v1" || s.checkpoint !== "R25" || s.manifestDigest !== hash(manifest(s)) || s.assembledBundleDigest) throw Error("R25 acquisition state is not mutable"); } function accept(s: R25State, x: X, r: R25Response) { live(s); if (x.response && canonicalSemanticJson(x.response) !== canonicalSemanticJson(r)) throw Error("R25 acquisition equivocation rejected"); checkResponse(s, { request: x.request, response: r }); x.response = r; return rd(r); }
export function createR25State(i: Omit<R25State, "schema" | "checkpoint" | "manifestDigest" | "evidence" | "specification" | "sensitivity" | "preregistration" | "analysis" | "disposition" | "assembledBundleDigest">): R25State { if (!i.campaignId || !Number.isFinite(Date.parse(i.createdAt))) throw Error("R25 acquisition identity invalid"); registry(i); return { ...i, schema: "open-autonomy.bench-r25-acquisition-state.v1", checkpoint: "R25", manifestDigest: hash(manifest(i)), evidence: { dependencies: {}, "train-sources": {}, cases: {}, ledger: {}, "held-sources": {}, predictions: {}, outcomes: {} }, assembledBundleDigest: null }; }
export function expectedR25Cells(s: R25State): Record<R25Kind, string[]> { return { dependencies: DEPS.map(enc), "train-sources": s.trainSourceIds.map(enc), cases: s.caseIds.map(enc), ledger: s.parameterPaths.map(enc), "held-sources": s.heldSourceIds.map(enc), predictions: s.caseIds.map(enc), outcomes: s.caseIds.map(enc) }; }
function descriptor(k: R25Kind, id: string) { const value = dec(id); return k === "dependencies" ? { checkpoint: value } : k === "train-sources" || k === "held-sources" ? { sourceId: value } : k === "cases" || k === "predictions" || k === "outcomes" ? { caseId: value } : { path: value }; }
function inputDigests(s: R25State) { return [rd(accepted(s.specification, "specification")), ...["dependencies", "train-sources", "cases", "ledger"].flatMap((k) => expectedR25Cells(s)[k as R25Kind].map((id) => rd(accepted(s.evidence[k as R25Kind][id], `${k} ${id}`))))]; }
function prereqs(s: R25State, k: R25Kind, d: any): D[] { if (["dependencies", "train-sources", "cases", "ledger"].includes(k)) return []; const pre = rd(accepted(s.preregistration, "preregistration")); if (k === "held-sources") return [pre]; if (k === "predictions") return [pre, rd(accepted(s.evidence.cases[enc(d.caseId)], `case ${d.caseId}`))]; return [pre, rd(accepted(s.evidence.predictions[enc(d.caseId)], `prediction ${d.caseId}`)), rd(accepted(s.evidence["held-sources"][enc((accepted(s.evidence.cases[enc(d.caseId)], "case").fragment as any).sourceId)], `held source for ${d.caseId}`))]; }
function signer(k: R25Kind, d: any) { return k === "dependencies" ? d.checkpoint : k; }
export function issueR25Evidence(s: R25State, k: R25Kind, id: string) { live(s); const cells = expectedR25Cells(s), ordinal = cells[k].indexOf(id), d = descriptor(k, id); if (ordinal < 0) throw Error("R25 acquisition cell is not registered"); const q = request(s, { action: "evidence", kind: k, cellId: id, signerId: signer(k, d), ordinal: ordinal + 1, descriptorDigest: hash(d), prerequisiteDigests: prereqs(s, k, d), candidateDigest: null }), old = s.evidence[k][id]; if (old && canonicalSemanticJson(old.request) !== canonicalSemanticJson(q)) throw Error("R25 acquisition evidence request drift"); s.evidence[k][id] ??= { request: q }; return s.evidence[k][id]!.request; }
function signed(x: any, n: string) { if (!x || x.digest !== hash(x.body) || !x.keyId || !Number.isFinite(Date.parse(x.signedAt)) || !x.signature) throw Error(`R25 acquisition ${n} signed fragment invalid`); }
function validEvidence(k: R25Kind, d: any, x: any) { if (!x) throw Error("R25 acquisition evidence invalid"); if (k === "dependencies") return; if (k === "train-sources" || k === "held-sources") { if (x.id !== d.sourceId || x.artifactDigest !== hash(x.artifact)) throw Error("R25 acquisition source substitution"); } else if (k === "cases") { if (x.id !== d.caseId) throw Error("R25 acquisition case substitution"); } else if (k === "ledger") { if (x.path !== d.path) throw Error("R25 acquisition parameter substitution"); } else if (k === "predictions") { signed(x, "prediction"); if (x.body.caseId !== d.caseId) throw Error("R25 acquisition prediction substitution"); } else if (x.caseId !== d.caseId || x.traceDigest !== hash(x.trace)) throw Error("R25 acquisition outcome substitution"); }
export function acceptR25Evidence(s: R25State, k: R25Kind, id: string, r: R25Response) { live(s); const x = s.evidence[k]?.[id]; if (!x) throw Error("R25 acquisition evidence request missing"); validEvidence(k, descriptor(k, id), r.fragment); return accept(s, x, r); }
function singleton(s: R25State, action: R25Request["action"], name: "specification" | "sensitivity" | "preregistration" | "analysis" | "disposition", prerequisites: D[], candidateDigest: D | null = null) { live(s); const q = request(s, { action, kind: null, cellId: name, signerId: name, ordinal: 0, descriptorDigest: null, prerequisiteDigests: prerequisites, candidateDigest }); s[name] ??= { request: q }; return s[name]!.request; }
export const issueR25Specification = (s: R25State) => singleton(s, "specification", "specification", []);
export function acceptR25Specification(s: R25State, r: R25Response) { if (!s.specification) throw Error("R25 acquisition specification request missing"); if (!r.fragment || typeof r.fragment !== "object") throw Error("R25 acquisition specification invalid"); return accept(s, s.specification, r); }
export const issueR25Sensitivity = (s: R25State) => singleton(s, "sensitivity", "sensitivity", inputDigests(s));
export function acceptR25Sensitivity(s: R25State, r: R25Response) { if (!s.sensitivity) throw Error("R25 acquisition sensitivity request missing"); signed(r.fragment, "sensitivity"); return accept(s, s.sensitivity, r); }
export const issueR25Preregistration = (s: R25State) => singleton(s, "preregistration", "preregistration", [...inputDigests(s), rd(accepted(s.sensitivity, "sensitivity"))]);
function validPreregistration(s: R25State, x: any) { signed(x, "preregistration"); const b = x.body, cases = expectedR25Cells(s).cases.map((id) => accepted(s.evidence.cases[id], `case ${id}`).fragment); if (canonicalSemanticJson(b.trainSourceIds) !== canonicalSemanticJson(s.trainSourceIds) || canonicalSemanticJson(b.heldOutSourceIds) !== canonicalSemanticJson(s.heldSourceIds) || b.caseManifestDigest !== hash(cases) || b.specificationDigest !== `sha256:${twinDigest(accepted(s.specification, "specification").fragment as any)}`) throw Error("R25 acquisition preregistration/domain mismatch"); for (const dep of DEPS) if (b.dependencyDigests[dep] !== hash(accepted(s.evidence.dependencies[enc(dep)], `dependency ${dep}`).fragment)) throw Error("R25 acquisition preregistration dependency mismatch"); }
export function acceptR25Preregistration(s: R25State, r: R25Response) { if (!s.preregistration) throw Error("R25 acquisition preregistration request missing"); validPreregistration(s, r.fragment); return accept(s, s.preregistration, r); }
function postDigests(s: R25State) { return ["held-sources", "predictions", "outcomes"].flatMap((k) => expectedR25Cells(s)[k as R25Kind].map((id) => rd(accepted(s.evidence[k as R25Kind][id], `${k} ${id}`)))); }
export const issueR25Analysis = (s: R25State) => singleton(s, "analysis", "analysis", postDigests(s));
export function acceptR25Analysis(s: R25State, r: R25Response) { if (!s.analysis) throw Error("R25 acquisition analysis request missing"); const x: any = r.fragment; if (!x || Object.keys(x).sort().join() !== "ablations,falsifyingTraces" || !Array.isArray(x.ablations) || !Array.isArray(x.falsifyingTraces)) throw Error("R25 acquisition analysis invalid"); return accept(s, s.analysis, r); }
export const issueR25Disposition = (s: R25State) => singleton(s, "disposition", "disposition", [rd(accepted(s.analysis, "analysis"))]);
export function acceptR25Disposition(s: R25State, r: R25Response) { if (!s.disposition) throw Error("R25 acquisition disposition request missing"); signed(r.fragment, "disposition"); return accept(s, s.disposition, r); }
function rows<T>(s: R25State, k: R25Kind) { return expectedR25Cells(s)[k].map((id) => accepted(s.evidence[k][id], `${k} ${id}`).fragment as T); }
function draft(s: R25State) { const disposition = accepted(s.disposition, "disposition").fragment as R25Calibration["disposition"], analysis: any = accepted(s.analysis, "analysis").fragment; return { schema: "autonomy.r25-external-calibration.v1", closureClaim: disposition.body.status === "calibrated", status: disposition.body.status, dependencies: Object.fromEntries(DEPS.map((d) => [d, rows(s, "dependencies")[DEPS.indexOf(d)]])) as any, preregistration: accepted(s.preregistration, "preregistration").fragment as any, specification: accepted(s.specification, "specification").fragment as any, sources: [...rows(s, "train-sources"), ...rows(s, "held-sources")] as any, cases: rows(s, "cases"), parameterLedger: rows(s, "ledger"), predictions: rows(s, "predictions"), outcomes: rows(s, "outcomes"), sensitivity: accepted(s.sensitivity, "sensitivity").fragment as any, ablations: analysis.ablations, falsifyingTraces: analysis.falsifyingTraces, disposition } as R25Calibration; }
export function assembleR25(s: R25State) { assertR25State(s); const artifact = draft(s), digest = hash(artifact); if (s.assembledBundleDigest && s.assembledBundleDigest !== digest) throw Error("R25 acquisition assembly drift"); s.assembledBundleDigest = digest; return artifact; }
export function assertR25State(s: R25State) { if (s.schema !== "open-autonomy.bench-r25-acquisition-state.v1" || s.checkpoint !== "R25" || !s.campaignId || !Number.isFinite(Date.parse(s.createdAt)) || s.manifestDigest !== hash(manifest(s))) throw Error("R25 acquisition state invalid"); registry(s); if (Object.keys(s.evidence).sort().join() !== [...KINDS].sort().join()) throw Error("R25 acquisition evidence registry invalid"); const check = (x: X | undefined) => { if (!x) return; checkRequest(s, x.request); checkResponse(s, x); }; for (const k of KINDS) for (const [id, x] of Object.entries(s.evidence[k])) { check(x); const cells = expectedR25Cells(s), ordinal = cells[k].indexOf(id), d = descriptor(k, id); if (ordinal < 0) throw Error("R25 acquisition unregistered stored cell"); const q = request(s, { action: "evidence", kind: k, cellId: id, signerId: signer(k, d), ordinal: ordinal + 1, descriptorDigest: hash(d), prerequisiteDigests: prereqs(s, k, d), candidateDigest: null }); if (canonicalSemanticJson(q) !== canonicalSemanticJson(x.request)) throw Error("R25 acquisition evidence request drift"); if (x.response) validEvidence(k, d, x.response.fragment); }
  check(s.specification); if (s.specification) { const q = request(s, { action: "specification", kind: null, cellId: "specification", signerId: "specification", ordinal: 0, descriptorDigest: null, prerequisiteDigests: [], candidateDigest: null }); if (canonicalSemanticJson(q) !== canonicalSemanticJson(s.specification.request)) throw Error("R25 acquisition specification request drift"); }
  check(s.sensitivity); if (s.sensitivity) { const q = request(s, { action: "sensitivity", kind: null, cellId: "sensitivity", signerId: "sensitivity", ordinal: 0, descriptorDigest: null, prerequisiteDigests: inputDigests(s), candidateDigest: null }); if (canonicalSemanticJson(q) !== canonicalSemanticJson(s.sensitivity.request)) throw Error("R25 acquisition sensitivity request drift"); if (s.sensitivity.response) signed(s.sensitivity.response.fragment, "sensitivity"); }
  check(s.preregistration); if (s.preregistration) { const q = request(s, { action: "preregistration", kind: null, cellId: "preregistration", signerId: "preregistration", ordinal: 0, descriptorDigest: null, prerequisiteDigests: [...inputDigests(s), rd(accepted(s.sensitivity, "sensitivity"))], candidateDigest: null }); if (canonicalSemanticJson(q) !== canonicalSemanticJson(s.preregistration.request)) throw Error("R25 acquisition preregistration request drift"); if (s.preregistration.response) validPreregistration(s, s.preregistration.response.fragment); }
  check(s.analysis); if (s.analysis) { const q = request(s, { action: "analysis", kind: null, cellId: "analysis", signerId: "analysis", ordinal: 0, descriptorDigest: null, prerequisiteDigests: postDigests(s), candidateDigest: null }); if (canonicalSemanticJson(q) !== canonicalSemanticJson(s.analysis.request)) throw Error("R25 acquisition analysis request drift"); }
  check(s.disposition); if (s.disposition) { const q = request(s, { action: "disposition", kind: null, cellId: "disposition", signerId: "disposition", ordinal: 0, descriptorDigest: null, prerequisiteDigests: [rd(accepted(s.analysis, "analysis"))], candidateDigest: null }); if (canonicalSemanticJson(q) !== canonicalSemanticJson(s.disposition.request)) throw Error("R25 acquisition disposition request drift"); if (s.disposition.response) signed(s.disposition.response.fragment, "disposition"); }
  if (s.assembledBundleDigest !== null && s.assembledBundleDigest !== hash(draft(s))) throw Error("R25 acquisition assembled state invalid"); return s; }
export function saveR25State(path: string, s: R25State) { assertR25State(s); saveR25Json(path, s); } export function saveR25Json(path: string, value: unknown) { const target = resolve(path), temporary = `${target}.tmp-${process.pid}`; writeFileSync(temporary, `${canonicalSemanticJson(value)}\n`, { flag: "wx", mode: 0o600 }); const file = openSync(temporary, "r"); try { fsyncSync(file); } finally { closeSync(file); } renameSync(temporary, target); const directory = openSync(dirname(target), "r"); try { fsyncSync(directory); } finally { closeSync(directory); } } export function loadR25State(path: string) { return assertR25State(JSON.parse(readFileSync(path, "utf8")) as R25State); }
