#!/usr/bin/env bun
import { existsSync, readFileSync } from "node:fs"; import { acceptR25Analysis, acceptR25Disposition, acceptR25Evidence, acceptR25Preregistration, acceptR25Sensitivity, acceptR25Specification, assembleR25, createR25State, expectedR25Cells, issueR25Analysis, issueR25Disposition, issueR25Evidence, issueR25Preregistration, issueR25Sensitivity, issueR25Specification, loadR25State, saveR25Json, saveR25State, type R25Kind, type R25Response } from "./r25-acquisition";
const COMMANDS = ["init", "status", "issue-specification", "accept-specification", "issue-evidence", "accept-evidence", "issue-sensitivity", "accept-sensitivity", "issue-preregistration", "accept-preregistration", "issue-analysis", "accept-analysis", "issue-disposition", "accept-disposition", "assemble"] as const; type Command = typeof COMMANDS[number];
function parse(argv: string[]) { const command = argv.shift() as Command, flags = new Map<string, string>(); if (!(COMMANDS as readonly string[]).includes(command)) throw Error(`usage: r25-acquire <${COMMANDS.join("|")}> [options]`); while (argv.length) { const k = argv.shift()!, v = argv.shift(); if (!k.startsWith("--") || v === undefined || flags.has(k)) throw Error("R25 acquisition arguments invalid"); flags.set(k, v); } const required = (k: string) => { const v = flags.get(k); if (!v) throw Error(`R25 acquisition ${k} required`); return v; }; return { command, required }; } const json = (path: string) => JSON.parse(readFileSync(path, "utf8"));
export async function runR25AcquisitionCli(argv: string[]) { const { command, required } = parse([...argv]), statePath = required("--state"); if (command === "init") { if (existsSync(statePath)) throw Error("R25 acquisition state already exists"); const s = createR25State(json(required("--registry"))); saveR25State(statePath, s); return { campaignId: s.campaignId, manifestDigest: s.manifestDigest }; } const s = loadR25State(statePath); if (command === "status") return { campaignId: s.campaignId, required: Object.fromEntries(Object.entries(expectedR25Cells(s)).map(([k, v]) => [k, v.length])), accepted: Object.fromEntries(Object.entries(s.evidence).map(([k, v]) => [k, Object.values(v).filter((x) => x.response).length])), specification: !!s.specification?.response, sensitivity: !!s.sensitivity?.response, preregistration: !!s.preregistration?.response, analysis: !!s.analysis?.response, disposition: !!s.disposition?.response, assembledBundleDigest: s.assembledBundleDigest };
  const response = () => json(required("--response")) as R25Response, durable = (value: unknown) => { saveR25State(statePath, s); saveR25Json(required("--out"), value); }; let result: unknown;
  if (command === "issue-specification") { const q = issueR25Specification(s); durable(q); result = { action: q.action }; } else if (command === "accept-specification") result = { responseDigest: acceptR25Specification(s, response()) };
  else if (command === "issue-evidence") { const kind = required("--kind") as R25Kind, id = required("--cell"), q = issueR25Evidence(s, kind, id); durable(q); result = { kind, cell: id, ordinal: q.ordinal }; } else if (command === "accept-evidence") { const kind = required("--kind") as R25Kind, id = required("--cell"); result = { responseDigest: acceptR25Evidence(s, kind, id, response()) }; }
  else if (command === "issue-sensitivity") { const q = issueR25Sensitivity(s); durable(q); result = { prerequisites: q.prerequisiteDigests.length }; } else if (command === "accept-sensitivity") result = { responseDigest: acceptR25Sensitivity(s, response()) };
  else if (command === "issue-preregistration") { const q = issueR25Preregistration(s); durable(q); result = { prerequisites: q.prerequisiteDigests.length }; } else if (command === "accept-preregistration") result = { responseDigest: acceptR25Preregistration(s, response()) };
  else if (command === "issue-analysis") { const q = issueR25Analysis(s); durable(q); result = { prerequisites: q.prerequisiteDigests.length }; } else if (command === "accept-analysis") result = { responseDigest: acceptR25Analysis(s, response()) };
  else if (command === "issue-disposition") { const q = issueR25Disposition(s); durable(q); result = { prerequisites: q.prerequisiteDigests.length }; } else if (command === "accept-disposition") result = { responseDigest: acceptR25Disposition(s, response()) };
  else { const artifact = assembleR25(s); durable(artifact); result = { bundleDigest: s.assembledBundleDigest }; } saveR25State(statePath, s); return result;
}
if (import.meta.main) runR25AcquisitionCli(process.argv.slice(2)).then((x) => console.log(JSON.stringify(x))).catch((e) => { console.error(e instanceof Error ? e.message : e); process.exitCode = 1; });
