#!/usr/bin/env bun
import { existsSync, readFileSync } from "node:fs"; import { acceptR26Decision, acceptR26Evidence, acceptR26Manifest, assembleR26, createR26State, expectedR26Cells, issueR26Decision, issueR26Evidence, issueR26Manifest, loadR26State, saveR26Json, saveR26State, type R26Kind, type R26Response } from "./r26-acquisition";
const COMMANDS = ["init", "status", "issue-manifest", "accept-manifest", "issue-evidence", "accept-evidence", "issue-decision", "accept-decision", "assemble"] as const; type Command = typeof COMMANDS[number]; function parse(argv: string[]) { const command = argv.shift() as Command, flags = new Map<string, string>(); if (!(COMMANDS as readonly string[]).includes(command)) throw Error(`usage: r26-acquire <${COMMANDS.join("|")}> [options]`); while (argv.length) { const k = argv.shift()!, v = argv.shift(); if (!k.startsWith("--") || v === undefined || flags.has(k)) throw Error("R26 acquisition arguments invalid"); flags.set(k, v); } const required = (k: string) => { const v = flags.get(k); if (!v) throw Error(`R26 acquisition ${k} required`); return v; }; return { command, required }; } const json = (path: string) => JSON.parse(readFileSync(path, "utf8"));
export async function runR26AcquisitionCli(argv: string[]) { const { command, required } = parse([...argv]), statePath = required("--state"); if (command === "init") { if (existsSync(statePath)) throw Error("R26 acquisition state already exists"); const s = createR26State(json(required("--registry"))); saveR26State(statePath, s); return { campaignId: s.campaignId, manifestDigest: s.manifestDigest }; } const s = loadR26State(statePath); if (command === "status") return { campaignId: s.campaignId, manifest: !!s.manifest?.response, required: s.domains && Object.fromEntries(Object.entries(expectedR26Cells(s)).map(([k, v]) => [k, v.length])), accepted: Object.fromEntries(Object.entries(s.evidence).map(([k, v]) => [k, Object.values(v).filter((x) => x.response).length])), decision: !!s.decision?.response, assembledBundleDigest: s.assembledBundleDigest };
  const response = () => json(required("--response")) as R26Response, durable = (value: unknown) => { saveR26State(statePath, s); saveR26Json(required("--out"), value); }; let result: unknown;
  if (command === "issue-manifest") { const q = issueR26Manifest(s); durable(q); result = { action: q.action }; } else if (command === "accept-manifest") result = { responseDigest: acceptR26Manifest(s, response()) };
  else if (command === "issue-evidence") { const kind = required("--kind") as R26Kind, id = required("--cell"), q = issueR26Evidence(s, kind, id); durable(q); result = { kind, cell: id, ordinal: q.ordinal }; } else if (command === "accept-evidence") { const kind = required("--kind") as R26Kind, id = required("--cell"); result = { responseDigest: acceptR26Evidence(s, kind, id, response()) }; }
  else if (command === "issue-decision") { const q = issueR26Decision(s); durable(q); result = { prerequisites: q.prerequisiteDigests.length }; } else if (command === "accept-decision") result = { responseDigest: acceptR26Decision(s, response()) };
  else { const certificate = assembleR26(s); durable(certificate); result = { bundleDigest: s.assembledBundleDigest }; } saveR26State(statePath, s); return result;
}
if (import.meta.main) runR26AcquisitionCli(process.argv.slice(2)).then((x) => console.log(JSON.stringify(x))).catch((e) => { console.error(e instanceof Error ? e.message : e); process.exitCode = 1; });
