// The local runner's defaults — declared ONCE, owned by the substrate. Every consumer reads these: the
// in-process TermfleetRunner (runner.ts), the vendored backend emitted into installs (backend.mjs), and
// the launch driver (run-agent.mjs). The TERMFLEET_* env vars are runtime OVERRIDES, not the home of the
// default. `harness` is which coding CLI termfleet launches: 'claude' (Claude Code) | 'codex'.
export const RUNNER_DEFAULTS = {
  cli: 'termfleet',
  harness: 'claude',
  providerUrl: 'http://127.0.0.1:7376',
  launchTimeoutMs: 45000,
} as const;

// Emitted into installs so the vendored JS runtime (plain .mjs, no TS/bundler) can import the same
// defaults instead of re-hardcoding them. Kept byte-stable with RUNNER_DEFAULTS above.
export function runnerDefaultsModule(): string {
  return `// Generated by @open-autonomy/substrate-local. The local runner's defaults; TERMFLEET_* env vars override.\nexport const RUNNER_DEFAULTS = ${JSON.stringify(RUNNER_DEFAULTS, null, 2)};\n`;
}
