// The local runner's defaults — declared ONCE, owned by the substrate. Every consumer reads these: the
// in-process TermfleetRunner (runner.ts), the vendored backend emitted into installs (backend.mjs), and
// the launch driver (run-agent.mjs). The TERMFLEET_* env vars are runtime OVERRIDES, not the home of the
// default. `harness` is which coding CLI termfleet launches: 'claude' (Claude Code) | 'codex'.
export const RUNNER_DEFAULTS = {
  cli: 'termfleet',
  harness: 'claude',
  // No providerUrl default on purpose: termfleet now resolves a provider itself
  // (TERMFLEET_PROVIDER_URL -> `termfleet use` context -> live local auto-discovery).
  // A baked-in port was the crutch that drifted to a dead provider; the runner
  // passes --url only when TERMFLEET_PROVIDER_URL is explicitly set.
  //
  // createAgentWindow BLOCKS until the launched agent's first response (claude cold-start + the setup
  // command), so its socket ack needs a generous timeout — the SDK default is far too short and the window
  // gets created server-side while the client times out, losing the terminalId (and so the post-session
  // effect marker). createTimeoutMs is that ack budget; launchTimeoutMs (the outer spawn cap) must exceed it.
  createTimeoutMs: 120000,
  launchTimeoutMs: 150000,
} as const;

// Emitted into installs so the vendored JS runtime (plain .mjs, no TS/bundler) can import the same
// defaults instead of re-hardcoding them. Kept byte-stable with RUNNER_DEFAULTS above.
export function runnerDefaultsModule(): string {
  return `// Generated by @open-autonomy/substrate-local. The local runner's defaults; TERMFLEET_* env vars override.\nexport const RUNNER_DEFAULTS = ${JSON.stringify(RUNNER_DEFAULTS, null, 2)};\n`;
}
