import {describe,expect,test} from 'bun:test';
import type {ComponentManifestV2} from './organization-component';
import type {OrganizationIR} from './organization-ir';
import {solveCertifiedDeployment,type DeploymentFiniteDomain} from './organization-deployment-solver';
import {verifyCertifiedDeploymentResult} from './organization-deployment-certificate';
import {deriveAtomicObligations,validateDeploymentCandidate,type AssurancePolicy} from './organization-solver';

const observed={assurance:'conformance-tested' as const,source:{uri:'test:provider'},observedAt:'2026-07-14T00:00:00Z'};
function manifest(id:string,options:{cost:number;capacity:number;minimum?:number;requires?:string[];region?:string;version?:string}):ComponentManifestV2{return{schema:'autonomy.component.v2',id,version:options.version??'1',configuration:{id:`${id}.config`,version:'1'},facets:{actor:{facet:'actor',operations:['run','identity'],interface:'api',evidence:observed},behavior:{facet:'behavior',operations:['invoke'],interface:'api',evidence:observed}},interfaces:{api:{id:'api',version:'1',transport:'function'}},state:[],trust:[{principal:id,zone:'test',enforcedBy:'process',evidence:observed}],failure:{detection:['probe'],healthCriterion:'ok',recovery:['restart'],upgrade:'replace',rollback:'restore',evidence:observed},topology:{mode:'standalone',minimumInstances:options.minimum??1,maximumInstances:3,isolation:'process',placement:[options.region??'us-east'],evidence:observed},capacity:[{value:options.capacity,unit:'concurrent-invocations',attribution:id,uncertainty:'exact',effectiveAt:'2026-07-14',evidence:observed}],cost:[{value:options.cost,unit:'USD',per:'month',attribution:'deployment',uncertainty:'exact',effectiveAt:'2026-07-14',evidence:observed}],requires:options.requires,extensions:{deployment:{regions:[options.region??'us-east'],tenants:['t1'],dataResidency:[options.region??'us-east'],credentials:['oidc'],upgradeFrom:['0']}}};}
const org:OrganizationIR={schema:'autonomy.organization.v2',name:'r7',behaviors:{work:{kind:'skill',inline:{procedure:'work'}}},actors:{worker:{kind:'agent',behaviors:['work']}}};
const policy:AssurancePolicy={minimum:{low:'conformance-tested',medium:'conformance-tested',high:'conformance-tested',critical:'conformance-tested'},allowApproximation:false,acceptedAssumptions:[],asOf:'2026-07-15T00:00:00Z',maxEvidenceAgeMs:7*86_400_000};
const domain=(constraints:DeploymentFiniteDomain['constraints']=[],maxAssignments=100):DeploymentFiniteDomain=>({completeness:'finite-exhaustive',maxAssignments,maxInstancesPerManifest:3,constraints});

describe('R7 certified finite deployment solver',()=>{
  test('constructively witnesses every required hard-constraint class',()=>{const worker=manifest('worker',{cost:5,capacity:1});const constraints:DeploymentFiniteDomain['constraints']=[{id:'version',class:'version',manifest:'worker',allowed:['1']},{id:'region',class:'region',allowed:['us-east']},{id:'tenant',class:'tenant',allowed:['t1']},{id:'topology',class:'topology',modes:['standalone'],isolations:['process']},{id:'cardinality',class:'cardinality',manifest:'worker',minimum:1,maximum:1},{id:'capacity',class:'capacity',unit:'concurrent-invocations',attribution:'worker',minimum:1},{id:'slo',class:'slo',unit:'concurrent-invocations',attribution:'worker',maximum:1},{id:'residency',class:'data-residency',allowed:['us-east']},{id:'credential',class:'credential',allowed:['oidc']},{id:'upgrade',class:'upgrade',allowed:['0']},{id:'cost',class:'cost',unit:'USD',per:'month',attribution:'deployment',maximum:5}];const finite=domain(constraints),result=solveCertifiedDeployment(org,{worker},{},policy,finite);expect(result.status).toBe('compatible');expect(result.frontier[0]?.certificate.constraintWitnesses.map(x=>x.class).sort()).toEqual(['capacity','cardinality','cost','credential','data-residency','region','slo','tenant','topology','upgrade','version']);expect(verifyCertifiedDeploymentResult(result,org,{worker},{},policy,finite)).toEqual({valid:true,errors:[]});});
  test('enumerates support-only components and cardinality, and proves its finite search boundary',()=>{const worker=manifest('worker',{cost:10,capacity:2,minimum:2,requires:['storage']});const support=manifest('support',{cost:1,capacity:1});support.facets={storage:{facet:'storage',operations:['represent'],interface:'api',evidence:observed}};const catalog={worker,support};const result=solveCertifiedDeployment(org,catalog,{},policy,domain([{id:'workers',class:'cardinality',manifest:'worker',minimum:2,maximum:2}]));expect(result.status).toBe('compatible');expect(result.complete).toBe(true);expect(result.explored).toBe(result.domainCardinality);expect(result.frontier[0]?.composition.instances).toMatchObject({'worker#0':{manifest:'worker'},'worker#1':{manifest:'worker'},'support#0':{manifest:'support'}});});
  test('uses the same exact manifest-id dependency semantics in producer and verifier',()=>{const worker=manifest('worker',{cost:1,capacity:1,requires:['support']}),support=manifest('support',{cost:1,capacity:1}),catalog={worker,support},finite=domain([{id:'worker',class:'cardinality',manifest:'worker',minimum:1}]);const result=solveCertifiedDeployment(org,catalog,{},policy,finite);expect(result.status).toBe('compatible');expect(result.frontier.every(x=>Object.values(x.composition.instances).some(i=>i.manifest==='support'))).toBe(true);expect(verifyCertifiedDeploymentResult(result,org,catalog,{},policy,finite).valid).toBe(true);});
  test('applies hard feasibility before Pareto economics and never adds unlike dimensions',()=>{const catalog={cheap:manifest('cheap',{cost:1,capacity:1}),capable:manifest('capable',{cost:5,capacity:8})};const result=solveCertifiedDeployment(org,catalog,{},policy,domain([{id:'capacity',class:'capacity',unit:'concurrent-invocations',attribution:'capable',minimum:8}]));expect(result.status).toBe('compatible');expect(result.frontier.every(x=>Object.values(x.composition.instances).some(i=>i.manifest==='capable'))).toBe(true);for(const candidate of result.frontier)expect(candidate.certificate.objective.map(x=>`${x.unit}/${x.per??''}/${x.attribution}`)).toContain('USD/month/deployment');});
  test('keeps optional economics outside feasibility and time-binds hard quantities',()=>{const worker=manifest('worker',{cost:1,capacity:1}),catalog={worker};worker.cost![0].effectiveAt='2020-01-01';expect(solveCertifiedDeployment(org,catalog,{},policy,domain()).status).toBe('compatible');const finite=domain([{id:'cost-bound',class:'cost',unit:'USD',per:'month',attribution:'deployment',maximum:2}]);expect(solveCertifiedDeployment(org,catalog,{},policy,finite).status).toBe('incompatible');const acceptedPolicy={...policy,acceptedAssumptions:[{assumption:'quantity:cost-bound:stale',acceptedBy:'operator',scope:'cost-bound',untilVersion:'1'}]},accepted=solveCertifiedDeployment(org,catalog,{},acceptedPolicy,finite);expect(accepted.status).toBe('compatible');expect(accepted.frontier[0]!.certificate.constraintWitnesses[0]!.assumptions).toContain('operator:quantity:cost-bound:stale');expect(verifyCertifiedDeploymentResult(accepted,org,catalog,{},acceptedPolicy,finite)).toEqual({valid:true,errors:[]});});
  test('returns bounded exhaustion without an UNSAT claim',()=>{const result=solveCertifiedDeployment(org,{worker:manifest('worker',{cost:1,capacity:1})},{},policy,domain([],0));expect(result).toMatchObject({status:'exhausted',complete:false,explored:0,unsatisfiedCore:[]});});
  test('verifies bounded compatible prefixes and rejects forged result-state shapes',()=>{const worker=manifest('worker',{cost:1,capacity:1}),catalog={worker},finite={...domain([],1),completeness:'bounded-heuristic' as const};const result=solveCertifiedDeployment(org,catalog,{},policy,finite);expect(result).toMatchObject({status:'compatible',complete:false,explored:1});expect(verifyCertifiedDeploymentResult(result,org,catalog,{},policy,finite)).toEqual({valid:true,errors:[]});const forged=structuredClone(result);forged.status='exhausted';expect(verifyCertifiedDeploymentResult(forged,org,catalog,{},policy,finite).errors.join(' ')).toContain('exhaustion requires an empty frontier');const empty=structuredClone(forged);empty.frontier=[];expect(verifyCertifiedDeploymentResult(empty,org,catalog,{},policy,finite).errors.join(' ')).toContain('feasible candidates in its explored prefix');});
  test('closes compatible and invalid result variants',()=>{const worker=manifest('worker',{cost:1,capacity:1}),catalog={worker},finite=domain(),result=solveCertifiedDeployment(org,catalog,{},policy,finite),forged=structuredClone(result);forged.unsatisfiedCore=[{id:'fake',class:'semantic',reason:'fake'}];forged.coreMinimality='classified';expect(verifyCertifiedDeploymentResult(forged,org,catalog,{},policy,finite).errors.join(' ')).toContain('cannot carry an unsatisfied core');const invalidDomain={...finite,maxInstancesPerManifest:0},invalid=solveCertifiedDeployment(org,catalog,{},policy,invalidDomain);expect(invalid.status).toBe('invalid');expect(verifyCertifiedDeploymentResult(invalid,org,catalog,{},policy,invalidDomain)).toEqual({valid:true,errors:[]});const fakeInvalid={...structuredClone(invalid),errors:['fake']};expect(verifyCertifiedDeploymentResult(fakeInvalid,org,catalog,{},policy,finite).errors.join(' ')).toContain('does not match independently');});
  test('returns a subset-minimal classified core for contradictory region constraints',()=>{const catalog={worker:manifest('worker',{cost:1,capacity:1,region:'us-east'})};const result=solveCertifiedDeployment(org,catalog,{},policy,domain([{id:'eu-only',class:'region',allowed:['eu-west']},{id:'any-version',class:'version',allowed:['1']}]));expect(result.status).toBe('incompatible');expect(result.coreMinimality).toBe('subset-minimal');expect(result.unsatisfiedCore.map(x=>x.id)).toEqual(['eu-only']);});
  test('rejects stale live evidence unless a scoped acceptance exists',()=>{const stale=manifest('worker',{cost:1,capacity:1});for(const facet of Object.values(stale.facets))facet.evidence={...facet.evidence,observedAt:'2020-01-01'};const result=solveCertifiedDeployment(org,{worker:stale},{},{...policy,maxEvidenceAgeMs:1000},domain([{id:'region',class:'region',allowed:['us-east']}]));expect(result.status).toBe('incompatible');});
  test('binds, records, and independently verifies stale semantic-evidence acceptances',()=>{const stale=manifest('worker',{cost:1,capacity:1,version:'2'});for(const facet of Object.values(stale.facets))facet.evidence={...facet.evidence,observedAt:'2020-01-01'};const acceptances=(untilVersion:string)=>deriveAtomicObligations(org).map(obligation=>({assumption:`evidence:${obligation.id}:stale`,acceptedBy:'operator',scope:obligation.id,untilVersion}));expect(solveCertifiedDeployment(org,{worker:stale},{},{...policy,acceptedAssumptions:acceptances('1')},domain()).status).toBe('incompatible');const acceptedPolicy={...policy,acceptedAssumptions:acceptances('2')},accepted=solveCertifiedDeployment(org,{worker:stale},{},acceptedPolicy,domain());expect(accepted.status).toBe('compatible');expect(accepted.frontier[0]!.ledger.witnesses.every(x=>!x.evidence||x.assumptions.some(a=>a.startsWith('operator:evidence:')))).toBe(true);const forged=structuredClone(accepted);for(const witness of forged.frontier[0]!.ledger.witnesses)witness.assumptions=[];expect(verifyCertifiedDeploymentResult(forged,org,{worker:stale},{},acceptedPolicy,domain()).errors.join(' ')).toContain('semantic ledger does not match');});
  test('keeps unlike economic horizons incomparable on the frontier',()=>{const monthly=manifest('monthly',{cost:10,capacity:1});const perRun=manifest('per-run',{cost:1,capacity:1});perRun.cost![0].per='run';perRun.cost![0].attribution='execution';const result=solveCertifiedDeployment(org,{monthly,perRun},{},policy,domain());expect(result.status).toBe('compatible');const dimensions=result.frontier.flatMap(x=>x.certificate.objective.map(y=>`${y.unit}/${y.per}/${y.attribution}`));expect(dimensions).toContain('USD/month/deployment');expect(dimensions).toContain('USD/run/execution');});
  test('does not let uncertain point estimates dominate exact values',()=>{const exact=manifest('exact',{cost:10,capacity:1});const volatile=manifest('volatile',{cost:1,capacity:1});volatile.cost![0].uncertainty='volatile';const result=solveCertifiedDeployment(org,{exact,volatile},{},policy,domain());expect(result.status).toBe('compatible');expect(result.frontier.some(x=>Object.values(x.composition.instances).some(i=>i.manifest==='exact'))).toBe(true);expect(result.frontier.some(x=>x.certificate.objective.some(y=>y.uncertainty==='volatile'))).toBe(true);});
  test('binds asserted semantic acceptance to the selected provider version',()=>{const assertedManifest=manifest('asserted',{cost:1,capacity:1,version:'2'});for(const facet of Object.values(assertedManifest.facets))facet.evidence={assurance:'asserted',source:{uri:'test:asserted'}};const assumptions=Object.keys(assertedManifest.facets).map(facet=>({assumption:`trust:asserted:${facet}:asserted`,acceptedBy:'operator',scope:'*',untilVersion:'1'}));const candidate=validateDeploymentCandidate(deriveAtomicObligations(org),{instances:{p:{manifest:'asserted'}},authorities:{}},{asserted:assertedManifest},{},{...policy,minimum:{low:'asserted',medium:'asserted',high:'asserted',critical:'asserted'},acceptedAssumptions:assumptions});expect(candidate.ledger.unresolved.length).toBeGreaterThan(0);});
  test('requires endpoint-specific adapters and constructs independently verified ordered migration paths',()=>{const worker=manifest('worker',{cost:1,capacity:1});const obligation=deriveAtomicObligations(org)[0];const adapter={schema:'autonomy.adapter.v1' as const,id:'work-v1-v2',version:'1',direction:'bridge' as const,from:{id:'work.v1',version:'1'},to:{id:'work.v2',version:'2'},interfaceMappings:[{from:'native',to:obligation.facet}],identity:'preserved' as const,causality:'preserved' as const,retry:'preserved' as const,conflicts:'preserved' as const,preconditions:['v1'],postconditions:['v2'],losses:[],reversible:false,evidence:observed};const other={...adapter,id:'other-adapter'};const constraints:DeploymentFiniteDomain['constraints']=[{id:'bridge',class:'adapter',adapter:'work-v1-v2',from:'work.v1',to:'work.v2',obligations:[obligation.id]},{id:'upgrade',class:'migration',kind:'component',from:'1',to:'3',obligations:[obligation.id]}];const finite={...domain(constraints),allowedAdapters:[adapter.id,other.id],migrations:[{id:'one-two',kind:'component' as const,from:'1',to:'2',lossy:false,sourcePaths:[obligation.path],rollback:'two-one'},{id:'two-three',kind:'component' as const,from:'2',to:'3',lossy:false,sourcePaths:[obligation.path],rollback:'three-two'},{id:'wrong-kind',kind:'organization' as const,from:'1',to:'3',lossy:false,sourcePaths:[obligation.path],rollback:'back'}]};const catalog={worker},adapters={[adapter.id]:adapter,[other.id]:other};const result=solveCertifiedDeployment(org,catalog,adapters,policy,finite);expect(result.status).toBe('compatible');expect(result.frontier[0]?.certificate.plan.adapters[0]?.adapter).toBe(adapter.id);expect(result.frontier[0]?.certificate.plan.adapters[0]?.obligations).toEqual([obligation.id]);expect(result.frontier[0]?.certificate.plan.migrations[0]?.steps).toEqual(['one-two','two-three']);expect(verifyCertifiedDeploymentResult(result,org,catalog,adapters,policy,finite)).toEqual({valid:true,errors:[]});const wrongAdapter=structuredClone(result);wrongAdapter.frontier[0]!.certificate.plan.adapters[0]!.adapter=other.id;expect(verifyCertifiedDeploymentResult(wrongAdapter,org,catalog,adapters,policy,finite).errors.join(' ')).toContain('invalid adapter witness');const wrongMigration=structuredClone(result);wrongMigration.frontier[0]!.certificate.plan.migrations[0]!.steps=['wrong-kind'];expect(verifyCertifiedDeploymentResult(wrongMigration,org,catalog,adapters,policy,finite).errors.join(' ')).toContain('invalid migration step');});
  test('independent replay rejects composition substitution despite intact witness labels',()=>{const weak=manifest('weak',{cost:1,capacity:1}),strong=manifest('strong',{cost:2,capacity:8});const catalog={weak,strong},finite=domain([{id:'strong-capacity',class:'capacity',unit:'concurrent-invocations',attribution:'strong',minimum:8}]);const result=solveCertifiedDeployment(org,catalog,{},policy,finite);expect(result.status).toBe('compatible');const forged=structuredClone(result);const candidate=forged.frontier[0]!;for(const instance of Object.values(candidate.composition.instances))if(instance.manifest==='strong')instance.manifest='weak';const verification=verifyCertifiedDeploymentResult(forged,org,catalog,{},policy,finite);expect(verification.valid).toBe(false);expect(verification.errors.join(' ')).toContain('capacity constraint');});
  test('independent replay rejects forged economics and forged UNSAT cores',()=>{const worker=manifest('worker',{cost:5,capacity:1}),catalog={worker};const solved=solveCertifiedDeployment(org,catalog,{},policy,domain());const forged=structuredClone(solved);forged.frontier[0]!.certificate.objective[0]!.value=0;expect(verifyCertifiedDeploymentResult(forged,org,catalog,{},policy,domain()).errors.join(' ')).toContain('objective does not match');const finite=domain([{id:'eu',class:'region',allowed:['eu-west']}]);const incompatible=solveCertifiedDeployment(org,catalog,{},policy,finite);expect(incompatible.status).toBe('incompatible');const badCore=structuredClone(incompatible);badCore.unsatisfiedCore=[];expect(verifyCertifiedDeploymentResult(badCore,org,catalog,{},policy,finite).errors.join(' ')).toContain('no unsatisfied core');});
  test('independent replay rejects an empty or partial compatible frontier',()=>{const a=manifest('a',{cost:1,capacity:1}),b=manifest('b',{cost:1,capacity:1}),catalog={a,b},finite=domain(),solved=solveCertifiedDeployment(org,catalog,{},policy,finite);expect(solved.frontier.length).toBeGreaterThan(1);const omitted=structuredClone(solved);omitted.frontier=[];expect(verifyCertifiedDeploymentResult(omitted,org,catalog,{},policy,finite).errors.join(' ')).toContain('omits or adds');});
  test('independent replay rejects stale hard evidence and honors scoped stale objective acceptance',()=>{
    const worker=manifest('worker',{cost:5,capacity:1}),catalog={worker},finite=domain([{id:'topology',class:'topology',modes:['standalone']}]);
    const solved=solveCertifiedDeployment(org,catalog,{},policy,finite);expect(solved.status).toBe('compatible');
    const staleCatalog=structuredClone(catalog);staleCatalog.worker.topology.evidence.observedAt='2020-01-01';
    expect(verifyCertifiedDeploymentResult(solved,org,staleCatalog,{},policy,finite).errors.join(' ')).toContain('evidence or freshness');
    const staleResult=solveCertifiedDeployment(org,staleCatalog,{},policy,finite);expect(staleResult.status).toBe('incompatible');expect(verifyCertifiedDeploymentResult(staleResult,org,staleCatalog,{},policy,finite)).toEqual({valid:true,errors:[]});
    const acceptedCatalog=structuredClone(catalog);acceptedCatalog.worker.cost![0].effectiveAt='2020-01-01';
    const scope='objective:worker:cost:USD',acceptedPolicy={...policy,acceptedAssumptions:[{assumption:`quantity:${scope}:stale`,acceptedBy:'operator',scope:'*'}]};
    const accepted=solveCertifiedDeployment(org,acceptedCatalog,{},acceptedPolicy,domain());expect(accepted.errors).toEqual([]);expect(accepted.status).toBe('compatible');expect(accepted.frontier[0]!.certificate.objective.some(x=>x.assumptions.includes(`operator:quantity:${scope}:stale`))).toBe(true);
    expect(verifyCertifiedDeploymentResult(accepted,org,acceptedCatalog,{},acceptedPolicy,domain())).toEqual({valid:true,errors:[]});
    const assertedCatalog=structuredClone(catalog);assertedCatalog.worker.cost![0].evidence={assurance:'asserted',source:{uri:'test:asserted-cost'}};
    const assertedPolicy={...policy,acceptedAssumptions:[{assumption:`evidence:${scope}:asserted`,acceptedBy:'operator',scope:'*'}]};
    const asserted=solveCertifiedDeployment(org,assertedCatalog,{},assertedPolicy,domain());expect(asserted.status).toBe('compatible');
    expect(verifyCertifiedDeploymentResult(asserted,org,assertedCatalog,{},assertedPolicy,domain())).toEqual({valid:true,errors:[]});
    const wrongVersion={...policy,acceptedAssumptions:[{assumption:`evidence:${scope}:asserted`,acceptedBy:'operator',scope:'*',untilVersion:'0'}]},withoutWrongVersionEconomics=solveCertifiedDeployment(org,assertedCatalog,{},wrongVersion,domain());expect(withoutWrongVersionEconomics.status).toBe('compatible');expect(withoutWrongVersionEconomics.frontier.every(x=>x.certificate.objective.every(y=>y.unit!=='USD'))).toBe(true);
    const malformedExpiry={...policy,acceptedAssumptions:[{assumption:`evidence:${scope}:asserted`,acceptedBy:'operator',scope:'*',expires:'not-a-date'}]},withoutMalformedAcceptance=solveCertifiedDeployment(org,assertedCatalog,{},malformedExpiry,domain());expect(withoutMalformedAcceptance.status).toBe('compatible');expect(withoutMalformedAcceptance.frontier.every(x=>x.certificate.objective.every(y=>y.unit!=='USD'))).toBe(true);
  });
  test('rejects adapter and migration bindings unrelated to their claimed semantic leaf',()=>{const worker=manifest('worker',{cost:1,capacity:1}),obligations=deriveAtomicObligations(org),behavior=obligations.find(x=>x.facet==='behavior')!;const adapter={schema:'autonomy.adapter.v1' as const,id:'actor-only',version:'1',direction:'bridge' as const,from:{id:'x',version:'1'},to:{id:'y',version:'1'},interfaceMappings:[{from:'x',to:'actor'}],identity:'preserved' as const,causality:'preserved' as const,retry:'preserved' as const,conflicts:'preserved' as const,preconditions:['x'],postconditions:['y'],losses:[],reversible:false,evidence:observed};const finite={...domain([{id:'bad-adapter',class:'adapter' as const,adapter:adapter.id,from:'x',to:'y',obligations:[behavior.id]}]),allowedAdapters:[adapter.id]};expect(solveCertifiedDeployment(org,{worker},{[adapter.id]:adapter},policy,finite).status).toBe('incompatible');const migrationDomain={...domain([{id:'bad-migration',class:'migration' as const,kind:'component' as const,from:'1',to:'2',obligations:[behavior.id]}]),migrations:[{id:'edge',kind:'component' as const,from:'1',to:'2',lossy:false,sourcePaths:['actors'],rollback:'back'}]};expect(solveCertifiedDeployment(org,{worker},{},policy,migrationDomain).status).toBe('incompatible');});
  test('requires the exact constructive adapter plan inventory',()=>{const worker=manifest('worker',{cost:1,capacity:1}),obligation=deriveAtomicObligations(org)[0],adapter={schema:'autonomy.adapter.v1' as const,id:'mapped',version:'1',direction:'bridge' as const,from:{id:'x',version:'1'},to:{id:'y',version:'1'},interfaceMappings:[{from:'x',to:obligation.facet}],identity:'preserved' as const,causality:'preserved' as const,retry:'preserved' as const,conflicts:'preserved' as const,preconditions:['x'],postconditions:['y'],losses:[],reversible:false,evidence:observed},catalog={worker},adapters={mapped:adapter},finite={...domain([{id:'mapping',class:'adapter' as const,adapter:'mapped',from:'x',to:'y',obligations:[obligation.id]}]),allowedAdapters:['mapped']};const result=solveCertifiedDeployment(org,catalog,adapters,policy,finite);expect(result.status).toBe('compatible');const forged=structuredClone(result);forged.frontier[0]!.certificate.plan.adapters=[];expect(verifyCertifiedDeploymentResult(forged,org,catalog,adapters,policy,finite).errors.join(' ')).toContain('exact adapter plan inventory');});
  test('requires an explicit freshness clock and age bound',()=>{const result=solveCertifiedDeployment(org,{worker:manifest('worker',{cost:1,capacity:1})},{},{...policy,maxEvidenceAgeMs:undefined},domain());expect(result.status).toBe('invalid');expect(result.errors.join(' ')).toContain('maxEvidenceAgeMs');});
  test('generated finite domains are stable under registry order and independently replay',()=>{for(let seed=1;seed<=12;seed++){const a=manifest(`a${seed}`,{cost:seed,capacity:(seed%3)+1}),b=manifest(`b${seed}`,{cost:13-seed,capacity:(seed%4)+1}),catalog={[a.id]:a,[b.id]:b},reversed={[b.id]:b,[a.id]:a},finite=domain([],50);const first=solveCertifiedDeployment(org,catalog,{},policy,finite),second=solveCertifiedDeployment(org,reversed,{},policy,finite);expect(first.status).toBe('compatible');expect(first.frontier.map(x=>x.objective.key)).toEqual(second.frontier.map(x=>x.objective.key));expect(verifyCertifiedDeploymentResult(first,org,catalog,{},policy,finite).valid).toBe(true);}});
});
