import{createHash}from"node:crypto";import{canonicalSemanticJson}from"./organization-canonical";
export type CensusRange={stars:[number,number];created?:[string,string]};
export type CensusTuple={node_id:string;full_name:string;stargazers_count:number;fork:boolean;archived:boolean};
export function splitStarRange([lo,hi]:[number,number]):[[number,number],[number,number]]{if(!Number.isSafeInteger(lo)||!Number.isSafeInteger(hi)||lo>=hi)throw Error("star range is not splittable");const mid=Math.floor((lo+hi)/2);return[[lo,mid],[mid+1,hi]]}
const epochDay=(date:string)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(date))throw Error("invalid UTC date");const value=Date.parse(`${date}T00:00:00Z`);if(!Number.isFinite(value))throw Error("invalid UTC date");return value/86_400_000},dateOf=(day:number)=>new Date(day*86_400_000).toISOString().slice(0,10);
export function splitCreationRange([lo,hi]:[string,string]):[[string,string],[string,string]]{const a=epochDay(lo),b=epochDay(hi);if(a>=b)throw Error("creation range is unpartitionable");const mid=Math.floor((a+b)/2);return[[dateOf(a),dateOf(mid)],[dateOf(mid+1),dateOf(b)]]}
export function assertAcceptedGitHubSearch(value:unknown){if(!value||typeof value!=="object")throw Error("malformed response schema");const v=value as any;if(!Number.isSafeInteger(v.total_count)||v.total_count<0||typeof v.incomplete_results!=="boolean"||!Array.isArray(v.items))throw Error("malformed response schema");for(const item of v.items)if(!item||typeof item!=="object"||typeof item.node_id!=="string"||!item.node_id||typeof item.full_name!=="string"||!item.full_name||!Number.isSafeInteger(item.stargazers_count)||item.stargazers_count<0||typeof item.fork!=="boolean"||typeof item.archived!=="boolean"||typeof item.default_branch!=="string"||!item.default_branch)throw Error("malformed response item");return v as{total_count:number;incomplete_results:boolean;items:any[]}}
export function censusTupleDigest(rows:CensusTuple[]){const sorted=rows.map(x=>[x.node_id,x.full_name,x.stargazers_count,x.fork,x.archived]as const).sort((a,b)=>a[0].localeCompare(b[0]));return`sha256:${createHash("sha256").update(canonicalSemanticJson(sorted)).digest("hex")}` as const}
export function leafCountDigest(entries:Array<[string,number]>){const map=Object.fromEntries([...entries].sort(([a],[b])=>a.localeCompare(b)));return`sha256:${createHash("sha256").update(canonicalSemanticJson(map)).digest("hex")}` as const}
export function selectOutDomainReview(nodeIds:string[]){const unique=[...new Set(nodeIds)];if(unique.length!==nodeIds.length)throw Error("duplicate review identity");return unique.map(nodeId=>({nodeId,digest:createHash("sha256").update("open-autonomy.u1.out-domain-review.v1\0").update(nodeId,"utf8").digest()})).sort((a,b)=>Buffer.compare(a.digest,b.digest)||Buffer.from(a.nodeId).compare(Buffer.from(b.nodeId))).slice(0,Math.ceil(unique.length/100)).map(x=>x.nodeId)}
