import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import { readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { canonicalSemanticJson as C } from "./organization-canonical";
import { verifyFrozenU3ObservationCalculus, type FrozenU3ObservationCalculus } from "./organization-u3-observation-calculus";

type Sha = `sha256:${string}`;
export const U4_SOURCE_INVENTORY_SCHEMA = "open-autonomy.u4-source-inventory.v1" as const;
export const U4_FACT_TAXONOMY = [
  "authority", "configuration", "evidence", "extensions", "failure", "lifecycle",
  "omissions", "prompt-context", "resource", "runtime", "safety-security",
] as const;
export type U4FactTaxonomy = (typeof U4_FACT_TAXONOMY)[number];
export const U4_U3_ANCHORS = {
  closureCommit: "7af2e958a7d92157bda932070b6763b3cde6f6d6",
  closurePath: "docs/universality/campaign-v9/u3-implementation-closure.json",
  closureSha256: "sha256:9d043694ae78e2fd61ddc96bbf21d9331f03e26beb50a11098ddcff03fb64fb0",
  validatorPath: "packages/core/src/organization-u3-implementation-closure.ts",
  validatorSha256: "sha256:231ee6398b0b43631eaafb594a388658379f9ba8e1373419a89e146f36c3e550",
} as const;
export const U4_V9_CHRONOLOGY_ANCHOR={claimDigest:"sha256:b8da679f4242e5a10dba70eb365041bc54e284751fcd879736dad37e3feec18a" as Sha,cutoffAt:"2026-07-30T23:59:59.999Z"} as const;

type AuthorityRole = "official-spec-publisher" | "native-schema-publisher" | "runtime-probe-operator" | "source-behavior-observer" | "independent-adjudicator" | "evidence-custodian" | "semantic-inventory-authority" | "inventory-freezer" | "frontend";
type ProvenanceKind = "official-spec" | "native-schema" | "runtime-probe" | "source-behavior";
export type FrozenU4SyntheticSourceRegistry = {
  schema: "open-autonomy.u4-synthetic-source-registry.v1"; fixtureKind: "synthetic";
  populationBoundary: "synthetic-fixture-only-external-u1-release-deferred";
  genericRegistryRelease: "deferred-external-validation";
  u1BoundaryStatus: "implementation-complete-external-validation-deferred";
  sources: Array<{ id: string; sourceSystemId: string; nativeVersion: string; sourceOwnerId: string; stratumId: string; profileId: string; taxonomyFloors: Array<{taxonomy:U4FactTaxonomy;minimum:"critical"|"noncritical";rationale:string}> }>;
  digest: Sha;
};
export type U4SourceInventory = {
  schema: typeof U4_SOURCE_INVENTORY_SCHEMA;
  fixtureKind: "synthetic";
  denominatorScope: "fixture-local";
  empiricalRegistration: false;
  closureClaim: false;
  campaignId: "organization-universality-2026-v9";
  u3Anchors: typeof U4_U3_ANCHORS;
  sourceRegistryDigest: Sha;
  calculusDigest: Sha;
  assurance: { level: "synthetic-contract-only"; externalTruth: "deferred"; promotionAllowed: false };
  authorities: Array<{ id: string; ownerId: string; role: AuthorityRole; trustRootSha256: Sha; verificationKeyDigest: Sha }>;
  sources: Array<{ id: string; sourceSystemId: string; sourceImplementerOwnerId: string; frontendOwnerId: string; stratumId: string; profileId: string; factIds: string[] }>;
  provenance: Array<{ id: string; sourceId:string; nativeSchemaId:string|null; kind: ProvenanceKind; producerAuthorityId: string; custodyAuthorityId:string; sourceVersion: string; mediaType: string; acquiredAt: string; bytesBase64: string; byteLength: number; sha256: Sha; bodyReceipt: string; custodyReceipt: string }>;
  nativeSchemas: Array<{ id: string; version: string; sourceId: string; pathPrefix: string; valueShape: {type:"boolean"|"string"|"number"|"object"|"array"|"null"}; schemaBytesBase64: string; schemaSha256: Sha; semanticSchemaDigest:Sha; producerAuthorityId:string; custodyAuthorityId:string; producerReceipt:string; custodyReceipt:string }>;
  facts: Array<{
    id: string; sourceId: string; taxonomy: U4FactTaxonomy; nativePath: string;
    nativeSchemaId: string; nativeSchemaVersion: string; denotation: string;
    default: { status: "present"; valueJson: string } | { status: "absent"; valueJson: null };
    absence: "unsupported" | "implicit" | "not-applicable" | null;
    criticality: "critical" | "noncritical"; mandatoryObservationIds: string[];
    provenanceIds: string[]; conflictIds: string[];
    factReceipt: string;
    criticalityEvidence: { rationale: string; authorityId: string; evidenceProvenanceId: string; receipt: string; sourceFloor: "critical" | "noncritical" };
    semantic: { relation: "declares" | "permits" | "forbids" | "transitions" | "fails-with" | "consumes" | "extends" | "omits"; from: string; to: string; domain: "authority" | "failure" | "lifecycle" | "prompt" | "skill" | "context" | "tool" | "memory" | "harness" | "model" | "resource" | "extension" | "configuration" | "runtime" | "evidence" | "safety-security"; extensionClass: string | null; opaqueVersion: string | null };
  }>;
  conflicts: Array<{ id: string; factId: string; leftProvenanceId: string; leftJsonPointer:string; rightProvenanceId: string; rightJsonPointer:string; leftProposition: string; leftValueDigest: Sha; rightProposition: string; rightValueDigest: Sha; status: "unresolved" | "adjudicated"; criticality: "critical" | "noncritical"; adjudicatorAuthorityId: string | null; resolutionKind:"choose-left"|"choose-right"|"new-proposition"|null; resolutionProposition: string | null; resolutionDigest: Sha | null; adjudicationEvidenceProvenanceId:string|null; adjudicationEvidenceDigest:Sha|null; adjudicationReceipt: string | null }>;
  chronology: Array<{ id: string; factId: string; observedAt: string; frozenAt: string; postResultMutation: false }>;
  dimensions: Array<{ sourceId: string; taxonomy: U4FactTaxonomy; status: "represented"; factIds: string[] }>;
  residualFactIds: [];
  chronologyPolicy: { claimDigest: Sha; cutoffAt: string; frontendOutcomeNotBefore: string };
  freezerAuthorityId: string;
  frontendAuthorityId: string;
  freezeReceipt: string;
};
export type U4TrustedVerificationInputs={authorityKeys:Array<{authorityId:string;ownerId:string;role:AuthorityRole;keyBase64:string;verificationKeyDigest:Sha}>;chronology:{claimDigest:Sha;cutoffAt:string;frontendOutcomeNotBefore:string;freezerAuthorityId:string;receipt:string}};
export type FrozenU4SourceInventory = U4SourceInventory & { digest: Sha };

const H = (x: string | Uint8Array) => `sha256:${createHash("sha256").update(x).digest("hex")}` as Sha;
const MAC=(key:Buffer,domain:string,body:unknown)=>createHmac("sha256",key).update(domain).update("\0").update(C(body)).digest("hex");
export const computeU4PropositionDigest=(proposition:string)=>H(`open-autonomy.u4-proposition.v1\0${C(proposition)}`);
export const computeU4ConflictResolutionDigest=(kind:"choose-left"|"choose-right"|"new-proposition",proposition:string)=>H(`open-autonomy.u4-conflict-resolution.v1\0${C({kind,proposition})}`);
export const computeU4NativeSchemaDigest=(shape:unknown)=>H(`open-autonomy.u4-native-schema.v1\0${C(shape)}`);
export const computeU4AdjudicationEvidenceDigest=(body:unknown)=>H(`open-autonomy.u4-adjudication-evidence.v1\0${C(body)}`);
const U4_TAXONOMY_COHERENCE:any={authority:{domains:["authority"],relations:["declares","permits","forbids"],defaults:["present"],absences:[null]},configuration:{domains:["configuration"],relations:["declares"],defaults:["present"],absences:[null]},evidence:{domains:["evidence"],relations:["declares"],defaults:["present"],absences:[null]},extensions:{domains:["extension"],relations:["extends"],defaults:["present"],absences:[null]},failure:{domains:["failure"],relations:["fails-with"],defaults:["present"],absences:[null]},lifecycle:{domains:["lifecycle"],relations:["transitions"],defaults:["present"],absences:[null]},omissions:{domains:["context"],relations:["omits"],defaults:["absent"],absences:["unsupported","implicit","not-applicable"]},"prompt-context":{domains:["prompt","skill","context","tool","memory","harness","model"],relations:["declares","consumes"],defaults:["present"],absences:[null]},resource:{domains:["resource"],relations:["declares","consumes"],defaults:["present"],absences:[null]},runtime:{domains:["runtime"],relations:["declares"],defaults:["present"],absences:[null]},"safety-security":{domains:["safety-security"],relations:["declares","forbids","permits"],defaults:["present"],absences:[null]}};
export function verifyU4TaxonomyCoherence(sourceIds:string[],facts:Array<Pick<U4SourceInventory["facts"][number],"sourceId"|"taxonomy"|"semantic"|"default"|"absence">>){if(!Array.isArray(sourceIds)||!sourceIds.length||new Set(sourceIds).size!==sourceIds.length)throw Error("U4 taxonomy source invalid");for(const sourceId of sourceIds){const sf=facts.filter(f=>f.sourceId===sourceId);for(const t of U4_FACT_TAXONOMY){const tf=sf.filter(f=>f.taxonomy===t),m=U4_TAXONOMY_COHERENCE[t];if(!tf.length)throw Error("U4 taxonomy coherence invalid");for(const f of tf)if(!m.domains.includes(f.semantic.domain)||!m.relations.includes(f.semantic.relation)||!m.defaults.includes(f.default.status)||!m.absences.includes(f.absence))throw Error("U4 taxonomy coherence invalid");if(t==="prompt-context"&&m.domains.some((d:string)=>!tf.some(f=>f.semantic.domain===d)))throw Error("U4 prompt-context subdomain totality invalid");}}return true;}
const DOMAIN = `${U4_SOURCE_INVENTORY_SCHEMA}\0`;
const sha = (x: unknown): x is Sha => typeof x === "string" && /^sha256:[0-9a-f]{64}$/.test(x);
const canonicalTime=(x:unknown):x is string=>typeof x==="string"&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(x)&&Number.isFinite(Date.parse(x))&&new Date(Date.parse(x)).toISOString()===x;
const pointer=(x:unknown):x is string=>typeof x==="string"&&(x===""||x==="/"||/^\/(?:[^~/]|~[01])+(?:\/(?:[^~/]|~[01])+)*$/.test(x));
const pathContained=(prefix:string,path:string)=>prefix==="/"?path.startsWith("/"):path===prefix||path.startsWith(prefix+"/");
function extractPointer(bytes:Buffer,p:string){let x:any;try{x=JSON.parse(bytes.toString("utf8"))}catch{throw Error("U4 conflict extraction bytes invalid")}if(p==="")return x;if(!pointer(p))throw Error("U4 conflict extraction pointer invalid");for(const raw of p.slice(1).split("/")){const k=raw.replace(/~1/g,"/").replace(/~0/g,"~"),ok=Array.isArray(x)?/^(0|[1-9]\d*)$/.test(k)&&Number(k)<x.length:!!x&&typeof x==="object"&&Object.prototype.hasOwnProperty.call(x,k);if(!ok)throw Error("U4 conflict extraction missing");x=x[k];}return x;}
const sid = (x: unknown): x is string => typeof x === "string" && x.length <= 200 && /^[a-z0-9](?:[a-z0-9._-]*[a-z0-9])?$/.test(x);
const txt = (x: unknown, n = 1000) => typeof x === "string" && x === x.trim() && x.length > 0 && Buffer.byteLength(x) <= n;
const exact = (x: unknown, keys: string[], at: string): any => {
  if (!x || typeof x !== "object" || Array.isArray(x) || C(Object.keys(x).sort()) !== C([...keys].sort())) throw Error(`U4 ${at} schema invalid`);
  return x;
};
const sorted = (xs: unknown, at: string): string[] => {
  if (!Array.isArray(xs) || xs.length > 512 || xs.some(x => !sid(x)) || new Set(xs).size !== xs.length || C(xs) !== C([...xs].sort())) throw Error(`U4 ${at} order invalid`);
  return xs;
};
function registry<T extends { id: string }>(xs: unknown, at: string, check: (x: any) => void) {
  if (!Array.isArray(xs) || xs.length > 512) throw Error(`U4 ${at} registry invalid`);
  const out = new Map<string, T>();
  for (const x of xs) { check(x); if (!sid(x.id) || out.has(x.id)) throw Error(`U4 ${at} identity invalid`); out.set(x.id, x); }
  if (C([...out.keys()]) !== C([...out.keys()].sort())) throw Error(`U4 ${at} order invalid`);
  return out;
}
function bounded(x: unknown) {
  const active = new Set<object>(); let nodes = 0, bytes = 0;
  const q: Array<[unknown, number, boolean]> = [[x, 0, true]];
  while (q.length) { const [v,d,enter]=q.pop()!; if (!enter) { active.delete(v as object); continue; } if (++nodes>20000||d>64) throw Error("U4 resource bound"); if (typeof v === "string") { bytes += Buffer.byteLength(v); if (Buffer.byteLength(v)>1_048_576) throw Error("U4 field bound"); continue; } if (!v||typeof v!=="object") continue; if(active.has(v as object))throw Error("U4 cyclic input"); active.add(v as object); q.push([v,d,false]); const vs=Array.isArray(v)?v:Object.values(v); if(vs.length>512)throw Error("U4 collection bound"); for(const y of vs)q.push([y,d+1,true]); }
  if(bytes>4_194_304)throw Error("U4 byte bound");
}
export const computeU4SourceInventoryDigest = (v: U4SourceInventory) => H(DOMAIN + C(v));
export const computeU4SyntheticSourceRegistryDigest=(v:Omit<FrozenU4SyntheticSourceRegistry,"digest">)=>H(`${v.schema}\0${C(v)}`);
export const EXPECTED_U4_SYNTHETIC_SOURCE_REGISTRY_DIGEST="sha256:3f6900cf4dc70d8387f87062ee8c2df8d554ad65800bad609b2b7a984c3894d8" as Sha;
export function freezeU4SyntheticSourceRegistry(input:Omit<FrozenU4SyntheticSourceRegistry,"digest">):FrozenU4SyntheticSourceRegistry{
  bounded(input);const v=exact(input,["schema","fixtureKind","populationBoundary","genericRegistryRelease","u1BoundaryStatus","sources"],"source registry");
  if(v.schema!=="open-autonomy.u4-synthetic-source-registry.v1"||v.fixtureKind!=="synthetic"||v.populationBoundary!=="synthetic-fixture-only-external-u1-release-deferred"||v.genericRegistryRelease!=="deferred-external-validation"||v.u1BoundaryStatus!=="implementation-complete-external-validation-deferred")throw Error("U4 registry boundary invalid");
  registry(v.sources,"registry source",s=>{exact(s,["id","sourceSystemId","nativeVersion","sourceOwnerId","stratumId","profileId","taxonomyFloors"],"registry source");if(!sid(s.sourceSystemId)||!sid(s.nativeVersion)||!sid(s.sourceOwnerId)||!sid(s.stratumId)||!sid(s.profileId)||!Array.isArray(s.taxonomyFloors)||s.taxonomyFloors.length!==U4_FACT_TAXONOMY.length)throw Error("U4 registry source invalid");let last="";for(const f of s.taxonomyFloors){exact(f,["taxonomy","minimum","rationale"],"taxonomy floor");if(!U4_FACT_TAXONOMY.includes(f.taxonomy)||f.taxonomy<=last||!["critical","noncritical"].includes(f.minimum)||!txt(f.rationale))throw Error("U4 taxonomy floor invalid");last=f.taxonomy;}});
  if(!v.sources.length)throw Error("U4 registry empty");const digest=computeU4SyntheticSourceRegistryDigest(v);if(digest!==EXPECTED_U4_SYNTHETIC_SOURCE_REGISTRY_DIGEST)throw Error("U4 independent registry fixture digest invalid");return deepFreeze({...structuredClone(v),digest});
}
export function verifyU4U3GitCustody(root = process.cwd()) {
  const a=U4_U3_ANCHORS, r=spawnSync("git",["rev-parse","--verify",`${a.closureCommit}^{commit}`],{cwd:root,encoding:"utf8"});
  if(r.status||r.stdout.trim()!==a.closureCommit)throw Error("U4 U3 commit custody invalid");
  const g=spawnSync("git",["show",`${a.closureCommit}:${a.closurePath}`],{cwd:root});
  if(g.status||H(g.stdout)!==a.closureSha256||H(readFileSync(`${root}/${a.closurePath}`))!==a.closureSha256||H(readFileSync(`${root}/${a.validatorPath}`))!==a.validatorSha256)throw Error("U4 U3 byte custody invalid");
}
export function freezeU4SourceInventory(input: U4SourceInventory, calculusInput: FrozenU3ObservationCalculus, sourceRegistry:FrozenU4SyntheticSourceRegistry,trusted:U4TrustedVerificationInputs): FrozenU4SourceInventory {
  bounded(input);bounded(trusted);exact(trusted,["authorityKeys","chronology"],"trusted inputs");
  const calculus=verifyFrozenU3ObservationCalculus(calculusInput,{requireFixtureDigest:false});
  const {digest:registryDigest,...registryBody}=sourceRegistry;if(freezeU4SyntheticSourceRegistry(registryBody).digest!==registryDigest)throw Error("U4 registry digest invalid");
  const v=exact(input,["schema","fixtureKind","denominatorScope","empiricalRegistration","closureClaim","campaignId","u3Anchors","sourceRegistryDigest","calculusDigest","assurance","authorities","sources","provenance","nativeSchemas","facts","conflicts","chronology","dimensions","residualFactIds","chronologyPolicy","freezerAuthorityId","frontendAuthorityId","freezeReceipt"],"inventory") as U4SourceInventory;
  if(v.schema!==U4_SOURCE_INVENTORY_SCHEMA||v.fixtureKind!=="synthetic"||v.denominatorScope!=="fixture-local"||v.empiricalRegistration!==false||v.closureClaim!==false||v.campaignId!=="organization-universality-2026-v9"||C(v.u3Anchors)!==C(U4_U3_ANCHORS)||v.sourceRegistryDigest!==sourceRegistry.digest||v.calculusDigest!==calculus.digest)throw Error("U4 boundary invalid");
  const assurance=exact(v.assurance,["level","externalTruth","promotionAllowed"],"assurance");
  if(assurance.level!=="synthetic-contract-only"||assurance.externalTruth!=="deferred"||assurance.promotionAllowed!==false)throw Error("U4 assurance invalid");
  const authorities=registry<any>(v.authorities,"authority",a=>{exact(a,["id","ownerId","role","trustRootSha256","verificationKeyDigest"],"authority");if(!sid(a.ownerId)||!["official-spec-publisher","native-schema-publisher","runtime-probe-operator","source-behavior-observer","independent-adjudicator","evidence-custodian","semantic-inventory-authority","inventory-freezer","frontend"].includes(a.role)||!sha(a.verificationKeyDigest)||a.trustRootSha256!==a.verificationKeyDigest)throw Error("U4 authority invalid");});
  const requiredRoles=["official-spec-publisher","native-schema-publisher","runtime-probe-operator","source-behavior-observer","independent-adjudicator","evidence-custodian","semantic-inventory-authority","inventory-freezer","frontend"];
  if(authorities.size!==requiredRoles.length||requiredRoles.some(role=>[...authorities.values()].filter(a=>a.role===role).length!==1)||new Set([...authorities.values()].map(a=>a.ownerId)).size!==authorities.size||new Set([...authorities.values()].map(a=>a.verificationKeyDigest)).size!==authorities.size)throw Error("U4 authority role independence invalid");
  if(!Array.isArray(trusted.authorityKeys))throw Error("U4 trusted keys invalid");const trustedKeys=new Map<string,any>();for(const k0 of trusted.authorityKeys){const k=exact(k0,["authorityId","ownerId","role","keyBase64","verificationKeyDigest"],"trusted key");let b:Buffer;try{b=Buffer.from(k.keyBase64,"base64")}catch{throw Error("U4 trusted key invalid")}const a=authorities.get(k.authorityId);if(!a||trustedKeys.has(k.authorityId)||a.ownerId!==k.ownerId||a.role!==k.role||b.length<32||H(b)!==k.verificationKeyDigest||a.verificationKeyDigest!==k.verificationKeyDigest)throw Error("U4 trusted key join invalid");trustedKeys.set(k.authorityId,k);}if(C([...trustedKeys.keys()])!==C([...trustedKeys.keys()].sort()))throw Error("U4 trusted key order invalid");
  if(trustedKeys.size!==authorities.size)throw Error("U4 trusted key totality invalid");
  const receipt=(aid:string,domain:string,body:unknown,sig:string)=>{const k=trustedKeys.get(aid);if(!k||typeof sig!=="string")return false;const expected=Buffer.from(MAC(Buffer.from(k.keyBase64,"base64"),domain,body),"hex"),got=Buffer.from(sig,"hex");return got.length===expected.length&&timingSafeEqual(got,expected)};
  const roleFor:any={"official-spec":"official-spec-publisher","native-schema":"native-schema-publisher","runtime-probe":"runtime-probe-operator","source-behavior":"source-behavior-observer"};
  const provenance=registry<any>(v.provenance,"provenance",p=>{exact(p,["id","sourceId","nativeSchemaId","kind","producerAuthorityId","custodyAuthorityId","sourceVersion","mediaType","acquiredAt","bytesBase64","byteLength","sha256","bodyReceipt","custodyReceipt"],"provenance");let b:Buffer;try{b=Buffer.from(p.bytesBase64,"base64");}catch{throw Error("U4 provenance bytes invalid");}const body={id:p.id,sourceId:p.sourceId,nativeSchemaId:p.nativeSchemaId,kind:p.kind,sourceVersion:p.sourceVersion,mediaType:p.mediaType,acquiredAt:p.acquiredAt,sha256:p.sha256};if(!sid(p.sourceId)||(p.kind==="native-schema"?!sid(p.nativeSchemaId):p.nativeSchemaId!==null)||!roleFor[p.kind]||authorities.get(p.producerAuthorityId)?.role!==roleFor[p.kind]||authorities.get(p.custodyAuthorityId)?.role!=="evidence-custodian"||p.producerAuthorityId===p.custodyAuthorityId||!txt(p.sourceVersion)||!txt(p.mediaType)||!canonicalTime(p.acquiredAt)||b.toString("base64")!==p.bytesBase64||b.length!==p.byteLength||!sha(p.sha256)||H(b)!==p.sha256||!receipt(p.producerAuthorityId,"u4-provenance-body",body,p.bodyReceipt)||!receipt(p.custodyAuthorityId,"u4-provenance-custody",{...body,producerAuthorityId:p.producerAuthorityId,bytesBase64:p.bytesBase64},p.custodyReceipt))throw Error("U4 provenance invalid");});
  const nativeSchemas=registry<any>(v.nativeSchemas,"native schema",s=>{exact(s,["id","version","sourceId","pathPrefix","valueShape","schemaBytesBase64","schemaSha256","semanticSchemaDigest","producerAuthorityId","custodyAuthorityId","producerReceipt","custodyReceipt"],"native schema");let b:Buffer,j:any;try{b=Buffer.from(s.schemaBytesBase64,"base64");j=JSON.parse(b.toString("utf8"))}catch{throw Error("U4 native schema invalid")}exact(s.valueShape,["type"],"value shape");if(!sid(s.version)||!sid(s.sourceId)||!pointer(s.pathPrefix)||s.pathPrefix===""||!["boolean","string","number","object","array","null"].includes(s.valueShape.type)||b.toString("base64")!==s.schemaBytesBase64||H(b)!==s.schemaSha256||C(j)!==b.toString("utf8")||C(j)!==C(s.valueShape)||s.semanticSchemaDigest!==computeU4NativeSchemaDigest(j)||authorities.get(s.producerAuthorityId)?.role!=="native-schema-publisher"||authorities.get(s.custodyAuthorityId)?.role!=="evidence-custodian"||!receipt(s.producerAuthorityId,"u4-native-schema",{id:s.id,version:s.version,sourceId:s.sourceId,pathPrefix:s.pathPrefix,schemaSha256:s.schemaSha256,semanticSchemaDigest:s.semanticSchemaDigest},s.producerReceipt)||!receipt(s.custodyAuthorityId,"u4-native-schema-custody",{id:s.id,schemaBytesBase64:s.schemaBytesBase64,schemaSha256:s.schemaSha256,producerAuthorityId:s.producerAuthorityId},s.custodyReceipt))throw Error("U4 native schema invalid");});
  for(const s of nativeSchemas.values()){const ps=[...provenance.values()].filter(p=>p.kind==="native-schema"&&p.nativeSchemaId===s.id&&p.sourceId===s.sourceId&&p.sourceVersion===s.version&&p.sha256===s.schemaSha256);if(ps.length!==1||ps[0].producerAuthorityId!==s.producerAuthorityId||ps[0].custodyAuthorityId!==s.custodyAuthorityId)throw Error("U4 native schema provenance join invalid");}if([...provenance.values()].filter(p=>p.kind==="native-schema").length!==nativeSchemas.size)throw Error("U4 surplus native schema provenance invalid");
  const observations=new Map(calculus.observations.map(o=>[o.id,o])), strata=new Set(calculus.strata.map(s=>s.id)), profiles=new Map(calculus.profiles.map(p=>[p.id,p]));
  const facts=registry<any>(v.facts,"fact",f=>{exact(f,["id","sourceId","taxonomy","nativePath","nativeSchemaId","nativeSchemaVersion","denotation","default","absence","criticality","mandatoryObservationIds","provenanceIds","conflictIds","semantic","factReceipt","criticalityEvidence"],"fact");const d=exact(f.default,["status","valueJson"],"default"),sm=exact(f.semantic,["relation","from","to","domain","extensionClass","opaqueVersion"],"semantic"),ce=exact(f.criticalityEvidence,["rationale","authorityId","evidenceProvenanceId","receipt","sourceFloor"],"criticality evidence");if(!U4_FACT_TAXONOMY.includes(f.taxonomy)||!/^\/(?:[^~/]|~[01])+(?:\/(?:[^~/]|~[01])+)*$/.test(f.nativePath)||!sid(f.nativeSchemaId)||!sid(f.nativeSchemaVersion)||!txt(f.denotation)||!["critical","noncritical"].includes(f.criticality)||![null,"unsupported","implicit","not-applicable"].includes(f.absence)||!(["present","absent"].includes(d.status))||(d.status==="present"?(typeof d.valueJson!=="string"||(()=>{try{return C(JSON.parse(d.valueJson))!==d.valueJson}catch{return true}})()||f.absence!==null):d.valueJson!==null||f.absence===null)||!["declares","permits","forbids","transitions","fails-with","consumes","extends","omits"].includes(sm.relation)||!txt(sm.from)||!txt(sm.to)||!["authority","failure","lifecycle","prompt","skill","context","tool","memory","harness","model","resource","extension","configuration","runtime","evidence","safety-security"].includes(sm.domain)||(sm.domain==="extension"?(!sid(sm.extensionClass)||!txt(sm.opaqueVersion)):sm.extensionClass!==null||sm.opaqueVersion!==null)||!txt(ce.rationale)||!["critical","noncritical"].includes(ce.sourceFloor)||(ce.sourceFloor==="critical"&&f.criticality!=="critical"))throw Error("U4 fact invalid");sorted(f.mandatoryObservationIds,"fact observations");sorted(f.provenanceIds,"fact provenance");sorted(f.conflictIds,"fact conflicts");if(f.provenanceIds.length!==4)throw Error("U4 provenance triangulation invalid");});
  const conflicts=registry<any>(v.conflicts,"conflict",c=>{exact(c,["id","factId","leftProvenanceId","leftJsonPointer","rightProvenanceId","rightJsonPointer","leftProposition","leftValueDigest","rightProposition","rightValueDigest","status","criticality","adjudicatorAuthorityId","resolutionKind","resolutionProposition","resolutionDigest","adjudicationEvidenceProvenanceId","adjudicationEvidenceDigest","adjudicationReceipt"],"conflict");if(!["unresolved","adjudicated"].includes(c.status)||!["critical","noncritical"].includes(c.criticality)||c.leftProvenanceId===c.rightProvenanceId||!pointer(c.leftJsonPointer)||!pointer(c.rightJsonPointer)||!txt(c.leftProposition)||!txt(c.rightProposition)||c.leftValueDigest!==computeU4PropositionDigest(c.leftProposition)||c.rightValueDigest!==computeU4PropositionDigest(c.rightProposition)||c.leftValueDigest===c.rightValueDigest)throw Error("U4 conflict invalid");if(c.status==="unresolved"?[c.adjudicatorAuthorityId,c.resolutionKind,c.resolutionProposition,c.resolutionDigest,c.adjudicationEvidenceProvenanceId,c.adjudicationEvidenceDigest,c.adjudicationReceipt].some(x=>x!==null):(!sid(c.adjudicatorAuthorityId)||!["choose-left","choose-right","new-proposition"].includes(c.resolutionKind)||!txt(c.resolutionProposition)||c.resolutionDigest!==computeU4ConflictResolutionDigest(c.resolutionKind,c.resolutionProposition)||!sid(c.adjudicationEvidenceProvenanceId)||!sha(c.adjudicationEvidenceDigest)||typeof c.adjudicationReceipt!=="string"||(c.resolutionKind==="choose-left"&&c.resolutionProposition!==c.leftProposition)||(c.resolutionKind==="choose-right"&&c.resolutionProposition!==c.rightProposition)))throw Error("U4 conflict resolution invalid");});
  const sources=registry<any>(v.sources,"source",s=>{exact(s,["id","sourceSystemId","sourceImplementerOwnerId","frontendOwnerId","stratumId","profileId","factIds"],"source");sorted(s.factIds,"source facts");if(!sid(s.sourceSystemId)||!sid(s.sourceImplementerOwnerId)||!sid(s.frontendOwnerId)||s.sourceImplementerOwnerId===s.frontendOwnerId||!strata.has(s.stratumId)||profiles.get(s.profileId)?.stratumId!==s.stratumId)throw Error("U4 source join invalid");});
  const chronology=registry<any>(v.chronology,"chronology",x=>{exact(x,["id","factId","observedAt","frozenAt","postResultMutation"],"chronology");if(!/^\d{4}-\d\d-\d\dT/.test(x.observedAt)||!/^\d{4}-\d\d-\d\dT/.test(x.frozenAt)||x.observedAt>x.frozenAt||x.postResultMutation!==false)throw Error("U4 chronology invalid");});
  const referencedFacts=new Set<string>(), referencedProv=new Set<string>(), referencedConflicts=new Set<string>();
  if(!authorities.size||!sources.size||!provenance.size||!facts.size||!v.dimensions.length)throw Error("U4 population empty");
  const rs=new Map(sourceRegistry.sources.map(s=>[s.id,s]));if(rs.size!==sources.size)throw Error("U4 registry source totality invalid");
  for(const s of sources.values()){const r=rs.get(s.id);if(!r||r.sourceSystemId!==s.sourceSystemId||r.sourceOwnerId!==s.sourceImplementerOwnerId||r.stratumId!==s.stratumId||r.profileId!==s.profileId)throw Error("U4 registry source join invalid");}
  const frontend=authorities.get(v.frontendAuthorityId),freezerAuthority=authorities.get(v.freezerAuthorityId),protectedOwners=new Set([...sources.values()].flatMap(s=>[s.sourceImplementerOwnerId,s.frontendOwnerId]));if(!frontend||frontend.role!=="frontend"||[...sources.values()].some(s=>s.frontendOwnerId!==frontend.ownerId)||!freezerAuthority||freezerAuthority.role!=="inventory-freezer"||protectedOwners.has(freezerAuthority.ownerId))throw Error("U4 source authority owner join invalid");for(const a of authorities.values())if(a.role!=="frontend"&&protectedOwners.has(a.ownerId))throw Error("U4 authority source independence invalid");
  for(const s of sources.values()){const owned=[...facts.values()].filter(f=>f.sourceId===s.id).map(f=>f.id).sort();if(C(owned)!==C(s.factIds))throw Error("U4 fact totality invalid");for(const id of s.factIds)referencedFacts.add(id);for(const t of U4_FACT_TAXONOMY)if(!owned.some(id=>facts.get(id)!.taxonomy===t))throw Error("U4 taxonomy totality invalid");}
  if(referencedFacts.size!==facts.size)throw Error("U4 surplus fact invalid");
  for(const f of facts.values()){
    if(!sources.has(f.sourceId)||f.id!==`${f.sourceId}.${f.taxonomy}.${H(f.nativePath).slice(7,23)}`)throw Error("U4 fact identity invalid");const ns=nativeSchemas.get(f.nativeSchemaId),rv=rs.get(f.sourceId)!;if(!pointer(f.nativePath)||f.nativePath===""||!ns||ns.sourceId!==f.sourceId||ns.version!==f.nativeSchemaVersion||rv.nativeVersion!==f.nativeSchemaVersion||!pathContained(ns.pathPrefix,f.nativePath))throw Error("U4 native schema join invalid");if(f.default.status==="present"){const x=JSON.parse(f.default.valueJson),shape=Array.isArray(x)?"array":x===null?"null":typeof x;if(shape!==ns.valueShape.type)throw Error("U4 native value shape invalid");}
    const kinds=new Set<string>();for(const id of f.provenanceIds){const p=provenance.get(id);if(!p||p.sourceId!==f.sourceId||p.sourceVersion!==rv.nativeVersion||(p.kind==="native-schema"&&p.nativeSchemaId!==f.nativeSchemaId))throw Error("U4 provenance join invalid");kinds.add(p.kind);referencedProv.add(id);}
    if(C([...kinds].sort())!==C([...(["native-schema","official-spec","runtime-probe","source-behavior"] as const)].sort()))throw Error("U4 provenance kinds invalid");
    if(f.mandatoryObservationIds.length===0)throw Error("U4 observation coverage invalid");for(const id of f.mandatoryObservationIds){const o=observations.get(id);if(!o||!o.applicability.some(a=>a.stratumId===sources.get(f.sourceId)!.stratumId&&a.status==="mandatory")||!profiles.get(sources.get(f.sourceId)!.profileId)!.observationIds.includes(id))throw Error("U4 observation join invalid");}const ce=f.criticalityEvidence,floor=rv.taxonomyFloors.find((x:any)=>x.taxonomy===f.taxonomy);if(!floor||ce.sourceFloor!==floor.minimum||ce.rationale!==floor.rationale||authorities.get(ce.authorityId)?.role!=="semantic-inventory-authority"||!f.provenanceIds.includes(ce.evidenceProvenanceId)||(floor.minimum==="critical"&&f.criticality!=="critical")||!receipt(ce.authorityId,"u4-criticality",{factId:f.id,criticality:f.criticality,rationale:ce.rationale,evidenceProvenanceId:ce.evidenceProvenanceId,sourceFloor:ce.sourceFloor},ce.receipt)||!receipt(ce.authorityId,"u4-fact",{...f,factReceipt:undefined,criticalityEvidence:{...ce,receipt:undefined}},f.factReceipt))throw Error("U4 fact receipt invalid");
    const actual=[...conflicts.values()].filter(c=>c.factId===f.id).map(c=>c.id).sort();if(C(actual)!==C(f.conflictIds))throw Error("U4 conflict totality invalid");for(const id of actual){referencedConflicts.add(id);const c=conflicts.get(id)!,lp=provenance.get(c.leftProvenanceId),rp=provenance.get(c.rightProvenanceId);if(c.criticality!==f.criticality||!lp||!rp||!f.provenanceIds.includes(lp.id)||!f.provenanceIds.includes(rp.id)||c.leftProposition!==C(extractPointer(Buffer.from(lp.bytesBase64,"base64"),c.leftJsonPointer))||c.rightProposition!==C(extractPointer(Buffer.from(rp.bytesBase64,"base64"),c.rightJsonPointer)))throw Error("U4 conflict join invalid");if(c.status==="adjudicated"){const a=authorities.get(c.adjudicatorAuthorityId),ep=provenance.get(c.adjudicationEvidenceProvenanceId),evidenceBody={...c,adjudicationEvidenceDigest:undefined,adjudicationReceipt:undefined,evidenceProvenanceSha256:ep?.sha256},signedBody={...c,adjudicationReceipt:undefined};if(!a||a.role!=="independent-adjudicator"||!ep||ep.sourceId!==f.sourceId||!f.provenanceIds.includes(ep.id)||c.adjudicationEvidenceDigest!==computeU4AdjudicationEvidenceDigest(evidenceBody)||!receipt(c.adjudicatorAuthorityId,"u4-adjudication",signedBody,c.adjudicationReceipt))throw Error("U4 adjudicator independence invalid");}if(c.criticality==="critical"&&c.status!=="adjudicated")throw Error("U4 unresolved critical conflict");}
  }
  if([...nativeSchemas.keys()].some(id=>![...facts.values()].some(f=>f.nativeSchemaId===id)))throw Error("U4 surplus native schema invalid");
  if(referencedProv.size!==provenance.size||referencedConflicts.size!==conflicts.size)throw Error("U4 surplus evidence invalid");
  if(C([...chronology.values()].map(x=>x.factId).sort())!==C([...facts.keys()].sort()))throw Error("U4 chronology totality invalid");
  if(!Array.isArray(v.dimensions)||v.dimensions.length!==sources.size*U4_FACT_TAXONOMY.length||!Array.isArray(v.residualFactIds)||v.residualFactIds.length!==0)throw Error("U4 closed world invalid");
  const dimKeys:string[]=[];for(const d0 of v.dimensions){const d=exact(d0,["sourceId","taxonomy","status","factIds"],"dimension");sorted(d.factIds,"dimension facts");if(!sources.has(d.sourceId)||!U4_FACT_TAXONOMY.includes(d.taxonomy)||d.status!=="represented"||C(d.factIds)!==C([...facts.values()].filter(f=>f.sourceId===d.sourceId&&f.taxonomy===d.taxonomy).map(f=>f.id).sort()))throw Error("U4 dimension invalid");dimKeys.push(`${d.sourceId}\0${d.taxonomy}`);}if(C(dimKeys)!==C([...dimKeys].sort())||new Set(dimKeys).size!==dimKeys.length)throw Error("U4 dimension order invalid");
  verifyU4TaxonomyCoherence([...sources.keys()],v.facts);
  const cp=exact(v.chronologyPolicy,["claimDigest","cutoffAt","frontendOutcomeNotBefore"],"chronology policy"),tcp=exact(trusted.chronology,["claimDigest","cutoffAt","frontendOutcomeNotBefore","freezerAuthorityId","receipt"],"trusted chronology");if(C(cp)!==C({claimDigest:tcp.claimDigest,cutoffAt:tcp.cutoffAt,frontendOutcomeNotBefore:tcp.frontendOutcomeNotBefore})||tcp.receipt!==v.freezeReceipt||tcp.freezerAuthorityId!==v.freezerAuthorityId||cp.claimDigest!==U4_V9_CHRONOLOGY_ANCHOR.claimDigest||cp.cutoffAt!==U4_V9_CHRONOLOGY_ANCHOR.cutoffAt||![cp.cutoffAt,cp.frontendOutcomeNotBefore].every(canonicalTime)||Date.parse(cp.cutoffAt)>=Date.parse(cp.frontendOutcomeNotBefore))throw Error("U4 chronology policy invalid");for(const x of chronology.values())if(!canonicalTime(x.observedAt)||!canonicalTime(x.frozenAt)||Date.parse(x.observedAt)>Date.parse(x.frozenAt)||Date.parse(x.frozenAt)>=Date.parse(cp.frontendOutcomeNotBefore)||Date.parse(x.observedAt)>Date.parse(cp.cutoffAt))throw Error("U4 chronology order invalid");
  if(!receipt(v.freezerAuthorityId,"u4-freeze",{inventoryDigest:computeU4SourceInventoryDigest({...v,freezeReceipt:""}),calculusDigest:v.calculusDigest,sourceRegistryDigest:v.sourceRegistryDigest,frontendOutcomeNotBefore:cp.frontendOutcomeNotBefore},v.freezeReceipt))throw Error("U4 freeze receipt invalid");
  const body=structuredClone(v), digest=computeU4SourceInventoryDigest(body);return deepFreeze({...body,digest});
}
export function verifyFrozenU4SourceInventory(input: FrozenU4SourceInventory, calculus: FrozenU3ObservationCalculus,registryInput:FrozenU4SyntheticSourceRegistry,trusted:U4TrustedVerificationInputs){const {digest,...body}=input;if(!sha(digest)||digest!==computeU4SourceInventoryDigest(body as U4SourceInventory))throw Error("U4 inventory digest invalid");const frozen=freezeU4SourceInventory(body as U4SourceInventory,calculus,registryInput,trusted);if(frozen.digest!==digest)throw Error("U4 inventory replay invalid");return frozen;}
function deepFreeze<T>(v:T):T{const q:any[]=[v];while(q.length){const x=q.pop();if(x&&typeof x==="object"&&!Object.isFrozen(x)){q.push(...Object.values(x));Object.freeze(x);}}return v;}
