import { expect, test } from "bun:test";
import { generateKeyPairSync, sign } from "node:crypto";
import { canonicalSemanticJson } from "./organization-canonical";
import { RUNTIME_SERVICES } from "./organization-runtime-reliability";
import { signableR21Campaign, signableR21Operator, signableR21Registration,
  verifyR21ExternalCampaign, type R21Campaign } from "./organization-r21-external-campaign";
import {acceptR21Collection,acceptR21CollectorIntent,acceptR21Evidence,acceptR21Registration,assembleR21,createR21State,issueR21Collection,issueR21CollectorIntent,issueR21Evidence,issueR21Registration,type R21Category,type R21Request}from"../../../bench/dev/evidence/r21-acquisition";
const d=(n:number)=>`sha256:${n.toString(16).padStart(64,"0")}` as const,k=()=>generateKeyPairSync("ed25519"),
  meta=(x:ReturnType<typeof k>,id:string,at:string)=>({signerId:id,publicKeyPem:x.publicKey.export({type:"spki",format:"pem"}).toString(),signedAt:at,signature:""}),
  seal=(body:unknown,x:ReturnType<typeof k>)=>sign(null,Buffer.from(canonicalSemanticJson(body)),x.privateKey).toString("base64");
function fixture(){const registrar=k(),collector=k(),operator=k(),custodian=k(),telemetry=k(),faultAuthority=k(),lifecycleAuthority=k(),billingKeys=[k(),k()],deps:any={R15:d(15),R16:d(16),R17:d(17),R18:d(18),R19:d(19),R20:d(20)},
  faults=["process","storage","dependency","network","control-plane","region"] as const,
  lifecycle=["upgrade","downgrade","schema-migration","credential-rotation","drain","decommission","restore"] as const,
  registration:any={schema:"autonomy.r21-external-registration.v1",campaignId:"r21-real-1",dependencies:deps,topologyDigest:d(1),regions:["a","b"],services:[...RUNTIME_SERVICES],faults:[...faults],lifecycle:[...lifecycle],slos:RUNTIME_SERVICES.map(service=>({service,minimumSamples:100,availabilityTarget:.99,p95TargetMs:500,maximumErrorBudgetBurn:1,maximumCostPerRequest:2})),rampConcurrency:[1,4,16],soakDurationMs:3600000,rpoTargetMs:1000,rtoTargetMs:5000,minimumDistinctBillingAuthorities:2,minimumUnfamiliarOperators:1,startsAt:"2026-07-16T10:00:00Z",endsAt:"2026-07-16T14:00:00Z",registrationAuthority:meta(registrar,"registrar","2026-07-16T09:00:00Z")};
  registration.registrationAuthority.signature=seal(signableR21Registration(registration),registrar);
  const services=RUNTIME_SERVICES.flatMap((service,si)=>registration.regions.flatMap((region:string,ri:number)=>[
      ...registration.rampConcurrency.map((concurrency:number,ci:number)=>({schema:"autonomy.r21-service-observation.v1" as const,campaignId:registration.campaignId,service,region,phase:"ramp" as const,concurrency,topologyDigest:d(1),workloadDigest:d(50+ci),endpointDigest:d(100+si),telemetryArtifactDigest:d(200+si*20+ri*5+ci),samples:100,successes:100,p95Ms:100,errorBudgetBurn:0,totalCost:1,currency:"USD",usageUnit:"request",startedAt:"2026-07-16T10:00:00Z",completedAt:"2026-07-16T10:01:00Z",observedAt:"2026-07-16T12:00:00Z"})),
      {schema:"autonomy.r21-service-observation.v1" as const,campaignId:registration.campaignId,service,region,phase:"soak" as const,concurrency:16,topologyDigest:d(1),workloadDigest:d(60),endpointDigest:d(100+si),telemetryArtifactDigest:d(250+si*2+ri),samples:100,successes:100,p95Ms:100,errorBudgetBurn:0,totalCost:1,currency:"USD",usageUnit:"request",startedAt:"2026-07-16T10:00:00Z",completedAt:"2026-07-16T11:00:00Z",observedAt:"2026-07-16T12:00:00Z"}])),
    faultRows=faults.flatMap((fault,fi)=>registration.regions.map((region:string,ri:number)=>({schema:"autonomy.r21-fault-observation.v1" as const,campaignId:registration.campaignId,fault,region,topologyDigest:d(1),targetDigest:d(300+fi),injectionArtifactDigest:d(400+fi*2+ri),recoveryArtifactDigest:d(500+fi*2+ri),recoveryCutDigest:d(505+fi*2+ri),beforeStateDigest:d(510+fi*2+ri),afterStateDigest:d(530+fi*2+ri),faultAt:"2026-07-16T11:00:00.000Z",recoveryPointAt:"2026-07-16T10:59:59.900Z",lastAcknowledgedSequence:10,recoveredSequence:10,distinctProcessOrRegion:true,rpoMs:100,rtoMs:1100,revokedPreserved:true,acknowledgedEffectsPreserved:true,startedAt:"2026-07-16T10:59:59.900Z",recoveredAt:"2026-07-16T11:00:01.000Z"}))),
    lifecycleRows=lifecycle.flatMap((operation,oi)=>RUNTIME_SERVICES.map((service,si)=>({schema:"autonomy.r21-lifecycle-observation.v1" as const,campaignId:registration.campaignId,operation,service,topologyDigest:d(1),beforeDigest:d(600+oi*10+si),afterDigest:d(700+oi*10+si),auditDigest:d(800+oi*10+si),completedAt:"2026-07-16T12:00:00Z"}))),
    billing=RUNTIME_SERVICES.map((service,i)=>{const rows=services.filter(x=>x.service===service);return{schema:"autonomy.r21-billing-observation.v1" as const,campaignId:registration.campaignId,service,authority:`authority-${i%2}`,provider:`provider-${i%2}`,currency:"USD",unit:"request",usage:rows.reduce((n,x)=>n+x.samples,0),amount:rows.reduce((n,x)=>n+x.totalCost,0),invoiceArtifactDigest:d(900+i),observedAt:"2026-07-16T13:00:00Z"}}),
    op:any={schema:"autonomy.r21-operator-observation.v1",campaignId:registration.campaignId,operatorId:"operator-1",unfamiliarityAttestationDigest:d(1000),alertDigest:d(1001),diagnosisDigest:d(1002),runbookDigest:d(1003),recoveryDigest:d(1004),startedAt:"2026-07-16T11:00:00Z",completedAt:"2026-07-16T11:10:00Z",outcome:"recovered",operatorSignature:meta(operator,"operator-1","2026-07-16T11:11:00Z"),custodianSignature:meta(custodian,"custodian","2026-07-16T11:12:00Z")};
  op.operatorSignature.signature=seal(signableR21Operator(op,"operatorSignature"),operator);op.custodianSignature.signature=seal(signableR21Operator(op,"custodianSignature"),custodian);
  const campaign:any={schema:"autonomy.r21-external-campaign.v1",closureClaim:true,registration,services,faults:faultRows,lifecycle:lifecycleRows,billing,operators:[op],collector:meta(collector,"collector","2026-07-16T13:30:00Z")};campaign.collector.signature=seal(signableR21Campaign(campaign),collector);
  const policy={regions:registration.regions,slos:registration.slos,rampConcurrency:registration.rampConcurrency,soakDurationMs:registration.soakDurationMs,rpoTargetMs:registration.rpoTargetMs,rtoTargetMs:registration.rtoTargetMs,minimumDistinctBillingAuthorities:registration.minimumDistinctBillingAuthorities,minimumUnfamiliarOperators:registration.minimumUnfamiliarOperators,topologyDigest:d(1),workloadDigests:{"ramp:1":d(50),"ramp:4":d(51),"ramp:16":d(52),"soak:16":d(60)},billing:{currency:"USD",usageUnit:"request",accountingMethod:"sum-authenticated-service-observations" as const,authorities:{"authority-0":"provider-0","authority-1":"provider-1"}}};
  return{campaign:campaign as R21Campaign,trust:{dependencyEvidence:deps,policy,registrationKeys:[registration.registrationAuthority.publicKeyPem],collectorKeys:[campaign.collector.publicKeyPem],custodianKeys:[op.custodianSignature.publicKeyPem],operatorKeys:{"operator-1":op.operatorSignature.publicKeyPem},billingAuthorityKeys:Object.fromEntries(billingKeys.map((x,i)=>[`authority-${i}`,x.publicKey.export({type:"spki",format:"pem"}).toString()])),verifyTelemetry:()=>true,verifyFault:()=>true,verifyLifecycle:()=>true,verifyBilling:()=>true},acquisitionKeys:{registrar,collector,operator,custodian,telemetry,faultAuthority,lifecycleAuthority,billingKeys}};}
test("verifies a complete externally authenticated eight-service R21 campaign",()=>{const{campaign,trust}=fixture();expect(verifyR21ExternalCampaign(campaign,trust)).toMatchObject({status:"R21-external-evidence-verified",closureClaim:true})});
test("reconstructs every exact disaster-campaign cell through assigned external authorities",()=>{const{campaign:source,trust,acquisitionKeys}=fixture(),p=(x:any)=>x.publicKey.export({type:"spki",format:"pem"}).toString(),
  ids={registrationKeyId:"registrar",collectorKeyId:"collector",telemetryKeyId:"telemetry",faultKeyId:"fault",lifecycleKeyId:"lifecycle",custodianKeyId:"custodian"},billingKeyIds={"authority-0":"billing-0","authority-1":"billing-1"},operatorKeyIds={"operator-1":"operator-1"},
  publicKeys={registrar:p(acquisitionKeys.registrar),collector:p(acquisitionKeys.collector),telemetry:p(acquisitionKeys.telemetry),fault:p(acquisitionKeys.faultAuthority),lifecycle:p(acquisitionKeys.lifecycleAuthority),custodian:p(acquisitionKeys.custodian),"billing-0":p(acquisitionKeys.billingKeys[0]),"billing-1":p(acquisitionKeys.billingKeys[1]),"operator-1":p(acquisitionKeys.operator)},
  state=createR21State({campaignId:source.registration.campaignId,createdAt:"2026-07-16T08:00:00Z",...ids,billingKeyIds,billingAssignments:Object.fromEntries(source.billing.map(x=>[x.service,x.authority])),operatorKeyIds,publicKeys}),
  keyFor=(q:R21Request)=>q.category==="services"?acquisitionKeys.telemetry:q.category==="faults"?acquisitionKeys.faultAuthority:q.category==="lifecycle"?acquisitionKeys.lifecycleAuthority:q.category==="billing"?acquisitionKeys.billingKeys[Number(q.signerId.slice(-1))]:q.category==="operators"?acquisitionKeys.custodian:q.cellId==="registration"?acquisitionKeys.registrar:acquisitionKeys.collector,
  respond=(q:R21Request,fragment:unknown)=>{const signerKeyId=q.category==="services"?ids.telemetryKeyId:q.category==="faults"?ids.faultKeyId:q.category==="lifecycle"?ids.lifecycleKeyId:q.category==="billing"?billingKeyIds[q.signerId as keyof typeof billingKeyIds]:q.category==="operators"?ids.custodianKeyId:q.cellId==="registration"?ids.registrationKeyId:ids.collectorKeyId,body={schema:"open-autonomy.bench-r21-acquisition-response.v1"as const,requestDigest:`sha256:${new Bun.CryptoHasher("sha256").update(canonicalSemanticJson(q)).digest("hex")}`as const,fragmentDigest:`sha256:${new Bun.CryptoHasher("sha256").update(canonicalSemanticJson(fragment)).digest("hex")}`as const,signerKeyId,signedAt:"2026-07-16T13:30:00Z"};return{...body,signature:seal(body,keyFor(q)),fragment}};
  let q=issueR21Registration(state);acceptR21Registration(state,respond(q,source.registration));
  const enc=(...xs:any[])=>xs.map(x=>encodeURIComponent(String(x))).join("/"),groups:[R21Category,any[],(x:any)=>string][]=[["services",source.services,x=>enc(x.service,x.region,x.phase,x.concurrency)],["faults",source.faults,x=>enc(x.fault,x.region)],["lifecycle",source.lifecycle,x=>enc(x.operation,x.service)],["billing",source.billing,x=>enc(x.service)],["operators",source.operators,x=>enc(x.operatorId)]];
  for(const[category,values,id]of groups)for(const value of[...values].reverse()){q=issueR21Evidence(state,category,id(value));acceptR21Evidence(state,category,id(value),respond(q,value))}
  q=issueR21CollectorIntent(state);const{signature:campaignSignature,...intent}=source.collector;acceptR21CollectorIntent(state,respond(q,intent));q=issueR21Collection(state);acceptR21Collection(state,respond(q,{campaignSignature}));const reconstructed=assembleR21(state);
  expect(canonicalSemanticJson(reconstructed)).toBe(canonicalSemanticJson(source));expect(verifyR21ExternalCampaign(reconstructed,trust)).toMatchObject({status:"R21-external-evidence-verified"})},15000);
test("rejects missing services/faults/lifecycle/billing and unavailable unfamiliar operator",()=>{const mutations=[(x:any)=>x.services.pop(),(x:any)=>x.faults.pop(),(x:any)=>x.lifecycle.pop(),(x:any)=>x.billing.pop(),(x:any)=>x.operators.pop()];for(const mutate of mutations){const{campaign,trust}=fixture();mutate(campaign);expect(()=>verifyR21ExternalCampaign(campaign,trust)).toThrow()}});
test("rejects SLO, recovery, invoice, dependency, authority, and signature fraud",()=>{const mutations=[(x:any)=>x.services[0].p95Ms=501,(x:any)=>x.faults[0].rtoMs=5001,(x:any)=>x.billing[0].amount=-1,(x:any)=>x.registration.dependencies.R20=d(999),(x:any)=>x.billing.forEach((b:any)=>b.authority="one"),(x:any)=>x.operators[0].custodianSignature.signature="forged",(x:any)=>x.collector.publicKeyPem=x.registration.registrationAuthority.publicKeyPem];for(const mutate of mutations){const{campaign,trust}=fixture();mutate(campaign);expect(()=>verifyR21ExternalCampaign(campaign,trust)).toThrow()}});
test("rejects disconnected clocks, untrusted dimensions, topology substitution, and workload substitution",()=>{const mutations=[
  (x:any)=>x.faults[0].recoveryPointAt="2026-07-15T10:59:59.900Z",
  (x:any)=>x.faults[0].faultAt="2026-07-16T10:59:59.800Z",
  (x:any)=>x.operators[0].operatorSignature.signedAt="2026-07-16T11:09:00Z",
  (x:any)=>x.billing[0].currency="EUR",
  (x:any)=>x.services[0].usageUnit="token",
  (x:any)=>x.services[0].topologyDigest=d(999),
  (x:any)=>x.services[0].workloadDigest=d(999),
];for(const mutate of mutations){const{campaign,trust}=fixture();mutate(campaign);expect(()=>verifyR21ExternalCampaign(campaign,trust)).toThrow()}});
