import { createHash, createPublicKey, verify } from "node:crypto";
import { canonicalSemanticJson } from "./organization-canonical";

type Digest = `sha256:${string}`;
type Signature = { signerId: string; publicKeyPem: string; signedAt: string; signature: string };
type CriterionRole="workload"|"environment"|"scorer"|"privacy"|"cost";
export const R22_CUSTODY_ATTACKS = ["read-hidden", "read-grader", "network", "edit-grader", "omit-failed", "select-success"] as const;
export const R22_COST_DIMENSIONS = ["wall-ms", "cpu-ms", "memory-byte-ms", "money-usd", "human-ms"] as const;
type Attack = (typeof R22_CUSTODY_ATTACKS)[number];
type Dimension = (typeof R22_COST_DIMENSIONS)[number];
export type R22Trial = { trialId: string; blockId: string; itemId: string; arm: "control" | "treatment" };
export type R22Registration = { schema: "autonomy.r22-external-registration.v1"; campaignId: string;
  dependencies: Record<"R3"|"R4"|"R8"|"R10"|"R11"|"R14"|"R16"|"R20"|"R21",Digest>; workloadDigest: Digest; environmentDigest: Digest;
  scorerDigest: Digest; privacyDigest: Digest; trials: R22Trial[]; raterIds: string[]; itemIds: string[];
  simulatorScores: Array<{itemId:string;score:number}>; statisticalPlan:{alpha:number;estimand:"equal-block-mean-difference";ciMethod:"fixed-critical-normal";criticalValue:number;minimumBlocks:number};
  protocol:{seed:string;randomization:"seeded-block";replications:number;stoppingRule:"fixed-matrix";retryPolicy:"no-retry";missingPolicy:"score-zero-for-failed-and-missing";censoringPolicy:"none";outcome:string;unit:string;populationDigest:Digest;contaminationPolicy:"isolated"};
  simulator:{id:string;version:string;role:"simulator";populationDigest:Digest;minimumScore:number;maximumScore:number};
  startsAt: string; endsAt: string; authority: Signature };
export type R22TrialObservation = R22Trial & { schema: "autonomy.r22-trial-observation.v1"; campaignId: string;
  status:"completed"|"failed"|"missing"; outcome: number|null; evidenceDigest: Digest; observedAt: string };
export type R22CustodyAttack = { schema: "autonomy.r22-custody-attack.v1"; campaignId: string; attack: Attack;
  rejected: true; evidenceDigest: Digest; observedAt: string };
export type R22Rating = { schema: "autonomy.r22-rating.v1"; campaignId: string; raterId: string; itemId: string;
  score: number; consentDigest: Digest; evidenceDigest: Digest; observedAt: string; signature: Signature };
export type R22CriterionAttestation={role:CriterionRole;digest:Digest;signature:Signature};
export type R22Enrollment={raterId:string;raterKeyFingerprint:string;consentDigest:Digest;populationDigest:Digest;validFrom:string;validUntil:string;signature:Signature};
export type R22Cost = { trialId: string; dimension: Dimension; unit: Dimension; value: number | null; status: "observed" | "unknown"; evidenceDigest: Digest; signature:Signature };
export type R22Analysis = { blockEffects: Array<{ blockId: string; effect: number }>; estimand: number; variance: number;
  ci95: [number, number]; simulatorScores: Array<{ itemId: string; score: number }>; transferRmse: number; costs: R22Cost[];costTotals:Array<{dimension:Dimension;value:number}> };
export type R22Campaign = { schema: "autonomy.r22-external-campaign.v1"; closureClaim: true; registration: R22Registration;
  criterionAttestations:R22CriterionAttestation[];enrollments:R22Enrollment[];trials: R22TrialObservation[]; custodyAttacks: R22CustodyAttack[]; ratings: R22Rating[]; analysis: R22Analysis; collector: Signature };
export type R22Trust = { dependencies: R22Registration["dependencies"]; workloadDigest: Digest; environmentDigest: Digest;
  scorerDigest: Digest; privacyDigest: Digest; registrationKeys: string[]; collectorKeys: string[];
  expectedRegistrationSignerId:string;expectedCollectorSignerId:string;
  simulatorScores:R22Registration["simulatorScores"]; statisticalPlan:R22Registration["statisticalPlan"];
  authorities:Record<CriterionRole,{id:string;publicKeyPem:string}>;candidateOwnerKeys:string[];
  protocol:R22Registration["protocol"];simulator:R22Registration["simulator"];
  raters: Record<string, { publicKeyPem: string; consentDigest: Digest; validFrom:string;validUntil:string;revoked:false;privacyAuthorityId:string }>;
  verifyRegistration(x: R22Registration): boolean; verifyTrial(x: R22TrialObservation): boolean;
  verifyCustodyAttack(x: R22CustodyAttack): boolean; verifyRating(x: R22Rating): boolean; verifyCost(x: R22Cost): boolean };

const json = canonicalSemanticJson, dig = (x: unknown): Digest => `sha256:${createHash("sha256").update(json(x)).digest("hex")}`;
const digest = (x: unknown): x is Digest => typeof x === "string" && /^sha256:[a-f0-9]{64}$/.test(x);
const date = (x: unknown) => typeof x === "string" && Number.isFinite(Date.parse(x));
const fp = (pem: string) => { try { return createHash("sha256").update(createPublicKey(pem).export({type:"spki",format:"der"})).digest("hex"); } catch { return "invalid"; } };
const same = (a: unknown, b: unknown) => json(a) === json(b);
function exact(x:unknown,ks:string[],label:string){if(!x||typeof x!=="object"||Array.isArray(x)||Object.keys(x).sort().join("\0")!==[...ks].sort().join("\0"))throw Error(`R22 ${label} schema invalid`);}
function signable(domain: string, x: any, key: string) { const body=structuredClone(x); body[key]={...body[key],signature:""}; return {domain,body}; }
function signed(body: unknown, s: Signature) { let ok=false; try { ok=createPublicKey(s.publicKeyPem).asymmetricKeyType==="ed25519"&&date(s.signedAt)&&verify(null,Buffer.from(json(body)),s.publicKeyPem,Buffer.from(s.signature,"base64")); } catch {} if(!ok)throw Error("R22 signature invalid"); }
export const signableR22Registration=(x:R22Registration)=>signable("open-autonomy/r22/registration/v1",x,"authority");
export const signableR22Rating=(x:R22Rating)=>signable("open-autonomy/r22/rating/v1",x,"signature");
export const signableR22Campaign=(x:R22Campaign)=>signable("open-autonomy/r22/collector/v1",x,"collector");
export const signableR22Criterion=(x:R22CriterionAttestation)=>signable(`open-autonomy/r22/criterion/${x.role}/v1`,x,"signature");
export const signableR22Enrollment=(x:R22Enrollment)=>signable("open-autonomy/r22/enrollment/v1",x,"signature");
export const signableR22Cost=(x:R22Cost)=>signable("open-autonomy/r22/cost/v1",x,"signature");
const keys=(xs:string[])=>xs.map(fp);
const exactSet=(actual:string[], expected:string[], label:string)=>{if(actual.length!==expected.length||new Set(actual).size!==actual.length||!same([...actual].sort(),[...expected].sort()))throw Error(`R22 ${label} matrix incomplete`);};
export function deriveR22SeededTrials(itemIds:string[],seed:string):R22Trial[]{return itemIds.slice().sort((a,b)=>dig({seed,itemId:a}).localeCompare(dig({seed,itemId:b}))).flatMap(itemId=>{const blockId=`${itemId}:0`,arms=dig({seed,blockId}).localeCompare(dig({seed,blockId,flip:true}))<0?["control","treatment"] as const:["treatment","control"] as const;return arms.map(arm=>({trialId:`${blockId}:${arm}`,blockId,itemId,arm}));});}

export function verifyR22ExternalCampaign(c:R22Campaign,t:R22Trust){
  exact(c,["schema","closureClaim","registration","criterionAttestations","enrollments","trials","custodyAttacks","ratings","analysis","collector"],"campaign");
  if(c.schema!=="autonomy.r22-external-campaign.v1"||c.closureClaim!==true)throw Error("R22 campaign invalid"); const r=c.registration;
  exact(r,["schema","campaignId","dependencies","workloadDigest","environmentDigest","scorerDigest","privacyDigest","trials","raterIds","itemIds","simulatorScores","statisticalPlan","protocol","simulator","startsAt","endsAt","authority"],"registration");
  if(r.schema!=="autonomy.r22-external-registration.v1"||!r.campaignId||!date(r.startsAt)||!date(r.endsAt)||Date.parse(r.startsAt)>=Date.parse(r.endsAt)||
    Object.keys(r.dependencies).sort().join("\0")!=="R10\0R11\0R14\0R16\0R20\0R21\0R3\0R4\0R8"||!same(r.dependencies,t.dependencies)||r.workloadDigest!==t.workloadDigest||r.environmentDigest!==t.environmentDigest||r.scorerDigest!==t.scorerDigest||r.privacyDigest!==t.privacyDigest||
    !same(r.simulatorScores,t.simulatorScores)||!same(r.statisticalPlan,t.statisticalPlan)||!same(r.protocol,t.protocol)||!same(r.simulator,t.simulator)||r.statisticalPlan.estimand!=="equal-block-mean-difference"||r.statisticalPlan.ciMethod!=="fixed-critical-normal"||r.statisticalPlan.alpha<=0||r.statisticalPlan.alpha>=1||r.statisticalPlan.criticalValue<=0||!Number.isSafeInteger(r.statisticalPlan.minimumBlocks)||r.statisticalPlan.minimumBlocks<2||
    ![...Object.values(r.dependencies),r.workloadDigest,r.environmentDigest,r.scorerDigest,r.privacyDigest].every(digest)||!t.verifyRegistration(r))throw Error("R22 registration policy/trust invalid");
  signed(signableR22Registration(r),r.authority); if(r.authority.signerId!==t.expectedRegistrationSignerId||!keys(t.registrationKeys).includes(fp(r.authority.publicKeyPem))||Date.parse(r.authority.signedAt)>Date.parse(r.startsAt))throw Error("R22 registration authority invalid");
  exact(r.protocol,["seed","randomization","replications","stoppingRule","retryPolicy","missingPolicy","censoringPolicy","outcome","unit","populationDigest","contaminationPolicy"],"protocol");exact(r.simulator,["id","version","role","populationDigest","minimumScore","maximumScore"],"simulator");if(!r.protocol.seed||r.protocol.randomization!=="seeded-block"||r.protocol.replications!==1||r.protocol.stoppingRule!=="fixed-matrix"||r.protocol.retryPolicy!=="no-retry"||r.protocol.missingPolicy!=="score-zero-for-failed-and-missing"||r.protocol.censoringPolicy!=="none"||!r.protocol.outcome||!r.protocol.unit||!digest(r.protocol.populationDigest)||r.protocol.contaminationPolicy!=="isolated"||!r.simulator.id||!r.simulator.version||r.simulator.role!=="simulator"||r.simulator.populationDigest!==r.protocol.populationDigest||r.simulator.minimumScore>=r.simulator.maximumScore)throw Error("R22 protocol/simulator invalid");
  const authorityRows=Object.values(t.authorities),authorityIds=authorityRows.map(x=>x.id),authorityFps=authorityRows.map(x=>fp(x.publicKeyPem)),candidateFps=t.candidateOwnerKeys.map(fp);if(authorityRows.length!==5||new Set(authorityIds).size!==5||new Set(authorityFps).size!==5||authorityFps.includes("invalid")||!candidateFps.length||candidateFps.includes("invalid")||new Set(candidateFps).size!==candidateFps.length||authorityFps.some(x=>candidateFps.includes(x)))throw Error("R22 digest authority independence invalid");
  const criterionDigest:Record<CriterionRole,Digest>={workload:r.workloadDigest,environment:r.environmentDigest,scorer:r.scorerDigest,privacy:r.privacyDigest,cost:dig({dimensions:R22_COST_DIMENSIONS})};exactSet(c.criterionAttestations.map(x=>x.role),Object.keys(t.authorities),"criterion attestation");for(const x of c.criterionAttestations){exact(x,["role","digest","signature"],"criterion attestation");const a=t.authorities[x.role];if(!a||x.digest!==criterionDigest[x.role]||x.signature.signerId!==a.id||fp(x.signature.publicKeyPem)!==fp(a.publicKeyPem)||Date.parse(x.signature.signedAt)>Date.parse(r.startsAt))throw Error("R22 criterion authority invalid");signed(signableR22Criterion(x),x.signature);}
  if(r.raterIds.length<2||new Set(r.raterIds).size!==r.raterIds.length||r.itemIds.length<30||new Set(r.itemIds).size!==r.itemIds.length||r.statisticalPlan.alpha!==.05||r.statisticalPlan.criticalValue!==1.96||r.statisticalPlan.minimumBlocks<30)throw Error("R22 preregistration invalid");
  const expectedTrials=deriveR22SeededTrials(r.itemIds,r.protocol.seed);if(!same(r.trials,expectedTrials))throw Error("R22 deterministic trial replay invalid");
  exactSet(r.simulatorScores.map(x=>x.itemId),r.itemIds,"registered simulator score");for(const x of r.simulatorScores){exact(x,["itemId","score"],"simulator score");if(!Number.isFinite(x.score)||x.score<r.simulator.minimumScore||x.score>r.simulator.maximumScore)throw Error("R22 simulator score invalid");}
  exactSet(c.trials.map(x=>x.trialId),r.trials.map(x=>x.trialId),"trial");
  const trialById=new Map(r.trials.map(x=>[x.trialId,x])); for(const x of c.trials){exact(x,["schema","campaignId","trialId","blockId","itemId","arm","status","outcome","evidenceDigest","observedAt"],"trial observation");const p=trialById.get(x.trialId);if(!p||!same({trialId:x.trialId,blockId:x.blockId,itemId:x.itemId,arm:x.arm},p)||x.schema!=="autonomy.r22-trial-observation.v1"||x.campaignId!==r.campaignId||!(["completed","failed","missing"] as const).includes(x.status)||(x.status==="completed"?!Number.isFinite(x.outcome):x.outcome!==null)||!digest(x.evidenceDigest)||!date(x.observedAt)||Date.parse(x.observedAt)<Date.parse(r.startsAt)||Date.parse(x.observedAt)>Date.parse(r.endsAt)||!t.verifyTrial(x))throw Error("R22 trial evidence invalid");}
  exactSet(c.custodyAttacks.map(x=>x.attack),[...R22_CUSTODY_ATTACKS],"custody attack"); for(const x of c.custodyAttacks){exact(x,["schema","campaignId","attack","rejected","evidenceDigest","observedAt"],"custody attack");if(x.schema!=="autonomy.r22-custody-attack.v1"||x.campaignId!==r.campaignId||x.rejected!==true||!digest(x.evidenceDigest)||!date(x.observedAt)||Date.parse(x.observedAt)<Date.parse(r.startsAt)||Date.parse(x.observedAt)>Date.parse(r.endsAt)||!t.verifyCustodyAttack(x))throw Error("R22 custody attack invalid");}
  const trustedIds=Object.keys(t.raters); exactSet(r.raterIds,trustedIds,"registered rater"); const trustedFps=trustedIds.map(id=>fp(t.raters[id]!.publicKeyPem)); if(trustedFps.includes("invalid")||new Set(trustedFps).size!==trustedFps.length)throw Error("R22 rater ID/key bijection invalid");
  exactSet(c.enrollments.map(x=>x.raterId),r.raterIds,"enrollment");for(const x of c.enrollments){exact(x,["raterId","raterKeyFingerprint","consentDigest","populationDigest","validFrom","validUntil","signature"],"enrollment");const rt=t.raters[x.raterId],pa=t.authorities.privacy;if(!rt||x.raterKeyFingerprint!==fp(rt.publicKeyPem)||x.consentDigest!==rt.consentDigest||x.populationDigest!==r.protocol.populationDigest||x.validFrom!==rt.validFrom||x.validUntil!==rt.validUntil||!date(x.validFrom)||!date(x.validUntil)||Date.parse(x.validFrom)>=Date.parse(x.validUntil)||x.signature.signerId!==pa.id||fp(x.signature.publicKeyPem)!==fp(pa.publicKeyPem)||Date.parse(x.signature.signedAt)>Date.parse(x.validFrom)||Date.parse(x.signature.signedAt)>Date.parse(r.startsAt))throw Error("R22 enrollment invalid");signed(signableR22Enrollment(x),x.signature);}
  exactSet(c.ratings.map(x=>`${x.raterId}:${x.itemId}`),r.raterIds.flatMap(a=>r.itemIds.map(b=>`${a}:${b}`)),"rating"); for(const x of c.ratings){exact(x,["schema","campaignId","raterId","itemId","score","consentDigest","evidenceDigest","observedAt","signature"],"rating");const rt=t.raters[x.raterId];if(x.schema!=="autonomy.r22-rating.v1"||x.campaignId!==r.campaignId||!rt||rt.revoked!==false||rt.privacyAuthorityId!==t.authorities.privacy.id||x.consentDigest!==rt.consentDigest||!digest(x.consentDigest)||!digest(x.evidenceDigest)||!Number.isFinite(x.score)||x.score<r.simulator.minimumScore||x.score>r.simulator.maximumScore||!date(x.observedAt)||Date.parse(x.observedAt)<Math.max(Date.parse(r.startsAt),Date.parse(rt.validFrom))||Date.parse(x.observedAt)>Math.min(Date.parse(r.endsAt),Date.parse(rt.validUntil))||!t.verifyRating(x))throw Error("R22 rating invalid");signed(signableR22Rating(x),x.signature);if(fp(x.signature.publicKeyPem)!==fp(rt.publicKeyPem)||x.signature.signerId!==x.raterId||Date.parse(x.signature.signedAt)<Date.parse(x.observedAt)||Date.parse(x.signature.signedAt)>Date.parse(r.endsAt))throw Error("R22 rating trust/causality invalid");}
  const blocks=[...new Set(r.trials.map(x=>x.blockId))], effects=blocks.map(blockId=>{const ps=r.trials.filter(x=>x.blockId===blockId),rows=ps.map(p=>c.trials.find(x=>x.trialId===p.trialId)!);const score=(x:R22TrialObservation)=>x.status==="completed"?x.outcome!:0;return {blockId,effect:score(rows.find(x=>x.arm==="treatment")!)-score(rows.find(x=>x.arm==="control")!)};}), mean=effects.reduce((n,x)=>n+x.effect,0)/effects.length, variance=effects.length>1?effects.reduce((n,x)=>n+(x.effect-mean)**2,0)/(effects.length*(effects.length-1)):0, half=1.96*Math.sqrt(variance);
  const plannedHalf=r.statisticalPlan.criticalValue*Math.sqrt(variance); exact(c.analysis,["blockEffects","estimand","variance","ci95","simulatorScores","transferRmse","costs","costTotals"],"analysis");if(!same(c.analysis.blockEffects,effects)||c.analysis.estimand!==mean||c.analysis.variance!==variance||!same(c.analysis.ci95,[mean-plannedHalf,mean+plannedHalf]))throw Error("R22 derived estimand invalid");
  if(!same(c.analysis.simulatorScores,r.simulatorScores))throw Error("R22 simulator analysis drift");const rmse=Math.sqrt(r.itemIds.reduce((n,id)=>{const human=c.ratings.filter(x=>x.itemId===id).reduce((a,x)=>a+x.score,0)/r.raterIds.length,sim=r.simulatorScores.find(x=>x.itemId===id)!.score;return n+(sim-human)**2;},0)/r.itemIds.length);if(c.analysis.transferRmse!==rmse)throw Error("R22 transfer invalid");
  exactSet(c.analysis.costs.map(x=>`${x.trialId}:${x.dimension}`),r.trials.flatMap(x=>R22_COST_DIMENSIONS.map(d=>`${x.trialId}:${d}`)),"cost");if(new Set(c.analysis.costs.map(x=>x.evidenceDigest)).size!==c.analysis.costs.length)throw Error("R22 cost evidence reused");for(const x of c.analysis.costs){exact(x,["trialId","dimension","unit","value","status","evidenceDigest","signature"],"cost");const ca=t.authorities.cost,trial=c.trials.find(y=>y.trialId===x.trialId);if(!trial||x.unit!==x.dimension||!digest(x.evidenceDigest)||!t.verifyCost(x)||x.status!=="observed"||x.value===null||!Number.isFinite(x.value)||x.value<0||x.signature.signerId!==ca.id||fp(x.signature.publicKeyPem)!==fp(ca.publicKeyPem)||Date.parse(x.signature.signedAt)<Date.parse(trial.observedAt)||Date.parse(x.signature.signedAt)>Date.parse(r.endsAt))throw Error("R22 cost invalid");signed(signableR22Cost(x),x.signature);}
  const totals=R22_COST_DIMENSIONS.map(dimension=>({dimension,value:c.analysis.costs.filter(x=>x.dimension===dimension).reduce((n,x)=>n+x.value!,0)}));if(!same(c.analysis.costTotals,totals))throw Error("R22 cost conservation invalid");
  signed(signableR22Campaign(c),c.collector);const latest=Math.max(...c.trials.map(x=>Date.parse(x.observedAt)),...c.ratings.map(x=>Date.parse(x.signature.signedAt)),...c.custodyAttacks.map(x=>Date.parse(x.observedAt)),...c.analysis.costs.map(x=>Date.parse(x.signature.signedAt)));const global=[fp(r.authority.publicKeyPem),fp(c.collector.publicKeyPem),...authorityFps,...trustedFps,...candidateFps];if(c.collector.signerId!==t.expectedCollectorSignerId||new Set(global).size!==global.length||!keys(t.collectorKeys).includes(fp(c.collector.publicKeyPem))||Date.parse(c.collector.signedAt)<latest||Date.parse(c.collector.signedAt)>Date.parse(r.endsAt))throw Error("R22 independent collector invalid");
  return {status:"R22-external-evidence-verified" as const,closureClaim:true as const,campaignId:r.campaignId,bundleDigest:dig(c)};
}
