import { createHash } from "node:crypto";
import { canonicalSemanticJson } from "./organization-canonical";
import{closeSync,existsSync,fsyncSync,mkdirSync,openSync,readFileSync,renameSync,rmSync,statSync,writeFileSync}from"node:fs";import{join}from"node:path";

export type FleetDriftClass="semantic"|"configuration"|"version"|"health"|"capacity"|"credential"|"policy"|"observation";
export type FleetComponent={id:string;semantic:string;configuration:string;version:string;healthy:boolean;capacity:number;credential:string;policy:string;observedAt:string};
export type FleetDesired={tenant:string;revision:string;components:Record<string,FleetComponent>;policy:{maxRepairsPerWindow:number;rateWindowMs:number;maintenanceWindows:Array<{start:string;end:string}>;canaryCount:number;maxFailures:number;observationMaxAgeMs:number;maxFutureSkewMs:number;hysteresisObservations?:number;maxOscillations?:number}};
export type FleetObservation={tenant:string;sequence:number;components:Record<string,FleetComponent>;observedAt:string;digest:string;signature:string};
export type FleetDrift={componentId:string;class:FleetDriftClass;desired:unknown;observed:unknown;repairable:boolean};
export type FleetEffect={id:string;tenant:string;fence:number;kind:"fence"|"repair"|"canary"|"rollback";componentIds:string[];desiredRevision:string;desiredDigest:string;driftFingerprint:string;drifts:FleetDrift[]};
export type FleetEffectAck={id:string;fence:number;durable:true;status:"healthy"|"failed";observedDigest:string};
export interface FleetRepairPort{perform(effect:FleetEffect):FleetEffectAck}
export interface FleetReconcilerTrust{sign(digest:string):string;verify(digest:string,signature:string):boolean;verifyObservation(digest:string,signature:string):boolean}
export interface FleetReconcilerBackend{load(tenant:string):FleetReconcilerState|undefined;compareAndSwap(tenant:string,expected:number|undefined,next:FleetReconcilerState):boolean}
export class MemoryFleetReconcilerBackend implements FleetReconcilerBackend{private values=new Map<string,FleetReconcilerState>();load(k:string){const v=this.values.get(k);return v&&structuredClone(v)}compareAndSwap(k:string,e:number|undefined,n:FleetReconcilerState){if(this.values.get(k)?.generation!==e)return false;this.values.set(k,structuredClone(n));return true}}
export const FLEET_FILE_BACKEND_PORTABILITY_ASSUMPTION="linux-proc-pid-start" as const;
export interface FleetProcessIdentityVerifier{identity(pid:number):string;alive(pid:number,identity:string):boolean}
const linuxProcessIdentity: FleetProcessIdentityVerifier={identity:processStart,alive:processAlive};
export class FileFleetReconcilerBackend implements FleetReconcilerBackend{
  static readonly portabilityAssumption=FLEET_FILE_BACKEND_PORTABILITY_ASSUMPTION;
  constructor(private root:string,private processIdentity:FleetProcessIdentityVerifier=linuxProcessIdentity,private orphanAgeMs=30_000){if(processIdentity===linuxProcessIdentity&&(process.platform!=="linux"||!existsSync("/proc/self/stat")||processStart(process.pid)==="unknown"))throw new Error(`${FLEET_FILE_BACKEND_PORTABILITY_ASSUMPTION} unavailable; inject FleetProcessIdentityVerifier`);mkdirSync(root,{recursive:true,mode:0o700})}private path(id:string){return join(this.root,`${createHash("sha256").update(id).digest("hex")}.fleet.json`)}
  load(id:string){try{return JSON.parse(readFileSync(this.path(id),"utf8"))as FleetReconcilerState}catch(e){if((e as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw e}}
  compareAndSwap(id:string,expected:number|undefined,next:FleetReconcilerState){const path=this.path(id),lock=`${path}.lock`,owner=this.acquire(lock);try{if(this.load(id)?.generation!==expected)return false;const temp=`${path}.${process.pid}.${owner.token}.tmp`,fd=openSync(temp,"wx",0o600);try{writeFileSync(fd,canonicalSemanticJson(next),"utf8");fsyncSync(fd)}finally{closeSync(fd)}renameSync(temp,path);const dir=openSync(this.root,"r");try{fsyncSync(dir)}finally{closeSync(dir)}return true}finally{try{const seen=JSON.parse(readFileSync(join(lock,"owner.json"),"utf8"));if(seen.token===owner.token)rmSync(lock,{recursive:true,force:true})}catch{}}}
  private acquire(lock:string){const owner={pid:process.pid,start:this.processIdentity.identity(process.pid),token:`${process.pid}:${Date.now()}:${Math.random()}`},wait=()=>Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,5);for(let n=0;n<6000;n++){try{mkdirSync(lock);writeFileSync(join(lock,"owner.json"),canonicalSemanticJson(owner),{mode:0o600,flag:"wx"});return owner}catch(e){if((e as NodeJS.ErrnoException).code!=="EEXIST")throw e;let malformed=false;try{const seen=JSON.parse(readFileSync(join(lock,"owner.json"),"utf8"))as{pid:number;start:string;token:string};if(!Number.isSafeInteger(seen.pid)||typeof seen.start!=="string"||typeof seen.token!=="string")malformed=true;else if(!this.processIdentity.alive(seen.pid,seen.start)){this.quarantine(lock);continue}}catch{malformed=true}if(malformed){try{if(Date.now()-statSync(lock).mtimeMs>=this.orphanAgeMs){this.quarantine(lock);continue}}catch{}}wait()}}throw new Error("fleet reconciler lock timeout")}
  private quarantine(lock:string){const claimed=`${lock}.reclaimed.${process.pid}.${Date.now()}.${Math.random().toString(16).slice(2)}`;try{renameSync(lock,claimed);rmSync(claimed,{recursive:true,force:true})}catch(e){if(!["ENOENT","EEXIST"].includes((e as NodeJS.ErrnoException).code??""))throw e}}
}
export type FleetTrace={id:string;at:string;kind:"repair"|"canary"|"rollback"|"pause"|"refusal"|"escalation"|"converged";detail:string;effectId?:string};
export type FleetReconcilerState={schema:"autonomy.fleet-reconciler.v1";tenant:string;generation:number;fence:number;desiredRevision?:string;desiredDigest?:string;lastObservationSequence:number;lastObservationDigest?:string;paused:boolean;repairTimes:string[];failures:number;driftFingerprint?:string;driftStreak:number;oscillations:number;effects:Record<string,{effect:FleetEffect;status:"prepared"|"acked"|"failed";ack?:FleetEffectAck}>;trace:FleetTrace[];digest:string;signature:string};
export type FleetReconcileResult={status:"green"|"repairing"|"paused"|"deferred"|"escalated";drifts:FleetDrift[];effects:string[];fence:number};

export class FleetReconciler{
  private operationNow?:string;
  constructor(readonly tenant:string,private backend:FleetReconcilerBackend,private port:FleetRepairPort,private trust:FleetReconcilerTrust,private clock:()=>string=()=>new Date().toISOString()){if(!tenant)throw new Error("fleet tenant required");this.initialize()}
  acquireFence(){let entry=Object.values(this.current().effects).find(e=>e.effect.kind==="fence"&&e.status==="prepared");if(!entry){this.mutate(s=>{s.fence++;const b={tenant:this.tenant,fence:s.fence,kind:"fence" as const,componentIds:[],desiredRevision:s.desiredRevision??"unbound",desiredDigest:s.desiredDigest??hash("unbound"),driftFingerprint:hash({kind:"fence",fence:s.fence}),drifts:[]},effect={id:hash(b),...b};s.effects[effect.id]={effect,status:"prepared"}});entry=Object.values(this.current().effects).find(e=>e.effect.kind==="fence"&&e.status==="prepared")!}const ack=this.port.perform(entry.effect);if(ack.id!==entry.effect.id||ack.fence!==entry.effect.fence||ack.durable!==true||ack.status!=="healthy")throw new Error("invalid fence acknowledgement");this.mutate(s=>{const live=s.effects[entry!.effect.id];if(!live||live.status!=="prepared"||live.effect.fence!==s.fence)throw new Error("stale fence takeover");live.status="acked";live.ack=ack});return entry.effect.fence}
  pause(fence:number){this.operationNow=undefined;this.mutate(s=>{this.assertFence(s,fence);s.paused=true;this.trace(s,"pause","repairs paused")})}
  resume(fence:number){this.operationNow=undefined;this.mutate(s=>{this.assertFence(s,fence);s.paused=false;this.trace(s,"pause","repairs resumed")})}
  reconcile(desired:FleetDesired,observed:FleetObservation,fence:number,now=this.clock()):FleetReconcileResult{
    this.operationNow=now;
    validateInputs(this.tenant,desired,observed,now);const observationDigest=fleetObservationDigest(observed);if(observed.digest!==observationDigest||!this.trust.verifyObservation(observationDigest,observed.signature))throw new Error("fleet observation attestation failed");const desiredDigest=hash(desired),drifts=classify(desired,observed,now);
    this.mutate(s=>{this.assertFence(s,fence);if(s.desiredDigest&&s.desiredDigest!==desiredDigest&&desired.revision===s.desiredRevision)throw new Error("desired revision equivocation");if(observed.sequence<s.lastObservationSequence)throw new Error("observation sequence rollback");if(observed.sequence===s.lastObservationSequence&&s.lastObservationDigest&&s.lastObservationDigest!==observationDigest)throw new Error("observation sequence equivocation");s.desiredRevision=desired.revision;s.desiredDigest=desiredDigest;s.lastObservationSequence=observed.sequence;s.lastObservationDigest=observationDigest});
    let state=this.current();
    if(!drifts.length){this.mutate(s=>{s.driftFingerprint=undefined;s.driftStreak=0;s.oscillations=0;this.trace(s,"converged",`healthy at observation ${observed.sequence}`)});return{status:"green",drifts:[],effects:[],fence}}
    if(drifts.some(d=>!d.repairable)){this.mutate(s=>this.trace(s,"escalation","irreconcilable observation drift"));return{status:"escalated",drifts,effects:[],fence}}
    if(state.paused){this.mutate(s=>this.trace(s,"pause","drift retained while paused"));return{status:"paused",drifts,effects:[],fence}}
    if(!inWindow(desired.policy.maintenanceWindows,now)){this.mutate(s=>this.trace(s,"refusal","outside maintenance window"));return{status:"deferred",drifts,effects:[],fence}}
    const cutoff=Date.parse(now)-desired.policy.rateWindowMs,recent=state.repairTimes.filter(t=>Date.parse(t)>=cutoff);if(recent.length>=desired.policy.maxRepairsPerWindow){this.mutate(s=>this.trace(s,"refusal","repair rate limit reached"));return{status:"deferred",drifts,effects:[],fence}}
    if(state.failures>=desired.policy.maxFailures){this.mutate(s=>this.trace(s,"escalation","repair failure bound reached"));return{status:"escalated",drifts,effects:[],fence}}
    const fingerprint=hash(drifts),required=desired.policy.hysteresisObservations??1,maxOscillations=desired.policy.maxOscillations??8;this.mutate(s=>{if(s.driftFingerprint===fingerprint)s.driftStreak++;else{if(s.driftFingerprint)s.oscillations++;s.driftFingerprint=fingerprint;s.driftStreak=1}});state=this.current();if(state.oscillations>=maxOscillations){this.mutate(s=>this.trace(s,"escalation","oscillation bound reached"));return{status:"escalated",drifts,effects:[],fence}}if(state.driftStreak<required){this.mutate(s=>this.trace(s,"refusal",`hysteresis ${state.driftStreak}/${required}`));return{status:"deferred",drifts,effects:[],fence}}
    const risky=drifts.some(d=>["semantic","version","policy"].includes(d.class)),ids=[...new Set(drifts.map(d=>d.componentId))].sort(),canaryIds=risky?ids.slice(0,Math.max(1,desired.policy.canaryCount)):ids,priorCanary=Object.values(state.effects).some(e=>e.effect.kind==="canary"&&e.effect.desiredDigest===desiredDigest&&e.effect.driftFingerprint===fingerprint&&e.effect.componentIds.join("\0")===canaryIds.join("\0")&&e.ack?.status==="healthy"&&!!e.ack.observedDigest),kind:FleetEffect["kind"]=risky&&!priorCanary?"canary":"repair",targetIds=kind==="canary"?canaryIds:ids,effectBody={tenant:this.tenant,fence,kind,componentIds:targetIds,desiredRevision:desired.revision,desiredDigest,driftFingerprint:fingerprint,drifts:drifts.filter(d=>targetIds.includes(d.componentId))},effect={id:hash(effectBody),...effectBody};
    this.mutate(s=>{this.assertFence(s,fence);s.effects[effect.id]??={effect,status:"prepared"};this.trace(s,kind,`${kind} prepared`,effect.id)});
    const ack=this.port.perform(effect);if(ack.id!==effect.id||ack.fence!==fence||ack.durable!==true)throw new Error("invalid fenced repair acknowledgement");
    this.mutate(s=>{this.assertFence(s,fence);const entry=s.effects[effect.id];if(!entry||hash(entry.effect)!==hash(effect))throw new Error("repair effect equivocation");entry.status="acked";entry.ack=ack;s.repairTimes=[...s.repairTimes.filter(t=>Date.parse(t)>=cutoff),now];if(ack.status==="failed"){s.failures++;this.trace(s,"rollback","canary failed; rollback required",effect.id);this.trace(s,"escalation","repair failure observed",effect.id)}else{s.failures=0;this.trace(s,kind,`${kind} healthy`,effect.id)}});
    if(ack.status==="failed"){const rollbackBody={tenant:this.tenant,fence,kind:"rollback" as const,componentIds:effect.componentIds,desiredRevision:desired.revision,desiredDigest,driftFingerprint:fingerprint,drifts:effect.drifts},rollback={id:hash(rollbackBody),...rollbackBody};this.mutate(s=>{this.assertFence(s,fence);s.effects[rollback.id]??={effect:rollback,status:"prepared"}});this.assertFence(this.current(),fence);const rollbackAck=this.port.perform(rollback);if(rollbackAck.id!==rollback.id||rollbackAck.fence!==fence||!rollbackAck.durable)throw new Error("invalid rollback acknowledgement");this.mutate(s=>{this.assertFence(s,fence);const e=s.effects[rollback.id];if(!e||e.status!=="prepared")throw new Error("rollback prepare lost");e.ack=rollbackAck;if(rollbackAck.status!=="healthy"){e.status="failed";this.trace(s,"escalation","rollback failed",rollback.id);return}e.status="acked";this.trace(s,"rollback","rollback effect acknowledged",rollback.id)})}
    return{status:ack.status==="failed"?"escalated":"repairing",drifts,effects:[effect.id],fence};
  }
  current(){const s=this.backend.load(this.tenant);if(!s){throw new Error("fleet reconciler state missing")}const expected=hash(body(s));if(s.digest!==expected||!this.trust.verify(expected,s.signature)||s.schema!=="autonomy.fleet-reconciler.v1"||s.trace.length>10_000||Object.keys(s.effects).length>10_000)throw new Error("fleet reconciler state integrity failure");return structuredClone(s)}
  private initialize(){if(this.backend.load(this.tenant)){this.current();return}const b={schema:"autonomy.fleet-reconciler.v1" as const,tenant:this.tenant,generation:1,fence:0,lastObservationSequence:0,paused:false,repairTimes:[],failures:0,driftStreak:0,oscillations:0,effects:{},trace:[]},digest=hash(b),n={...b,digest,signature:this.trust.sign(digest)};if(!this.backend.compareAndSwap(this.tenant,undefined,n))throw new Error("fleet reconciler creation race")}
  private mutate<T>(fn:(s:FleetReconcilerState)=>T){for(let i=0;i<12;i++){const old=this.current(),next=structuredClone(old),result=fn(next);next.generation++;const digest=hash(body(next));next.digest=digest;next.signature=this.trust.sign(digest);if(this.backend.compareAndSwap(this.tenant,old.generation,next))return result}throw new Error("fleet reconciler CAS contention")}
  private assertFence(s:FleetReconcilerState,fence:number){if(fence!==s.fence)throw new Error("stale fleet reconciliation fence")}
  private trace(s:FleetReconcilerState,kind:FleetTrace["kind"],detail:string,effectId?:string){const at=this.operationNow??this.clock(),t={id:hash({generation:s.generation,at,kind,detail,effectId}),at,kind,detail,...(effectId?{effectId}:{})};s.trace.push(t);if(s.trace.length>10_000)s.trace.splice(0,s.trace.length-10_000)}
}

export function classify(desired:FleetDesired,observed:FleetObservation,now:string){const out:FleetDrift[]=[];for(const id of Object.keys(observed.components))if(!desired.components[id])out.push({componentId:id,class:"observation",desired:"absent",observed:"extra",repairable:false});for(const [id,want] of Object.entries(desired.components)){const got=observed.components[id];if(!got){out.push({componentId:id,class:"observation",desired:"present",observed:"missing",repairable:false});continue}const add=(c:FleetDriftClass,a:unknown,b:unknown,r=true)=>{if(a!==b)out.push({componentId:id,class:c,desired:a,observed:b,repairable:r})};add("semantic",want.semantic,got.semantic);add("configuration",want.configuration,got.configuration);add("version",want.version,got.version);add("health",want.healthy,got.healthy);if(got.capacity<want.capacity)out.push({componentId:id,class:"capacity",desired:want.capacity,observed:got.capacity,repairable:true});add("credential",want.credential,got.credential);add("policy",want.policy,got.policy);if(!Number.isFinite(Date.parse(got.observedAt))||Date.parse(now)-Date.parse(got.observedAt)>desired.policy.observationMaxAgeMs)out.push({componentId:id,class:"observation",desired:`age<=${desired.policy.observationMaxAgeMs}`,observed:got.observedAt,repairable:false})}return out.sort((a,b)=>a.componentId.localeCompare(b.componentId)||a.class.localeCompare(b.class))}
export function fleetObservationDigest(o:FleetObservation){const{digest:_,signature:__,...body}=o;return hash(body)}
function validateInputs(t:string,d:FleetDesired,o:FleetObservation,n:string){const now=Date.parse(n),future=now+d.policy.maxFutureSkewMs,times=[o.observedAt,...Object.values(o.components).map(c=>c.observedAt)];if(d.tenant!==t||o.tenant!==t||!d.revision||!Number.isSafeInteger(o.sequence)||o.sequence<0||!Number.isFinite(now)||!Number.isSafeInteger(d.policy.maxFutureSkewMs)||d.policy.maxFutureSkewMs<0||times.some(v=>!Number.isFinite(Date.parse(v))||Date.parse(v)>future)||d.policy.maxRepairsPerWindow<1||d.policy.rateWindowMs<1||d.policy.maxFailures<1)throw new Error("fleet reconcile input invalid")}
function inWindow(w:FleetDesired["policy"]["maintenanceWindows"],now:string){return !w.length||w.some(x=>Date.parse(x.start)<=Date.parse(now)&&Date.parse(now)<=Date.parse(x.end))}
function body(s:FleetReconcilerState){const{digest:_,signature:__,...b}=s;return b}function hash(v:unknown){return createHash("sha256").update(canonicalSemanticJson(v)).digest("hex")}
function processStart(pid:number){try{return readFileSync(`/proc/${pid}/stat`,"utf8").split(" ")[21]??"unknown"}catch{return"unknown"}}function processAlive(pid:number,start:string){try{process.kill(pid,0);return processStart(pid)===start}catch{return false}}
