import{createHash}from"node:crypto";import{canonicalSemanticJson}from"./organization-canonical";import{fleetObservationDigest,type FleetEffect,type FleetEffectAck,type FleetObservation,type FleetRepairPort}from"./organization-fleet-reconciler";

export interface FleetObservationSigner{signObservation(digest:string):string}
export type RuntimeComponentIdentity={id:string;semantic:string;configuration:string;version:string;credential:string;policy:string};
export interface HermesFleetLifecycle{fence():number;pause(operationId:string):void;resume(operationId:string):void;repair(operationId:string,components:string[]):void;rollback(operationId:string,components:string[]):void}
export interface PaperclipFleetLifecycle{fence():number;restart(operationId:string):unknown;rollback(operationId:string):unknown}
function sealObservation(body:Omit<FleetObservation,"digest"|"signature">,signer:FleetObservationSigner):FleetObservation{const provisional={...body,digest:"",signature:""},digest=fleetObservationDigest(provisional);return{...body,digest,signature:signer.signObservation(digest)}}
export function runtimeAdapterDigest(v:unknown){return createHash("sha256").update(canonicalSemanticJson(v)).digest("hex")}

export type NativeRuntimeProbe=()=>RuntimeComponentIdentity&{healthy:boolean;capacity:number;observedAt:string};
export class NativeFleetObservationAdapter{constructor(private tenant:string,private probe:NativeRuntimeProbe,private signer:FleetObservationSigner){}observe(sequence:number){const component=this.probe();return sealObservation({tenant:this.tenant,sequence,components:{[component.id]:component},observedAt:component.observedAt},this.signer)}}
export interface VerifiedRepairEvidence{observe(effect:FleetEffect):FleetObservation;verify(observation:FleetObservation):boolean;cleared(effect:FleetEffect,observation:FleetObservation):boolean}
export class VerifiedRuntimeFleetRepairAdapter implements FleetRepairPort{private receipts=new Map<string,FleetEffectAck>();constructor(private hermes:HermesFleetLifecycle,private paperclip:PaperclipFleetLifecycle,private evidence:VerifiedRepairEvidence){}perform(effect:FleetEffect){const prior=this.receipts.get(effect.id);if(prior)return prior;const substrates=new Set(effect.componentIds.map(id=>id.startsWith("hermes")?"hermes":id.startsWith("paperclip")?"paperclip":"unknown"));if(substrates.has("unknown")||substrates.size>1||(!effect.componentIds.length&&effect.kind!=="fence"))throw new Error("mixed or empty runtime repair effect refused atomically");const paperclip=substrates.has("paperclip"),target=paperclip?this.paperclip:this.hermes;if(target.fence()!==effect.fence)throw new Error("verified runtime repair fence mismatch");if(effect.kind==="rollback"){if(paperclip)this.paperclip.rollback(effect.id);else this.hermes.rollback(effect.id,effect.componentIds)}else if(effect.kind!=="fence"){if(paperclip)this.paperclip.restart(effect.id);else this.hermes.repair(effect.id,effect.componentIds)}const observation=this.evidence.observe(effect);if(!this.evidence.verify(observation)||!this.evidence.cleared(effect,observation))return{id:effect.id,fence:effect.fence,durable:true,status:"failed",observedDigest:observation.digest};const ack:FleetEffectAck={id:effect.id,fence:effect.fence,durable:true,status:"healthy",observedDigest:runtimeAdapterDigest({effectId:effect.id,observationDigest:observation.digest})};this.receipts.set(effect.id,ack);return ack}}
export type WeakerTeardownResidual={kind:"weaker-teardown-guarantee";resourceId:string;requested:"delete";observed:"archived";detail:string};
