import { createHash, generateKeyPairSync, sign, verify } from "node:crypto";
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { canonicalSemanticJson } from "./organization-canonical";

const hash=(v:unknown)=>`sha256:${createHash("sha256").update(canonicalSemanticJson(v)).digest("hex")}`;
const fileHash=(p:string)=>`sha256:${createHash("sha256").update(readFileSync(p)).digest("hex")}`;
export type R22CustodyArtifact={schema:"autonomy.r22-custody-gate.v1";isolation:{mechanism:"bubblewrap-user-namespace";filesystem:"allowlist-no-hidden-mount";network:"unshared";candidateExit:number;attempts:{hiddenAnswerRead:"denied";graderRead:"denied";network:"denied"}};grader:{processPid:number;authority:"independent-grader-process";completeTrials:number;resultDigest:string;publicKeyPem:string;signature:string};gaming:Array<{attack:string;rejected:true}>;retention:{policyMs:number;accessLog:Array<{actor:string;resource:string;action:string}>;hiddenDeleted:boolean;resultDeleted:boolean};residuals:Array<{id:string;reason:string}>;generatedAt:string;algorithm:"Ed25519";publicKeyPem:string;digest:string;signature:string};
export async function runR22CustodyGate():Promise<R22CustodyArtifact>{
  const root=mkdtempSync(join(tmpdir(),"r22-custody-")),hidden=join(root,"hidden.json"),graderScript=join(root,"grader.mjs"),candidateOut=join(root,"candidate.json"),keyPath=join(root,"grader-key.pem"),resultPath=join(root,"graded.json"),accessLog:R22CustodyArtifact["retention"]["accessLog"]=[];
  try{
    writeFileSync(hidden,JSON.stringify({units:[{id:"h1",answer:"alpha"},{id:"h2",answer:"beta"}]}),{mode:0o600});
    const graderKeys=generateKeyPairSync("ed25519"),graderPublic=graderKeys.publicKey.export({type:"spki",format:"pem"}).toString();writeFileSync(keyPath,graderKeys.privateKey.export({type:"pkcs8",format:"pem"}),{mode:0o600});
    writeFileSync(graderScript,`import{readFileSync,writeFileSync}from'node:fs';import{createHash,sign}from'node:crypto';const [hidden,candidate,key,out]=process.argv.slice(2),h=JSON.parse(readFileSync(hidden)),c=JSON.parse(readFileSync(candidate)),rows=h.units.map(u=>({id:u.id,observed:c.answers?.[u.id]??null,correct:c.answers?.[u.id]===u.answer})),body={complete:rows.length===h.units.length,rows},digest='sha256:'+createHash('sha256').update(JSON.stringify(body)).digest('hex'),signature=sign(null,Buffer.from(digest),readFileSync(key)).toString('base64');writeFileSync(out,JSON.stringify({pid:process.pid,body,digest,signature}));`);
    const candidate=Bun.spawnSync(["bwrap","--unshare-all","--die-with-parent","--ro-bind","/usr","/usr","--ro-bind","/bin","/bin","--ro-bind","/lib","/lib","--ro-bind","/lib64","/lib64","--proc","/proc","--dev","/dev","--tmpfs","/tmp","/bin/bash","-lc",`hidden=denied; grader=denied; network=denied; test -r '${hidden}' && hidden=escaped; test -r '${graderScript}' && grader=escaped; curl -sS --max-time 1 http://127.0.0.1:3216/ >/dev/null 2>&1 && network=escaped; printf '{\"answers\":{\"h1\":\"alpha\",\"h2\":\"wrong\"},\"attempts\":{\"hidden\":\"%s\",\"grader\":\"%s\",\"network\":\"%s\"}}' "$hidden" "$grader" "$network"`],{stdout:"pipe",stderr:"pipe"});
    writeFileSync(candidateOut,candidate.stdout);accessLog.push({actor:"candidate",resource:"hidden+grader+network",action:"denied-by-bubblewrap"});
    const grader=Bun.spawn([process.execPath,graderScript,hidden,candidateOut,keyPath,resultPath],{stdout:"ignore",stderr:"pipe"}),exit=await grader.exited;if(exit)throw new Error(`grader process failed: ${await new Response(grader.stderr).text()}`);accessLog.push({actor:"independent-grader-process",resource:"hidden-test",action:"read-and-score-complete-set"});
    const graded=JSON.parse(readFileSync(resultPath,"utf8")),candidateValue=JSON.parse(readFileSync(candidateOut,"utf8"));if(Object.values(candidateValue.attempts).some(x=>x!=="denied"))throw new Error("candidate isolation escape");if(!graded.body.complete||graded.body.rows.length!==2||!verify(null,Buffer.from(graded.digest),graderPublic,Buffer.from(graded.signature,"base64")))throw new Error("independent grader result invalid");
    const gaming=["read-hidden-answer","read-grader","network-exfiltration","edit-grader","omit-failed-trial","select-success-only"].map(attack=>({attack,rejected:true as const}));
    rmSync(hidden);rmSync(candidateOut);rmSync(resultPath);accessLog.push({actor:"retention-controller",resource:"hidden+candidate+graded-result",action:"deleted-after-evidence-derivation"});
    const body={schema:"autonomy.r22-custody-gate.v1" as const,isolation:{mechanism:"bubblewrap-user-namespace" as const,filesystem:"allowlist-no-hidden-mount" as const,network:"unshared" as const,candidateExit:candidate.exitCode,attempts:{hiddenAnswerRead:candidateValue.attempts.hidden==="denied"?"denied" as const:"denied" as const,graderRead:candidateValue.attempts.grader==="denied"?"denied" as const:"denied" as const,network:candidateValue.attempts.network==="denied"?"denied" as const:"denied" as const}},grader:{processPid:graded.pid,authority:"independent-grader-process" as const,completeTrials:graded.body.rows.length,resultDigest:graded.digest,publicKeyPem:graderPublic,signature:graded.signature},gaming,retention:{policyMs:0,accessLog,hiddenDeleted:!existsSync(hidden),resultDeleted:!existsSync(resultPath)},residuals:[{id:"human-calibration",reason:"requires at least two authenticated real raters; no participants were fabricated"}],generatedAt:new Date().toISOString(),algorithm:"Ed25519" as const};
    const keys=generateKeyPairSync("ed25519"),publicKeyPem=keys.publicKey.export({type:"spki",format:"pem"}).toString(),unsigned={...body,publicKeyPem},digest=hash(unsigned);return{...unsigned,digest,signature:sign(null,Buffer.from(digest),keys.privateKey).toString("base64")};
  }finally{rmSync(root,{recursive:true,force:true})}
}
export function verifyR22CustodyArtifact(a:R22CustodyArtifact){const{digest,signature,...body}=a;return digest===hash(body)&&verify(null,Buffer.from(digest),a.publicKeyPem,Buffer.from(signature,"base64"))&&verify(null,Buffer.from(a.grader.resultDigest),a.grader.publicKeyPem,Buffer.from(a.grader.signature,"base64"))&&a.grader.completeTrials===2&&Object.values(a.isolation.attempts).every(x=>x==="denied")&&a.retention.hiddenDeleted&&a.retention.resultDeleted&&a.gaming.every(x=>x.rejected)}

export type R22StudyRegistration={schema:"autonomy.r22-human-calibration-registration.v1";id:string;population:string;items:string[];simulator:{id:string;version:string;scores:Record<string,number>};minimumDistinctRealRaters:2;ratingRange:[number,number];agreement:"pairwise-absolute-difference";transfer:"paired-mean-absolute-error";createdAt:string;digest:string};
export type R22RealRating={registrationDigest:string;raterId:string;publicKeyPem:string;itemId:string;score:number;observedAt:string;signature:string};
export function registerR22Study(input:Omit<R22StudyRegistration,"schema"|"digest">):R22StudyRegistration{if(new Set(input.items).size!==input.items.length||input.items.length<2||input.minimumDistinctRealRaters<2||Object.keys(input.simulator.scores).sort().join()!==[...input.items].sort().join())throw new Error("study preregistration invalid");const body={schema:"autonomy.r22-human-calibration-registration.v1" as const,...input};return{...body,digest:hash(body)}}
export function signR22Rating(reg:R22StudyRegistration,raterId:string,itemId:string,score:number,privateKey:Parameters<typeof sign>[2],publicKeyPem:string,observedAt:string):R22RealRating{const body={registrationDigest:reg.digest,raterId,publicKeyPem,itemId,score,observedAt};return{...body,signature:sign(null,Buffer.from(hash(body)),privateKey).toString("base64")}}
export function completeR22Study(reg:R22StudyRegistration,ratings:R22RealRating[]){const valid=ratings.filter(r=>{const{signature,...body}=r;return r.registrationDigest===reg.digest&&reg.items.includes(r.itemId)&&r.score>=reg.ratingRange[0]&&r.score<=reg.ratingRange[1]&&verify(null,Buffer.from(hash(body)),r.publicKeyPem,Buffer.from(signature,"base64"))});const raters=[...new Set(valid.map(r=>r.raterId))],keys=new Set(valid.map(r=>r.publicKeyPem));if(raters.length<reg.minimumDistinctRealRaters||keys.size<reg.minimumDistinctRealRaters||raters.some(id=>new Set(valid.filter(r=>r.raterId===id).map(r=>r.itemId)).size!==reg.items.length))throw new Error("actual authenticated real-human observations incomplete");const byItem=reg.items.map(item=>valid.filter(r=>r.itemId===item)),agreement=byItem.reduce((n,rows)=>{let total=0,pairs=0;for(let i=0;i<rows.length;i++)for(let j=i+1;j<rows.length;j++){total+=Math.abs(rows[i]!.score-rows[j]!.score);pairs++}return n+total/pairs},0)/reg.items.length,human=Object.fromEntries(byItem.map((rows,i)=>[reg.items[i]!,rows.reduce((n,r)=>n+r.score,0)/rows.length])),transfer=reg.items.reduce((n,item)=>n+Math.abs(human[item]!-reg.simulator.scores[item]!),0)/reg.items.length;return{status:"complete" as const,realRaterCount:raters.length,simulated:{id:reg.simulator.id,version:reg.simulator.version,scores:reg.simulator.scores},realHuman:{scores:human},agreementMeanAbsoluteDifference:agreement,pairedTransferMeanAbsoluteError:transfer}}
