import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import { canonicalSemanticJson as C } from "./organization-canonical";
import type { FrozenU3ObservationCalculus } from "./organization-u3-observation-calculus";
import { verifyFrozenU4SourceInventory, type FrozenU4SourceInventory, type FrozenU4SyntheticSourceRegistry, type U4TrustedVerificationInputs } from "./organization-u4-source-inventory";

type Sha=`sha256:${string}`;
type Kind=FrozenU4SourceInventory["provenance"][number]["kind"];
const H=(x:string|Uint8Array)=>`sha256:${createHash("sha256").update(x).digest("hex")}` as Sha;
const MAC=(key:Buffer,domain:string,value:unknown)=>createHmac("sha256",key).update(domain).update("\0").update(C(value)).digest("hex");
const SPEC_SCHEMA="open-autonomy.u4-extraction-specification.v1" as const;
const RESULT_SCHEMA="open-autonomy.u4-evidence-extraction.v2" as const;
const KINDS:Kind[]=["native-schema","official-spec","runtime-probe","source-behavior"];
/** Independently reviewed synthetic preregistration. Changing any declaration requires
 * a code-reviewed anchor update; a caller cannot redigest a post-evidence plan. */
export const EXPECTED_U4_SYNTHETIC_EXTRACTION_SPEC_DIGEST="sha256:207e20b68d65c7d958d7a90714e87aaa0f1d6b5461895f8d328409628c22b809" as Sha;
export const U4_SYNTHETIC_EXTRACTION_SCENARIO_ANCHORS=Object.freeze({base:EXPECTED_U4_SYNTHETIC_EXTRACTION_SPEC_DIGEST,"critical-gap":"sha256:3e1a06bc05ab1b3bec0d81b85081c41f1ce0e578648955fd4924c3c018fd4dbc" as Sha,"noncritical-gap":"sha256:91a90efba4952d20a4162a6b874b5fbb2845bcda9204dfb3f9da183d5730e088" as Sha});

export type U4ExtractionLocator={
  id:string; slotId:string; slotTaxonomy:"behavior-proposition"|"probe-proposition"|"native-schema-leaf"|"official-spec-leaf"; factId:string; provenanceId:string; provenanceKind:Kind; sourceId:string;
  sourceVersion:string; nativePath:string; nativeSchemaId:string;
  mode:"json-pointer"|"terminal"; pointer:string|null;
  terminal:"unsupported"|"opaque"|null;
};
export type U4ExtractionDocument={
  provenanceId:string;sourceId:string;sourceVersion:string;provenanceKind:Kind; traversal:"canonical-json-leaves-v1"|"opaque-terminal-only";
  allowedLeafPointers:string[];
};
export type U4ExtractionSlotDeclaration={id:string;factId:string;denotation:string;comparisonKinds:Kind[];metadataKinds:Kind[];requiredComparisonKinds:Kind[];criticalityPolicy:"inherit-fact"};
export type U4ExtractionSpecification={
  schema:typeof SPEC_SCHEMA; fixtureKind:"synthetic"; denominatorScope:"fixture-local";
  empiricalRegistration:false; closureClaim:false;
  genericExtractorCompleteness:"deferred-external-validation";
  campaignId:string;sourceRegistryDigest:Sha;calculusDigest:Sha; issuedAt:string; authorityId:string;
  documents:U4ExtractionDocument[]; slots:U4ExtractionSlotDeclaration[];locators:U4ExtractionLocator[]; receipt:string;
};
export type U4EvidenceCandidate=U4ExtractionLocator&{
  provenanceId:string; evidenceSha256:Sha;
  documentLocator:{byteStart:0;byteEnd:number;jsonPointer:string|null};
  propositionJson:string|null; propositionDigest:Sha|null;
  semanticSlot:{denotation:string;comparable:boolean;criticalityPolicy:"inherit-fact"};
  inventoryJoin:{taxonomy:FrozenU4SourceInventory["facts"][number]["taxonomy"];nativePath:string;denotationDigest:Sha;assertion:"candidate-only-no-empirical-truth-claim"};
};
export type U4EvidenceExtraction={
  schema:typeof RESULT_SCHEMA;fixtureKind:"synthetic";denominatorScope:"fixture-local";
  empiricalRegistration:false;closureClaim:false;genericExtractorCompleteness:"deferred-external-validation";
  inventoryDigest:Sha;specificationDigest:Sha;candidates:U4EvidenceCandidate[];
  specifiedLocatorIds:string[];extractedLocatorIds:string[];digest:Sha;
};

function bounded(...roots:unknown[]){let nodes=0,bytes=0;const active=new Set<object>(),q:Array<[unknown,number,boolean]>=roots.map(x=>[x,0,true]);while(q.length){const[x,d,e]=q.pop()!;if(!e){active.delete(x as object);continue}if(++nodes>30000||d>48)throw Error("U4 extraction resource bound");if(typeof x==="string"){const n=Buffer.byteLength(x);if(n>1_048_576)throw Error("U4 extraction field bound");bytes+=n;continue}if(!x||typeof x!=="object")continue;if(active.has(x as object))throw Error("U4 extraction cyclic input");active.add(x as object);q.push([x,d,false]);const values=Array.isArray(x)?x:Object.values(x);if(values.length>4096)throw Error("U4 extraction collection bound");for(const y of values)q.push([y,d+1,true])}if(bytes>8_388_608)throw Error("U4 extraction byte bound")}
const time=(x:unknown):x is string=>typeof x==="string"&&/^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(x)&&Number.isFinite(Date.parse(x))&&new Date(Date.parse(x)).toISOString()===x;
const ptr=(x:unknown):x is string=>typeof x==="string"&&(x===""||/^\/(?:[^~/]|~[01])+(?:\/(?:[^~/]|~[01])+)*$/.test(x));
const sid=(x:unknown):x is string=>typeof x==="string"&&/^[a-z0-9](?:[a-z0-9._-]*[a-z0-9])?$/.test(x)&&x.length<=200;
const sorted=(x:string[])=>Array.isArray(x)&&new Set(x).size===x.length&&C(x)===C([...x].sort());
const exact=(x:unknown,keys:string[],at:string):any=>{if(!x||typeof x!=="object"||Array.isArray(x)||C(Object.keys(x).sort())!==C([...keys].sort()))throw Error(`U4 extraction ${at} schema invalid`);return x};
const freeze=<T>(v:T):T=>{const q:any[]=[v];while(q.length){const x=q.pop();if(x&&typeof x==="object"&&!Object.isFrozen(x)){q.push(...Object.values(x));Object.freeze(x)}}return v};
const specBody=(s:U4ExtractionSpecification)=>{const{receipt:_,...body}=s;void _;return body};
export const computeU4ExtractionSpecificationDigest=(s:U4ExtractionSpecification)=>H(`${SPEC_SCHEMA}\0${C(specBody(s))}`);
export const signU4ExtractionSpecification=(keyBase64:string,s:U4ExtractionSpecification)=>MAC(Buffer.from(keyBase64,"base64"),"u4-extraction-specification",specBody(s));

function leaves(value:unknown,path=""):string[]{if(value===null||typeof value!=="object")return[path];const entries=Array.isArray(value)?value.map((v,i)=>[String(i),v] as const):Object.keys(value as object).sort().map(k=>[k,(value as any)[k]] as const);if(!entries.length)return[path];return entries.flatMap(([k,v])=>leaves(v,`${path}/${k.replace(/~/g,"~0").replace(/\//g,"~1")}`))}
function at(value:unknown,path:string){if(path==="")return value;let x:any=value;for(const raw of path.slice(1).split("/")){const k=raw.replace(/~1/g,"/").replace(/~0/g,"~");const ok=Array.isArray(x)?/^(0|[1-9]\d*)$/.test(k)&&Number(k)<x.length:x!==null&&typeof x==="object"&&Object.prototype.hasOwnProperty.call(x,k);if(!ok)throw Error("U4 extraction pointer missing");x=x[k]}return x}
function locatorIdentity(x:Omit<U4ExtractionLocator,"id">){return`locator.${H(`open-autonomy.u4-extraction-locator.v1\0${C(x)}`).slice(7)}`}

function verifyU4ExtractionSpecificationAgainstVerifiedInventory(spec:U4ExtractionSpecification,inventory:FrozenU4SourceInventory,trusted:U4TrustedVerificationInputs){
  bounded(spec);exact(spec,["schema","fixtureKind","denominatorScope","empiricalRegistration","closureClaim","genericExtractorCompleteness","campaignId","sourceRegistryDigest","calculusDigest","issuedAt","authorityId","documents","slots","locators","receipt"],"specification");if(spec.schema!==SPEC_SCHEMA||spec.fixtureKind!=="synthetic"||spec.denominatorScope!=="fixture-local"||spec.empiricalRegistration!==false||spec.closureClaim!==false||spec.genericExtractorCompleteness!=="deferred-external-validation"||spec.campaignId!==inventory.campaignId||spec.sourceRegistryDigest!==inventory.sourceRegistryDigest||spec.calculusDigest!==inventory.calculusDigest||!time(spec.issuedAt)||!Array.isArray(spec.documents)||!Array.isArray(spec.slots)||!spec.slots.length||!Array.isArray(spec.locators)||!spec.locators.length)throw Error("U4 extraction specification boundary invalid");
  const preregistrationDigest=computeU4ExtractionSpecificationDigest(spec);if(!(Object.values(U4_SYNTHETIC_EXTRACTION_SCENARIO_ANCHORS) as Sha[]).includes(preregistrationDigest))throw Error("U4 independent synthetic extraction preregistration invalid");
  const authority=inventory.authorities.find(a=>a.id===spec.authorityId),key=trusted.authorityKeys.find(k=>k.authorityId===spec.authorityId),keyBytes=Buffer.from(key?.keyBase64??"","base64");if(!authority||authority.role!=="semantic-inventory-authority"||!key||key.role!==authority.role||key.ownerId!==authority.ownerId||key.verificationKeyDigest!==authority.verificationKeyDigest||H(keyBytes)!==authority.verificationKeyDigest)throw Error("U4 extraction specification authority invalid");const expected=Buffer.from(MAC(keyBytes,"u4-extraction-specification",specBody(spec)),"hex"),got=Buffer.from(spec.receipt,"hex");if(got.length!==expected.length||!timingSafeEqual(got,expected))throw Error("U4 extraction specification receipt invalid");
  const ps=inventory.provenance,facts=new Map(inventory.facts.map(f=>[f.id,f])),docs=new Map<string,U4ExtractionDocument>(),resolved=new Map<string,(typeof ps)[number]>();for(const d of spec.documents){exact(d,["provenanceId","sourceId","sourceVersion","provenanceKind","traversal","allowedLeafPointers"],"document");const p=ps.find(p=>p.id===d.provenanceId);if(docs.has(d.provenanceId)||!p||p.sourceId!==d.sourceId||p.sourceVersion!==d.sourceVersion||p.kind!==d.provenanceKind||!["canonical-json-leaves-v1","opaque-terminal-only"].includes(d.traversal)||!sorted(d.allowedLeafPointers)||d.allowedLeafPointers.some(p=>!ptr(p)))throw Error("U4 extraction document invalid");if(Date.parse(spec.issuedAt)>=Date.parse(p.acquiredAt))throw Error("U4 extraction specification chronology invalid");let parsed:unknown,ok=true;try{parsed=JSON.parse(Buffer.from(p.bytesBase64,"base64").toString("utf8"))}catch{ok=false}if(d.traversal==="canonical-json-leaves-v1"?(!ok||C(d.allowedLeafPointers)!==C(leaves(parsed).sort())):(ok||d.allowedLeafPointers.length))throw Error("U4 extraction leaf exhaustiveness invalid");docs.set(d.provenanceId,d);resolved.set(d.provenanceId,p)}if(docs.size!==ps.length)throw Error("U4 extraction document totality invalid");
  const slotDeclarations=new Map<string,U4ExtractionSlotDeclaration>();for(const d of spec.slots){exact(d,["id","factId","denotation","comparisonKinds","metadataKinds","requiredComparisonKinds","criticalityPolicy"],"semantic slot");const k=`${d.factId}\0${d.id}`,all=[...d.comparisonKinds,...d.metadataKinds];if(slotDeclarations.has(k)||!facts.has(d.factId)||!sid(d.id)||typeof d.denotation!=="string"||!d.denotation||d.criticalityPolicy!=="inherit-fact"||!sorted(d.comparisonKinds)||!sorted(d.metadataKinds)||!sorted(d.requiredComparisonKinds)||(d.comparisonKinds.length!==0&&d.comparisonKinds.length<2)||C(d.requiredComparisonKinds)!==C(d.comparisonKinds)||new Set(all).size!==all.length||all.some(x=>!KINDS.includes(x)))throw Error("U4 extraction semantic slot declaration invalid");slotDeclarations.set(k,d)}
  const ids=new Set<string>(),slots=new Set<string>(),semanticSlots=new Map<string,Set<Kind>>(),edgeCounts=new Map<string,number>(),pointerCoverage=new Map<string,Set<string>>();for(const l of spec.locators){exact(l,["id","slotId","slotTaxonomy","factId","provenanceId","provenanceKind","sourceId","sourceVersion","nativePath","nativeSchemaId","mode","pointer","terminal"],"locator");const{id,...body}=l,p=resolved.get(l.provenanceId),f=facts.get(l.factId),decl=slotDeclarations.get(`${l.factId}\0${l.slotId}`),expectedTaxonomy=l.provenanceKind==="source-behavior"?"behavior-proposition":l.provenanceKind==="runtime-probe"?"probe-proposition":l.provenanceKind==="native-schema"?"native-schema-leaf":"official-spec-leaf";if(id!==locatorIdentity(body)||ids.has(id)||!sid(l.slotId)||l.slotTaxonomy!==expectedTaxonomy||!decl||![...decl.comparisonKinds,...decl.metadataKinds].includes(l.provenanceKind)||slots.has(`${l.factId}\0${l.provenanceKind}\0${l.slotId}`)||!p||!f||p.kind!==l.provenanceKind||p.sourceId!==l.sourceId||p.sourceVersion!==l.sourceVersion||p.sourceId!==f.sourceId||l.sourceId!==f.sourceId||l.nativePath!==f.nativePath||l.nativeSchemaId!==f.nativeSchemaId||!f.provenanceIds.includes(p.id))throw Error("U4 extraction locator identity join invalid");const d=docs.get(l.provenanceId)!;if(l.mode==="json-pointer"?(l.terminal!==null||!ptr(l.pointer)||d.traversal!=="canonical-json-leaves-v1"||!d.allowedLeafPointers.includes(l.pointer)):(l.pointer!==null||!(["unsupported","opaque"] as unknown[]).includes(l.terminal)||d.traversal!=="opaque-terminal-only"))throw Error("U4 extraction locator mode invalid");ids.add(id);slots.add(`${l.factId}\0${l.provenanceKind}\0${l.slotId}`);const semanticKey=`${l.factId}\0${l.slotId}`,kinds=semanticSlots.get(semanticKey)??new Set<Kind>();kinds.add(l.provenanceKind);semanticSlots.set(semanticKey,kinds);const edge=`${l.factId}\0${p.id}`;edgeCounts.set(edge,(edgeCounts.get(edge)??0)+1);if(l.pointer!==null){const set=pointerCoverage.get(l.provenanceId)??new Set<string>();set.add(l.pointer);pointerCoverage.set(l.provenanceId,set)}}
  if(semanticSlots.size!==slotDeclarations.size)throw Error("U4 extraction semantic slot declaration totality invalid");for(const [k,d] of slotDeclarations){const kinds=semanticSlots.get(k);if(!kinds||C([...kinds].sort())!==C([...d.comparisonKinds,...d.metadataKinds].sort()))throw Error("U4 extraction semantic slot evidence totality invalid")}
  const expectedEdges=inventory.facts.flatMap(f=>f.provenanceIds.map(p=>`${f.id}\0${p}`));if(expectedEdges.some(e=>!edgeCounts.has(e))||[...edgeCounts].some(([e])=>!expectedEdges.includes(e)))throw Error("U4 extraction fact provenance totality invalid");for(const [k,d] of docs)if(d.traversal==="canonical-json-leaves-v1"&&C([...(pointerCoverage.get(k)??new Set())].sort())!==C(d.allowedLeafPointers))throw Error("U4 extraction pointer totality invalid");return freeze(structuredClone(spec));
}

function deriveU4EvidenceCandidates(inventory:FrozenU4SourceInventory,specInput:U4ExtractionSpecification,trusted:U4TrustedVerificationInputs):U4EvidenceExtraction{const spec=verifyU4ExtractionSpecificationAgainstVerifiedInventory(specInput,inventory,trusted),facts=new Map(inventory.facts.map(f=>[f.id,f]));const candidates=spec.locators.map(l=>{const p=inventory.provenance.find(p=>p.id===l.provenanceId)!,f=facts.get(l.factId)!,decl=spec.slots.find(d=>d.factId===l.factId&&d.id===l.slotId)!,bytes=Buffer.from(p.bytesBase64,"base64");let propositionJson:string|null=null;if(l.mode==="json-pointer")propositionJson=C(at(JSON.parse(bytes.toString("utf8")),l.pointer!));return{...l,evidenceSha256:p.sha256,documentLocator:{byteStart:0 as const,byteEnd:bytes.length,jsonPointer:l.pointer},propositionJson,propositionDigest:propositionJson===null?null:H(`open-autonomy.u4-extracted-proposition.v1\0${propositionJson}`),semanticSlot:{denotation:decl.denotation,comparable:decl.comparisonKinds.includes(l.provenanceKind),criticalityPolicy:decl.criticalityPolicy},inventoryJoin:{taxonomy:f.taxonomy,nativePath:f.nativePath,denotationDigest:H(f.denotation),assertion:"candidate-only-no-empirical-truth-claim" as const}}}).sort((a,b)=>a.id.localeCompare(b.id));const specifiedLocatorIds=spec.locators.map(x=>x.id).sort(),extractedLocatorIds=candidates.map(x=>x.id).sort();if(C(specifiedLocatorIds)!==C(extractedLocatorIds))throw Error("U4 extraction candidate graph totality invalid");const body={schema:RESULT_SCHEMA,fixtureKind:"synthetic" as const,denominatorScope:"fixture-local" as const,empiricalRegistration:false as const,closureClaim:false as const,genericExtractorCompleteness:"deferred-external-validation" as const,inventoryDigest:inventory.digest,specificationDigest:computeU4ExtractionSpecificationDigest(spec),candidates,specifiedLocatorIds,extractedLocatorIds};return freeze({...body,digest:H(`${RESULT_SCHEMA}\0${C(body)}`)})}
export function verifyU4ExtractionSpecification(spec:U4ExtractionSpecification,inventory:FrozenU4SourceInventory,calculus:FrozenU3ObservationCalculus,registry:FrozenU4SyntheticSourceRegistry,trusted:U4TrustedVerificationInputs){bounded(spec,inventory,calculus,registry,trusted);return verifyU4ExtractionSpecificationAgainstVerifiedInventory(spec,verifyFrozenU4SourceInventory(inventory,calculus,registry,trusted),trusted)}
export function createU4EvidenceExtraction(inventory:FrozenU4SourceInventory,calculus:FrozenU3ObservationCalculus,registry:FrozenU4SyntheticSourceRegistry,trusted:U4TrustedVerificationInputs,spec:U4ExtractionSpecification){bounded(inventory,calculus,registry,trusted,spec);return deriveU4EvidenceCandidates(verifyFrozenU4SourceInventory(inventory,calculus,registry,trusted),spec,trusted)}
export function verifyU4EvidenceExtraction(extraction:U4EvidenceExtraction,inventory:FrozenU4SourceInventory,calculus:FrozenU3ObservationCalculus,registry:FrozenU4SyntheticSourceRegistry,trusted:U4TrustedVerificationInputs,spec:U4ExtractionSpecification){bounded(extraction);const expected=createU4EvidenceExtraction(inventory,calculus,registry,trusted,spec);if(C(extraction)!==C(expected))throw Error("U4 extraction replay mismatch");return expected}
export function createU4ExtractionLocator(body:Omit<U4ExtractionLocator,"id">):U4ExtractionLocator{return{id:locatorIdentity(body),...body}}
