import { describe, expect, test } from "bun:test";
import { createHmac } from "node:crypto";
import { BoundedImprovementLoop, MemoryImprovementStore, improvementDigest, type ActorAttestation, type ImprovementEffectPort, type ImprovementPolicy, type ImprovementTrust, type LoopRole } from "./organization-improvement-loop";

const members: Record<LoopRole, string[]> = { worker: ["worker"], proposer: ["planner"], evaluator: ["evaluator"], approver: ["alice", "bob"], deployer: ["deployer"], auditor: ["auditor"] };
const key = (actor: string, role: LoopRole) => `key:${actor}:${role}`;
const mac = (key: string, digest: string) => createHmac("sha256", key).update(digest).digest("hex");
const trust: ImprovementTrust = { verifyActor: (actor, role, digest, signature) => members[role].includes(actor) && mac(key(actor, role), digest) === signature, signState: (d) => mac("state-key", d), verifyState: (d, s) => mac("state-key", d) === s };
const attest = <T>(actor: string, role: LoopRole, payload: T): ActorAttestation<T> => { const digest = improvementDigest(payload); return { actor, payload, digest, signature: mac(key(actor, role), digest) }; };
const policy: ImprovementPolicy = { constitutionDigest: "constitution:v1", graderDigest: "grader:v1", authorityCeilingDigest: "authority:v1", evidencePolicyDigest: "evidence:v1", pauseGuardDigest: "pause:v1", rollbackGuardDigest: "rollback:v1", protectedPaths: ["constitution","grader","authorityCeiling","evidence","pause","rollback"], allowedScopes: ["worker.capacity"], authorityCeiling: { repo: 1 }, proposalWindowMs: 1000, maxProposalsPerWindow: 10, maxSpendPerProposal: 10, maxCumulativeSpend: 20, maxOperationsPerProposal: 2, maxCumulativeChanges: 4, maximumCanaryFraction: .1, maximumExperimentSamples: 100, approvalQuorum: 2, roleMembers: members };
class Effects implements ImprovementEffectPort { semantic = new Map<string,string>(); calls: string[] = []; perform(effect: { id: string }) { this.calls.push(effect.id); this.semantic.set(effect.id, this.semantic.get(effect.id) ?? `receipt:${effect.id}`); return { id: effect.id, durable: true as const, receipt: this.semantic.get(effect.id)! }; } }
const workerPayload = () => { const base = { historyDigest: "history:1", observations: 100 }; const workerDigest = improvementDigest(base); return { ...base, worker: "worker", workerDigest, workerSignature: mac(key("worker", "worker"), workerDigest) }; };
const deployAuth = (id: string, loop: BoundedImprovementLoop, kind = "deploy") => { const w = loop.current().workflows[id]!, context = improvementDigest({ proposal: w.artifacts.proposal!.digest, preregistration: w.artifacts.preregistration!.digest, approvals: w.approvals.map((a) => a.digest).sort(), policy: improvementDigest(policy) }), digest = improvementDigest({ id, kind, context }); return `deployer:${mac(key("deployer", "deployer"), digest)}`; };
function progressToEvaluation(id: string, store: MemoryImprovementStore, effects: Effects, options: { benchmarkPassed?: boolean; guardrail?: number } = {}) {
  let now = 100; const restart = () => new BoundedImprovementLoop("org", policy, trust, store, effects, () => now++); let loop = restart();
  loop.start(id, attest("auditor", "auditor", workerPayload())); loop = restart();
  loop.measure(id, attest("evaluator", "evaluator", { metric: "throughput", baseline: 10, unit: "tasks/day", horizon: "7d", evidenceDigest: loop.current().workflows[id]!.artifacts.evidence!.digest })); loop = restart();
  loop.updateTwin(id, attest("evaluator", "evaluator", { version: "1", replayDigest: "replay:1", calibrated: true, residuals: [] })); loop = restart();
  loop.propose(id, attest("planner", "proposer", { patchDigest: `patch:${id}`, paths: ["workers.capacity"], scope: "worker.capacity", operations: 1, spend: 2, authority: { repo: 1 }, expectedMetric: "throughput", claim: "causal" as const })); loop = restart();
  loop.recordChecks(id, attest("evaluator", "evaluator", { patchDigest: `patch:${id}`, compile: true, conform: true, formal: true, inheritedObligationsDigest: "obligations:1" })); loop = restart();
  loop.recordBenchmark(id, attest("evaluator", "evaluator", { patchDigest: `patch:${id}`, graderDigest: policy.graderDigest, passed: options.benchmarkPassed ?? true, resultDigest: `benchmark:${id}`, independent: true })); loop = restart();
  loop.preregister(id, attest("auditor", "auditor", { metric: "throughput", minimumImprovement: 1, guardrails: { defects: 0 }, sampleCount: 20, canaryFraction: .05, causalDesign: "randomized" as const, rollbackTrigger: "defects > 0" })); loop = restart();
  const w = loop.current().workflows[id]!; for (const actor of ["alice","bob"]) { loop.approve(id, attest(actor, "approver", { proposalId: id, proposalDigest: w.artifacts.proposal!.digest, preregistrationDigest: w.artifacts.preregistration!.digest, expiresAt: "2099-01-01T00:00:00Z", decision: "approve" as const })); loop = restart(); }
  loop.deploy(id, deployAuth(id, loop)); loop = restart();
  loop.recordCanary(id, attest("auditor", "auditor", { proposalId: id, samples: 20, metricImprovement: 2, confidenceInterval: [1.2,2.8] as [number,number], guardrailValues: { defects: options.guardrail ?? 0 }, evidenceDigest: `canary:${id}` })); return restart();
}

describe("R28 synthetic crash-recoverable dogfood", () => {
  test("synthetically accepts one, rejects one, and automatically rolls back one with restart at every phase", () => { const store = new MemoryImprovementStore(), effects = new Effects(); let loop = progressToEvaluation("accepted", store, effects); loop.evaluate("accepted", attest("evaluator", "evaluator", { proposalId: "accepted", metricImprovement: 2, confidenceInterval: [1.2,2.8] as [number,number], guardrailsPassed: true, causalClaim: true, analysisDigest: "analysis:accepted" })); loop = new BoundedImprovementLoop("org", policy, trust, store, effects, () => 500); expect(loop.current().workflows.accepted.phase).toBe("accepted"); expect(loop.reconstruct("accepted").decisionEvidenceDigest).toBeTruthy();
    loop = progressToEvaluation("rejected", store, effects); loop.evaluate("rejected", attest("evaluator", "evaluator", { proposalId: "rejected", metricImprovement: .2, confidenceInterval: [-.1,.5] as [number,number], guardrailsPassed: true, causalClaim: true, analysisDigest: "analysis:rejected" })); expect(loop.current().workflows.rejected.phase).toBe("rejected");
    loop = progressToEvaluation("rollback", store, effects, { guardrail: 1 }); expect(loop.current().workflows.rollback.phase).toBe("rolled-back"); expect(loop.current().workflows.rollback.decision?.reason).toContain("automatic"); expect(new Set(effects.semantic.keys()).size).toBe(5); expect(loop.current()).toEqual(expect.objectContaining({ cumulativeSpend: 6, cumulativeChanges: 3 })); // rejected and rolled-back work still consumes bounds
  });
  test("synthetic fixture is deterministic and durable effects retain approval context", () => { const run = () => { const store = new MemoryImprovementStore(), effects = new Effects(), loop = progressToEvaluation("p", store, effects); return { workflow: loop.current().workflows.p, effects: [...effects.semantic] }; }; expect(run()).toEqual(run()); });
});

describe("R28 authority, forgery and optimizer-boundary defenses", () => {
  test("rejects compromised worker evidence and forged human approval", () => { const store = new MemoryImprovementStore(), effects = new Effects(), loop = new BoundedImprovementLoop("org", policy, trust, store, effects, () => 1); const compromised = workerPayload(); compromised.workerSignature = "forged"; expect(() => loop.start("bad", attest("auditor", "auditor", compromised))).toThrow("compromised");
    const valid = workerPayload(); loop.start("p", attest("auditor", "auditor", valid)); const forged = attest("alice", "approver", { proposalId: "p", proposalDigest: "x", preregistrationDigest: "x", expiresAt: "2099-01-01T00:00:00Z", decision: "approve" as const }); forged.signature = "forged"; expect(() => loop.approve("p", forged)).toThrow("attestation invalid"); });
  test("optimizer cannot patch constitution, grader, authority ceiling, evidence, pause or rollback guard", () => { for (const path of policy.protectedPaths) { const store = new MemoryImprovementStore(), effects = new Effects(), loop = new BoundedImprovementLoop("org", policy, trust, store, effects, () => 1); loop.start("p", attest("auditor", "auditor", workerPayload())); loop.measure("p", attest("evaluator", "evaluator", { metric: "x", baseline: 0, unit: "x", horizon: "x", evidenceDigest: loop.current().workflows.p.artifacts.evidence!.digest })); loop.updateTwin("p", attest("evaluator", "evaluator", { version: "1", replayDigest: "r", calibrated: false, residuals: ["synthetic"] })); expect(() => loop.propose("p", attest("planner", "proposer", { patchDigest: "x", paths: [path], scope: "worker.capacity", operations: 1, spend: 0, authority: { repo: 1 }, expectedMetric: "x", claim: "prediction" as const }))).toThrow("immutable"); } });
  test("separates roles, enforces quorum and binds deployment to unexpired approvals", () => { expect(() => new BoundedImprovementLoop("org", { ...policy, roleMembers: { ...members, evaluator: ["planner"] } }, trust, new MemoryImprovementStore(), new Effects())).toThrow("roles not separated"); const store = new MemoryImprovementStore(), effects = new Effects(); let loop = progressToEvaluation("p", store, effects); expect(loop.current().workflows.p.approvals.map((a) => a.actor)).toEqual(["alice","bob"]); expect(loop.current().workflows.p.effects[0]!.approvalContextDigest).toBeTruthy(); });
});

describe("R28 bounded control and causal reconstruction", () => {
  test("global pause enters deterministic safe state and prevents new activity", () => { const store = new MemoryImprovementStore(), effects = new Effects(), loop = new BoundedImprovementLoop("org", policy, trust, store, effects, () => 1); loop.start("p", attest("auditor", "auditor", workerPayload())); const digest = improvementDigest({ organization: "org", action: "pause", policyDigest: improvementDigest(policy) }); loop.pause("auditor", mac(key("auditor", "auditor"), digest)); expect(loop.current().workflows.p.phase).toBe("safe-state"); expect(() => loop.start("q", attest("auditor", "auditor", workerPayload()))).toThrow("global pause"); });
  test("global pause rolls back an already deployed canary using its durable approval context", () => { const store = new MemoryImprovementStore(), effects = new Effects(), loop = progressToEvaluation("p", store, effects), digest = improvementDigest({ organization: "org", action: "pause", policyDigest: improvementDigest(policy) }); loop.pause("auditor", mac(key("auditor","auditor"),digest)); expect(loop.current().workflows.p.phase).toBe("rolled-back"); expect(loop.current().workflows.p.effects.map((e) => e.kind)).toEqual(["deploy","rollback"]); });
  test("promotion requires the preregistered lower confidence bound and preserves complete audit reconstruction", () => { const store = new MemoryImprovementStore(), effects = new Effects(), loop = progressToEvaluation("p", store, effects); expect(() => loop.evaluate("p", attest("evaluator", "evaluator", { proposalId: "p", metricImprovement: 2, confidenceInterval: [1.2,2.8] as [number,number], guardrailsPassed: true, causalClaim: false, analysisDigest: "posthoc" }))).toThrow("causal binding"); loop.evaluate("p", attest("evaluator", "evaluator", { proposalId: "p", metricImprovement: 2, confidenceInterval: [1.2,2.8] as [number,number], guardrailsPassed: true, causalClaim: true, analysisDigest: "preregistered" })); const reconstruction = loop.reconstruct("p"); expect(reconstruction.workflow.effects.map((e) => e.kind)).toEqual(["deploy","promote"]); expect(reconstruction.audit.at(-1)?.phase).toBe("accepted"); expect(reconstruction.preregistrationDigest).toBeTruthy(); });
});
