import{createHash,generateKeyPairSync,sign,verify}from"node:crypto";import{readFileSync}from"node:fs";import{canonicalSemanticJson}from"./organization-canonical";import{verifyR22CustodyArtifact,type R22CustodyArtifact}from"./organization-r22-external-evidence-live";
const hash=(v:unknown)=>`sha256:${createHash("sha256").update(canonicalSemanticJson(v)).digest("hex")}`,fileHash=(p:string)=>`sha256:${createHash("sha256").update(readFileSync(p)).digest("hex")}`;
export type R23LocalArtifact={schema:"autonomy.r23-local-evidence.v1";sourceBindings:Array<{checkpoint:"R20"|"R21"|"R22"|"R23";files:Array<{path:string;digest:string}>}>;testRun:{command:string[];exitCode:number;stdoutDigest:string;stderrDigest:string;assertions:number};dependencyDag:Array<{checkpoint:"R20"|"R21"|"R22"|"R23";dependsOn:string[];localProperty:"pass";closure:"pending-external";residuals:string[]}>;r22CustodyVerified:boolean;closureClaim:false;generatedAt:string;algorithm:"Ed25519";publicKeyPem:string;digest:string;signature:string};
const groups={R20:["packages/core/src/organization-command-plane.ts","packages/core/src/organization-command-transports.ts"],R21:["packages/core/src/organization-runtime-reliability.ts","packages/core/src/organization-runtime-reliability-live.ts"],R22:["packages/core/src/organization-benchmark-protocol.ts","packages/core/src/organization-r22-external-evidence-live.ts"],R23:["packages/core/src/organization-autonomy-accounting.ts"]}as const;
export function buildR23LocalArtifact(repo:string,testRun:R23LocalArtifact["testRun"],r22:R22CustodyArtifact,generatedAt=new Date().toISOString()):R23LocalArtifact{if(testRun.exitCode!==0||testRun.assertions<1||!verifyR22CustodyArtifact(r22))throw new Error("R23 local evidence prerequisites failed");const sourceBindings=Object.entries(groups).map(([checkpoint,paths])=>({checkpoint:checkpoint as keyof typeof groups,files:paths.map(path=>({path,digest:fileHash(`${repo}/${path}`)}))})),dependencyDag:R23LocalArtifact["dependencyDag"]=[{checkpoint:"R20",dependsOn:["R10","R17","R18","R19"],localProperty:"pass",closure:"pending-external",residuals:["real Slack workspace protocol run","real usability/accessibility participants"]},{checkpoint:"R21",dependsOn:["R15","R16","R17","R18","R19","R20"],localProperty:"pass",closure:"pending-external",residuals:["complete deployed eight-service load/soak and billed cost","owned regional failure/restore","external KMS","unfamiliar human operator"]},{checkpoint:"R22",dependsOn:["R3","R4","R8","R10","R11","R14","R16","R20","R21"],localProperty:"pass",closure:"pending-external",residuals:["two or more authenticated real raters","real-human simulator transfer calibration"]},{checkpoint:"R23",dependsOn:["R18","R20","R22"],localProperty:"pass",closure:"pending-external",residuals:["real-human timing calibration","live cross-provider billing/compute normalization"]}],body={schema:"autonomy.r23-local-evidence.v1" as const,sourceBindings,testRun,dependencyDag,r22CustodyVerified:true,closureClaim:false as const,generatedAt,algorithm:"Ed25519" as const},keys=generateKeyPairSync("ed25519"),publicKeyPem=keys.publicKey.export({type:"spki",format:"pem"}).toString(),unsigned={...body,publicKeyPem},digest=hash(unsigned);return{...unsigned,digest,signature:sign(null,Buffer.from(digest),keys.privateKey).toString("base64")}}
export function verifyR23LocalArtifact(a:R23LocalArtifact){const{digest,signature,...body}=a;return digest===hash(body)&&verify(null,Buffer.from(digest),a.publicKeyPem,Buffer.from(signature,"base64"))&&a.closureClaim===false&&a.r22CustodyVerified&&a.testRun.exitCode===0&&a.dependencyDag.every(x=>x.localProperty==="pass"&&x.closure==="pending-external"&&x.residuals.length>0)}

export type HumanTimingRegistration={schema:"autonomy.r23-human-timing-registration.v1";id:string;population:string;tasks:string[];simulatorMilliseconds:Record<string,number>;minimumDistinctHumans:2;createdAt:string;digest:string};export type HumanTimingObservation={registrationDigest:string;humanId:string;publicKeyPem:string;taskId:string;milliseconds:number;observedAt:string;signature:string};
const validTimestamp=(v:string)=>typeof v==="string"&&Number.isFinite(Date.parse(v));
const validMilliseconds=(v:number)=>Number.isSafeInteger(v)&&v>=0;
export function registerHumanTiming(x:Omit<HumanTimingRegistration,"schema"|"digest">):HumanTimingRegistration{if(x.minimumDistinctHumans<2||x.tasks.length<2||new Set(x.tasks).size!==x.tasks.length||Object.keys(x.simulatorMilliseconds).sort().join()!==[...x.tasks].sort().join()||!Object.values(x.simulatorMilliseconds).every(validMilliseconds)||!validTimestamp(x.createdAt))throw new Error("timing registration invalid");const b={schema:"autonomy.r23-human-timing-registration.v1" as const,...x};return{...b,digest:hash(b)}}
export function signHumanTimingObservation(body:Omit<HumanTimingObservation,"signature">,privateKeyPem:string):HumanTimingObservation{if(!body.humanId||!body.publicKeyPem||!body.taskId||!validMilliseconds(body.milliseconds)||!validTimestamp(body.observedAt))throw new Error("timing observation invalid");return{...body,signature:sign(null,Buffer.from(hash(body)),privateKeyPem).toString("base64")}}
export function completeHumanTiming(r:HumanTimingRegistration,rows:HumanTimingObservation[]){const humanToKey=new Map<string,string>(),keyToHuman=new Map<string,string>(),seen=new Set<string>();for(const x of rows){const{signature,...body}=x;let authentic=false;try{authentic=x.registrationDigest===r.digest&&r.tasks.includes(x.taskId)&&Boolean(x.humanId)&&Boolean(x.publicKeyPem)&&validMilliseconds(x.milliseconds)&&validTimestamp(x.observedAt)&&verify(null,Buffer.from(hash(body)),x.publicKeyPem,Buffer.from(signature,"base64"))}catch{authentic=false}if(!authentic)throw new Error("invalid or unauthenticated human timing observation");if(humanToKey.has(x.humanId)&&humanToKey.get(x.humanId)!==x.publicKeyPem||keyToHuman.has(x.publicKeyPem)&&keyToHuman.get(x.publicKeyPem)!==x.humanId)throw new Error("human timing identity/key mapping is not one-to-one");humanToKey.set(x.humanId,x.publicKeyPem);keyToHuman.set(x.publicKeyPem,x.humanId);const cell=`${x.humanId}\0${x.taskId}`;if(seen.has(cell))throw new Error("duplicate human/task timing observation");seen.add(cell)}const humans=[...humanToKey.keys()];if(humans.length<r.minimumDistinctHumans||humans.some(id=>r.tasks.some(task=>!seen.has(`${id}\0${task}`)))||rows.length!==humans.length*r.tasks.length)throw new Error("actual authenticated human timing observations incomplete");const observed=Object.fromEntries(r.tasks.map(task=>{const x=rows.filter(v=>v.taskId===task);return[task,x.reduce((n,v)=>n+v.milliseconds,0)/x.length]})),pairedMae=r.tasks.reduce((n,t)=>n+Math.abs(observed[t]!-r.simulatorMilliseconds[t]!),0)/r.tasks.length;return{status:"complete" as const,humanCount:humans.length,realHumanMilliseconds:observed,simulatorMilliseconds:r.simulatorMilliseconds,pairedTransferMaeMilliseconds:pairedMae}}
