import {createHash} from "node:crypto";import{readFileSync}from"node:fs";import{spawnSync}from"node:child_process";import{expect,test}from"bun:test";
import closure from "../../../docs/universality/campaign-v9/u3-implementation-closure.json";import*as calculus from"./organization-u3-observation-calculus";import*as evaluator from"./organization-u3-observation-evaluator";import*as certificate from"./organization-u3-preservation-certificate";import{EXPECTED_U3_IMPLEMENTATION_CLOSURE_DIGEST,U3_EXPECTED_EVIDENCE,U3_EXTERNAL_REQUIREMENTS,U3_IMPLEMENTATION_ANCHORS,digestU3ImplementationClosure,verifyU3ImplementationClosure}from"./organization-u3-implementation-closure";
const validators:Record<string,unknown>={freezeU3ObservationCalculus:calculus.freezeU3ObservationCalculus,verifyU3PredecessorGitCustody:calculus.verifyU3PredecessorGitCustody,computeU3ObservationCalculusDigest:calculus.computeU3ObservationCalculusDigest,freezeU3TraceEvaluationContract:evaluator.freezeU3TraceEvaluationContract,evaluateU3ObservationTrace:evaluator.evaluateU3ObservationTrace,verifyU3EvaluationReport:evaluator.verifyU3EvaluationReport,createU3PreservationCertificate:certificate.createU3PreservationCertificate,verifyU3PreservationCertificate:certificate.verifyU3PreservationCertificate,composeU3PreservationCertificates:certificate.composeU3PreservationCertificates,verifyU3ComposedPreservationCertificate:certificate.verifyU3ComposedPreservationCertificate};
const exactTestNames=(source:string)=>{const names:string[]=[];for(const match of source.matchAll(/\btest\s*\(\s*(["'])(.*?)\1\s*,/gs))names.push(match[2]);for(const match of source.matchAll(/^\s*\[\s*"([^"]+)"\s*,\s*\(x\)/gm))names.push(`rejects ${match[1]}`);if(new Set(names).size!==names.length)throw Error("duplicate registered test name");return new Set(names)};
const hash=(x:Uint8Array)=>`sha256:${createHash("sha256").update(x).digest("hex")}`;
test("machine-indexes exact concrete U3 evidence tuples to literal registered tests",()=>{expect(verifyU3ImplementationClosure(closure)).toBe(closure);expect(closure.obligations.map(x=>x.id)).toEqual(Object.keys(U3_EXPECTED_EVIDENCE));const cache=new Map<string,Set<string>>();for(const o of closure.obligations){expect(o.evidence).toEqual(U3_EXPECTED_EVIDENCE[o.id]);for(const evidence of o.evidence){expect(typeof validators[evidence.validator]).toBe("function");if(!cache.has(evidence.testFile))cache.set(evidence.testFile,exactTestNames(readFileSync(evidence.testFile,"utf8")));if(!cache.get(evidence.testFile)!.has(evidence.testName))throw Error(`unregistered exact test: ${evidence.testName}`)}}});
test("hard-binds original sources and intermediate evidence commit blobs plus current bytes",()=>{expect(closure.implementationAnchors).toEqual(U3_IMPLEMENTATION_ANCHORS);const objects=[
  [U3_IMPLEMENTATION_ANCHORS.calculus.sourceCommit,U3_IMPLEMENTATION_ANCHORS.calculus.sourcePath,U3_IMPLEMENTATION_ANCHORS.calculus.sourceCommittedSha256,U3_IMPLEMENTATION_ANCHORS.calculus.sourceCurrentSha256],[U3_IMPLEMENTATION_ANCHORS.calculus.evidenceCommit,U3_IMPLEMENTATION_ANCHORS.calculus.testPath,U3_IMPLEMENTATION_ANCHORS.calculus.testCommittedSha256,U3_IMPLEMENTATION_ANCHORS.calculus.testCurrentSha256],
  [U3_IMPLEMENTATION_ANCHORS.evaluator.sourceCommit,U3_IMPLEMENTATION_ANCHORS.evaluator.sourcePath,U3_IMPLEMENTATION_ANCHORS.evaluator.sourceCommittedSha256,U3_IMPLEMENTATION_ANCHORS.evaluator.sourceCurrentSha256],[U3_IMPLEMENTATION_ANCHORS.evaluator.evidenceCommit,U3_IMPLEMENTATION_ANCHORS.evaluator.testPath,U3_IMPLEMENTATION_ANCHORS.evaluator.testCommittedSha256,U3_IMPLEMENTATION_ANCHORS.evaluator.testCurrentSha256],
  [U3_IMPLEMENTATION_ANCHORS.certificate.sourceCommit,U3_IMPLEMENTATION_ANCHORS.certificate.sourcePath,U3_IMPLEMENTATION_ANCHORS.certificate.sourceCommittedSha256,U3_IMPLEMENTATION_ANCHORS.certificate.sourceCurrentSha256],[U3_IMPLEMENTATION_ANCHORS.certificate.evidenceCommit,U3_IMPLEMENTATION_ANCHORS.certificate.testPath,U3_IMPLEMENTATION_ANCHORS.certificate.testCommittedSha256,U3_IMPLEMENTATION_ANCHORS.certificate.testCurrentSha256],
]as const;for(const[commit,path,committed,current]of objects){const rev=spawnSync("git",["rev-parse","--verify",`${commit}^{commit}`],{encoding:"utf8"});expect(rev.status).toBe(0);expect(rev.stdout.trim()).toBe(commit);const shown=spawnSync("git",["show",`${commit}:${path}`]);expect(shown.status).toBe(0);expect(hash(shown.stdout)).toBe(committed);expect(hash(readFileSync(path))).toBe(current)}const prior=spawnSync("git",["show",`${U3_IMPLEMENTATION_ANCHORS.certificate.predecessorSourceCommit}:${U3_IMPLEMENTATION_ANCHORS.certificate.sourcePath}`]);expect(prior.status).toBe(0);expect(hash(prior.stdout)).toBe(U3_IMPLEMENTATION_ANCHORS.certificate.predecessorSourceSha256)});
test("rejects exact tuple schema content order accounting and boundary mutations",()=>{const attacks=[(x:any)=>x.surplus=true,(x:any)=>x.obligations.reverse(),(x:any)=>x.obligations[0].evidence[0].clause+=" altered",(x:any)=>x.obligations[0].evidence[0].testName="nonexistent exact test",(x:any)=>x.externalDeferred[0].requires.pop(),(x:any)=>x.externalDeferred[0].requirement+=" altered",(x:any)=>x.accounting.dischargedInternal=24,(x:any)=>x.downstreamBoundary.allowed.pop(),(x:any)=>x.downstreamBoundary.prerequisiteIds.pop(),(x:any)=>x.digest=`sha256:${"0".repeat(64)}`];for(const attack of attacks){const x=structuredClone(closure)as any;attack(x);expect(()=>verifyU3ImplementationClosure(x)).toThrow()}});
test("rejects consistently redigested substitutions against independent closure semantics",()=>{expect(closure.digest).toBe(EXPECTED_U3_IMPLEMENTATION_CLOSURE_DIGEST);const attacks=[(x:any)=>x.scope+=" altered",(x:any)=>x.obligations[0].claim+=" altered",(x:any)=>x.obligations[0].evidence[0].validator="evaluateU3ObservationTrace",(x:any)=>x.implementationAnchors.calculus.testCommittedSha256=`sha256:${"1".repeat(64)}`,(x:any)=>x.externalDeferred[9].requires[1]="generalization-allowed",(x:any)=>x.skepticalReview.finding+=" altered"];for(const attack of attacks){const x=structuredClone(closure)as any;attack(x);x.digest=digestU3ImplementationClosure(x);expect(x.digest).not.toBe(EXPECTED_U3_IMPLEMENTATION_CLOSURE_DIGEST);expect(()=>verifyU3ImplementationClosure(x)).toThrow()}});
test("compiles exact external requirements and blocks empirical U4 and UG1 claims",()=>{expect(closure.externalDeferred).toEqual(structuredClone(U3_EXTERNAL_REQUIREMENTS) as any);expect(closure.accounting).toEqual({openInternal:0,dischargedInternal:25,deferredExternal:10});expect(closure.downstreamBoundary.forbidden).toEqual(["U4 empirical inventories","U4 semantic checkpoint closure","publication or reuse of empirical U4 denominators","claiming UG1 passage"]);expect(closure.prohibitedClaims).toContain("U3 semantic closure is complete")});
