import{createHash}from"node:crypto";import{spawnSync}from"node:child_process";import{canonicalSemanticJson as C}from"./organization-canonical";import{verifyU5ImplementationClosure}from"./organization-u5-implementation-closure";
type Sha=`sha256:${string}`;const S="open-autonomy.u5-closure-attestation.v1",H=(x:string|Uint8Array)=>`sha256:${createHash("sha256").update(x).digest("hex")}`as Sha,COMMIT="9f901a8c14ffde8f88fac701c820c856e2c0f8cf",CLOSURE_DIGEST="sha256:10ae9cfc3ddf90559645f29c2d82463fa9a2fea46e398a74ae1a5a6e4c469839",FILES=[
 {kind:"source",path:"packages/core/src/organization-u5-implementation-closure.ts",sha256:"sha256:e0ca693cdb6af4b1548fd092fc8da71f6a22cdc2c6f6156f4417ffa306225526"},
 {kind:"test",path:"packages/core/src/organization-u5-implementation-closure.test.ts",sha256:"sha256:2d7d7b1ea1eea079cc8b83d986a47a0001fc0af0db87ade59fdf69e27e74570b"},
 {kind:"artifact",path:"docs/universality/campaign-v9/u5-implementation-closure.json",sha256:"sha256:ba77f4e6a493b38cd5bbcf2b8a5c9faeaf1e4c9cf18e6afc7ffd820c1d517c53"}]as const;
const keys=(x:any,k:string[],n:string)=>{if(!x||typeof x!=="object"||Array.isArray(x)||C(Object.keys(x).sort())!==C([...k].sort()))throw Error(`U5 attestation ${n} schema invalid`)},eq=(a:any,b:any,n:string)=>{if(C(a)!==C(b))throw Error(`U5 attestation ${n} invalid`)},cache=new Map<string,any>();function bound(v:any){let n=0,z=0;const active=new Set<any>(),q:any[]=[[v,0]];while(q.length){const[x,exit]=q.pop();if(exit){active.delete(x);continue}if(++n>20000)throw Error("U5 attestation resource bound");if(typeof x==="string"){z+=Buffer.byteLength(x);if(x.length>100000)throw Error("U5 attestation field bound")}else if(x&&typeof x==="object"){if(active.has(x))throw Error("U5 attestation cyclic input");active.add(x);q.push([x,1],...Object.values(x).map(y=>[y,0]))}}if(z>2e6)throw Error("U5 attestation resource bound")}
const freeze=<T>(v:T):T=>{const q:any[]=[v];while(q.length){const x=q.pop();if(x&&typeof x==="object"&&!Object.isFrozen(x)){q.push(...Object.values(x));Object.freeze(x)}}return v};
function committedClosure(root:string){const key=`${root}\0${COMMIT}\0${C(FILES)}`;if(cache.has(key))return cache.get(key);const rev=spawnSync("git",["rev-parse","--verify",`${COMMIT}^{commit}`],{cwd:root,encoding:"utf8"});if(rev.status||typeof rev.stdout!=="string"||rev.stdout.trim()!==COMMIT)throw Error("U5 attestation commit custody invalid");let artifact:Buffer|undefined;for(const f of FILES){const g=spawnSync("git",["show",`${COMMIT}:${f.path}`],{cwd:root});if(g.status||!g.stdout||H(g.stdout)!==f.sha256)throw Error("U5 attestation byte custody invalid");if(f.kind==="artifact")artifact=g.stdout}let parsed:any;try{parsed=JSON.parse(artifact!.toString("utf8"))}catch{throw Error("U5 attestation closure artifact invalid")}const closure=verifyU5ImplementationClosure(parsed,{root});if(closure.digest!==CLOSURE_DIGEST||closure.accounting.dischargedInternal!==15||closure.accounting.pendingAttestationInternal!==1||closure.accounting.openInternal!==0||closure.externalDeferred.length!==10||closure.externalDeferred.some((e:any)=>e.status!=="deferred"||e.dischargedBy.length)||closure.fixtureKind!=="synthetic"||closure.closureClaim||closure.empiricalRegistration||closure.assurancePromotionAllowed)throw Error("U5 attestation closure boundary invalid");cache.set(key,closure);return closure}
export function digestU5ClosureAttestation(v:any){const{digest:_,...b}=v;void _;return H(`${S}\0${C(b)}`)}
export const U5_ATTESTATION_RESOLVED_REJECTION_CLASSES=Object.freeze(["non-exact policy authority and denominator anchors","unpreserved canonical observations","unbounded or unreachable derived evidence DAG","opaque fallback for lowered dispositions","unclassified extension strata","canonical credit granted to opaque or abstracted dispositions","non-total fact ownership and evidence assignment","credit lattice count or weight inflation","coverage report not derived from verified ledger","cross-role owner or chronology aliasing","stale commit or blob anchors","premature 16-of-16 discharge before post-commit attestation"] as const);
export function createU5ClosureAttestation({root=process.cwd()}={}){const closure=committedClosure(root),body:any={schema:S,checkpoint:"U5",status:"locally-attested-external-deferred",fixtureKind:"synthetic",empiricalRegistration:false,closureClaim:false,assurancePromotionAllowed:false,closureAnchor:{commit:COMMIT,closureDigest:CLOSURE_DIGEST,files:FILES},closureAccountingBefore:{dischargedInternal:15,pendingAttestationInternal:1,openInternal:0},localAccountingAfter:{dischargedInternal:16,pendingAttestationInternal:0,openInternal:0,totalInternal:16,dischargedObligationId:"U5-I16"},externalDeferred:closure.externalDeferred,skepticalReview:{status:"accepted",reviewedCommit:COMMIT,scope:["semantic I1-I16","E1-E10","evidence DAG","custody","attacks"],priorRejectionClassesResolved:U5_ATTESTATION_RESOLVED_REJECTION_CLASSES,evidenceKind:"synthetic-reviewer-process",externalHumanE5:false},selfCustody:{status:"deferred-to-UG1",reason:"attestation structural code and test are custodied at UG1; no recursive self-attestation"}};return freeze({...body,digest:digestU5ClosureAttestation(body)})}
export function verifyU5ClosureAttestation(v:any,{root=process.cwd()}={}){bound(v);keys(v,["schema","checkpoint","status","fixtureKind","empiricalRegistration","closureClaim","assurancePromotionAllowed","closureAnchor","closureAccountingBefore","localAccountingAfter","externalDeferred","skepticalReview","selfCustody","digest"],"root");const expected=createU5ClosureAttestation({root});eq(v,expected,"exact attestation");if(v.digest!==digestU5ClosureAttestation(v))throw Error("U5 attestation digest invalid");keys(v.closureAnchor,["commit","closureDigest","files"],"closure anchor");keys(v.skepticalReview,["status","reviewedCommit","scope","priorRejectionClassesResolved","evidenceKind","externalHumanE5"],"review");keys(v.localAccountingAfter,["dischargedInternal","pendingAttestationInternal","openInternal","totalInternal","dischargedObligationId"],"accounting");return freeze(structuredClone(v))}
