import { createHash } from "node:crypto";
import { canonicalSemanticJson } from "./organization-canonical";

export type LoopRole = "worker" | "proposer" | "evaluator" | "approver" | "deployer" | "auditor";
export type ImprovementPhase = "observing" | "measured" | "twin-updated" | "proposed" | "checked" | "benchmarked" | "preregistered" | "approved" | "deployed" | "canary" | "evaluating" | "accepted" | "rejected" | "rolled-back" | "safe-state";
export type ActorAttestation<T> = { actor: string; payload: T; digest: string; signature: string };
export interface ImprovementTrust { verifyActor(actor: string, role: LoopRole, digest: string, signature: string): boolean; signState(digest: string): string; verifyState(digest: string, signature: string): boolean }
export interface ImprovementStore { load(organization: string): ImprovementLoopState | undefined; compareAndSwap(organization: string, expectedGeneration: number | undefined, next: ImprovementLoopState): boolean }
export class MemoryImprovementStore implements ImprovementStore { private values = new Map<string, ImprovementLoopState>(); load(id: string) { const value = this.values.get(id); return value && structuredClone(value); } compareAndSwap(id: string, expected: number | undefined, next: ImprovementLoopState) { if (this.values.get(id)?.generation !== expected) return false; this.values.set(id, structuredClone(next)); return true; } }

export type ImprovementPolicy = {
  constitutionDigest: string; graderDigest: string; authorityCeilingDigest: string; evidencePolicyDigest: string; pauseGuardDigest: string; rollbackGuardDigest: string;
  protectedPaths: string[]; allowedScopes: string[]; authorityCeiling: Record<string, number>;
  proposalWindowMs: number; maxProposalsPerWindow: number; maxSpendPerProposal: number; maxCumulativeSpend: number; maxOperationsPerProposal: number; maxCumulativeChanges: number;
  maximumCanaryFraction: number; maximumExperimentSamples: number; approvalQuorum: number; roleMembers: Record<LoopRole, string[]>;
};
export type EvidencePayload = { historyDigest: string; worker: string; workerDigest: string; workerSignature: string; observations: number };
export type MeasurementPayload = { metric: string; baseline: number; unit: string; horizon: string; evidenceDigest: string };
export type TwinPayload = { version: string; replayDigest: string; calibrated: boolean; residuals: string[] };
export type ProposalPayload = { patchDigest: string; paths: string[]; scope: string; operations: number; spend: number; authority: Record<string, number>; expectedMetric: string; claim: "prediction" | "causal" };
export type ChecksPayload = { patchDigest: string; compile: boolean; conform: boolean; formal: boolean; inheritedObligationsDigest: string };
export type BenchmarkPayload = { patchDigest: string; graderDigest: string; passed: boolean; resultDigest: string; independent: boolean };
export type PreregistrationPayload = { metric: string; minimumImprovement: number; guardrails: Record<string, number>; sampleCount: number; canaryFraction: number; causalDesign: "randomized" | "switchback" | "prediction-only"; rollbackTrigger: string };
export type ApprovalPayload = { proposalId: string; proposalDigest: string; preregistrationDigest: string; expiresAt: string; decision: "approve" };
export type CanaryPayload = { proposalId: string; samples: number; metricImprovement: number; confidenceInterval: [number, number]; guardrailValues: Record<string, number>; evidenceDigest: string };
export type EvaluationPayload = { proposalId: string; metricImprovement: number; confidenceInterval: [number, number]; guardrailsPassed: boolean; causalClaim: boolean; analysisDigest: string };
export type DurableEffect = { id: string; proposalId: string; kind: "deploy" | "promote" | "rollback"; approvalContextDigest: string; patchDigest: string; status: "prepared" | "acknowledged"; receipt?: string };
export interface ImprovementEffectPort { perform(effect: Omit<DurableEffect, "status" | "receipt">): { id: string; durable: true; receipt: string } }

type ArtifactMap = { evidence?: ActorAttestation<EvidencePayload>; measurement?: ActorAttestation<MeasurementPayload>; twin?: ActorAttestation<TwinPayload>; proposal?: ActorAttestation<ProposalPayload>; checks?: ActorAttestation<ChecksPayload>; benchmark?: ActorAttestation<BenchmarkPayload>; preregistration?: ActorAttestation<PreregistrationPayload>; canary?: ActorAttestation<CanaryPayload>; evaluation?: ActorAttestation<EvaluationPayload> };
export type ImprovementWorkflow = { id: string; phase: ImprovementPhase; createdAtMs: number; artifacts: ArtifactMap; approvals: ActorAttestation<ApprovalPayload>[]; effects: DurableEffect[]; decision?: { outcome: "accepted" | "rejected" | "rolled-back"; reason: string; evidenceDigest: string } };
export type ImprovementLoopState = { schema: "autonomy.improvement-loop.v1"; organization: string; generation: number; policyDigest: string; paused: boolean; cumulativeSpend: number; cumulativeChanges: number; proposalTimes: number[]; workflows: Record<string, ImprovementWorkflow>; audit: Array<{ id: string; proposalId: string; phase: ImprovementPhase; actor: string; artifactDigest: string; atMs: number }>; digest: string; signature: string };

export class BoundedImprovementLoop {
  constructor(readonly organization: string, readonly policy: ImprovementPolicy, private trust: ImprovementTrust, private store: ImprovementStore, private effects: ImprovementEffectPort, private clock: () => number = Date.now) { validatePolicy(policy); this.initialize(); }
  start(id: string, evidence: ActorAttestation<EvidencePayload>) { this.assertActive(); this.verify(evidence, "auditor"); this.verifyWorkerEvidence(evidence.payload); const now = this.clock(); this.mutate((s) => { if (s.workflows[id]) return this.assertIdempotent(s.workflows[id]!.artifacts.evidence, evidence); const recent = s.proposalTimes.filter((t) => t > now - this.policy.proposalWindowMs); if (recent.length >= this.policy.maxProposalsPerWindow) throw new Error("proposal rate bound exceeded"); s.proposalTimes = [...recent, now]; s.workflows[id] = { id, phase: "observing", createdAtMs: now, artifacts: { evidence: structuredClone(evidence) }, approvals: [], effects: [] }; this.audit(s, id, "observing", evidence.actor, evidence.digest); }); }
  measure(id: string, artifact: ActorAttestation<MeasurementPayload>) { this.advance(id, "observing", "measured", "measurement", artifact, "evaluator", (w) => { if (artifact.payload.evidenceDigest !== w.artifacts.evidence!.digest) throw new Error("measurement evidence binding failed"); }); }
  updateTwin(id: string, artifact: ActorAttestation<TwinPayload>) { this.advance(id, "measured", "twin-updated", "twin", artifact, "evaluator", () => { if (!artifact.payload.replayDigest) throw new Error("twin replay evidence required"); }); }
  propose(id: string, artifact: ActorAttestation<ProposalPayload>) { this.assertActive(); this.verify(artifact, "proposer"); this.mutate((s) => { const w = this.workflow(s, id); this.expect(w, "twin-updated"); const p = artifact.payload; if (p.spend > this.policy.maxSpendPerProposal || s.cumulativeSpend + p.spend > this.policy.maxCumulativeSpend || p.operations > this.policy.maxOperationsPerProposal || s.cumulativeChanges + p.operations > this.policy.maxCumulativeChanges || !this.policy.allowedScopes.includes(p.scope) || p.paths.some((path) => this.policy.protectedPaths.some((protectedPath) => path === protectedPath || path.startsWith(`${protectedPath}.`))) || Object.entries(p.authority).some(([scope, value]) => value > (this.policy.authorityCeiling[scope] ?? 0))) throw new Error("proposal violates immutable scope, authority, spend, or change bounds"); w.artifacts.proposal = structuredClone(artifact); s.cumulativeSpend += p.spend; s.cumulativeChanges += p.operations; w.phase = "proposed"; this.audit(s, id, w.phase, artifact.actor, artifact.digest); }); }
  recordChecks(id: string, artifact: ActorAttestation<ChecksPayload>) { this.advance(id, "proposed", "checked", "checks", artifact, "evaluator", (w) => { if (artifact.payload.patchDigest !== w.artifacts.proposal!.payload.patchDigest || !artifact.payload.compile || !artifact.payload.conform || !artifact.payload.formal || !artifact.payload.inheritedObligationsDigest) throw new Error("static/formal checks failed or lost obligation continuity"); }); }
  recordBenchmark(id: string, artifact: ActorAttestation<BenchmarkPayload>) { this.advance(id, "checked", "benchmarked", "benchmark", artifact, "evaluator", (w) => { if (artifact.actor === w.artifacts.proposal!.actor || artifact.payload.patchDigest !== w.artifacts.proposal!.payload.patchDigest || artifact.payload.graderDigest !== this.policy.graderDigest || !artifact.payload.independent) throw new Error("benchmark independence or immutable grader failed"); }); }
  preregister(id: string, artifact: ActorAttestation<PreregistrationPayload>) { this.advance(id, "benchmarked", "preregistered", "preregistration", artifact, "auditor", (w) => { const p = artifact.payload; if (!w.artifacts.benchmark!.payload.passed || p.metric !== w.artifacts.proposal!.payload.expectedMetric || p.sampleCount < 1 || p.sampleCount > this.policy.maximumExperimentSamples || p.canaryFraction <= 0 || p.canaryFraction > this.policy.maximumCanaryFraction || !p.rollbackTrigger) throw new Error("preregistration or benchmark gate failed"); if (w.artifacts.proposal!.payload.claim === "causal" && p.causalDesign === "prediction-only") throw new Error("causal claim lacks causal design"); }); }
  approve(id: string, approval: ActorAttestation<ApprovalPayload>) { this.assertActive(); this.verify(approval, "approver"); this.mutate((s) => { const w = this.workflow(s, id); if (!['preregistered','approved'].includes(w.phase)) throw new Error("approval phase invalid"); const p = approval.payload; if (p.proposalId !== id || p.proposalDigest !== w.artifacts.proposal!.digest || p.preregistrationDigest !== w.artifacts.preregistration!.digest || Date.parse(p.expiresAt) < this.clock() || w.artifacts.proposal!.actor === approval.actor || w.approvals.some((a) => a.actor === approval.actor)) throw new Error("approval binding, expiry, separation, or uniqueness failed"); w.approvals.push(structuredClone(approval)); if (w.approvals.length >= this.policy.approvalQuorum) w.phase = "approved"; this.audit(s, id, w.phase, approval.actor, approval.digest); }); }
  deploy(id: string, actor: string) { this.assertActive(); const approvalContext = this.prepareEffect(id, actor, "approved", "deploy", "deployed"); this.deliverEffect(id, "deploy", approvalContext); }
  recordCanary(id: string, artifact: ActorAttestation<CanaryPayload>) { this.assertActive(); this.verify(artifact, "auditor"); let rollback = false, context = ""; this.mutate((s) => { const w = this.workflow(s, id); this.expect(w, "deployed"); const prereg = w.artifacts.preregistration!.payload; if (artifact.payload.proposalId !== id || artifact.payload.samples > prereg.sampleCount || artifact.payload.samples < 1) throw new Error("canary sample binding failed"); w.artifacts.canary = structuredClone(artifact); w.phase = "canary"; const breached = Object.entries(prereg.guardrails).some(([name, maximum]) => (artifact.payload.guardrailValues[name] ?? Number.POSITIVE_INFINITY) > maximum); this.audit(s, id, w.phase, artifact.actor, artifact.digest); if (breached) { context = this.deployedApprovalContext(w); this.addEffect(w, "rollback", context); rollback = true; } else w.phase = "evaluating"; }); if (rollback) { this.deliverEffect(id, "rollback", context); this.mutate((s) => { const w = this.workflow(s, id); w.phase = "rolled-back"; w.decision = { outcome: "rolled-back", reason: "automatic preregistered guardrail rollback", evidenceDigest: artifact.digest }; this.audit(s, id, w.phase, "controller", artifact.digest); }); } }
  evaluate(id: string, artifact: ActorAttestation<EvaluationPayload>) { this.assertActive(); this.verify(artifact, "evaluator"); let promote = false, context = ""; this.mutate((s) => { const w = this.workflow(s, id); this.expect(w, "evaluating"); const prereg = w.artifacts.preregistration!.payload, proposal = w.artifacts.proposal!.payload; if (artifact.payload.proposalId !== id || artifact.payload.causalClaim !== (proposal.claim === "causal") || artifact.payload.causalClaim && prereg.causalDesign === "prediction-only") throw new Error("evaluation causal binding failed"); w.artifacts.evaluation = structuredClone(artifact); const improved = artifact.payload.metricImprovement >= prereg.minimumImprovement && artifact.payload.confidenceInterval[0] >= prereg.minimumImprovement && artifact.payload.guardrailsPassed; if (improved) { context = this.deployedApprovalContext(w); this.addEffect(w, "promote", context); promote = true; } else { w.phase = "rejected"; w.decision = { outcome: "rejected", reason: "preregistered improvement or safety criterion not met", evidenceDigest: artifact.digest }; this.audit(s, id, w.phase, artifact.actor, artifact.digest); } }); if (promote) { this.deliverEffect(id, "promote", context); this.mutate((s) => { const w = this.workflow(s, id); w.phase = "accepted"; w.decision = { outcome: "accepted", reason: "preregistered improvement met without safety regression", evidenceDigest: artifact.digest }; this.audit(s, id, w.phase, artifact.actor, artifact.digest); }); } }
  reject(id: string, artifact: ActorAttestation<{ reason: string; evidenceDigest: string }>) { this.assertActive(); this.verify(artifact, "evaluator"); this.mutate((s) => { const w = this.workflow(s, id); if (!['benchmarked','preregistered'].includes(w.phase)) throw new Error("rejection phase invalid"); w.phase = "rejected"; w.decision = { outcome: "rejected", reason: artifact.payload.reason, evidenceDigest: artifact.payload.evidenceDigest }; this.audit(s, id, w.phase, artifact.actor, artifact.digest); }); }
  pause(actor: string, signature: string) { const d = improvementDigest({ organization: this.organization, action: "pause", policyDigest: improvementDigest(this.policy) }); if (!this.trust.verifyActor(actor, "auditor", d, signature)) throw new Error("pause authorization failed"); const rollback: Array<{id:string;context:string}> = []; this.mutate((s) => { s.paused = true; for (const w of Object.values(s.workflows)) if (!terminal(w.phase)) { if (["deployed","canary","evaluating"].includes(w.phase)) { const context = this.deployedApprovalContext(w); this.addEffect(w,"rollback",context); rollback.push({id:w.id,context}); } w.phase = "safe-state"; } }); for (const item of rollback) { this.deliverEffect(item.id,"rollback",item.context); this.mutate((s) => { const w = this.workflow(s,item.id); w.phase="rolled-back"; w.decision={outcome:"rolled-back",reason:"global pause rollback",evidenceDigest:d}; this.audit(s,item.id,w.phase,actor,d); }); } }
  current() { const s = this.store.load(this.organization); if (!s) throw new Error("improvement state absent"); const expected = improvementDigest(stateBody(s)); if (s.schema !== "autonomy.improvement-loop.v1" || s.policyDigest !== improvementDigest(this.policy) || s.digest !== expected || !this.trust.verifyState(expected, s.signature)) throw new Error("improvement state integrity or immutable policy failure"); return structuredClone(s); }
  reconstruct(id: string) { const s = this.current(), w = this.workflow(s, id), audit = s.audit.filter((a) => a.proposalId === id); if (!w.decision || !audit.length || audit[audit.length - 1]!.phase !== w.phase) throw new Error("causal/audit reconstruction incomplete"); return { workflow: structuredClone(w), audit, policyDigest: s.policyDigest, causalClaim: w.artifacts.proposal!.payload.claim, preregistrationDigest: w.artifacts.preregistration?.digest, decisionEvidenceDigest: w.decision.evidenceDigest }; }
  private advance<K extends keyof ArtifactMap>(id: string, from: ImprovementPhase, to: ImprovementPhase, key: K, artifact: NonNullable<ArtifactMap[K]>, role: LoopRole, validate: (w: ImprovementWorkflow) => void) { this.assertActive(); this.verify(artifact, role); this.mutate((s) => { const w = this.workflow(s, id); if (w.phase === to) { if (improvementDigest(w.artifacts[key]) !== improvementDigest(artifact)) throw new Error("phase idempotency equivocation"); return; } this.expect(w, from); validate(w); (w.artifacts[key] as NonNullable<ArtifactMap[K]>) = structuredClone(artifact); w.phase = to; this.audit(s, id, to, artifact.actor, artifact.digest); }); }
  private prepareEffect(id: string, actor: string, from: ImprovementPhase, kind: DurableEffect["kind"], to: ImprovementPhase) { const state = this.current(), w0 = this.workflow(state, id), context = this.approvalContext(w0), authDigest = improvementDigest({ id, kind, context }); const signature = actor.includes(":") ? actor.split(":")[1]! : ""; const identity = actor.includes(":") ? actor.split(":")[0]! : actor; if (!this.trust.verifyActor(identity, "deployer", authDigest, signature)) throw new Error("deployer authorization failed"); this.mutate((s) => { const w = this.workflow(s, id); if (w.phase !== from && w.phase !== to) throw new Error("deployment phase invalid"); this.addEffect(w, kind, context); w.phase = to; this.audit(s, id, to, identity, authDigest); }); return context; }
  private deliverEffect(id: string, kind: DurableEffect["kind"], context: string) { const state = this.current(), w = this.workflow(state, id), effect = w.effects.find((e) => e.kind === kind)!; if (effect.status === "acknowledged") return; const ack = this.effects.perform({ id: effect.id, proposalId: id, kind, approvalContextDigest: context, patchDigest: effect.patchDigest }); if (ack.id !== effect.id || ack.durable !== true || !ack.receipt) throw new Error("invalid durable effect acknowledgement"); this.mutate((s) => { const live = this.workflow(s, id).effects.find((e) => e.id === effect.id); if (!live || live.approvalContextDigest !== context) throw new Error("effect approval context changed"); live.status = "acknowledged"; live.receipt = ack.receipt; }); }
  private addEffect(w: ImprovementWorkflow, kind: DurableEffect["kind"], context: string) { const patchDigest = w.artifacts.proposal!.payload.patchDigest, id = improvementDigest({ proposalId: w.id, kind, context, patchDigest }); const prior = w.effects.find((e) => e.kind === kind); if (prior && prior.id !== id) throw new Error("effect context equivocation"); if (!prior) w.effects.push({ id, proposalId: w.id, kind, approvalContextDigest: context, patchDigest, status: "prepared" }); }
  private approvalContext(w: ImprovementWorkflow) { if (w.approvals.length < this.policy.approvalQuorum || w.approvals.some((a) => Date.parse(a.payload.expiresAt) < this.clock())) throw new Error("approval quorum absent or expired"); return improvementDigest({ proposal: w.artifacts.proposal!.digest, preregistration: w.artifacts.preregistration!.digest, approvals: w.approvals.map((a) => a.digest).sort(), policy: improvementDigest(this.policy) }); }
  private deployedApprovalContext(w: ImprovementWorkflow) { const deployed = w.effects.find((e) => e.kind === "deploy" && e.status === "acknowledged"); if (!deployed) throw new Error("durable deployment approval context absent"); return deployed.approvalContextDigest; }
  private verify(artifact: ActorAttestation<unknown>, role: LoopRole) { if (artifact.digest !== improvementDigest(artifact.payload) || !this.policy.roleMembers[role].includes(artifact.actor) || !this.trust.verifyActor(artifact.actor, role, artifact.digest, artifact.signature)) throw new Error(`${role} attestation invalid`); }
  private verifyWorkerEvidence(p: EvidencePayload) { if (p.workerDigest !== improvementDigest({ historyDigest: p.historyDigest, observations: p.observations }) || !this.policy.roleMembers.worker.includes(p.worker) || !this.trust.verifyActor(p.worker, "worker", p.workerDigest, p.workerSignature)) throw new Error("worker evidence compromised or forged"); }
  private assertActive() { if (this.current().paused) throw new Error("global pause active"); }
  private workflow(s: ImprovementLoopState, id: string) { const w = s.workflows[id]; if (!w) throw new Error("proposal workflow absent"); return w; }
  private expect(w: ImprovementWorkflow, phase: ImprovementPhase) { if (w.phase !== phase) throw new Error(`expected phase ${phase}, got ${w.phase}`); }
  private assertIdempotent<T>(prior: T | undefined, next: T) { if (improvementDigest(prior) !== improvementDigest(next)) throw new Error("phase idempotency equivocation"); }
  private audit(s: ImprovementLoopState, proposalId: string, phase: ImprovementPhase, actor: string, artifactDigest: string) { s.audit.push({ id: improvementDigest({ proposalId, phase, actor, artifactDigest, generation: s.generation }), proposalId, phase, actor, artifactDigest, atMs: this.clock() }); }
  private mutate(fn: (state: ImprovementLoopState) => void) { for (let i = 0; i < 16; i++) { const old = this.current(), next = structuredClone(old); fn(next); next.generation++; const d = improvementDigest(stateBody(next)); next.digest = d; next.signature = this.trust.signState(d); if (this.store.compareAndSwap(this.organization, old.generation, next)) return; } throw new Error("improvement state CAS contention"); }
  private initialize() { if (this.store.load(this.organization)) { this.current(); return; } const body = { schema: "autonomy.improvement-loop.v1" as const, organization: this.organization, generation: 1, policyDigest: improvementDigest(this.policy), paused: false, cumulativeSpend: 0, cumulativeChanges: 0, proposalTimes: [], workflows: {}, audit: [] }, d = improvementDigest(body), state = { ...body, digest: d, signature: this.trust.signState(d) }; if (!this.store.compareAndSwap(this.organization, undefined, state)) this.current(); }
}

function validatePolicy(p: ImprovementPolicy) { const protectedRequired = ["constitution", "grader", "authorityCeiling", "evidence", "pause", "rollback"]; const roleActors = Object.entries(p.roleMembers).flatMap(([role, actors]) => actors.map((actor) => `${role}:${actor}`)); const actorRoles = new Map<string, string[]>(); for (const item of roleActors) { const [role, actor] = item.split(":"); actorRoles.set(actor!, [...(actorRoles.get(actor!) ?? []), role!]); } if ([p.constitutionDigest,p.graderDigest,p.authorityCeilingDigest,p.evidencePolicyDigest,p.pauseGuardDigest,p.rollbackGuardDigest].some((x) => !x) || protectedRequired.some((x) => !p.protectedPaths.includes(x)) || Object.values(p.roleMembers).some((a) => !a.length) || [...actorRoles.values()].some((roles) => roles.some((r) => ["proposer","evaluator","approver","deployer","auditor"].includes(r)) && roles.filter((r) => ["proposer","evaluator","approver","deployer","auditor"].includes(r)).length > 1) || p.approvalQuorum < 1 || p.roleMembers.approver.length < p.approvalQuorum || p.maxProposalsPerWindow < 1 || p.proposalWindowMs < 1 || p.maxSpendPerProposal < 0 || p.maxCumulativeSpend < 0 || p.maxOperationsPerProposal < 1 || p.maxCumulativeChanges < 1 || p.maximumCanaryFraction <= 0 || p.maximumCanaryFraction > 1 || p.maximumExperimentSamples < 1) throw new Error("improvement policy invalid or roles not separated"); }
function terminal(p: ImprovementPhase) { return ["accepted","rejected","rolled-back","safe-state"].includes(p); }
function stateBody(s: ImprovementLoopState) { const { digest: _, signature: __, ...body } = s; return body; }
export function improvementDigest(value: unknown) { return createHash("sha256").update(canonicalSemanticJson(value)).digest("hex"); }
