import { createHash, createHmac, timingSafeEqual } from "node:crypto";
import { canonicalSemanticJson as C } from "./organization-canonical";
import type { FrozenU3ObservationCalculus } from "./organization-u3-observation-calculus";
import { computeU4PropositionDigest, computeU4SourceInventoryDigest, type FrozenU4SourceInventory, type U4TrustedVerificationInputs } from "./organization-u4-source-inventory";
import { verifyU4EvidenceExtraction, type U4EvidenceExtraction, type U4ExtractionSpecification } from "./organization-u4-evidence-extractor";
import type { FrozenU4SyntheticSourceRegistry } from "./organization-u4-source-inventory";

type Sha=`sha256:${string}`;
type Kind=FrozenU4SourceInventory["provenance"][number]["kind"];
const KINDS:Kind[]=["native-schema","official-spec","runtime-probe","source-behavior"];
const SCHEMA="open-autonomy.u4-automatic-triangulation.v1" as const;
const PARTITION_SCHEMA="open-autonomy.u4-four-stream-partition-registry.v1" as const;
export const EXPECTED_U4_FOUR_STREAM_PARTITION_REGISTRY_DIGEST="sha256:3647fe3cd5c7e23d205bd818f724379154319730e2ee7cf2bafbe5267946ace6" as Sha;
const H=(x:string|Uint8Array)=>`sha256:${createHash("sha256").update(x).digest("hex")}` as Sha;
const MAC=(key:Buffer,domain:string,body:unknown)=>createHmac("sha256",key).update(domain).update("\0").update(C(body)).digest("hex");
const exact=(x:unknown,ks:string[],at:string):any=>{if(!x||typeof x!=="object"||Array.isArray(x)||C(Object.keys(x).sort())!==C([...ks].sort()))throw Error(`U4 triangulation ${at} schema invalid`);return x};
const freeze=<T>(v:T):T=>{const q:any[]=[v];while(q.length){const x=q.pop();if(x&&typeof x==="object"&&!Object.isFrozen(x)){q.push(...Object.values(x));Object.freeze(x)}}return v};
const sorted=(xs:string[])=>new Set(xs).size===xs.length&&C(xs)===C([...xs].sort());
function bounded(...roots:unknown[]){let n=0,b=0;const active=new Set<object>(),q:Array<[unknown,number,boolean]>=roots.map(x=>[x,0,true]);while(q.length){const[x,d,e]=q.pop()!;if(!e){active.delete(x as object);continue}if(++n>50000||d>48)throw Error("U4 triangulation resource bound");if(typeof x==="string"){if(Buffer.byteLength(x)>1_048_576)throw Error("U4 triangulation field bound");b+=Buffer.byteLength(x);continue}if(!x||typeof x!=="object")continue;if(active.has(x as object))throw Error("U4 triangulation cyclic input");active.add(x as object);q.push([x,d,false]);const vs=Array.isArray(x)?x:Object.values(x);if(vs.length>4096)throw Error("U4 triangulation collection bound");for(const y of vs)q.push([y,d+1,true])}if(b>8_388_608)throw Error("U4 triangulation byte bound")}
function at(value:unknown,path:string){if(path==="")return value;let x:any=value;for(const raw of path.slice(1).split("/")){const k=raw.replace(/~1/g,"/").replace(/~0/g,"~");const ok=Array.isArray(x)?/^(0|[1-9]\d*)$/.test(k)&&Number(k)<x.length:x!==null&&typeof x==="object"&&Object.prototype.hasOwnProperty.call(x,k);if(!ok)throw Error("U4 triangulation pointer missing");x=x[k]}return x}

export type U4TriangulationAdjudication={
  id:string; conflictId:string; adjudicatorAuthorityId:string; custodyAuthorityId:string;
  resolutionKind:"choose-left"|"choose-right"|"new-proposition"; resolutionProposition:string;
  adjudicatorReceipt:string; custodyReceipt:string;
};
export type U4EvidenceGapDisposition={
  id:string; edgeId:string; disposition:"unresolved-noncritical";
  semanticAuthorityId:string; receipt:string;
};
export type U4TriangulationInput={
  adjudications:U4TriangulationAdjudication[];
  gapDispositions:U4EvidenceGapDisposition[];
};
export type U4TriangulationEdge={
  id:string;factId:string;slotId:string;leftKind:Kind;rightKind:Kind;
  leftCandidateId:string|null;rightCandidateId:string|null;
  status:"agreement"|"conflict"|"evidence-gap";
  propositionJson:string|null;conflictId:string|null;gapDispositionId:string|null;
};
export type U4AutomaticTriangulation={
  schema:typeof SCHEMA;fixtureKind:"synthetic";denominatorScope:"fixture-local";
  empiricalRegistration:false;closureClaim:false;extractionDigest:Sha;inventoryDigest:Sha;
  factIds:string[];slotKeys:string[];slotPartitions:Array<{factId:string;slotId:string;comparisonKinds:Kind[];metadataKinds:Kind[];requiredComparisonKinds:Kind[];candidateIds:string[];expectedPairCount:number;edgeIds:string[]}>;edges:U4TriangulationEdge[];
  expectedEdgeCount:number;agreementCount:number;conflictCount:number;gapCount:number;
  inventoryConflictIds:string[];adjudicationIds:string[];gapDispositionIds:string[];digest:Sha;
};

const adjudicationBody=(a:U4TriangulationAdjudication)=>({id:a.id,conflictId:a.conflictId,adjudicatorAuthorityId:a.adjudicatorAuthorityId,custodyAuthorityId:a.custodyAuthorityId,resolutionKind:a.resolutionKind,resolutionProposition:a.resolutionProposition});
const gapBody=(g:U4EvidenceGapDisposition)=>({id:g.id,edgeId:g.edgeId,disposition:g.disposition,semanticAuthorityId:g.semanticAuthorityId});
const adjudicationIdentityBody=(a:U4TriangulationAdjudication)=>({conflictId:a.conflictId,adjudicatorAuthorityId:a.adjudicatorAuthorityId,custodyAuthorityId:a.custodyAuthorityId,resolutionKind:a.resolutionKind,resolutionProposition:a.resolutionProposition});
const gapIdentityBody=(g:U4EvidenceGapDisposition)=>({edgeId:g.edgeId,disposition:g.disposition,semanticAuthorityId:g.semanticAuthorityId});
export const computeU4TriangulationAdjudicationId=(a:Omit<U4TriangulationAdjudication,"id"|"adjudicatorReceipt"|"custodyReceipt">)=>`adjudication.${H(`open-autonomy.u4-triangulation-adjudication-id.v1\0${C(a)}`).slice(7)}`;
export const computeU4EvidenceGapDispositionId=(g:Omit<U4EvidenceGapDisposition,"id"|"receipt">)=>`gap.${H(`open-autonomy.u4-triangulation-gap-id.v1\0${C(g)}`).slice(7)}`;
export const signU4TriangulationAdjudication=(keyBase64:string,a:U4TriangulationAdjudication)=>MAC(Buffer.from(keyBase64,"base64"),"u4-triangulation-adjudication",adjudicationBody(a));
export const signU4TriangulationCustody=(keyBase64:string,a:U4TriangulationAdjudication)=>MAC(Buffer.from(keyBase64,"base64"),"u4-triangulation-custody",{...adjudicationBody(a),adjudicatorReceipt:a.adjudicatorReceipt});
export const signU4EvidenceGapDisposition=(keyBase64:string,g:U4EvidenceGapDisposition)=>MAC(Buffer.from(keyBase64,"base64"),"u4-triangulation-gap",gapBody(g));
function receipt(trusted:U4TrustedVerificationInputs,inventory:FrozenU4SourceInventory,authorityId:string,role:string,domain:string,body:unknown,value:string){const a=inventory.authorities.find(x=>x.id===authorityId),k=trusted.authorityKeys.find(x=>x.authorityId===authorityId);if(!a||a.role!==role||!k||k.role!==a.role||k.ownerId!==a.ownerId||k.verificationKeyDigest!==a.verificationKeyDigest)throw Error("U4 triangulation authority invalid");const kb=Buffer.from(k.keyBase64,"base64");if(H(kb)!==a.verificationKeyDigest)throw Error("U4 triangulation trust root invalid");const e=Buffer.from(MAC(kb,domain,body),"hex"),g=Buffer.from(value,"hex");if(e.length!==g.length||!timingSafeEqual(e,g))throw Error("U4 triangulation receipt invalid");return a}
function canonical(x:string){let v:unknown;try{v=JSON.parse(x)}catch{throw Error("U4 triangulation proposition invalid")}if(C(v)!==x)throw Error("U4 triangulation proposition noncanonical");return x}

export type U4FourStreamPartitionRegistry={schema:typeof PARTITION_SCHEMA;kinds:Kind[];partitions:Array<{id:string;blocks:Kind[][];pairKeys:string[];expectedPairCount:number}>;digest:Sha};
function setPartitions<T>(values:T[]):T[][][]{if(!values.length)return[[]];const [head,...tail]=values,out:T[][][]=[];for(const p of setPartitions(tail)){out.push([[head],...p.map(b=>[...b])]);for(let i=0;i<p.length;i++)out.push(p.map((b,j)=>j===i?[head,...b]:[...b]))}return out}
export function verifyU4FourStreamPartitionTopology():U4FourStreamPartitionRegistry{const partitions=setPartitions(KINDS).map(blocks=>blocks.map(b=>[...b].sort() as Kind[]).sort((a,b)=>a[0].localeCompare(b[0]))).map(blocks=>{const pairKeys=blocks.flatMap(block=>block.flatMap((a,i)=>block.slice(i+1).map(b=>`${a}|${b}`))).sort(),expectedPairCount=blocks.reduce((n,b)=>n+b.length*(b.length-1)/2,0),id=`partition.${H(`open-autonomy.u4-four-stream-partition.v1\0${C(blocks)}`).slice(7)}`;if(pairKeys.length!==expectedPairCount||new Set(pairKeys).size!==pairKeys.length)throw Error("U4 partition pair topology invalid");return{id,blocks,pairKeys,expectedPairCount}}).sort((a,b)=>a.id.localeCompare(b.id));if(partitions.length!==15||new Set(partitions.map(p=>p.id)).size!==15)throw Error("U4 partition registry totality invalid");const body={schema:PARTITION_SCHEMA,kinds:[...KINDS],partitions},digest=H(`${PARTITION_SCHEMA}\0${C(body)}`);if(digest!==EXPECTED_U4_FOUR_STREAM_PARTITION_REGISTRY_DIGEST)throw Error("U4 partition registry anchor invalid");return freeze({...body,digest})}

function compileVerifiedU4Triangulation(extraction:U4EvidenceExtraction,inventory:FrozenU4SourceInventory,trusted:U4TrustedVerificationInputs,specification:U4ExtractionSpecification,input:U4TriangulationInput):U4AutomaticTriangulation{
  bounded(extraction,inventory,trusted,input);exact(input,["adjudications","gapDispositions"],"input");
  const{digest:inventoryDigest,...inventoryBody}=inventory;if(computeU4SourceInventoryDigest(inventoryBody as any)!==inventoryDigest)throw Error("U4 triangulation inventory digest invalid");
  const{digest:extractionDigest,...extractionBody}=extraction;if(H(`${extraction.schema}\0${C(extractionBody)}`)!==extractionDigest)throw Error("U4 triangulation extraction digest invalid");
  if(extraction.inventoryDigest!==inventory.digest||extraction.fixtureKind!=="synthetic"||extraction.denominatorScope!=="fixture-local"||extraction.empiricalRegistration!==false||extraction.closureClaim!==false)throw Error("U4 triangulation extraction boundary invalid");
  const ps=new Map(inventory.provenance.map(p=>[p.id,p])),fs=new Map(inventory.facts.map(f=>[f.id,f])),candidateIds=new Set<string>();
  const cells=new Map<string,Map<Kind,typeof extraction.candidates[number]>>();
  for(const c of extraction.candidates){if(candidateIds.has(c.id))throw Error("U4 triangulation candidate identity invalid");candidateIds.add(c.id);const p=ps.get(c.provenanceId),f=fs.get(c.factId);if(!p||!f||!f.provenanceIds.includes(p.id)||p.kind!==c.provenanceKind||p.sha256!==c.evidenceSha256||p.sourceId!==c.sourceId||f.sourceId!==c.sourceId||f.nativePath!==c.nativePath||f.nativeSchemaId!==c.nativeSchemaId)throw Error("U4 triangulation candidate join invalid");let proposition:string|null=null;if(c.mode==="json-pointer"){let parsed:unknown;try{parsed=JSON.parse(Buffer.from(p.bytesBase64,"base64").toString("utf8"))}catch{throw Error("U4 triangulation evidence parse invalid")}proposition=C(at(parsed,c.pointer!));if(c.propositionJson!==proposition||c.propositionDigest!==H(`open-autonomy.u4-extracted-proposition.v1\0${proposition}`))throw Error("U4 triangulation candidate replay invalid")}else if(c.propositionJson!==null||c.propositionDigest!==null)throw Error("U4 triangulation terminal replay invalid");const key=`${c.factId}\0${c.slotId}`,m=cells.get(key)??new Map();if(m.has(p.kind))throw Error("U4 triangulation duplicate stream slot invalid");m.set(p.kind,c);cells.set(key,m)}
  const factIds=[...fs.keys()].sort(),slotKeys=[...cells.keys()].sort(),declarations=new Map(specification.slots.map(s=>[`${s.factId}\0${s.id}`,s]));if(!factIds.length||!slotKeys.length||declarations.size!==specification.slots.length||factIds.some(id=>!slotKeys.some(k=>k.startsWith(`${id}\0`)))||!sorted(extraction.specifiedLocatorIds)||!sorted(extraction.extractedLocatorIds)||C(extraction.specifiedLocatorIds)!==C([...candidateIds].sort())||C(extraction.extractedLocatorIds)!==C([...candidateIds].sort())||C([...declarations.keys()].sort())!==C(slotKeys))throw Error("U4 triangulation candidate totality invalid");for(const[key,m]of cells){const d=declarations.get(key)!;if([...m].some(([k])=>![...d.comparisonKinds,...d.metadataKinds].includes(k))||d.requiredComparisonKinds.some(k=>!m.has(k)))throw Error("U4 triangulation semantic slot declaration join invalid")}
  const conflicts=new Map(inventory.conflicts.map(c=>[c.id,c])),usedConflicts=new Set<string>(),edges:U4TriangulationEdge[]=[];
  for(const key of slotKeys){const[factId,slotId]=key.split("\0"),m=cells.get(key)!,d=declarations.get(key)!,pairs=d.comparisonKinds.flatMap((a,i)=>d.comparisonKinds.slice(i+1).map(b=>[a,b] as const));for(const[leftKind,rightKind]of pairs){const l=m.get(leftKind),r=m.get(rightKind),lp=l?.propositionJson??null,rp=r?.propositionJson??null;const base={factId,slotId,leftKind,rightKind,leftCandidateId:l?.id??null,rightCandidateId:r?.id??null},id=`edge.${H(`open-autonomy.u4-triangulation-edge.v1\0${C(base)}`).slice(7)}`;let status:U4TriangulationEdge["status"],propositionJson:string|null=null,conflictId:string|null=null;if(lp===null||rp===null)status="evidence-gap";else if(canonical(lp)===canonical(rp)){status="agreement";propositionJson=lp}else{status="conflict";const matches=inventory.conflicts.filter(c=>c.factId===factId&&((c.leftProvenanceId===l!.provenanceId&&c.rightProvenanceId===r!.provenanceId&&c.leftJsonPointer===l!.pointer&&c.rightJsonPointer===r!.pointer&&c.leftProposition===lp&&c.rightProposition===rp)||(c.leftProvenanceId===r!.provenanceId&&c.rightProvenanceId===l!.provenanceId&&c.leftJsonPointer===r!.pointer&&c.rightJsonPointer===l!.pointer&&c.leftProposition===rp&&c.rightProposition===lp)));if(matches.length!==1)throw Error("U4 triangulation inventory conflict topology invalid");const c=matches[0];if(c.leftValueDigest!==computeU4PropositionDigest(c.leftProposition)||c.rightValueDigest!==computeU4PropositionDigest(c.rightProposition))throw Error("U4 triangulation inventory conflict proposition invalid");conflictId=c.id;usedConflicts.add(c.id)}edges.push({...base,id,status,propositionJson,conflictId,gapDispositionId:null})}}
  const adjudications=new Map<string,U4TriangulationAdjudication>();for(const a of input.adjudications){exact(a,["id","conflictId","adjudicatorAuthorityId","custodyAuthorityId","resolutionKind","resolutionProposition","adjudicatorReceipt","custodyReceipt"],"adjudication");if(adjudications.has(a.conflictId)||a.id!==`adjudication.${H(`open-autonomy.u4-triangulation-adjudication-id.v1\0${C(adjudicationIdentityBody(a))}`).slice(7)}`)throw Error("U4 triangulation adjudication identity invalid");canonical(a.resolutionProposition);const c=conflicts.get(a.conflictId);if(!c||!usedConflicts.has(c.id)||c.status!=="adjudicated"||c.adjudicatorAuthorityId!==a.adjudicatorAuthorityId||c.resolutionKind!==a.resolutionKind||c.resolutionProposition!==a.resolutionProposition)throw Error("U4 triangulation adjudication join invalid");const aa=receipt(trusted,inventory,a.adjudicatorAuthorityId,"independent-adjudicator","u4-triangulation-adjudication",adjudicationBody(a),a.adjudicatorReceipt),ca=receipt(trusted,inventory,a.custodyAuthorityId,"evidence-custodian","u4-triangulation-custody",{...adjudicationBody(a),adjudicatorReceipt:a.adjudicatorReceipt},a.custodyReceipt);if(aa.ownerId===ca.ownerId||a.adjudicatorAuthorityId===a.custodyAuthorityId)throw Error("U4 triangulation adjudication independence invalid");adjudications.set(a.conflictId,a)}
  const gapDispositions=new Map<string,U4EvidenceGapDisposition>();for(const g of input.gapDispositions){exact(g,["id","edgeId","disposition","semanticAuthorityId","receipt"],"gap disposition");const e=edges.find(x=>x.id===g.edgeId);if(!e||e.status!=="evidence-gap"||gapDispositions.has(g.edgeId)||g.disposition!=="unresolved-noncritical"||g.id!==`gap.${H(`open-autonomy.u4-triangulation-gap-id.v1\0${C(gapIdentityBody(g))}`).slice(7)}`)throw Error("U4 triangulation gap disposition invalid");const f=fs.get(e.factId)!;if(f.criticality!=="noncritical")throw Error("U4 triangulation critical evidence gap");receipt(trusted,inventory,g.semanticAuthorityId,"semantic-inventory-authority","u4-triangulation-gap",gapBody(g),g.receipt);gapDispositions.set(g.edgeId,g);e.gapDispositionId=g.id}
  const conflictEdges=edges.filter(e=>e.status==="conflict"),gapEdges=edges.filter(e=>e.status==="evidence-gap");if(conflictEdges.some(e=>fs.get(e.factId)!.criticality==="critical"&&!adjudications.has(e.conflictId!))||gapEdges.some(e=>fs.get(e.factId)!.criticality==="critical"))throw Error("U4 triangulation critical disagreement unresolved");if(conflictEdges.some(e=>{const c=conflicts.get(e.conflictId!)!;return c.status==="adjudicated"?!adjudications.has(c.id):fs.get(e.factId)!.criticality==="critical"})||gapEdges.some(e=>!gapDispositions.has(e.id)))throw Error("U4 triangulation disposition totality invalid");if(usedConflicts.size!==conflicts.size||[...conflicts].some(([id])=>!usedConflicts.has(id)))throw Error("U4 triangulation inventory conflict surplus invalid");
  const expectedEdgeCount=specification.slots.reduce((n,s)=>n+s.comparisonKinds.length*(s.comparisonKinds.length-1)/2,0);if(edges.length!==expectedEdgeCount||new Set(edges.map(e=>e.id)).size!==edges.length)throw Error("U4 triangulation pair graph totality invalid");edges.sort((a,b)=>a.id.localeCompare(b.id));const slotPartitions=slotKeys.map(key=>{const[factId,slotId]=key.split("\0"),d=declarations.get(key)!,candidateIds=[...cells.get(key)!.values()].map(c=>c.id).sort(),edgeIds=edges.filter(e=>e.factId===factId&&e.slotId===slotId).map(e=>e.id).sort(),expectedPairCount=d.comparisonKinds.length*(d.comparisonKinds.length-1)/2;if(edgeIds.length!==expectedPairCount)throw Error("U4 triangulation slot partition pair count invalid");return{factId,slotId,comparisonKinds:[...d.comparisonKinds],metadataKinds:[...d.metadataKinds],requiredComparisonKinds:[...d.requiredComparisonKinds],candidateIds,expectedPairCount,edgeIds}});if(slotPartitions.reduce((n,p)=>n+p.expectedPairCount,0)!==expectedEdgeCount||new Set(slotPartitions.flatMap(p=>p.candidateIds)).size!==candidateIds.size)throw Error("U4 triangulation slot partition totality invalid");const body={schema:SCHEMA,fixtureKind:"synthetic" as const,denominatorScope:"fixture-local" as const,empiricalRegistration:false as const,closureClaim:false as const,extractionDigest:extraction.digest,inventoryDigest:inventory.digest,factIds,slotKeys,slotPartitions,edges,expectedEdgeCount,agreementCount:edges.filter(e=>e.status==="agreement").length,conflictCount:conflictEdges.length,gapCount:gapEdges.length,inventoryConflictIds:[...usedConflicts].sort(),adjudicationIds:[...adjudications.values()].map(x=>x.id).sort(),gapDispositionIds:[...gapDispositions.values()].map(x=>x.id).sort()};return freeze({...body,digest:H(`${SCHEMA}\0${C(body)}`)})
}

export function createU4AutomaticTriangulation(extraction:U4EvidenceExtraction,inventory:FrozenU4SourceInventory,calculus:FrozenU3ObservationCalculus,registry:FrozenU4SyntheticSourceRegistry,trusted:U4TrustedVerificationInputs,specification:U4ExtractionSpecification,input:U4TriangulationInput):U4AutomaticTriangulation{
  bounded(extraction,inventory,calculus,registry,trusted,specification,input);
  const verified=verifyU4EvidenceExtraction(extraction,inventory,calculus,registry,trusted,specification);
  return compileVerifiedU4Triangulation(verified,inventory,trusted,specification,input);
}
export function verifyU4AutomaticTriangulation(value:U4AutomaticTriangulation,extraction:U4EvidenceExtraction,inventory:FrozenU4SourceInventory,calculus:FrozenU3ObservationCalculus,registry:FrozenU4SyntheticSourceRegistry,trusted:U4TrustedVerificationInputs,specification:U4ExtractionSpecification,input:U4TriangulationInput){bounded(value);const expected=createU4AutomaticTriangulation(extraction,inventory,calculus,registry,trusted,specification,input);if(C(value)!==C(expected))throw Error("U4 triangulation replay mismatch");return expected}
