import { describe, expect, test } from "bun:test";
import { ExecutableOrganizationTwin, ablateNode, compareIntervention, diagnosePosteriorCalibration, inferTwinParameters, observationalEquivalence, predictRecovery, predictTwin, scoreHeldOut, simulateTwin, twinDigest, type TwinEvent, type TwinParameter, type TwinSpecification } from "./organization-twin";

const parameter = (name: string, value: number, patch: Partial<TwinParameter> = {}): TwinParameter => ({ name, value, standardError: 1, source: "estimated", observations: 10, identifiable: true, confoundedWith: [], ...patch });
const spec: TwinSpecification = { schema: "autonomy.organization-twin.v1", version: "1.0.0", budget: 100, assumptions: ["stationary arrivals within horizon"], abstractionError: { throughput: 1, latencyMs: 2, cost: .1, quality: .01, recoveryMs: 5 }, nodes: [
  { id: "worker", provider: "hermes", capacity: 1, queueLimit: 10, service: { kind: "deterministic", meanMs: parameter("worker.service.meanMs", 10), standardDeviationMs: parameter("worker.service.sdMs", 2) }, failureProbability: parameter("worker.failureProbability", .1), costPerMs: parameter("worker.costPerMs", .01), human: false, retryLimit: 1, reviewNode: "review", routes: [{ destination: "review", probability: 1 }] },
  { id: "review", provider: "human", capacity: 1, queueLimit: 10, service: { kind: "deterministic", meanMs: parameter("review.service.meanMs", 5), standardDeviationMs: parameter("review.service.sdMs", 1) }, failureProbability: parameter("review.failureProbability", 0), costPerMs: parameter("review.costPerMs", .02), human: true, retryLimit: 0, routes: [] },
] };
const history: TwinEvent[] = [
  { sequence: 1, atMs: 0, kind: "arrival", workId: "w1", node: "worker", priority: 1 }, { sequence: 2, atMs: 1, kind: "start", workId: "w1", node: "worker", attempt: 1 }, { sequence: 3, atMs: 11, kind: "complete", workId: "w1", node: "worker", attempt: 1, cost: 1, quality: .9, humanMinutes: 0 }, { sequence: 4, atMs: 12, kind: "route", workId: "w1", from: "worker", to: "review" }, { sequence: 5, atMs: 13, kind: "start", workId: "w1", node: "review", attempt: 2 }, { sequence: 6, atMs: 18, kind: "complete", workId: "w1", node: "review", attempt: 2, cost: 2, quality: 1, humanMinutes: 2 },
  { sequence: 7, atMs: 20, kind: "arrival", workId: "w2", node: "worker", priority: 2 }, { sequence: 8, atMs: 21, kind: "start", workId: "w2", node: "worker", attempt: 1 }, { sequence: 9, atMs: 33, kind: "failure", workId: "w2", node: "worker", attempt: 1, retry: true }, { sequence: 10, atMs: 34, kind: "start", workId: "w2", node: "worker", attempt: 2 }, { sequence: 11, atMs: 45, kind: "complete", workId: "w2", node: "worker", attempt: 2, cost: 1, quality: .8, humanMinutes: 0 }, { sequence: 12, atMs: 46, kind: "route", workId: "w2", from: "worker", to: "review" }, { sequence: 13, atMs: 47, kind: "start", workId: "w2", node: "review", attempt: 3 }, { sequence: 14, atMs: 53, kind: "complete", workId: "w2", node: "review", attempt: 3, cost: 2, quality: .9, humanMinutes: 3 },
];

describe("R25 executable transition and replay semantics", () => {
  test("replays identity, priority queues, retries, review, resources and human seams", () => { const state = new ExecutableOrganizationTwin(spec).replay(history); expect(state.sequence).toBe(14); expect(state.completed).toBe(2); expect(state.failed).toBe(0); expect(state.spent).toBe(6); expect(state.work.w2).toEqual(expect.objectContaining({ status: "done", attempt: 3, humanMinutes: 3 })); expect(state.trace).toEqual(history); });
  test("rejects duplicate identity, sequence gaps, capacity violations and invalid retries", () => {
    const twin = new ExecutableOrganizationTwin(spec); twin.apply(history[0]!); expect(() => twin.apply({ ...history[0]!, sequence: 2 })).toThrow("identity equivocation");
    expect(() => new ExecutableOrganizationTwin(spec).apply({ ...history[0]!, sequence: 2 })).toThrow("ordering");
    const capacity = new ExecutableOrganizationTwin(spec); capacity.apply(history[0]!); capacity.apply(history[1]!); capacity.apply({ sequence: 3, atMs: 2, kind: "arrival", workId: "other", node: "worker", priority: 0 }); expect(() => capacity.apply({ sequence: 4, atMs: 3, kind: "start", workId: "other", node: "worker", attempt: 1 })).toThrow("queue/service");
  });
  test("requires authoritative digest and reconstructs repeatably", () => { const input = { events: history, authoritativeDigest: twinDigest(history) }; expect(inferTwinParameters(spec, [input]).replayDigest).toBeTruthy(); expect(() => inferTwinParameters(spec, [{ ...input, authoritativeDigest: "forged" }])).toThrow("digest mismatch"); expect(new ExecutableOrganizationTwin(spec).replay(history)).toEqual(new ExecutableOrganizationTwin(spec).replay(history)); });
});

describe("R25 inference, identifiability and prediction calibration", () => {
  test("recovers synthetic service parameters with uncertainty and provenance", () => { const result = inferTwinParameters(spec, [{ events: history, authoritativeDigest: twinDigest(history) }]); const worker = result.parameters.find((p) => p.name === "worker.service.meanMs")!; expect(worker.value).toBe(11); expect(worker.standardError).toBeCloseTo(.57735, 4); expect(worker.source).toBe("estimated"); expect(worker.observations).toBe(3); expect(result.diagnostics.find((d) => d.parameter === worker.name)?.status).toBe("identified"); });
  test("reports sparse and observationally mixed parameters instead of selecting a causal story", () => { const routed = structuredClone(spec); routed.nodes[0]!.routes[0]!.probability = .5; routed.nodes[0]!.routes.push({ destination: "worker", probability: .5 }); const inference = inferTwinParameters(routed, [{ events: history, authoritativeDigest: twinDigest(history) }]); expect(inference.diagnostics.find((d) => d.parameter === "worker.service.meanMs")).toEqual(expect.objectContaining({ status: "weak", observationallyEquivalent: ["worker->review", "worker->worker"] })); expect(inference.diagnostics.find((d) => d.parameter === "review.failureProbability")?.status).toBe("identified"); });
  test("scores held-out coverage and refuses to call systematic misses calibrated", () => { const parameters = spec.nodes.flatMap((n) => [n.service.meanMs, n.failureProbability, n.costPerMs]); expect(predictTwin(spec, parameters, 10, 100).every((p) => !p.calibrated)).toBe(true); const predictions = predictTwin(spec, parameters, 10, 100, { heldOutObservations: 20, coverage90: .9 }), good = predictions.map((p) => ({ metric: p.metric, value: p.point })); expect(scoreHeldOut(predictions, good).calibrated).toBe(true); const missed = Array.from({ length: 10 }, () => ({ metric: "latencyMs" as const, value: 10_000 })); const score = scoreHeldOut(predictions, missed); expect(score.coverage90).toBe(0); expect(score.calibrated).toBe(false); expect(score.falsifying).toHaveLength(10); expect(predictions.find((p) => p.metric === "quality")!.interval90[1]).toBeLessThan(5); });
  test("an assumed or unidentifiable parameter prevents calibrated status", () => { const parameters = spec.nodes.flatMap((n) => [n.service.meanMs, n.failureProbability, n.costPerMs]).map((p, i) => i ? p : { ...p, source: "assumed" as const, identifiable: false }); expect(predictTwin(spec, parameters, 10, 100).every((p) => !p.calibrated)).toBe(true); });
});

describe("R25 recovery, ablation and interventions", () => {
  test("predicts backlog recovery under surviving capacity with uncertainty", () => { const recovery = predictRecovery(10, { ...spec.nodes[0]!, capacity: 3 }, 1); expect(recovery).toEqual(expect.objectContaining({ survivingCapacity: 2, pointMs: 50, identifiable: true })); expect(recovery.interval90[0]).toBeLessThan(50); expect(() => predictRecovery(10, spec.nodes[0]!, 1)).toThrow("no feasible"); });
  test("computes ablation sensitivity and labels noncausal counterfactuals", () => { const parameters = spec.nodes.flatMap((n) => [n.service.meanMs, n.failureProbability, n.costPerMs]); const ablation = ablateNode(spec, "review", parameters, 10, 100); expect(ablation.deltas.latencyMs).toBe(-5); const comparison = compareIntervention(spec, parameters, 10, 100, { id: "faster-worker", parameter: "worker.service.meanMs", value: 5 }, "prediction"); expect(comparison.claim).toBe("prediction"); expect(comparison.assumptions[0]).toContain("not causal"); expect(comparison.deltas.latencyMs).toBe(-5); });
  test("rejects causal claims for assumed, confounded or unidentifiable interventions", () => { const parameters = spec.nodes.flatMap((n) => [n.service.meanMs, n.failureProbability, n.costPerMs]), bad = parameters.map((p) => p.name === "worker.service.meanMs" ? { ...p, identifiable: false, source: "assumed" as const, confoundedWith: ["routing"] } : p); expect(() => compareIntervention(spec, bad, 10, 100, { id: "claim", parameter: "worker.service.meanMs", value: 5 }, "causal")).toThrow("non-identifiable or confounded"); });
  test("rejects routing distributions that do not conserve probability", () => { const invalid = structuredClone(spec); invalid.nodes[0]!.routes[0]!.probability = .5; expect(() => new ExecutableOrganizationTwin(invalid)).toThrow("specification invalid"); });
});
describe("R25 seeded generative queue twin",()=>{
  const arrivals=Array.from({length:6},(_,i)=>({id:`job-${i}`,atMs:i, node:"worker",priority:i%2,quality:.9}));
  test("executes arrivals, bounded queues, capacity, routing, retries, resources and human seams reproducibly",()=>{const simulationSpec=structuredClone(spec);simulationSpec.nodes.forEach((n)=>n.failureProbability.value=0);const a=simulateTwin(simulationSpec,arrivals,1000,17),b=simulateTwin(simulationSpec,arrivals,1000,17);expect(a).toEqual(b);expect(a.arrived).toBe(6);expect(a.completed+a.failed+a.blocked).toBe(6);expect(a.trace.some((e)=>e.kind==="route"&&e.node==="review")).toBe(true);expect(a.humanMinutes).toBeGreaterThan(0);expect(a.cost).toBeGreaterThan(0);expect(Object.values(a.maximumQueue).every((n)=>n<=10)).toBe(true);});
  test("samples lognormal service distributions from the seed and exposes posterior held-out calibration",()=>{const stochastic=structuredClone(spec);stochastic.nodes[0]!.service.kind="lognormal";stochastic.nodes[0]!.service.standardDeviationMs.value=8;stochastic.nodes.forEach((n)=>n.failureProbability.value=0);expect(simulateTwin(stochastic,arrivals,1000,1)).toEqual(simulateTwin(stochastic,arrivals,1000,1));expect(simulateTwin(stochastic,arrivals,1000,1).trace).not.toEqual(simulateTwin(stochastic,arrivals,1000,2).trace);const diagnostics=diagnosePosteriorCalibration(Array.from({length:10},()=>({metric:"throughput" as const,point:1,interval90:[0,2] as [number,number],actual:1})));expect(diagnostics[0]).toEqual(expect.objectContaining({observations:10,coverage90:1,calibrated:true}));});
  test("reports observationally equivalent models instead of inventing identification",()=>{const equivalent=observationalEquivalence([spec,structuredClone(spec)],arrivals,1000,[1,2,3]);expect(equivalent.identifiable).toBe(false);expect(equivalent.groups[0]).toEqual([0,1]);const changed=structuredClone(spec);changed.nodes[0]!.service.meanMs.value=100;expect(observationalEquivalence([spec,changed],arrivals,1000,[1,2,3]).identifiable).toBe(true);});
});
