import {createHash} from "node:crypto";
import {canonicalSemanticJson} from "./organization-canonical";
import{closeSync,fsyncSync,mkdirSync,openSync,readFileSync,renameSync,rmSync,statSync,writeFileSync}from"node:fs";
import{resolve}from"node:path";
import type {PaperclipDeploymentObservation,PaperclipDeploymentState,PaperclipReleasePin} from "./organization-paperclip-deployment";
import type {PaperclipEventState} from "./organization-paperclip-events";
import type {PaperclipPortableBackup,PaperclipProviderState} from "./organization-paperclip-live-provider";

export interface PaperclipRuntimeLifecycle{initialize():PaperclipDeploymentState;start(id:string):PaperclipDeploymentState;inspect():{state:PaperclipDeploymentState;observed:PaperclipDeploymentObservation};restart(id:string):PaperclipDeploymentState;backup(id:string,path:string):PaperclipDeploymentState;restore(id:string):PaperclipDeploymentState;upgrade(id:string,target:PaperclipReleasePin,path:string):PaperclipDeploymentState;rollback(id:string,target?:PaperclipReleasePin):PaperclipDeploymentState;teardown(id:string):void}
export type RuntimeCheckpoint={epoch:number;digest:string};
export interface PaperclipRuntimeControl{deploy():PaperclipProviderState;health():{healthy:boolean;residuals:Array<{kind:string;id:string;detail:string}>;[key:string]:unknown};exportPortableBackup():PaperclipPortableBackup;invalidateCheckpoint(operationId:string,epoch:number):void;rebuildCheckpoint(operationId:string,epoch:number):PaperclipProviderState;checkpoint():RuntimeCheckpoint;cleanupOwned(operationId:string):string;}
export interface PaperclipRuntimeEvents{initialize():PaperclipEventState;current():PaperclipEventState;sync(limit?:number):PaperclipEventState;invalidateCheckpoint(operationId:string,epoch:number):void;rebuildCheckpoint(operationId:string,epoch:number):PaperclipEventState;checkpoint():RuntimeCheckpoint;cleanupOwned(operationId:string):string;}
export interface PaperclipRuntimeParticipant{id:string;kind:"sidecar"|"bridge"|"credential"|"artifact";invalidateCheckpoint(operationId:string,epoch:number):void;rebuildCheckpoint(operationId:string,epoch:number):RuntimeCheckpoint;checkpoint():RuntimeCheckpoint;cleanupOwned(operationId:string):string;}
export interface PaperclipRuntimeTrust{sign(digest:string):string;verify(digest:string,signature:string):boolean}
export interface PaperclipRuntimeJournalStore{load(id:string):PaperclipRuntimeJournalState|undefined;compareAndSwap(id:string,expected:number|undefined,next:PaperclipRuntimeJournalState):boolean}
export class MemoryPaperclipRuntimeJournalStore implements PaperclipRuntimeJournalStore{private values=new Map<string,PaperclipRuntimeJournalState>();load(id:string){const v=this.values.get(id);return v&&structuredClone(v)}compareAndSwap(id:string,e:number|undefined,n:PaperclipRuntimeJournalState){if(this.values.get(id)?.generation!==e)return false;this.values.set(id,structuredClone(n));return true}}
export class DiskPaperclipRuntimeJournalStore implements PaperclipRuntimeJournalStore{
 constructor(private root:string){mkdirSync(root,{recursive:true})}
 private path(id:string){return resolve(this.root,`${createHash("sha256").update(id).digest("hex")}.runtime.json`)}
 load(id:string){try{return JSON.parse(readFileSync(this.path(id),"utf8")) as PaperclipRuntimeJournalState}catch(error){if((error as NodeJS.ErrnoException).code==="ENOENT")return undefined;throw error}}
 compareAndSwap(id:string,expected:number|undefined,next:PaperclipRuntimeJournalState){const path=this.path(id),lock=`${path}.lock`;this.acquire(lock);try{if(this.load(id)?.generation!==expected)return false;const temp=`${path}.${process.pid}.${Date.now()}.tmp`,fd=openSync(temp,"wx",0o600);try{writeFileSync(fd,canonicalSemanticJson(next),"utf8");fsyncSync(fd)}finally{closeSync(fd)}renameSync(temp,path);const dir=openSync(this.root,"r");try{fsyncSync(dir)}finally{closeSync(dir)}return true}finally{rmSync(lock,{force:true})}}
 private acquire(lock:string){for(let attempt=0;attempt<3000;attempt++){try{const fd=openSync(lock,"wx",0o600);try{writeFileSync(fd,canonicalSemanticJson({pid:process.pid,createdAt:Date.now()}),"utf8");fsyncSync(fd)}finally{closeSync(fd)}return}catch(error){if((error as NodeJS.ErrnoException).code!=="EEXIST")throw error;let dead=false;try{const owner=JSON.parse(readFileSync(lock,"utf8")) as{pid?:number;createdAt?:number},age=Date.now()-statSync(lock).mtimeMs;if(age>30_000){if(Number.isSafeInteger(owner.pid))try{process.kill(owner.pid!,0)}catch(probe){dead=(probe as NodeJS.ErrnoException).code==="ESRCH"}else dead=true}}catch{try{dead=Date.now()-statSync(lock).mtimeMs>30_000}catch{dead=true}}if(dead){try{rmSync(lock,{force:true})}catch{}continue}Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,10)}}throw new Error("Paperclip runtime journal lock timeout")}
}
type OperationKind="deploy"|"restart"|"backup"|"restore"|"upgrade"|"rollback"|"teardown";
type RuntimeOperation={id:string;kind:OperationKind;requestDigest:string;status:"prepared"|"running"|"completed";step:number;epochBefore:number;epochAfter:number;steps:string[];artifacts:{nativeBackupDigest?:string;portableBackupDigest?:string;lifecycleDigest?:string;providerDigest?:string;eventDigest?:string;providerSequence?:number;eventGeneration?:number;participantDigests:Record<string,string>;cleanupDigests:Record<string,string>};receipt?:PaperclipRuntimeReceipt};
export type PaperclipRuntimeJournalState={schema:"autonomy.paperclip-runtime-journal.v1";runtimeId:string;generation:number;epoch:number;status:"active"|"tombstone";operations:Record<string,RuntimeOperation>;tombstone?:{operationId:string;epoch:number;receiptDigest:string;cleanupDigests:Record<string,string>;receipt?:PaperclipRuntimeReceipt};digest:string;signature:string};
export type PaperclipRuntimeReceipt={schema:"autonomy.paperclip-runtime-receipt.v2";operation:OperationKind;operationId:string;epoch:number;lifecycleSequence:number;lifecycleFence:number;providerSequence:number;eventGeneration:number;nativeBackupDigest?:string;portableBackupDigest?:string;participantDigests:Record<string,string>;digest:string};
export type PaperclipRuntimeOptions={runtimeId:string;trust:PaperclipRuntimeTrust;store:PaperclipRuntimeJournalStore;participants?:PaperclipRuntimeParticipant[];afterEffect?:(operationId:string,step:string)=>void};

export class PaperclipOrganizationRuntime{
 private participants:PaperclipRuntimeParticipant[];
 constructor(private lifecycle:PaperclipRuntimeLifecycle,private control:PaperclipRuntimeControl,private events:PaperclipRuntimeEvents,private options:PaperclipRuntimeOptions){if(!options.runtimeId)throw new Error("runtime id required");this.participants=[...(options.participants??[])];const keys=this.participants.map(p=>`${p.kind}:${p.id}`);if(new Set(keys).size!==keys.length)throw new Error("duplicate runtime participant");this.initializeJournal()}
 deploy(id:string){return this.execute(id,"deploy",{},["lifecycle-initialize","lifecycle-start","provider-deploy","events-initialize","verify-health"],(op,step)=>{if(step==="lifecycle-initialize")this.lifecycle.initialize();else if(step==="lifecycle-start")this.setLifecycle(op,this.lifecycle.start(`runtime:${id}:start`));else if(step==="provider-deploy")this.setProvider(op,this.control.deploy());else if(step==="events-initialize")this.setEvents(op,this.events.initialize());else this.assertHealthy(op,false)})}
 restart(id:string){return this.execute(id,"restart",{},["lifecycle-restart","provider-deploy","events-current","verify-health"],(op,step)=>{if(step==="lifecycle-restart")this.setLifecycle(op,this.lifecycle.restart(`runtime:${id}:restart`));else if(step==="provider-deploy")this.setProvider(op,this.control.deploy());else if(step==="events-current")this.setEvents(op,this.events.current());else this.assertHealthy(op,false)})}
 backup(id:string,path:string){return this.execute(id,"backup",{path},["portable-backup","native-backup","provider-current","events-current","pair-digests"],(op,step)=>{if(step==="portable-backup"){const b=this.control.exportPortableBackup();this.patchArtifacts(op,{portableBackupDigest:b.digest})}else if(step==="native-backup"){const s=this.lifecycle.backup(`runtime:${id}:native`,path);if(!s.backup)throw new Error("lifecycle omitted native backup");this.setLifecycle(op,s);this.patchArtifacts(op,{nativeBackupDigest:s.backup.digest})}else if(step==="provider-current")this.setProvider(op,this.control.deploy());else if(step==="events-current")this.setEvents(op,this.events.current());else{const a=this.operation(op).artifacts;if(!sha(a.nativeBackupDigest)||!sha(a.portableBackupDigest))throw new Error("paired native and portable backup digests required")}})}
 restore(id:string){return this.epochTransition(id,"restore",{},()=>this.lifecycle.restore(`runtime:${id}:restore`))}
 upgrade(id:string,target:PaperclipReleasePin,path:string){return this.epochTransition(id,"upgrade",{target,path},()=>this.lifecycle.upgrade(`runtime:${id}:upgrade`,target,path))}
 rollback(id:string,target?:PaperclipReleasePin){return this.epochTransition(id,"rollback",{target},()=>this.lifecycle.rollback(`runtime:${id}:rollback`,target))}
 synchronize(limit?:number){const i=this.lifecycle.inspect();if(!i.observed.running||!i.observed.healthy)throw new Error("Paperclip deployment is unavailable for event sync");return this.events.sync(limit)}
 health(){const lifecycle=this.lifecycle.inspect(),control=this.control.health(),events=this.events.current(),journal=this.current(),checkpoints=[this.control.checkpoint(),this.events.checkpoint(),...this.participants.map(p=>p.checkpoint())],eventGaps=events.gaps.map(g=>({kind:"observation-gap" as const,id:g.id,detail:g.detail})),checkpointGaps=checkpoints.filter(c=>c.epoch!==journal.epoch).map((c,i)=>({kind:"checkpoint-epoch" as const,id:String(i),detail:`checkpoint epoch ${c.epoch} differs from runtime ${journal.epoch}`})),residuals=[...control.residuals,...eventGaps,...checkpointGaps],blockingResiduals=residuals.filter(r=>r.kind!=="assumption");return{healthy:journal.status==="active"&&lifecycle.observed.running&&lifecycle.observed.healthy&&control.healthy&&blockingResiduals.length===0,epoch:journal.epoch,lifecycle,control,eventGeneration:events.generation,contiguousEventSequence:events.contiguousSequence,observedEventHighWater:events.observedHighWater,residuals}}
 teardown(id:string){const steps=[...this.participants.map(p=>`cleanup:${p.kind}:${p.id}`),"cleanup:events","cleanup:control","lifecycle-teardown","tombstone"];return this.execute(id,"teardown",{},steps,(op,step)=>{if(step.startsWith("cleanup:")){const key=step.slice(8),digest=key==="events"?this.events.cleanupOwned(`runtime:${id}:${step}`):key==="control"?this.control.cleanupOwned(`runtime:${id}:${step}`):this.participants.find(p=>`${p.kind}:${p.id}`===key)!.cleanupOwned(`runtime:${id}:${step}`);if(!sha(digest))throw new Error(`cleanup ${key} lacks durable digest`);this.patchCleanup(op,key,digest)}else if(step==="lifecycle-teardown")this.lifecycle.teardown(`runtime:${id}:teardown`);else this.markTombstone(op)})}
 snapshot(){return this.current()}
 private epochTransition(id:string,kind:"restore"|"rollback"|"upgrade",request:unknown,lifecycleAction:()=>PaperclipDeploymentState){const resources=["control","events",...this.participants.map(p=>`${p.kind}:${p.id}`)],steps=["lifecycle-transition","epoch-advance",...resources.map(x=>`invalidate:${x}`),...resources.map(x=>`rebuild:${x}`),"verify-health"];return this.execute(id,kind,request,steps,(op,step)=>{if(step==="lifecycle-transition")this.setLifecycle(op,lifecycleAction());else if(step==="epoch-advance"){const operation=this.operation(op),lifecycle=this.lifecycle.inspect().state,target=Math.max(operation.epochBefore+1,lifecycle.restoreEpoch);this.mutate(s=>{s.epoch=target;s.operations[op]!.epochAfter=target})}else if(step.startsWith("invalidate:")){const target=step.slice(11),epoch=this.current().epoch;if(target==="control")this.control.invalidateCheckpoint(`runtime:${id}:${step}`,epoch);else if(target==="events")this.events.invalidateCheckpoint(`runtime:${id}:${step}`,epoch);else this.participant(target).invalidateCheckpoint(`runtime:${id}:${step}`,epoch)}else if(step.startsWith("rebuild:")){const target=step.slice(8),epoch=this.current().epoch;if(target==="control")this.setProvider(op,this.control.rebuildCheckpoint(`runtime:${id}:${step}`,epoch));else if(target==="events")this.setEvents(op,this.events.rebuildCheckpoint(`runtime:${id}:${step}`,epoch));else{const c=this.participant(target).rebuildCheckpoint(`runtime:${id}:${step}`,epoch);if(c.epoch!==epoch||!sha(c.digest))throw new Error(`${target} checkpoint rebuild mismatch`);this.patchParticipant(op,target,c.digest)}}else this.assertHealthy(op,true)})}
 private execute(id:string,kind:OperationKind,request:unknown,steps:string[],effect:(op:string,step:string)=>void){if(!id)throw new Error("operation id required");const snapshot=this.current();if(snapshot.status==="tombstone"&&!(kind==="teardown"&&snapshot.tombstone?.operationId===id)){throw new Error("runtime tombstoned")}if(snapshot.status==="tombstone"&&snapshot.tombstone?.receipt)return structuredClone(snapshot.tombstone.receipt);const requestDigest=hash({kind,request}),existing=snapshot.operations[id];if(existing&&(existing.kind!==kind||existing.requestDigest!==requestDigest))throw new Error("runtime operation equivocation");if(!existing)this.mutate(s=>{s.operations[id]={id,kind,requestDigest,status:"prepared",step:0,epochBefore:s.epoch,epochAfter:s.epoch,steps:[...steps],artifacts:{participantDigests:{},cleanupDigests:{}}}});for(;;){const op=this.operation(id);if(op.status==="completed")return structuredClone(op.receipt!);const step=op.steps[op.step];if(!step) return this.complete(id);this.mutate(s=>{s.operations[id]!.status="running"});effect(id,step);this.options.afterEffect?.(id,step);this.mutate(s=>{const live=s.operations[id]!;if(live.steps[live.step]!==step)throw new Error("runtime journal step lost ownership");live.step++})}}
 private complete(id:string){const op=this.operation(id),l=this.lifecycle.inspect().state,epoch=this.current().epoch;if(op.kind!=="teardown"&&(this.control.checkpoint().epoch!==epoch||this.events.checkpoint().epoch!==epoch))throw new Error("runtime receipt checkpoint epoch mismatch");const body={schema:"autonomy.paperclip-runtime-receipt.v2" as const,operation:op.kind,operationId:id,epoch,lifecycleSequence:l.sequence,lifecycleFence:l.fence,providerSequence:op.artifacts.providerSequence??0,eventGeneration:op.artifacts.eventGeneration??0,...(op.artifacts.nativeBackupDigest?{nativeBackupDigest:op.artifacts.nativeBackupDigest}:{}),...(op.artifacts.portableBackupDigest?{portableBackupDigest:op.artifacts.portableBackupDigest}:{}),participantDigests:structuredClone(op.artifacts.participantDigests)},receipt={...body,digest:hash(body)};this.mutate(s=>{if(op.kind==="teardown"&&s.tombstone){s.tombstone.receiptDigest=receipt.digest;s.tombstone.receipt=receipt;s.operations={}}else{s.operations[id]!.status="completed";s.operations[id]!.receipt=receipt}});return receipt}
 private assertHealthy(op:string,epochRequired:boolean){const i=this.lifecycle.inspect(),c=this.control.health(),epoch=this.current().epoch;if(!i.observed.running||!i.observed.healthy||!c.healthy||c.residuals.some(r=>r.kind!=="assumption"))throw new Error("composite runtime health failed");if(epochRequired){const all=[this.control.checkpoint(),this.events.checkpoint(),...this.participants.map(p=>p.checkpoint())];if(all.some(v=>v.epoch!==epoch||!sha(v.digest)))throw new Error("stale checkpoint accepted after epoch transition")}this.patchArtifacts(op,{lifecycleDigest:i.state.digest})}
 private setLifecycle(op:string,s:PaperclipDeploymentState){this.patchArtifacts(op,{lifecycleDigest:s.digest})}private setProvider(op:string,s:PaperclipProviderState){this.patchArtifacts(op,{providerDigest:s.digest,providerSequence:s.sequence})}private setEvents(op:string,s:PaperclipEventState){this.patchArtifacts(op,{eventDigest:s.digest,eventGeneration:s.generation})}
 private patchArtifacts(id:string,p:Partial<RuntimeOperation["artifacts"]>){this.mutate(s=>{const target=s.operations[id]!.artifacts;for(const[key,value]of Object.entries(p)){const prior=target[key as keyof typeof target];if(prior!==undefined&&canonicalSemanticJson(prior)!==canonicalSemanticJson(value))throw new Error(`runtime artifact ${key} equivocation`);(target as Record<string,unknown>)[key]=structuredClone(value)}})}private patchParticipant(id:string,key:string,d:string){this.mutate(s=>{const target=s.operations[id]!.artifacts.participantDigests,prior=target[key];if(prior&&prior!==d)throw new Error(`participant ${key} digest equivocation`);target[key]=d})}private patchCleanup(id:string,key:string,d:string){this.mutate(s=>{const target=s.operations[id]!.artifacts.cleanupDigests,prior=target[key];if(prior&&prior!==d)throw new Error(`cleanup ${key} digest equivocation`);target[key]=d})}
 private markTombstone(id:string){const op=this.operation(id);this.mutate(s=>{s.status="tombstone";s.tombstone={operationId:id,epoch:s.epoch,receiptDigest:hash({id,epoch:s.epoch,cleanup:op.artifacts.cleanupDigests}),cleanupDigests:structuredClone(op.artifacts.cleanupDigests)};s.operations=Object.fromEntries([[id,s.operations[id]!]])})}
 private participant(key:string){const p=this.participants.find(v=>`${v.kind}:${v.id}`===key);if(!p)throw new Error(`unknown runtime participant ${key}`);return p}
 private operation(id:string){const op=this.current().operations[id];if(!op)throw new Error("runtime operation missing");return op}
 private initializeJournal(){if(this.options.store.load(this.options.runtimeId)){this.current();return}const next=seal({schema:"autonomy.paperclip-runtime-journal.v1",runtimeId:this.options.runtimeId,generation:1,epoch:0,status:"active",operations:{}},this.options.trust);if(!this.options.store.compareAndSwap(this.options.runtimeId,undefined,next))throw new Error("runtime journal creation race")}
 private current(){const s=this.options.store.load(this.options.runtimeId);if(!s)throw new Error("runtime journal missing");const{digest,signature,...body}=s,expected=hash(body);if(digest!==expected||!this.options.trust.verify(expected,signature)||s.runtimeId!==this.options.runtimeId)throw new Error("runtime journal authentication failed");return structuredClone(s)}
 private mutate(change:(s:PaperclipRuntimeJournalState)=>void){for(let n=0;n<12;n++){const old=this.current(),next=structuredClone(old);change(next);next.generation++;const{digest:_,signature:__,...body}=next,sealed=seal(body,this.options.trust);if(this.options.store.compareAndSwap(this.options.runtimeId,old.generation,sealed))return}throw new Error("runtime journal CAS contention")}
}
function seal(body:Omit<PaperclipRuntimeJournalState,"digest"|"signature">,trust:PaperclipRuntimeTrust){const digest=hash(body);return{...structuredClone(body),digest,signature:trust.sign(digest)}}
function hash(v:unknown){return`sha256:${createHash("sha256").update(canonicalSemanticJson(v)).digest("hex")}`}
function sha(v:unknown):v is string{return typeof v==="string"&&/^sha256:[a-f0-9]{64}$/.test(v)}
