import { describe, expect, test } from "bun:test";
import { createHmac } from "node:crypto";
import { BoundedImprovementLoop, MemoryImprovementStore, improvementDigest, type ActorAttestation, type ImprovementEffectPort, type ImprovementPolicy, type ImprovementTrust, type LoopRole } from "./organization-improvement-loop";

const members: Record<LoopRole, string[]> = { worker:["worker"], proposer:["planner"], evaluator:["evaluator"], approver:["alice","bob"], deployer:["deployer"], auditor:["auditor"] };
const key=(a:string,r:LoopRole)=>`r28-v3:${a}:${r}`, mac=(k:string,d:string)=>createHmac("sha256",k).update(d).digest("hex");
const trust: ImprovementTrust={ verifyActor:(a,r,d,s)=>members[r].includes(a)&&mac(key(a,r),d)===s, signState:d=>mac("r28-v3-state",d), verifyState:(d,s)=>mac("r28-v3-state",d)===s };
const attest=<T>(a:string,r:LoopRole,p:T):ActorAttestation<T>=>{const digest=improvementDigest(p);return{actor:a,payload:p,digest,signature:mac(key(a,r),digest)}};
const policy: ImprovementPolicy={ constitutionDigest:"constitution:v3",graderDigest:"grader:v3",authorityCeilingDigest:"authority:v3",evidencePolicyDigest:"evidence:v3",pauseGuardDigest:"pause:v3",rollbackGuardDigest:"rollback:v3",protectedPaths:["constitution","grader","authorityCeiling","evidence","pause","rollback"],allowedScopes:["repository.fixture"],authorityCeiling:{repo:1},proposalWindowMs:1000,maxProposalsPerWindow:4,maxSpendPerProposal:2,maxCumulativeSpend:6,maxOperationsPerProposal:1,maxCumulativeChanges:3,maximumCanaryFraction:.1,maximumExperimentSamples:20,approvalQuorum:2,roleMembers:members };
class CrashAfterEffect implements ImprovementEffectPort {
  receipts=new Map<string,string>(); calls:string[]=[]; crashOnce=false;
  perform(e:{id:string}) { this.calls.push(e.id); const receipt=this.receipts.get(e.id)??`durable:${e.id}`; this.receipts.set(e.id,receipt); if(this.crashOnce){this.crashOnce=false;throw new Error("injected crash after external effect before receipt")} return{id:e.id,durable:true as const,receipt}; }
}
const worker=()=>{const b={historyDigest:"git-history:v3",observations:30},workerDigest=improvementDigest(b);return{...b,worker:"worker",workerDigest,workerSignature:mac(key("worker","worker"),workerDigest)}};
const restart=(store:MemoryImprovementStore,effects:CrashAfterEffect,now=100)=>new BoundedImprovementLoop("open-autonomy-r28-v3",policy,trust,store,effects,()=>now);
const deployAuth=(id:string,l:BoundedImprovementLoop,kind="deploy")=>{const w=l.current().workflows[id]!,context=improvementDigest({proposal:w.artifacts.proposal!.digest,preregistration:w.artifacts.preregistration!.digest,approvals:w.approvals.map(a=>a.digest).sort(),policy:improvementDigest(policy)}),d=improvementDigest({id,kind,context});return`deployer:${mac(key("deployer","deployer"),d)}`};
function stage(id:string,store:MemoryImprovementStore,effects:CrashAfterEffect){let l=restart(store,effects);l.start(id,attest("auditor","auditor",worker()));l=restart(store,effects);l.measure(id,attest("evaluator","evaluator",{metric:"verified-tests",baseline:10,unit:"tests",horizon:"commit",evidenceDigest:l.current().workflows[id]!.artifacts.evidence!.digest}));l=restart(store,effects);l.updateTwin(id,attest("evaluator","evaluator",{version:"v3",replayDigest:`replay:${id}`,calibrated:true,residuals:[]}));l=restart(store,effects);l.propose(id,attest("planner","proposer",{patchDigest:`patch:${id}`,paths:[`fixtures/${id}`],scope:"repository.fixture",operations:1,spend:2,authority:{repo:1},expectedMetric:"verified-tests",claim:"causal" as const}));l=restart(store,effects);l.recordChecks(id,attest("evaluator","evaluator",{patchDigest:`patch:${id}`,compile:true,conform:true,formal:true,inheritedObligationsDigest:"obligations:v3"}));l=restart(store,effects);l.recordBenchmark(id,attest("evaluator","evaluator",{patchDigest:`patch:${id}`,graderDigest:policy.graderDigest,passed:true,resultDigest:`bench:${id}`,independent:true}));l=restart(store,effects);l.preregister(id,attest("auditor","auditor",{metric:"verified-tests",minimumImprovement:1,guardrails:{regressions:0},sampleCount:20,canaryFraction:.05,causalDesign:"randomized" as const,rollbackTrigger:"regressions > 0"}));for(const a of ["alice","bob"]){l.approve(id,attest(a,"approver",{proposalId:id,proposalDigest:l.current().workflows[id]!.artifacts.proposal!.digest,preregistrationDigest:l.current().workflows[id]!.artifacts.preregistration!.digest,expiresAt:"2099-01-01T00:00:00Z",decision:"approve" as const}));l=restart(store,effects)}return l}
function deployAndCanary(id:string,l:BoundedImprovementLoop,store:MemoryImprovementStore,effects:CrashAfterEffect,regressions=0){l.deploy(id,deployAuth(id,l));l=restart(store,effects);l.recordCanary(id,attest("auditor","auditor",{proposalId:id,samples:20,metricImprovement:2,confidenceInterval:[1.2,2.8] as [number,number],guardrailValues:{regressions},evidenceDigest:`canary:${id}`}));return restart(store,effects)}

describe("R28 V3 actual BoundedImprovementLoop dogfood",()=>{
  test("runs accepted, rejected and automatic rollback chains with durable receipts and causal reconstruction",()=>{const store=new MemoryImprovementStore(),effects=new CrashAfterEffect();let l=deployAndCanary("accepted",stage("accepted",store,effects),store,effects);l.evaluate("accepted",attest("evaluator","evaluator",{proposalId:"accepted",metricImprovement:2,confidenceInterval:[1.2,2.8] as [number,number],guardrailsPassed:true,causalClaim:true,analysisDigest:"analysis:accepted"}));expect(restart(store,effects).reconstruct("accepted").workflow.effects.map(e=>[e.kind,e.status])).toEqual([["deploy","acknowledged"],["promote","acknowledged"]]);l=deployAndCanary("rejected",stage("rejected",store,effects),store,effects);l.evaluate("rejected",attest("evaluator","evaluator",{proposalId:"rejected",metricImprovement:.2,confidenceInterval:[-.1,.5] as [number,number],guardrailsPassed:true,causalClaim:true,analysisDigest:"analysis:rejected"}));expect(l.reconstruct("rejected").workflow.phase).toBe("rejected");l=deployAndCanary("rollback",stage("rollback",store,effects),store,effects,1);expect(l.reconstruct("rollback").workflow.phase).toBe("rolled-back");expect(l.current()).toEqual(expect.objectContaining({cumulativeSpend:6,cumulativeChanges:3}));});
  test("recovers external-effect-before-receipt ambiguity by replaying the same idempotency key",()=>{const store=new MemoryImprovementStore(),effects=new CrashAfterEffect(),l=stage("ambiguous",store,effects);effects.crashOnce=true;expect(()=>l.deploy("ambiguous",deployAuth("ambiguous",l))).toThrow("after external effect");const prepared=restart(store,effects).current().workflows.ambiguous!.effects[0]!;expect(prepared.status).toBe("prepared");const recovered=restart(store,effects);recovered.deploy("ambiguous",deployAuth("ambiguous",recovered));expect(effects.calls.at(-1)).toBe(effects.calls.at(-2));expect(restart(store,effects).current().workflows.ambiguous!.effects[0]!.status).toBe("acknowledged");});
  test("enforces forgery, worker, protected-self-modification, scope, authority, spend, operation and experiment bounds",()=>{const s=new MemoryImprovementStore(),e=new CrashAfterEffect(),l=restart(s,e);const bad=worker();bad.workerSignature="forged";expect(()=>l.start("bad",attest("auditor","auditor",bad))).toThrow("compromised");let p=stage("bounds",s,e);const forged=attest("alice","approver",{proposalId:"bounds",proposalDigest:"x",preregistrationDigest:"x",expiresAt:"2099-01-01T00:00:00Z",decision:"approve" as const});forged.signature="forged";expect(()=>p.approve("bounds",forged)).toThrow("attestation invalid");for(const mutation of [{paths:["constitution"]},{scope:"other"},{authority:{repo:2}},{spend:3},{operations:2}]){const ss=new MemoryImprovementStore(),ee=new CrashAfterEffect();let x=restart(ss,ee);x.start("x",attest("auditor","auditor",worker()));x.measure("x",attest("evaluator","evaluator",{metric:"m",baseline:0,unit:"u",horizon:"h",evidenceDigest:x.current().workflows.x!.artifacts.evidence!.digest}));x.updateTwin("x",attest("evaluator","evaluator",{version:"v",replayDigest:"r",calibrated:true,residuals:[]}));expect(()=>x.propose("x",attest("planner","proposer",{patchDigest:"p",paths:["fixtures/x"],scope:"repository.fixture",operations:1,spend:0,authority:{repo:1},expectedMetric:"m",claim:"prediction" as const,...mutation}))).toThrow("bounds")}expect(()=>new BoundedImprovementLoop("bad",{...policy,maximumCanaryFraction:2},trust,new MemoryImprovementStore(),e)).toThrow("policy invalid");});
  test("pause forces safe-state, rolls back deployed work, and rejects subsequent activity",()=>{const s=new MemoryImprovementStore(),e=new CrashAfterEffect();let l=stage("deployed",s,e);l.deploy("deployed",deployAuth("deployed",l));const d=improvementDigest({organization:"open-autonomy-r28-v3",action:"pause",policyDigest:improvementDigest(policy)});l.pause("auditor",mac(key("auditor","auditor"),d));expect(l.current().workflows.deployed!.phase).toBe("rolled-back");expect(l.current().workflows.deployed!.effects.at(-1)!.kind).toBe("rollback");expect(()=>l.start("later",attest("auditor","auditor",worker()))).toThrow("global pause");});
  test("directly witnesses proposal-rate, cumulative resource, and role-separation rejection",()=>{const rs=new MemoryImprovementStore(),re=new CrashAfterEffect(),rate=restart(rs,re);for(let i=0;i<4;i++)rate.start(`rate-${i}`,attest("auditor","auditor",worker()));expect(()=>rate.start("rate-4",attest("auditor","auditor",worker()))).toThrow("rate bound");const s=new MemoryImprovementStore(),e=new CrashAfterEffect();stage("c1",s,e);stage("c2",s,e);stage("c3",s,e);expect(()=>stage("c4",s,e)).toThrow("bounds");expect(()=>new BoundedImprovementLoop("bad-roles",{...policy,roleMembers:{...members,evaluator:["planner"]}},trust,new MemoryImprovementStore(),e)).toThrow("roles not separated");});
});
