import{createHash}from"node:crypto";import{spawnSync}from"node:child_process";import{canonicalSemanticJson as C}from"./organization-canonical";import{verifyU4ImplementationClosure}from"./organization-u4-implementation-closure";
type Sha=`sha256:${string}`;const S="open-autonomy.u4-closure-attestation.v1",H=(x:string|Uint8Array)=>`sha256:${createHash("sha256").update(x).digest("hex")}`as Sha,COMMIT="cf58319d048bbcc64849b85f4f8db57b5afb8f65",CLOSURE_DIGEST="sha256:35fe3c46be2d10a9d2b711f8cac9c6223ecdd5623cdf3d4de3b7cb0fd73811fc",FILES=[
 {kind:"source",path:"packages/core/src/organization-u4-implementation-closure.ts",sha256:"sha256:19135dc15b11ed4ce1e9874046a525b28609da64b49ce19dc12526b94924795d"},
 {kind:"test",path:"packages/core/src/organization-u4-implementation-closure.test.ts",sha256:"sha256:b0aca311ec83de97da922749ee1d56dcb643a8d9c38c8c7dd2c4393433f22970"},
 {kind:"artifact",path:"docs/universality/campaign-v9/u4-implementation-closure.json",sha256:"sha256:1984e37a6a7f26a33ef3448b68680265a3db9b17d1045bdff2417a923392b8c6"}]as const;
const keys=(x:any,k:string[],n:string)=>{if(!x||typeof x!=="object"||Array.isArray(x)||C(Object.keys(x).sort())!==C([...k].sort()))throw Error(`U4 attestation ${n} schema invalid`)},eq=(a:any,b:any,n:string)=>{if(C(a)!==C(b))throw Error(`U4 attestation ${n} invalid`)},cache=new Map<string,any>();function bound(v:any){let n=0,z=0;const active=new Set<any>(),q:any[]=[[v,0]];while(q.length){const[x,exit]=q.pop();if(exit){active.delete(x);continue}if(++n>20000)throw Error("U4 attestation resource bound");if(typeof x==="string"){z+=Buffer.byteLength(x);if(x.length>100000)throw Error("U4 attestation field bound")}else if(x&&typeof x==="object"){if(active.has(x))throw Error("U4 attestation cyclic input");active.add(x);q.push([x,1],...Object.values(x).map(y=>[y,0]))}}if(z>2e6)throw Error("U4 attestation resource bound")}
const freeze=<T>(v:T):T=>{const q:any[]=[v];while(q.length){const x=q.pop();if(x&&typeof x==="object"&&!Object.isFrozen(x)){q.push(...Object.values(x));Object.freeze(x)}}return v};
function committedClosure(root:string){const key=`${root}\0${COMMIT}\0${C(FILES)}`;if(cache.has(key))return cache.get(key);const rev=spawnSync("git",["rev-parse","--verify",`${COMMIT}^{commit}`],{cwd:root,encoding:"utf8"});if(rev.status||typeof rev.stdout!=="string"||rev.stdout.trim()!==COMMIT)throw Error("U4 attestation commit custody invalid");let artifact:Buffer|undefined;for(const f of FILES){const g=spawnSync("git",["show",`${COMMIT}:${f.path}`],{cwd:root});if(g.status||!g.stdout||H(g.stdout)!==f.sha256)throw Error("U4 attestation byte custody invalid");if(f.kind==="artifact")artifact=g.stdout}let parsed:any;try{parsed=JSON.parse(artifact!.toString("utf8"))}catch{throw Error("U4 attestation closure artifact invalid")}const closure=verifyU4ImplementationClosure(parsed,{root});if(closure.digest!==CLOSURE_DIGEST||closure.accounting.dischargedInternal!==24||closure.accounting.pendingAttestationInternal!==1||closure.accounting.openInternal!==0||closure.externalDeferred.length!==10||closure.externalDeferred.some((e:any)=>e.status!=="deferred"||e.dischargedBy.length)||closure.closureClaim||closure.empiricalRegistration||closure.assurancePromotionAllowed)throw Error("U4 attestation closure boundary invalid");cache.set(key,closure);return closure}
export function digestU4ClosureAttestation(v:any){const{digest:_,...b}=v;void _;return H(`${S}\0${C(b)}`)}
export const U4_ATTESTATION_RESOLVED_REJECTION_CLASSES=Object.freeze(["generated round-robin obligation mappings","wrong I/E numbering or semantics","incomplete evidence DAG with missing I18-I25 incoming edges or reachability","generic non-exact E1-E10 requirements","obsolete contradictory legacyDefs registry","semantic-key registry not enforced by verifier","missing direct I6 I17 I18 semantic attack tests","insufficient frontend I24 named evidence","stale commit or blob anchors","expensive Git custody before cheap validation enabling resource amplification","premature localGapIds empty and 25-of-25 discharge before post-commit attestation"] as const);
export function createU4ClosureAttestation({root=process.cwd()}={}){const closure=committedClosure(root),body:any={schema:S,checkpoint:"U4",status:"locally-attested-external-deferred",fixtureKind:"synthetic",empiricalRegistration:false,closureClaim:false,assurancePromotionAllowed:false,closureAnchor:{commit:COMMIT,closureDigest:CLOSURE_DIGEST,files:FILES},closureAccountingBefore:{dischargedInternal:24,pendingAttestationInternal:1,openInternal:0},localAccountingAfter:{dischargedInternal:25,pendingAttestationInternal:0,openInternal:0,totalInternal:25,dischargedObligationId:"U4-I25"},externalDeferred:closure.externalDeferred,skepticalReview:{status:"accepted",reviewedCommit:COMMIT,scope:["semantic I1-I25","E1-E10","evidence DAG","custody","attacks"],priorRejectionClassesResolved:U4_ATTESTATION_RESOLVED_REJECTION_CLASSES,evidenceKind:"synthetic-reviewer-process",externalHumanE6:false},selfCustody:{status:"deferred-to-UG1",reason:"attestation structural code and test are custodied at UG1; no recursive self-attestation"}};return freeze({...body,digest:digestU4ClosureAttestation(body)})}
export function verifyU4ClosureAttestation(v:any,{root=process.cwd()}={}){bound(v);keys(v,["schema","checkpoint","status","fixtureKind","empiricalRegistration","closureClaim","assurancePromotionAllowed","closureAnchor","closureAccountingBefore","localAccountingAfter","externalDeferred","skepticalReview","selfCustody","digest"],"root");const expected=createU4ClosureAttestation({root});eq(v,expected,"exact attestation");if(v.digest!==digestU4ClosureAttestation(v))throw Error("U4 attestation digest invalid");keys(v.closureAnchor,["commit","closureDigest","files"],"closure anchor");keys(v.skepticalReview,["status","reviewedCommit","scope","priorRejectionClassesResolved","evidenceKind","externalHumanE6"],"review");keys(v.localAccountingAfter,["dischargedInternal","pendingAttestationInternal","openInternal","totalInternal","dischargedObligationId"],"accounting");return freeze(structuredClone(v))}
