export type ProcessRole="supervisor"|"launcher"|"hermes"|"tool";
export type LinuxProcessIdentity={pid:number;pgid:number;startTicks:string;bootId:string;role:ProcessRole;parentPid:number|null;containmentId:string};
export type ProcessTreeSupervisorTrace={schema:"autonomy.process-tree-supervisor.v2";assurance:"ordinary-timeout"|"supervisor-death-safe";containment:{kind:"provider-supervised-tree"|"cgroup-v2"|"provider-job";id:string;owner:"provider-supervisor"|"kernel-or-service";killPrimitive:"provider-tree-kill"|"cgroup.kill"|"provider-job-kill";escapePreventionEvidence:string};timeout:{deadlineAt:string;graceMs:number};supervisor:{identity:LinuxProcessIdentity;diedAt:string|null};processes:LinuxProcessIdentity[];groupRelation:"shared"|"separate";observations:Array<{at:string;source:"procfs+provider"|"procfs+cgroup"|"provider-runtime";members:LinuxProcessIdentity[];populated:boolean;evidenceDigest:string}>;signals:Array<{kind:"TERM"|"KILL";at:string;targetContainmentId:string;authority:"provider-supervisor"|"kernel-or-service";evidenceDigest:string}>;terminal:Array<{identity:LinuxProcessIdentity;at:string;kind:"exited"|"signaled";status:number|string;evidenceDigest:string}>;final:{at:string;populated:false;members:[];reap:Array<{identity:LinuxProcessIdentity;proof:"pid-absent"|"pid-start-identity-changed"|"provider-reaped";evidenceDigest:string}>;evidenceDigest:string}};
const dig=(x:string)=>/^sha256:[a-f0-9]{64}$/.test(x),time=(x:string)=>{const n=Date.parse(x);if(!Number.isFinite(n))throw Error("invalid supervisor timestamp");return n},same=(a:LinuxProcessIdentity,b:LinuxProcessIdentity)=>a.pid===b.pid&&a.startTicks===b.startTicks&&a.bootId===b.bootId;
function identity(x:LinuxProcessIdentity,id:string){if(!Number.isSafeInteger(x.pid)||x.pid<1||!Number.isSafeInteger(x.pgid)||x.pgid<1||!/^\d+$/.test(x.startTicks)||!x.bootId||x.containmentId!==id)throw Error("invalid or uncontained process identity")}
export function verifyProcessTreeSupervisorTrace(t:ProcessTreeSupervisorTrace){
  if(t.schema!=="autonomy.process-tree-supervisor.v2"||!t.containment.id||!t.containment.escapePreventionEvidence)throw Error("supervisor envelope invalid");
  const ordinary=t.assurance==="ordinary-timeout",deathSafe=t.assurance==="supervisor-death-safe";
  if(ordinary&&(t.containment.kind!=="provider-supervised-tree"||t.containment.owner!=="provider-supervisor"||t.containment.killPrimitive!=="provider-tree-kill"||t.supervisor.diedAt!==null))throw Error("ordinary timeout requires surviving provider supervisor");
  if(deathSafe&&(t.containment.owner!=="kernel-or-service"||![["cgroup-v2","cgroup.kill"],["provider-job","provider-job-kill"]].some(([k,p])=>t.containment.kind===k&&t.containment.killPrimitive===p)))throw Error("death-safe containment absent");
  if(!ordinary&&!deathSafe)throw Error("unknown assurance profile");
  const deadline=time(t.timeout.deadlineAt);if(!Number.isSafeInteger(t.timeout.graceMs)||t.timeout.graceMs<100||t.timeout.graceMs>60_000)throw Error("invalid TERM grace");
  identity(t.supervisor.identity,t.containment.id);if(t.supervisor.identity.role!=="supervisor")throw Error("supervisor identity role invalid");
  if(t.processes.length<3)throw Error("complete launcher/Hermes/tool tree absent");for(const x of t.processes)identity(x,t.containment.id);
  const roles=new Map(t.processes.map(x=>[x.role,x]));if(roles.size!==3||!roles.get("launcher")||!roles.get("hermes")||!roles.get("tool")||roles.has("supervisor"))throw Error("separate process roles absent");
  const launcher=roles.get("launcher")!,hermes=roles.get("hermes")!,tool=roles.get("tool")!;
  if(new Set([t.supervisor.identity,...t.processes].map(x=>x.pid)).size!==t.processes.length+1||hermes.parentPid!==launcher.pid||tool.parentPid!==hermes.pid)throw Error("process lineage/identity invalid");
  const actualRelation=new Set(t.processes.map(x=>x.pgid)).size===1?"shared":"separate";if(t.groupRelation!==actualRelation)throw Error("PGID relation evidence inconsistent");
  if(!t.observations.some(x=>x.populated&&[launcher,hermes,tool].every(p=>x.members.some(y=>same(y,p)))))throw Error("complete observed descendant evidence absent");
  for(const o of t.observations){time(o.at);if(!dig(o.evidenceDigest))throw Error("observation evidence invalid");for(const x of o.members)identity(x,t.containment.id)}
  const term=t.signals.filter(x=>x.kind==="TERM"),kill=t.signals.filter(x=>x.kind==="KILL");if(term.length!==1||kill.length!==1||[...term,...kill].some(x=>x.targetContainmentId!==t.containment.id||!dig(x.evidenceDigest)))throw Error("containment-wide TERM/KILL sequence incomplete");
  const termAt=time(term[0]!.at),killAt=time(kill[0]!.at);if(termAt<deadline||killAt<termAt+t.timeout.graceMs)throw Error("TERM grace was not honored");
  if(ordinary&&[...term,...kill].some(x=>x.authority!=="provider-supervisor"))throw Error("ordinary provider cleanup authority invalid");
  if(deathSafe&&t.supervisor.diedAt!==null&&(time(t.supervisor.diedAt)>killAt||kill[0]!.authority!=="kernel-or-service"))throw Error("supervisor-death cleanup lacks external authority");
  const terminalIds=new Set<string>();for(const x of t.terminal){identity(x.identity,t.containment.id);if(!dig(x.evidenceDigest)||time(x.at)<termAt)throw Error("terminal evidence invalid");terminalIds.add(`${x.identity.pid}:${x.identity.startTicks}:${x.identity.bootId}`)}if(t.processes.some(x=>!terminalIds.has(`${x.pid}:${x.startTicks}:${x.bootId}`)))throw Error("descendant terminal evidence incomplete");
  if(time(t.final.at)<killAt||t.final.populated!==false||t.final.members.length||!dig(t.final.evidenceDigest)||t.final.reap.length!==t.processes.length)throw Error("containment not proven empty");
  for(const x of t.processes){const r=t.final.reap.find(y=>same(y.identity,x));if(!r||!dig(r.evidenceDigest))throw Error("complete PID-reuse-resistant reap proof absent");if(t.containment.kind==="provider-job"&&r.proof!=="provider-reaped")throw Error("provider containment requires provider reap evidence")}
  return{safe:true as const,assurance:t.assurance,deathSafe:deathSafe as boolean,containedProcesses:t.processes.length,groupRelation:t.groupRelation,finalPopulated:false as const}
}
export function localLinuxContainmentCapabilities(read:(path:string)=>string|undefined){const bootId=read("/proc/sys/kernel/random/boot_id")?.trim()||null,cgroup=read("/sys/fs/cgroup/cgroup.controllers"),cgroupKill=read("/sys/fs/cgroup/cgroup.kill");return{procIdentity:Boolean(bootId),bootId,cgroupV2:Boolean(cgroup),cgroupKill:Boolean(cgroupKill),subreaper:"requires prctl(PR_SET_CHILD_SUBREAPER) native helper",processGroupOnlyDeathSafe:false,nodePidfdSupport:false,ordinaryProviderTreePossible:true,providerObservationRequired:!cgroup||!cgroupKill}}
