import { createHash } from "node:crypto";
import { canonicalSemanticJson as C } from "./organization-canonical";

const SCHEMA = "open-autonomy.universality-checkpoint-implementation-closure.v1", DOMAIN = "open-autonomy.u3-implementation-closure.v2\0";
type Evidence = { validator: string; testFile: string; testName: string; clause: string };
const exact = (x: unknown, keys: string[], at: string) => { if (!x || typeof x !== "object" || Array.isArray(x) || C(Object.keys(x).sort()) !== C([...keys].sort())) throw Error(`U3 closure ${at} schema invalid`); return x as any; }, same = (a: unknown, b: unknown, at: string) => { if (C(a) !== C(b)) throw Error(`U3 closure ${at} invalid`); }, ids = (p: string, n: number) => Array.from({ length: n }, (_, i) => `${p}${i + 1}`), sha = (x: unknown) => typeof x === "string" && /^sha256:[0-9a-f]{64}$/.test(x);
const CALC = "packages/core/src/organization-u3-observation-calculus.test.ts", EVAL = "packages/core/src/organization-u3-observation-evaluator.test.ts", CERT = "packages/core/src/organization-u3-preservation-certificate.test.ts";
const e = (validator: string, testFile: string, testName: string, clause: string): Evidence => ({ validator, testFile, testName, clause });
export const U3_IMPLEMENTATION_ANCHORS = {
  calculus: { sourceCommit: "d00c5190e3284482493328925a88e682404362be", sourcePath: "packages/core/src/organization-u3-observation-calculus.ts", sourceCommittedSha256: "sha256:bb313242dd918e934861a32ec8fd3f28bee59fee31bd79689dea68d20c7f843b", sourceCurrentSha256: "sha256:bb313242dd918e934861a32ec8fd3f28bee59fee31bd79689dea68d20c7f843b", evidenceCommit: "7f328f9314e6fdf6824e699bb80f0020df1154fa", testPath: CALC, testCommittedSha256: "sha256:48f1ac6a6dee36ff36ea761628c215faaaaf8e38c4b4e0bbc552f9819b8f5fcb", testCurrentSha256: "sha256:48f1ac6a6dee36ff36ea761628c215faaaaf8e38c4b4e0bbc552f9819b8f5fcb" },
  evaluator: { sourceCommit: "743e563b3bc63005763d8a66c95e7a7e6faa6a48", sourcePath: "packages/core/src/organization-u3-observation-evaluator.ts", sourceCommittedSha256: "sha256:ee98925853f4fc49b056152cc1bbb5123539234c52bb59421198be7a31a0e86d", sourceCurrentSha256: "sha256:ee98925853f4fc49b056152cc1bbb5123539234c52bb59421198be7a31a0e86d", evidenceCommit: "17f36f111148e056795746a05ad259302ecf658c", testPath: EVAL, testCommittedSha256: "sha256:e6f961ce0928c2be354f82fc0475027cbf6027697afecd301f506dbe5b682ddd", testCurrentSha256: "sha256:e6f961ce0928c2be354f82fc0475027cbf6027697afecd301f506dbe5b682ddd" },
  certificate: { predecessorSourceCommit: "fae0f596c7e005666f99cdc75c1454fd598ef5ba", predecessorSourceSha256: "sha256:e4f3bdfc848cf22fb2b4748c7a8a549cd1eb3d8402c2826eb145352a3df79d62", sourceCommit: "7f328f9314e6fdf6824e699bb80f0020df1154fa", sourcePath: "packages/core/src/organization-u3-preservation-certificate.ts", sourceCommittedSha256: "sha256:a8d828dd61ceda2c5862fdb417af16467c493cffb18dd522c9368a46b41c6e91", sourceCurrentSha256: "sha256:a8d828dd61ceda2c5862fdb417af16467c493cffb18dd522c9368a46b41c6e91", evidenceCommit: "7f328f9314e6fdf6824e699bb80f0020df1154fa", testPath: CERT, testCommittedSha256: "sha256:204a2425c9b021397f96b0dcf285d1f1c9b4e8339f03fd47d3e946b9e26b35d3", testCurrentSha256: "sha256:204a2425c9b021397f96b0dcf285d1f1c9b4e8339f03fd47d3e946b9e26b35d3" },
} as const;
export const U3_EXPECTED_EVIDENCE: Record<string, Evidence[]> = {
  "U3-I1":[e("freezeU3ObservationCalculus",CALC,"purely freezes and verifies independently anchored synthetic L1-L9","canonical calculus fixture has an independent digest"),e("verifyU3PredecessorGitCustody",CALC,"explicit trusted wrapper verifies predecessor Git custody","predecessor bytes and commits are custody checked")],
  "U3-I2":[e("freezeU3ObservationCalculus",CALC,"purely freezes and verifies independently anchored synthetic L1-L9","all registered taxonomy members are fixture covered")],
  "U3-I3":[e("freezeU3ObservationCalculus",CALC,"rejects schema version join","observation schema versions join the registry"),e("freezeU3ObservationCalculus",CALC,"rejects typed endpoint schema version","typed endpoint schema versions join observations"),e("freezeU3ObservationCalculus",CALC,"rejects projection version join","projection input and output versions join schemas"),e("freezeU3ObservationCalculus",CALC,"rejects observation unrelated projection","observation source projections must exist"),e("freezeU3ObservationCalculus",CALC,"rejects comparison unrelated source projection","comparison projections must exist"),e("freezeU3ObservationCalculus",CALC,"rejects isolated right-to-left projection topology reversal","directional endpoint and projection topology is exact")],
  "U3-I4":[e("freezeU3ObservationCalculus",CALC,"isolates excluded applicability evidence and predicate authority","excluded applicability requires evidence and a registered predicate")],
  "U3-I5":[e("freezeU3ObservationCalculus",CALC,"rejects missing root profile","profile ancestry requires a root"),e("freezeU3ObservationCalculus",CALC,"rejects arbitrary profile version","profile versions are semantic versions"),e("freezeU3ObservationCalculus",CALC,"rejects parent major mismatch","child and parent major versions align"),e("freezeU3ObservationCalculus",CALC,"rejects parent lineage mismatch","child and parent lineage identities align"),e("freezeU3ObservationCalculus",CALC,"rejects parent effective loss","children cannot erase inherited effective observations"),e("freezeU3ObservationCalculus",CALC,"rejects pair omission","profile pair coverage is total"),e("freezeU3ObservationCalculus",CALC,"rejects pair orientation lie","profile pair orientation is derived"),e("freezeU3ObservationCalculus",CALC,"rejects unrelated profiles claim equivalence","unrelated profiles cannot claim equivalence")],
  "U3-I6":[e("freezeU3ObservationCalculus",CALC,"rejects isolated right-to-left projection topology reversal","right-to-left algebra cannot reverse typed projection topology")],
  "U3-I7":[e("freezeU3ObservationCalculus",CALC,"isolates metric unit window and aggregation variance dimensions","metric unit window and aggregation are independently attacked")],
  "U3-I8":[e("freezeU3ObservationCalculus",CALC,"rejects mandatory observation loss","mandatory observations cannot be removed"),e("freezeU3ObservationCalculus",CALC,"rejects mandatory forbidden-loss removal","mandatory observations remain forbidden losses")],
  "U3-I9":[e("freezeU3ObservationCalculus",CALC,"isolates cyclic depth UTF-8 and field resource bounds","calculus cycle depth UTF-8 and field bounds reject"),e("evaluateU3ObservationTrace",EVAL,"isolates evaluator cycle depth field and aggregate work bounds","evaluator cycle depth field and aggregate work bounds reject")],
  "U3-I10":[e("freezeU3TraceEvaluationContract",EVAL,"freezes bounded semantic shape registry and verifies calculus Git custody","contract shape and calculus custody are exact"),e("freezeU3TraceEvaluationContract",EVAL,"isolates evaluation contract tool registry schema identity version digest and reachability","adapter compiler and runtime registries enforce record schema identity version digest and exact trace reachability")],
  "U3-I11":[e("evaluateU3ObservationTrace",EVAL,"rejects version, integrity, trust, causal, correlation, surplus custody, cycle, depth, and work attacks","event integrity authority and version attacks reject")],
  "U3-I12":[e("evaluateU3ObservationTrace",EVAL,"rejects forged loss custody, malformed quotients, and consistently re-digested report topology/accounting","evidence provenance and custody forgery rejects")],
  "U3-I13":[e("evaluateU3ObservationTrace",EVAL,"mixed wall/monotonic envelopes evaluate and policy attacks reach their authenticated checks","wall monotonic and causal envelopes are authenticated")],
  "U3-I14":[e("evaluateU3ObservationTrace",EVAL,"E2E emits equivalent, refinement, abstraction, variance, violation, unknown, incompatible, and typed-loss terminals","all eight evaluator terminal classes are reached")],
  "U3-I15":[e("evaluateU3ObservationTrace",EVAL,"rejects typed-loss observation overlap and mandatory-observation loss","loss observation exclusivity and mandatory-loss rejection are isolated"),e("evaluateU3ObservationTrace",EVAL,"E2E emits equivalent, refinement, abstraction, variance, violation, unknown, incompatible, and typed-loss terminals","valid optional typed loss is constructively reached")],
  "U3-I16":[e("verifyU3EvaluationReport",EVAL,"rejects forged loss custody, malformed quotients, and consistently re-digested report topology/accounting","report witness topology and accounting resist redigestion")],
  "U3-I17":[e("verifyU3EvaluationReport",EVAL,"E2E emits equivalent, refinement, abstraction, variance, violation, unknown, incompatible, and typed-loss terminals","report verification independently replays every terminal fixture")],
  "U3-I18":[e("createU3PreservationCertificate",CERT,"creates an exact replay certificate with an independently anchored fixture","certificate fixture binds exact replay inputs and independent digest")],
  "U3-I19":[e("verifyU3PreservationCertificate",CERT,"rejects substitution, re-digest, version skew, surplus, trust, and bounded-resource attacks","certificate substitutions version skew and redigestion reject")],
  "U3-I20":[e("verifyU3PreservationCertificate",CERT,"binds prompt context provider probe model and harness domains without generalization","prompt context provider probe model and harness domains each change the certificate")],
  "U3-I21":[e("composeU3PreservationCertificates",CERT,"composition is deterministic, aligns the intermediate artifact, and conserves relations","typed intermediate endpoint bijection composes non-diagonal paths")],
  "U3-I22":[e("composeU3PreservationCertificates",CERT,"composition rejects artifact substitution, unsupported relation mixing, quotient mismatch, and assumption conflict","domain guarantee mismatch and changed-model discharge reject")],
  "U3-I23":[e("composeU3PreservationCertificates",CERT,"composition rejects artifact substitution, unsupported relation mixing, quotient mismatch, and assumption conflict","mixed direction relation and quotient algebra reject")],
  "U3-I24":[e("composeU3PreservationCertificates",CERT,"variance composition uses typed absolute and relative bound algebra","absolute relative direction and operator variance algebra is tested")],
  "U3-I25":[e("verifyU3ComposedPreservationCertificate",CERT,"composition conserves violated unknown assumptions and outer witnesses","violated unknown incompatible typed-loss assumptions and outer witnesses are not erased"),e("verifyU3ComposedPreservationCertificate",CERT,"composition is deterministic, aligns the intermediate artifact, and conserves relations","composed certificate replay is deterministic")],
};
export const U3_EXTERNAL_REQUIREMENTS = [
  {id:"U3-E1",requirement:"Empirical U1 strata determine the real U3 observation denominator",requires:["verified-u1-population-digest","stratum-membership-custody"]},
  {id:"U3-E2",requirement:"Independent authority freezes mandatory sets and U4 inventory interfaces",requires:["independent-authority-identity","registered-u4-inventory"]},
  {id:"U3-E3",requirement:"Native semantics and projections are externally established",requires:["native-schema-custody","projection-validity-evidence"]},
  {id:"U3-E4",requirement:"Independent experts adjudicate semantic equivalence",requires:["expert-independence","equivalence-adjudications"]},
  {id:"U3-E5",requirement:"Variance and fairness thresholds are externally calibrated",requires:["calibration-population","fairness-authority"]},
  {id:"U3-E6",requirement:"Preservation is run against real baselines",requires:["real-source-baselines","real-lifted-runs"]},
  {id:"U3-E7",requirement:"Identities clocks tool versions and custody are authenticated",requires:["external-trust-roots","authenticated-clock-and-version-receipts"]},
  {id:"U3-E8",requirement:"An independent party replays evaluation and certificates",requires:["independent-replayer","replay-receipts"]},
  {id:"U3-E9",requirement:"Holdout selection predates protected evaluation",requires:["timestamped-holdout-registration","protected-result-chronology"]},
  {id:"U3-E10",requirement:"Claims remain limited to observed prompt context provider probe model and harness domains",requires:["domain-registration","cross-domain-non-generalization-review"]},
] as const;
export const EXPECTED_U3_IMPLEMENTATION_CLOSURE_DIGEST = "sha256:fc70da0f37e45052d736da547047dc3f2da4d73fe17795dcddf6421f03e048cb";
export function digestU3ImplementationClosure(v: Record<string, unknown>) { const {digest:_,...body}=v;void _;return `sha256:${createHash("sha256").update(DOMAIN).update(C(body)).digest("hex")}`; }
export function verifyU3ImplementationClosure(input: unknown) {
  const v=exact(input,["schema","checkpoint","status","scope","claimDigest","implementationAnchors","obligations","externalDeferred","accounting","prohibitedClaims","skepticalReview","downstreamBoundary","nextImplementation","nextExternal","digest"],"root");
  if(v.schema!==SCHEMA||v.checkpoint!=="U3"||v.status!=="implementation-complete-external-validation-deferred"||!sha(v.claimDigest))throw Error("U3 closure identity invalid");
  if(v.scope!=="local U3 observation calculus, authenticated synthetic trace evaluator, preservation certificates, composition algebra, deterministic validators, and adversarial proof machinery only; no empirical U3 result, U3 semantic closure, or UG1 passage is claimed")throw Error("U3 closure scope invalid");
  same(v.implementationAnchors,U3_IMPLEMENTATION_ANCHORS,"anchors");
  if(!Array.isArray(v.obligations)||v.obligations.length!==25)throw Error("U3 closure obligations invalid");same(v.obligations.map((x:any)=>x.id),ids("U3-I",25),"obligation order");
  for(const o0 of v.obligations){const o=exact(o0,["id","claim","evidence"],"obligation");if(typeof o.claim!=="string"||o.claim!==o.claim.trim()||o.claim.length<30)throw Error("U3 closure claim invalid");same(o.evidence,U3_EXPECTED_EVIDENCE[o.id],`evidence ${o.id}`);}
  same(v.externalDeferred,U3_EXTERNAL_REQUIREMENTS,"external requirements");same(v.accounting,{openInternal:0,dischargedInternal:25,deferredExternal:10},"accounting");
  same(v.prohibitedClaims,["a V9 empirical U3 observation population is registered","U3 semantic closure is complete","UG1 has passed","U4 empirical inventories or denominators are frozen"],"prohibited claims");
  const review=exact(v.skepticalReview,["finding","disposition"],"review");if(Object.values(review).some(x=>typeof x!=="string"||!x))throw Error("U3 closure review invalid");
  const d=exact(v.downstreamBoundary,["allowed","forbidden","releaseCondition","prerequisiteIds"],"boundary");same(d.allowed,["U4 interface development","U4 synthetic inventory fixtures","U4 property tests over synthetic fixtures"],"allowed");same(d.forbidden,["U4 empirical inventories","U4 semantic checkpoint closure","publication or reuse of empirical U4 denominators","claiming UG1 passage"],"forbidden");same(d.prerequisiteIds,[...ids("U1-E",4),...ids("U2-E",12),...ids("U3-E",10)],"prerequisites");
  if(d.releaseCondition!=="verified external U1 and U2 population digests plus discharge of every U3-E1 through U3-E10 external obligation"||v.nextImplementation!=="U4"||v.nextExternal!=="U1-E1")throw Error("U3 closure boundary invalid");
  if(v.digest!==EXPECTED_U3_IMPLEMENTATION_CLOSURE_DIGEST||v.digest!==digestU3ImplementationClosure(v))throw Error("U3 closure digest invalid");return v;
}
