import type {AdapterContract,ComponentComposition,ComponentManifestV2,ManifestEvidence,QuantityContract} from './organization-component';
import type {MigrationEdge} from './organization-migrate';
import type {OrganizationIR} from './organization-ir';
import {deriveAtomicObligations,validateDeploymentCandidate,type AssurancePolicy,type DeploymentCandidateV2} from './organization-solver';

export type DeploymentConstraintClass='version'|'region'|'tenant'|'topology'|'cardinality'|'capacity'|'slo'|'data-residency'|'credential'|'upgrade'|'cost'|'adapter'|'migration';
interface BaseConstraint {id:string;manifest?:string;quantifier?:'all'|'any'}
export type DeploymentConstraint=
  | BaseConstraint&{class:'version';allowed:string[]}
  | BaseConstraint&{class:'region'|'tenant'|'data-residency'|'credential'|'upgrade';allowed:string[]}
  | BaseConstraint&{class:'topology';modes?:ComponentManifestV2['topology']['mode'][];isolations?:ComponentManifestV2['topology']['isolation'][]}
  | BaseConstraint&{class:'cardinality';minimum:number;maximum?:number}
  | BaseConstraint&{class:'capacity';unit:string;per?:string;attribution?:string;minimum:number}
  | BaseConstraint&{class:'slo'|'cost';unit:string;per?:string;attribution?:string;maximum:number}
  | BaseConstraint&{class:'adapter';adapter:string;from:string;to:string;obligations:string[];allowLosses?:boolean}
  | BaseConstraint&{class:'migration';kind:MigrationEdge['kind'];from:string;to:string;obligations:string[];allowLossy?:boolean};

export interface DeploymentExtension {regions?:string[];tenants?:string[];dataResidency?:string[];credentials?:string[];upgradeFrom?:string[]}
export interface DeploymentMigration {id:string;kind:MigrationEdge['kind'];from:string;to:string;lossy:boolean;sourcePaths:string[];rollback?:string}
export interface DeploymentFiniteDomain {
  completeness:'finite-exhaustive'|'bounded-heuristic';maxAssignments:number;maxInstancesPerManifest:number;
  constraints:DeploymentConstraint[];allowedAdapters?:string[];migrations?:DeploymentMigration[];preferredManifests?:string[];
}
export interface ConstraintWitness {constraint:string;class:DeploymentConstraintClass;providers:string[];evidence:string[];assumptions:string[];detail:string}
export interface ObjectiveCoordinate {measure:'cost'|'latency'|'capacity';unit:string;per?:string;attribution:string;value:number;uncertainty:QuantityContract['uncertainty'];effectiveAt:string;evidence:string[];assumptions:string[]}
export interface ConstructivePlan {adapters:Array<{constraint:string;adapter:string;from:string;to:string;obligations:string[];losses:string[]}>;migrations:Array<{constraint:string;steps:string[];obligations:string[];lossy:boolean}>}
export interface DeploymentCertificate {domainCardinality:number;explored:number;complete:boolean;constraintWitnesses:ConstraintWitness[];semanticObligations:string[];plan:ConstructivePlan;objective:ObjectiveCoordinate[]}
export interface CertifiedDeploymentCandidate extends DeploymentCandidateV2 {certificate:DeploymentCertificate}
export interface DeploymentSolverResult {
  status:'compatible'|'incompatible'|'exhausted'|'invalid';frontier:CertifiedDeploymentCandidate[];explored:number;domainCardinality:number;complete:boolean;
  unsatisfiedCore:Array<{id:string;class:DeploymentConstraintClass|'semantic' ;reason:string}>;coreMinimality:'subset-minimal'|'classified'|'none';errors:string[];
}

export function solveCertifiedDeployment(organization:OrganizationIR,manifests:Record<string,ComponentManifestV2>,adapters:Record<string,AdapterContract>,policy:AssurancePolicy,domain:DeploymentFiniteDomain):DeploymentSolverResult{
  const inputErrors=validateInputs(manifests,adapters,policy,domain);if(inputErrors.length)return{status:'invalid',frontier:[],explored:0,domainCardinality:0,complete:false,unsatisfiedCore:[],coreMinimality:'none',errors:inputErrors};
  const manifestIds=Object.keys(manifests).sort();const maxima=manifestIds.map(id=>Math.min(domain.maxInstancesPerManifest,manifests[id].topology.maximumInstances??domain.maxInstancesPerManifest));
  const cardinality=maxima.reduce((n,max)=>n*(max+1),1)-1;let explored=0,boundHit=false;const feasible:CertifiedDeploymentCandidate[]=[];
  const counts=new Array(manifestIds.length).fill(0);
  const visit=(index:number)=>{if(boundHit)return;if(index<counts.length){for(let count=0;count<=maxima[index];count++){counts[index]=count;visit(index+1);if(boundHit)return;}return;}if(counts.every(x=>x===0))return;if(explored>=domain.maxAssignments){boundHit=true;return;}explored++;
    const composition=compositionFor(manifestIds,counts,manifests);const checked=checkAssignment(composition,organization,manifests,adapters,policy,domain);if(checked)feasible.push(checked);
  };visit(0);
  const complete=domain.completeness==='finite-exhaustive'&&!boundHit&&explored===cardinality;
  if(feasible.length){for(const item of feasible){item.certificate.domainCardinality=cardinality;item.certificate.explored=explored;item.certificate.complete=complete;}const frontier=paretoFrontier(feasible);return{status:'compatible',frontier,explored,domainCardinality:cardinality,complete,unsatisfiedCore:[],coreMinimality:'none',errors:[]};}
  if(!complete)return{status:'exhausted',frontier:[],explored,domainCardinality:cardinality,complete:false,unsatisfiedCore:[],coreMinimality:'none',errors:['declared finite domain was not exhausted; incompatibility is not established']};
  const core=minimalConstraintCore(domain.constraints,constraints=>hasAssignment(organization,manifests,adapters,policy,{...domain,constraints,maxAssignments:cardinality+1}));
  if(core.length)return{status:'incompatible',frontier:[],explored,domainCardinality:cardinality,complete:true,unsatisfiedCore:core.map(item=>({id:item.id,class:item.class,reason:`no assignment satisfies ${item.class} constraint '${item.id}' within the declared finite domain`})),coreMinimality:'subset-minimal',errors:['finite deployment domain is unsatisfiable']};
  return{status:'incompatible',frontier:[],explored,domainCardinality:cardinality,complete:true,unsatisfiedCore:[{id:'semantic:organization',class:'semantic',reason:'no finite assignment discharges every semantic obligation'}],coreMinimality:'classified',errors:['finite deployment domain is semantically unsatisfiable']};
}

function checkAssignment(composition:ComponentComposition,organization:OrganizationIR,manifests:Record<string,ComponentManifestV2>,adapters:Record<string,AdapterContract>,policy:AssurancePolicy,domain:DeploymentFiniteDomain):CertifiedDeploymentCandidate|undefined{
  const selected=Object.entries(composition.instances).map(([instance,value])=>({instance,manifest:manifests[value.manifest]}));
  for(const {manifest} of selected){const count=selected.filter(x=>x.manifest.id===manifest.id).length;if(count<manifest.topology.minimumInstances)return;for(const required of manifest.requires??[])if(!selected.some(x=>x.manifest.id===required||Object.values(x.manifest.facets).some(f=>f.facet===required)))return;if((manifest.conflictsWith??[]).some(id=>selected.some(x=>x.manifest.id===id)))return;}
  const obligations=deriveAtomicObligations(organization);const obligationIds=new Set(obligations.map(x=>x.id));const witnesses:ConstraintWitness[]=[];const plan:ConstructivePlan={adapters:[],migrations:[]};
  for(const constraint of domain.constraints)if((constraint.class==='adapter'||constraint.class==='migration')&&(!constraint.obligations.length||constraint.obligations.some(id=>!obligationIds.has(id))))return;
  for(const constraint of domain.constraints){const witness=checkConstraint(constraint,selected,adapters,domain,policy,plan,obligations);if(!witness)return;witnesses.push(witness);}
  const semantic=validateDeploymentCandidate(obligations,composition,manifests,adapters,policy,domain.preferredManifests??[]);if(semantic.ledger.unresolved.length)return;for(const item of semantic.ledger.witnesses){const version=item.provider?manifests[composition.instances[item.provider]?.manifest]?.version:item.adapter?adapters[item.adapter]?.version:undefined;if(item.evidence&&(!version||!freshObserved(item.evidence,policy,item.obligation,version)))return;}
  const objective=coordinates(selected.map(x=>x.manifest),policy);if(!objective)return;
  return{...semantic,certificate:{domainCardinality:0,explored:0,complete:false,constraintWitnesses:witnesses,semanticObligations:semantic.ledger.witnesses.filter(x=>!semantic.ledger.unresolved.includes(x.obligation)).map(x=>x.obligation).sort(),plan,objective}};
}

function checkConstraint(constraint:DeploymentConstraint,selected:Array<{instance:string;manifest:ComponentManifestV2}>,adapters:Record<string,AdapterContract>,domain:DeploymentFiniteDomain,policy:AssurancePolicy,plan:ConstructivePlan,obligations:ReturnType<typeof deriveAtomicObligations>):ConstraintWitness|undefined{
  const applicable=constraint.manifest?selected.filter(x=>x.manifest.id===constraint.manifest):selected;if(constraint.manifest&&!applicable.length)return;
  const versions=[...new Set(applicable.map(x=>x.manifest.version))];const evidence=(items:ManifestEvidence[])=>{const accepted:string[]=[];for(const item of items){const verdict=fresh(item,policy,constraint.id,versions);if(!verdict)return;accepted.push(...verdict);}return accepted;};
  if(constraint.class==='adapter'){const adapter=adapters[constraint.adapter];if(!adapter||(domain.allowedAdapters&&!domain.allowedAdapters.includes(adapter.id))||adapter.from.id!==constraint.from||adapter.to.id!==constraint.to||(!constraint.allowLosses&&adapter.losses.length)||!constraint.obligations.every(id=>adapterMapsObligation(adapter,id,obligations)))return;const accepted=fresh(adapter.evidence,policy,constraint.id,[adapter.version]);if(!accepted)return;plan.adapters.push({constraint:constraint.id,adapter:adapter.id,from:adapter.from.id,to:adapter.to.id,obligations:[...constraint.obligations].sort(),losses:[...adapter.losses]});return witness(constraint,[],[adapter.evidence.source?.uri??adapter.id],accepted,'validated endpoint-specific obligation mapping');}
  if(constraint.class==='migration'){const path=migrationPath(domain.migrations??[],constraint.kind,constraint.from,constraint.to,constraint.allowLossy??false);if(!path||!constraint.obligations.every(id=>migrationMapsObligation(path,id,obligations))||path.some(edge=>!edge.lossy&&!edge.rollback))return;plan.migrations.push({constraint:constraint.id,steps:path.map(x=>x.id),obligations:[...constraint.obligations].sort(),lossy:path.some(x=>x.lossy)});return witness(constraint,[],path.map(x=>x.id),[],'validated ordered path-specific reversible migration');}
  if(constraint.class==='cardinality'){const count=applicable.length;if(count<constraint.minimum||(constraint.maximum!==undefined&&count>constraint.maximum))return;return witness(constraint,applicable.map(x=>x.instance),[],[],`cardinality ${count}`);}
  if(constraint.class==='capacity'||constraint.class==='cost'){
    const quantities=applicable.flatMap(({manifest})=>(constraint.class==='cost'?manifest.cost??[]:manifest.capacity??[]).filter(q=>sameDimension(q,constraint)&&q.value!==undefined).map(quantity=>({quantity,version:manifest.version})));if(!quantities.length)return;const total=quantities.reduce((sum,item)=>sum+item.quantity.value!,0);if(constraint.class==='capacity'?total<constraint.minimum:total>constraint.maximum)return;const accepted=evidence(quantities.map(x=>x.quantity.evidence));if(!accepted)return;const quantityAssumptions:string[]=[];for(const item of quantities){const acceptance=quantityFresh(item.quantity,policy,constraint.id,item.version);if(!acceptance)return;quantityAssumptions.push(...acceptance);}return witness(constraint,applicable.map(x=>x.instance),quantities.map(x=>x.quantity.evidence.source?.uri??'inline'),[...accepted,...quantityAssumptions].sort(),`${constraint.class} aggregate ${total} ${constraint.unit}${constraint.per?`/${constraint.per}`:''}`);
  }
  const matching=applicable.filter(({manifest})=>{
    const ext=(manifest.extensions?.deployment??{}) as DeploymentExtension;
    if(constraint.class==='version')return constraint.allowed.includes(manifest.version);
    if(constraint.class==='region')return intersects(ext.regions,constraint.allowed);
    if(constraint.class==='tenant')return intersects(ext.tenants,constraint.allowed);
    if(constraint.class==='data-residency')return intersects(ext.dataResidency,constraint.allowed);
    if(constraint.class==='credential')return intersects(ext.credentials,constraint.allowed);
    if(constraint.class==='upgrade')return intersects(ext.upgradeFrom,constraint.allowed)&&Boolean(manifest.failure.upgrade&&manifest.failure.rollback);
    if(constraint.class==='topology')return(!constraint.modes||constraint.modes.includes(manifest.topology.mode))&&(!constraint.isolations||constraint.isolations.includes(manifest.topology.isolation));
    if(constraint.class!=='slo')return false;const values=(manifest.capacity??[]).filter(q=>sameDimension(q,constraint)&&q.value!==undefined);return values.length>0&&values.every(q=>q.value!<=constraint.maximum);
  });const requireAll=constraint.quantifier!=='any'&&constraint.class!=='credential';if(requireAll?matching.length!==applicable.length:!matching.length)return;
  const evidenceItems=matching.flatMap(({manifest})=>constraint.class==='topology'?[manifest.topology.evidence]:constraint.class==='upgrade'?[manifest.failure.evidence]:constraint.class==='slo'?(manifest.capacity??[]).filter(q=>sameDimension(q,constraint)).map(q=>q.evidence):Object.values(manifest.facets).map(x=>x.evidence));
  const accepted=evidence(evidenceItems);if(!accepted)return;if(constraint.class==='slo')for(const {manifest} of matching)for(const quantity of (manifest.capacity??[]).filter(q=>sameDimension(q,constraint))){const acceptance=quantityFresh(quantity,policy,constraint.id,manifest.version);if(!acceptance)return;accepted.push(...acceptance);}return witness(constraint,matching.map(x=>x.instance),evidenceItems.map(x=>x.source?.uri??'inline'),[...accepted].sort(),'hard constraint satisfied');
}

function compositionFor(ids:string[],counts:number[],manifests:Record<string,ComponentManifestV2>):ComponentComposition{const instances:ComponentComposition['instances']={};for(let i=0;i<ids.length;i++)for(let n=0;n<counts[i];n++)instances[`${ids[i]}#${n}`]={manifest:ids[i]};const authorities:Record<string,string>={};for(const state of [...new Set(Object.values(instances).flatMap(x=>manifests[x.manifest].state.filter(s=>s.authority==='authoritative').map(s=>s.state)))]){const owners=Object.keys(instances).filter(id=>manifests[instances[id].manifest].state.some(s=>s.state===state&&s.authority==='authoritative'));if(owners.length===1)authorities[state]=owners[0];}return{instances,authorities};}
function coordinates(manifests:ComponentManifestV2[],policy:AssurancePolicy):ObjectiveCoordinate[]{const groups=new Map<string,ObjectiveCoordinate>();for(const manifest of manifests)for(const [measure,items] of [['cost',manifest.cost??[]],['capacity',manifest.capacity??[]]] as const)for(const item of items){if(item.value===undefined||!Number.isFinite(item.value))continue;const scope=`objective:${manifest.id}:${measure}:${item.unit}`,evidenceAcceptance=fresh(item.evidence,policy,scope,[manifest.version]),quantityAcceptance=quantityFresh(item,policy,scope,manifest.version);if(!evidenceAcceptance||!quantityAcceptance)continue;const key=`${measure}|${item.unit}|${item.per??''}|${item.attribution}`;const prior=groups.get(key),evidence=item.evidence.source?.digest??item.evidence.source?.uri;if(!evidence)continue;groups.set(key,{measure:measure==='cost'?'cost':item.unit==='latency-ms'?'latency':'capacity',unit:item.unit,per:item.per,attribution:item.attribution,value:(prior?.value??0)+item.value,uncertainty:worse(prior?.uncertainty??'exact',item.uncertainty),effectiveAt:prior&&prior.effectiveAt<item.effectiveAt!?prior.effectiveAt:item.effectiveAt!,evidence:[...new Set([...(prior?.evidence??[]),evidence])].sort(),assumptions:[...new Set([...(prior?.assumptions??[]),...evidenceAcceptance,...quantityAcceptance])].sort()});}return[...groups.values()].sort((a,b)=>dimensionKey(a).localeCompare(dimensionKey(b)));}
function paretoFrontier(values:CertifiedDeploymentCandidate[]){const nondominated=values.filter((candidate,index)=>!values.some((other,j)=>j!==index&&dominates(other.certificate.objective,candidate.certificate.objective)));return nondominated.sort((a,b)=>a.objective.key.localeCompare(b.objective.key));}
function dominates(a:ObjectiveCoordinate[],b:ObjectiveCoordinate[]){if(a.length!==b.length||a.some((x,i)=>dimensionKey(x)!==dimensionKey(b[i])||x.uncertainty!=='exact'||b[i].uncertainty!=='exact'))return false;let strict=false;for(let i=0;i<a.length;i++){const av=a[i].measure==='capacity'?-a[i].value:a[i].value,bv=b[i].measure==='capacity'?-b[i].value:b[i].value;if(av>bv)return false;if(av<bv)strict=true;}return strict;}
function minimalConstraintCore(constraints:DeploymentConstraint[],sat:(constraints:DeploymentConstraint[])=>boolean){if(!constraints.length||sat(constraints))return[];let core=[...constraints];for(const item of [...core]){const reduced=core.filter(x=>x!==item);if(!sat(reduced))core=reduced;}return core;}
function hasAssignment(org:OrganizationIR,manifests:Record<string,ComponentManifestV2>,adapters:Record<string,AdapterContract>,policy:AssurancePolicy,domain:DeploymentFiniteDomain){const ids=Object.keys(manifests).sort(),counts=new Array(ids.length).fill(0),maxima=ids.map(id=>Math.min(domain.maxInstancesPerManifest,manifests[id].topology.maximumInstances??domain.maxInstancesPerManifest));let found=false,seen=0;const visit=(i:number)=>{if(found||seen>=domain.maxAssignments)return;if(i<ids.length){for(let n=0;n<=maxima[i];n++){counts[i]=n;visit(i+1);}return;}if(counts.every(x=>x===0))return;seen++;found=Boolean(checkAssignment(compositionFor(ids,counts,manifests),org,manifests,adapters,policy,domain));};visit(0);return found;}
function migrationPath(edges:DeploymentMigration[],kind:MigrationEdge['kind'],from:string,to:string,allowLossy:boolean){const queue:Array<{at:string;path:DeploymentMigration[]}>= [{at:from,path:[]}],seen=new Set([from]);while(queue.length){const current=queue.shift()!;if(current.at===to)return current.path;for(const edge of edges.filter(x=>x.kind===kind&&x.from===current.at&&!seen.has(x.to)&&(!x.lossy||allowLossy)).sort((a,b)=>a.id.localeCompare(b.id))){seen.add(edge.to);queue.push({at:edge.to,path:[...current.path,edge]});}}}
function adapterMapsObligation(adapter:AdapterContract,id:string,obligations:ReturnType<typeof deriveAtomicObligations>){const obligation=obligations.find(x=>x.id===id);return Boolean(obligation&&adapter.interfaceMappings.some(x=>x.to===obligation.facet||x.to===`${obligation.facet}.${obligation.operation}`));}
function migrationMapsObligation(path:DeploymentMigration[],id:string,obligations:ReturnType<typeof deriveAtomicObligations>){const obligation=obligations.find(x=>x.id===id);return Boolean(obligation&&path.every(edge=>edge.sourcePaths.some(source=>obligation.path===source||obligation.path.startsWith(`${source}.`))));}
function fresh(evidence:ManifestEvidence,policy:AssurancePolicy,scope:string,versions:string[]=[]):string[]|undefined{if(evidence.assurance==='unknown')return;if(evidence.assurance==='asserted'){const assumption=`evidence:${scope}:asserted`;const item=policy.acceptedAssumptions.find(x=>x.assumption===assumption&&(x.scope==='*'||x.scope===scope)&&validAcceptance(x,policy,versions));return item?[`${item.acceptedBy}:${assumption}`]:undefined;}const maxAge=policy.maxEvidenceAgeMs;if(maxAge!==undefined){if(!policy.asOf||!evidence.observedAt)return;const age=Date.parse(policy.asOf)-Date.parse(evidence.observedAt);if(!Number.isFinite(age)||age<0||age>maxAge){const assumption=`evidence:${scope}:stale`;const item=policy.acceptedAssumptions.find(x=>x.assumption===assumption&&(x.scope==='*'||x.scope===scope)&&validAcceptance(x,policy,versions));return item?[`${item.acceptedBy}:${assumption}`]:undefined;}}return[];}
function validAcceptance(item:AssurancePolicy['acceptedAssumptions'][number],policy:AssurancePolicy,versions:string[]=[]){if(!item.acceptedBy||!policy.asOf)return false;const asOf=Date.parse(policy.asOf);if(!Number.isFinite(asOf))return false;if(item.expires){const expires=Date.parse(item.expires);if(!Number.isFinite(expires)||expires<asOf)return false;}if(item.untilVersion&&(!versions.length||versions.some(version=>item.untilVersion!==version)))return false;return true;}
function freshObserved(evidence:ManifestEvidence,policy:AssurancePolicy,scope:string,version:string){if(policy.maxEvidenceAgeMs===undefined)return true;if(!policy.asOf||!evidence.observedAt)return false;const age=Date.parse(policy.asOf)-Date.parse(evidence.observedAt);if(Number.isFinite(age)&&age>=0&&age<=policy.maxEvidenceAgeMs)return true;return policy.acceptedAssumptions.some(item=>item.assumption===`evidence:${scope}:stale`&&(item.scope==='*'||item.scope===scope)&&validAcceptance(item,policy,[version]));}
function quantityFresh(item:QuantityContract,policy:AssurancePolicy,scope:string,version:string):string[]|undefined{if(!policy.asOf||!item.effectiveAt)return;const age=Date.parse(policy.asOf)-Date.parse(item.effectiveAt);if(Number.isFinite(age)&&age>=0&&policy.maxEvidenceAgeMs!==undefined&&age<=policy.maxEvidenceAgeMs)return[];const assumption=`quantity:${scope}:stale`,entry=policy.acceptedAssumptions.find(x=>x.assumption===assumption&&(x.scope==='*'||x.scope===scope)&&validAcceptance(x,policy,[version]));return entry?[`${entry.acceptedBy}:${assumption}`]:undefined;}
function validateInputs(manifests:Record<string,ComponentManifestV2>,adapters:Record<string,AdapterContract>,policy:AssurancePolicy,domain:DeploymentFiniteDomain){const errors:string[]=[];if(!Number.isSafeInteger(domain.maxAssignments)||domain.maxAssignments<0)errors.push('maxAssignments must be a nonnegative safe integer');if(!Number.isSafeInteger(domain.maxInstancesPerManifest)||domain.maxInstancesPerManifest<1)errors.push('maxInstancesPerManifest must be a positive safe integer');if(new Set(domain.constraints.map(x=>x.id)).size!==domain.constraints.length)errors.push('constraint ids must be unique');if(!policy.asOf||!Number.isFinite(Date.parse(policy.asOf)))errors.push('assurance policy requires a valid asOf clock');if(!Number.isSafeInteger(policy.maxEvidenceAgeMs)||policy.maxEvidenceAgeMs!<0)errors.push('maxEvidenceAgeMs must be a nonnegative safe integer');let cardinality=1;for(const manifest of Object.values(manifests)){const maximum=Math.min(domain.maxInstancesPerManifest,manifest.topology.maximumInstances??domain.maxInstancesPerManifest);cardinality*=maximum+1;}if(!Number.isSafeInteger(cardinality-1))errors.push('declared finite domain cardinality exceeds safe integer range');for(const [id,manifest] of Object.entries(manifests))for(const q of [...manifest.cost??[],...manifest.capacity??[]])if(q.value!==undefined&&(!Number.isFinite(q.value)||q.value<0))errors.push(`manifest '${id}' has invalid quantity`);for(const id of domain.allowedAdapters??[])if(!adapters[id])errors.push(`allowed adapter '${id}' is absent`);return errors;}
function witness(c:DeploymentConstraint,providers:string[],evidence:string[],assumptions:string[],detail:string):ConstraintWitness{return{constraint:c.id,class:c.class,providers,evidence,assumptions,detail};}
function intersects(values:string[]|undefined,allowed:string[]){return Boolean(values?.some(x=>allowed.includes(x)));}
function sameDimension(q:QuantityContract,c:{unit:string;per?:string;attribution?:string}){return q.unit===c.unit&&q.per===c.per&&(!c.attribution||q.attribution===c.attribution);}
function dimensionKey(x:ObjectiveCoordinate){return`${x.measure}|${x.unit}|${x.per??''}|${x.attribution}`;}
function worse(a:QuantityContract['uncertainty'],b:QuantityContract['uncertainty']){const order:QuantityContract['uncertainty'][]=['exact','bounded','estimated','volatile','unknown'];return order[Math.max(order.indexOf(a),order.indexOf(b))];}
