import { createHash } from "node:crypto";
import {
  canonicalU1AcceptedResponseId, canonicalU1RequestKey, canonicalU1RequestUrl,
  canonicalU1TailRequestKey, canonicalU1TailRequestUrl, validateU1CapturedResponse,
  validateU1TerminalReplay, verifySourceCensusOccurrenceContract,
  normalizeGithubRepositoryName,
  type FrozenSourceCensusOccurrenceContract, type U1AcceptedRequest, type U1AttemptHistory,
  type U1CompletePass, type U1Occurrence, type U1TerminalReplay, type ValidatedU1TerminalReplay,
} from "./organization-universality-occurrence-contract";

export type CaptureQuery={attemptId:string;attemptNumber:number;completePassOrdinal:1|2;requestPosition:number;parentRequestPosition:number|null;kind:"tail-probe"|"range";url:string;requestKey:string;queryStars:[number,number];queryCreated:[string,string]|null};
export type ProviderResponse={status:number;headers:Record<string,string>;bodyBytes:Uint8Array;startedAt:string;observedAt:string;transportEvidence?:string};
export type AcceptedRequestProvider=(query:CaptureQuery)=>Promise<ProviderResponse>;
export type CaptureClock={now():string;peek?():string;waitUntil(epochSeconds:number):Promise<void>};
export type CaptureFailureCode="transport-failure"|"non-rate-limit-non-200"|"malformed-response-schema"|"incomplete-results-true"|"terminal-item-ineligible-or-created-outside-query"|"accepted-response-at-or-after-cutoff"|"unpartitionable-overflow-leaf"|"maximum-attempts-exhausted"|"rate-limit-wait-failed";
export class U1CaptureError extends Error{constructor(readonly code:CaptureFailureCode,message:string,readonly partial?:AttemptPartial,options?:ErrorOptions){super(message,options)}}
export type FailedCustody={attemptId:string;attemptNumber:number;request:CaptureQuery|null;code:CaptureFailureCode|"rate-limit-wait";evidence:string;response?:{status:number;headers:Record<string,string>;bodyBase64:string;startedAt:string;observedAt:string};transportReceipt?:TransportReceipt};
export type CaptureCampaignResult={replay:ValidatedU1TerminalReplay;failedCustody:FailedCustody[]};
export const CAPTURE_EXHAUSTION_INVALIDATION="four-total-attempts-with-fewer-than-two-complete-passes" as const;
export type CaptureInvalidationReason=Exclude<CaptureFailureCode,"maximum-attempts-exhausted">|typeof CAPTURE_EXHAUSTION_INVALIDATION|"final-validator-node-id-alias"|"final-validator-rejection";
export type CaptureCampaignCustody={reason:CaptureInvalidationReason;attempts:U1AttemptHistory[];completePasses:U1CompletePass[];acceptedRequests:U1AcceptedRequest[];occurrences:U1Occurrence[];failedCustody:FailedCustody[]};
export class CaptureCampaignInvalidation extends Error{constructor(readonly custody:CaptureCampaignCustody,options?:ErrorOptions){super(`U1 capture campaign invalid: ${custody.reason}`,options)}}
export type TransportReceipt={endpoint:string;startedAt:string;endedAt:string;errorClassification:string};
export class CaptureTransportError extends Error{constructor(readonly receipt:TransportReceipt,options?:ErrorOptions){super(`transport failure: ${receipt.errorClassification}`,options)}}
type AttemptPartial={requests:U1AcceptedRequest[];occurrences:U1Occurrence[];failedCustody:FailedCustody[]};
type CompleteCapture=AttemptPartial&{pass:U1CompletePass};
const sha=(x:Uint8Array)=>`sha256:${createHash("sha256").update(x).digest("hex")}`as const,b64=(x:Uint8Array)=>Buffer.from(x).toString("base64");
const midpoint=(lo:string,hi:string)=>new Date(Date.parse(`${lo}T00:00:00.000Z`)+Math.floor((Date.parse(`${hi}T00:00:00.000Z`)-Date.parse(`${lo}T00:00:00.000Z`))/172800000)*86400000).toISOString().slice(0,10);
const nextDay=(x:string)=>new Date(Date.parse(`${x}T00:00:00.000Z`)+86400000).toISOString().slice(0,10);
const exactUtc=(x:string)=>/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(x)&&new Date(x).toISOString()===x;
const retryable=new Set<CaptureFailureCode>(["transport-failure","non-rate-limit-non-200","malformed-response-schema","incomplete-results-true","terminal-item-ineligible-or-created-outside-query"]);
const itemToReturned=(x:any)=>({repository:x.full_name,stars:x.stargazers_count,defaultBranch:x.default_branch,license:x.license?.spdx_id??null,fork:x.fork,archived:x.archived,createdAt:x.created_at,description:x.description,topics:[...x.topics],htmlUrl:x.html_url});

async function captureAttempt(contract:FrozenSourceCensusOccurrenceContract,provider:AcceptedRequestProvider,clock:CaptureClock,attemptId:string,attemptNumber:number,ordinal:1|2,startedAt:string):Promise<CompleteCapture>{
  const requests:U1AcceptedRequest[]=[],occurrences:U1Occurrence[]=[],failedCustody:FailedCustody[]=[];let position=0,previous:string|null=null;
  const fail=(code:CaptureFailureCode,message:string,request:CaptureQuery|null,evidence:string,response?:ProviderResponse,transportReceipt?:TransportReceipt):never=>{const custody:FailedCustody={attemptId,attemptNumber,request,code,evidence,...response?{response:{status:response.status,headers:structuredClone(response.headers),bodyBase64:b64(response.bodyBytes),startedAt:response.startedAt,observedAt:response.observedAt}}:{},...transportReceipt?{transportReceipt}:{}};failedCustody.push(custody);throw new U1CaptureError(code,message,{requests,occurrences,failedCustody})};
  const accept=async(kind:CaptureQuery["kind"],stars:[number,number],created:[string,string]|null,parent:number|null)=>{
    const requestPosition=position++,tail=kind==="tail-probe",url=tail?canonicalU1TailRequestUrl(stars[0]):canonicalU1RequestUrl(stars,created),requestKey=tail?canonicalU1TailRequestKey(stars[0]):canonicalU1RequestKey(stars,created),query:CaptureQuery={attemptId,attemptNumber,completePassOrdinal:ordinal,requestPosition,parentRequestPosition:parent,kind,url,requestKey,queryStars:stars,queryCreated:created};
    let response!:ProviderResponse;const readClock=()=>clock.peek?.()??clock.now();
    const validateResponseTime=(candidate:ProviderResponse)=>{if(!exactUtc(candidate.startedAt)||!exactUtc(candidate.observedAt)||candidate.startedAt>candidate.observedAt||(previous!==null&&previous>candidate.startedAt))fail("malformed-response-schema","invalid response chronology",query,"chronology",candidate);if(candidate.observedAt>=contract.censusCutoff)fail("accepted-response-at-or-after-cutoff","response reached census cutoff",query,"cutoff",candidate)};
    while(true){const loopNow=readClock();if(!exactUtc(loopNow)||loopNow>=contract.censusCutoff)fail("accepted-response-at-or-after-cutoff","provider loop reached census cutoff",query,"provider-loop-cutoff");try{response=await provider(query)}catch(cause){if(cause instanceof CaptureTransportError){const receipt=cause.receipt,valid=receipt.endpoint===query.url&&exactUtc(receipt.startedAt)&&exactUtc(receipt.endedAt)&&receipt.startedAt<=receipt.endedAt&&receipt.startedAt>=startedAt&&receipt.endedAt<contract.censusCutoff&&(previous===null||previous<=receipt.startedAt);fail("transport-failure","provider transport failure",query,valid?receipt.errorClassification:"invalid-transport-receipt",undefined,valid?receipt:undefined)}fail("transport-failure","provider transport failure",query,"unauthenticated-test-provider-error")}
      validateResponseTime(response);if(response.status===403&&/^\d+$/.test(response.headers["x-ratelimit-reset"]??"")){const reset=Number(response.headers["x-ratelimit-reset"]),now=readClock(),cutoff=Math.floor(Date.parse(contract.censusCutoff)/1000);if(!Number.isSafeInteger(reset)||!exactUtc(now)||reset<=Math.floor(Date.parse(now)/1000)||reset>=cutoff||now>=contract.censusCutoff)fail("accepted-response-at-or-after-cutoff","rate-limit reset invalid or reaches cutoff",query,"rate-limit-cutoff",response);failedCustody.push({attemptId,attemptNumber,request:query,code:"rate-limit-wait",evidence:"valid-x-ratelimit-reset",response:{status:response.status,headers:structuredClone(response.headers),bodyBase64:b64(response.bodyBytes),startedAt:response.startedAt,observedAt:response.observedAt}});try{await clock.waitUntil(reset)}catch(cause){fail("rate-limit-wait-failed","rate-limit wait rejected",query,"rate-limit-wait-rejected")}const afterWait=readClock();if(!exactUtc(afterWait)||afterWait>=contract.censusCutoff)fail("accepted-response-at-or-after-cutoff","rate-limit wait reached census cutoff",query,"provider-loop-cutoff");continue}break}
    if(response.status!==200)fail("non-rate-limit-non-200",`HTTP ${response.status}`,query,"http-status",response);
    let raw:any;try{raw=JSON.parse(Buffer.from(response.bodyBytes).toString("utf8"))}catch{fail("malformed-response-schema","response JSON invalid",query,"json",response)}
    if(raw?.incomplete_results===true)fail("incomplete-results-true","GitHub marked response incomplete",query,"incomplete_results",response);
    const sidecarBytes=Buffer.from(JSON.stringify({url,startedAt:response.startedAt,observedAt:response.observedAt,status:response.status,headers:response.headers,bodyDigest:sha(response.bodyBytes)}));
    let parsed!:ReturnType<typeof validateU1CapturedResponse>;try{parsed=validateU1CapturedResponse(sidecarBytes,response.bodyBytes)}catch(cause){fail("malformed-response-schema","accepted response schema invalid",query,String(cause),response)}
    const bodyDigest=sha(response.bodyBytes),sidecarDigest=sha(sidecarBytes),requestDigest=sha(Buffer.from(url));previous=response.observedAt;
    const request:U1AcceptedRequest={schema:"open-autonomy.source-census-terminal-request.v1",kind:tail?"tail-probe":parsed.body.total_count<=100?"terminal-range":"nonterminal-range",attemptId,attemptNumber,completePassOrdinal:ordinal,requestPosition,parentRequestPosition:parent,startedAt:response.startedAt,observedAt:response.observedAt,requestKey,sidecarBase64:b64(sidecarBytes),responseBodyBase64:b64(response.bodyBytes),requestDigest,responseBodyDigest:bodyDigest,sidecarDigest,acceptedResponseId:canonicalU1AcceptedResponseId(requestDigest,bodyDigest,sidecarDigest,response.observedAt),queryStars:[...stars],queryCreated:created?[...created]:null,fixedQuery:{fork:true,perPage:100,page:1,sort:"stars",order:"desc"},totalCount:parsed.body.total_count,custody:{encoding:"base64",sidecar:"exact-captured-sidecar-json-bytes",responseBody:"exact-uncompressed-response-body-bytes"}};requests.push(request);return{request,body:parsed.body};
  };
  let upper=2000;while(true){const x=await accept("tail-probe",[upper,Number.MAX_SAFE_INTEGER],null,null);if(x.body.total_count===0)break;upper*=2;if(!Number.isSafeInteger(upper))fail("malformed-response-schema","tail threshold overflow",null,"safe-integer")}
  const visit=async(stars:[number,number],created:[string,string]|null,parent:number|null):Promise<void>=>{const{request,body}=await accept("range",stars,created,parent);if(body.total_count<=100){for(const[itemPosition,item]of body.items.entries()){if(item.stargazers_count<contract.adoption.threshold||(created&&(item.created_at.slice(0,10)<created[0]||item.created_at.slice(0,10)>created[1])))fail("terminal-item-ineligible-or-created-outside-query","terminal item violates global eligibility or creation range",request as any,"terminal-containment");occurrences.push({schema:"open-autonomy.source-census-terminal-occurrence.v1",attemptId,completePassOrdinal:ordinal,requestPosition:request.requestPosition,itemPosition,requestKey:request.requestKey,requestDigest:request.requestDigest,responseDigest:request.responseBodyDigest,nodeId:item.node_id,observedAt:request.observedAt,queryStars:[...stars],queryCreated:created?[...created]:null,returned:itemToReturned(item)})}return}if(stars[0]<stars[1]){const mid=Math.floor((stars[0]+stars[1])/2);await visit([stars[0],mid],created,request.requestPosition);await visit([mid+1,stars[1]],created,request.requestPosition);return}const lo=created?.[0]??contract.enumeration.overflowPartition.lowerBound,hi=created?.[1]??startedAt.slice(0,10);if(lo===hi)fail("unpartitionable-overflow-leaf","single day overflow",request as any,"overflow");const mid=midpoint(lo,hi);await visit(stars,[lo,mid],request.requestPosition);await visit(stars,[nextDay(mid),hi],request.requestPosition)};
  await visit([contract.adoption.threshold,upper-1],null,null);const completedAt=clock.now();if(!exactUtc(completedAt)||completedAt<previous!||completedAt>=contract.censusCutoff)fail("accepted-response-at-or-after-cutoff","invalid completion time",null,"completion-clock");
  return{requests,occurrences,failedCustody,pass:{schema:"open-autonomy.source-census-complete-pass.v1",attemptId,attemptNumber,completePassOrdinal:ordinal,startedAt,completedAt,requestCount:requests.length,occurrenceCount:occurrences.length,frameFrozenAt:ordinal===2?completedAt:null}};
}

export async function captureU1Campaign(contractInput:FrozenSourceCensusOccurrenceContract,provider:AcceptedRequestProvider,clock:CaptureClock):Promise<CaptureCampaignResult>{
  const contract=verifySourceCensusOccurrenceContract(contractInput),attempts:U1AttemptHistory[]=[],complete:CompleteCapture[]=[],failedCustody:FailedCustody[]=[],abandonedRequests:U1AcceptedRequest[]=[],abandonedOccurrences:U1Occurrence[]=[];
  const invalidate=(reason:CaptureInvalidationReason,cause?:unknown):never=>{const sortedAttempts=[...attempts].sort((a,b)=>a.attemptNumber-b.attemptNumber),attemptById=new Map(sortedAttempts.map(a=>[a.attemptId,a.attemptNumber])),sortedPasses=complete.map(x=>x.pass).sort((a,b)=>a.completePassOrdinal-b.completePassOrdinal),sortedRequests=[...complete.flatMap(x=>x.requests),...abandonedRequests].sort((a,b)=>a.attemptNumber-b.attemptNumber||a.requestPosition-b.requestPosition),sortedOccurrences=[...complete.flatMap(x=>x.occurrences),...abandonedOccurrences].sort((a,b)=>(attemptById.get(a.attemptId)??Number.MAX_SAFE_INTEGER)-(attemptById.get(b.attemptId)??Number.MAX_SAFE_INTEGER)||a.requestPosition-b.requestPosition||a.itemPosition-b.itemPosition);throw new CaptureCampaignInvalidation({reason,attempts:structuredClone(sortedAttempts),completePasses:structuredClone(sortedPasses),acceptedRequests:structuredClone(sortedRequests),occurrences:structuredClone(sortedOccurrences),failedCustody:structuredClone(failedCustody)},{cause})};
  for(let attemptNumber=1;attemptNumber<=contract.completion.pass.maximumTotalAttempts&&complete.length<2;attemptNumber++){
    const attemptId=`attempt-${attemptNumber}`,startedAt=clock.now();
    if(!exactUtc(startedAt)||startedAt>=contract.censusCutoff||(attempts.length>0&&attempts.at(-1)!.endedAt>startedAt))invalidate("accepted-response-at-or-after-cutoff");
    try{const captured=await captureAttempt(contract,provider,clock,attemptId,attemptNumber,(complete.length+1)as 1|2,startedAt);complete.push(captured);attempts.push({schema:"open-autonomy.source-census-attempt-history.v1",attemptId,attemptNumber,startedAt,endedAt:captured.pass.completedAt,status:"complete",failure:null});failedCustody.push(...captured.failedCustody)}
    catch(cause){if(!(cause instanceof U1CaptureError))throw cause;failedCustody.push(...(cause.partial?.failedCustody??[]));abandonedRequests.push(...(cause.partial?.requests??[]));abandonedOccurrences.push(...(cause.partial?.occurrences??[]));const last=failedCustody.at(-1),rawRecheckedAt=clock.now(),recheckedAt=exactUtc(rawRecheckedAt)&&rawRecheckedAt>=startedAt&&rawRecheckedAt<contract.censusCutoff?rawRecheckedAt:startedAt,rawEndedAt=last?.response?.observedAt??last?.transportReceipt?.endedAt??recheckedAt,endedAt=exactUtc(rawEndedAt)&&rawEndedAt>=startedAt&&rawEndedAt<=recheckedAt?rawEndedAt:recheckedAt;attempts.push({schema:"open-autonomy.source-census-attempt-history.v1",attemptId,attemptNumber,startedAt,endedAt,status:"failed",failure:cause.code as any});if(!retryable.has(cause.code))invalidate(cause.code==="maximum-attempts-exhausted"?CAPTURE_EXHAUSTION_INVALIDATION:cause.code,cause)}
  }
  if(complete.length!==2)invalidate(CAPTURE_EXHAUSTION_INVALIDATION);
  const replay:U1TerminalReplay={schema:"open-autonomy.source-census-terminal-replay.v1",attempts,passes:complete.map(x=>x.pass),requests:complete.flatMap(x=>x.requests),occurrences:complete.flatMap(x=>x.occurrences)};
  try{const nodeByName=new Map<string,string>();for(const occurrence of replay.occurrences){const name=normalizeGithubRepositoryName(occurrence.returned.repository),prior=nodeByName.get(name);if(prior!==undefined&&prior!==occurrence.nodeId)invalidate("final-validator-node-id-alias");nodeByName.set(name,occurrence.nodeId)}return{replay:validateU1TerminalReplay(contract,replay),failedCustody}}
  catch(cause){if(cause instanceof CaptureCampaignInvalidation)throw cause;invalidate("final-validator-rejection",cause)}
  throw new Error("unreachable capture validation state");
}

export function createGitHubFetchProvider(fetchImpl:typeof fetch,token?:string):AcceptedRequestProvider{return async query=>{const startedAt=new Date().toISOString();let response:Response;try{response=await fetchImpl(query.url,{redirect:"error",headers:{Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28",...(token?{Authorization:`Bearer ${token}`}:{})}})}catch(cause){throw new CaptureTransportError({endpoint:query.url,startedAt,endedAt:new Date().toISOString(),errorClassification:"fetch-rejected"},{cause})}if(!response.url||response.url!==query.url)throw new CaptureTransportError({endpoint:query.url,startedAt,endedAt:new Date().toISOString(),errorClassification:"response-url-mismatch"});const bodyBytes=new Uint8Array(await response.arrayBuffer()),headers=Object.fromEntries([...response.headers.entries()].map(([k,v])=>[k.toLowerCase(),v]));return{status:response.status,headers,bodyBytes,startedAt,observedAt:new Date().toISOString(),transportEvidence:"fetch"}}}
