import{expect,test}from"bun:test";import v8 from"../../../docs/universality/campaign-v8/source-census-contract.json";import{CAPTURE_EXHAUSTION_INVALIDATION,CaptureTransportError,captureU1Campaign,createGitHubFetchProvider,type AcceptedRequestProvider,type CaptureClock,type CaptureQuery,type ProviderResponse}from"./organization-u1-occurrence-capture";import{canonicalU1Frame,freezeSourceCensusOccurrenceContract,sourceCensusOccurrenceConstants,type SourceCensusOccurrenceContract}from"./organization-universality-occurrence-contract";
const contract=()=>{const{digest:_,...b}=structuredClone(v8);return freezeSourceCensusOccurrenceContract({...b,schema:"open-autonomy.source-census-occurrence-contract.v5",id:"capture",campaignId:"capture",completion:structuredClone({pass:sourceCensusOccurrenceConstants.pass,leaf:sourceCensusOccurrenceConstants.leaf,aggregation:sourceCensusOccurrenceConstants.aggregation}),invalidation:structuredClone(sourceCensusOccurrenceConstants.invalidation)}as unknown as SourceCensusOccurrenceContract)};
const item={node_id:"N1",full_name:"owner/repo",stargazers_count:1200,default_branch:"main",license:null,fork:false,archived:false,created_at:"2020-01-01T00:00:00Z",description:null,topics:[],html_url:"https://github.com/owner/repo"};
const body=(total:number,items:any[])=>Buffer.from(JSON.stringify({total_count:total,incomplete_results:false,items}));
const response=(q:CaptureQuery,total=0,items:any[]=[],extra:Partial<ProviderResponse>={}):ProviderResponse=>{const minute=String(q.requestPosition).padStart(2,"0"),day=String(q.attemptNumber).padStart(2,"0");return{status:200,headers:{"content-type":"application/json"},bodyBytes:body(total,items),startedAt:`2025-06-${day}T00:${minute}:00.000Z`,observedAt:`2025-06-${day}T00:${minute}:01.000Z`,...extra}};
const clock=(max=8):CaptureClock=>{let call=0;return{now(){const attempt=Math.floor(call/2)+1,end=call%2;call++;return`2025-06-${String(attempt).padStart(2,"0")}T0${end}:00:00.000Z`},peek:()=>"2025-06-01T00:00:00.000Z",async waitUntil(){if(--max<0)throw Error("wait loop")}}};
const happy:AcceptedRequestProvider=async q=>q.kind==="tail-probe"?response(q):response(q,2,[item,item]);

test("campaign derives policy from frozen contract and returns only validated replay",async()=>{const out=await captureU1Campaign(contract(),happy,clock());expect(out.replay.passes).toHaveLength(2);expect(out.replay.attempts.map(a=>a.status)).toEqual(["complete","complete"]);expect(canonicalU1Frame(out.replay)).toHaveLength(1);expect(out.failedCustody).toEqual([])});
test("retryable failure restarts root, retains history and raw custody",async()=>{let failed=false;const provider:AcceptedRequestProvider=async q=>{if(q.attemptNumber===1&&!failed){failed=true;return response(q,0,[],{status:500,bodyBytes:Buffer.from("server")})}return happy(q)};const out=await captureU1Campaign(contract(),provider,clock());expect(out.replay.attempts.map(a=>a.status)).toEqual(["failed","complete","complete"]);expect(out.replay.passes.map(p=>p.attemptNumber)).toEqual([2,3]);expect(out.failedCustody[0]).toMatchObject({code:"non-rate-limit-non-200",attemptNumber:1});expect(out.failedCustody[0]!.response!.bodyBase64).toBe(Buffer.from("server").toString("base64"));expect(out.replay.requests.filter(r=>r.kind==="tail-probe").map(r=>r.requestPosition)).toEqual([0,0])});
test("403 with valid reset retries identical request without consuming attempt",async()=>{let calls=0,waits=0;const reset=1748737000,times=["2025-06-01T00:00:00.000Z","2025-06-01T01:00:00.000Z","2025-06-02T00:00:00.000Z","2025-06-02T01:00:00.000Z"],c:CaptureClock={now:()=>times.shift()!,peek:()=>"2025-06-01T00:00:00.000Z",waitUntil:async n=>{expect(n).toBe(reset);waits++}};const provider:AcceptedRequestProvider=async q=>{calls++;if(calls===1)return response(q,0,[],{status:403,headers:{"x-ratelimit-reset":String(reset)}});return happy(q)};const out=await captureU1Campaign(contract(),provider,c);expect(waits).toBe(1);expect(out.replay.attempts).toHaveLength(2);expect(out.failedCustody).toHaveLength(1);expect(out.failedCustody[0]!.code).toBe("rate-limit-wait");expect(calls).toBe(5)});
test("rate-limit reset at cutoff is immediate and never waits",async()=>{let waited=false;const c=clock();c.waitUntil=async()=>{waited=true};try{await captureU1Campaign(contract(),async q=>response(q,0,[],{status:403,headers:{"x-ratelimit-reset":"4102444800"}}),c);throw Error("expected invalidation")}catch(e:any){expect(e.custody.reason).toBe("accepted-response-at-or-after-cutoff");expect(e.custody.failedCustody).toHaveLength(1);expect(waited).toBe(false)}});
test("classifies incomplete and terminal containment as retryable",async()=>{for(const mode of["incomplete","containment"]as const){const provider:AcceptedRequestProvider=async q=>{if(q.attemptNumber===1){if(mode==="incomplete")return{...response(q),bodyBytes:Buffer.from(JSON.stringify({total_count:0,incomplete_results:true,items:[]}))};if(q.kind==="range")return response(q,1,[{...item,stargazers_count:999}])}return happy(q)};const out=await captureU1Campaign(contract(),provider,clock());expect(out.replay.attempts[0]!.failure).toBe(mode==="incomplete"?"incomplete-results-true":"terminal-item-ineligible-or-created-outside-query");expect(out.failedCustody).toHaveLength(1)}});
test("immediate cutoff invalidation preserves prior campaign custody",async()=>{let immediate=false;const provider:AcceptedRequestProvider=async q=>{if(q.attemptNumber===2&&!immediate){immediate=true;return response(q,0,[],{startedAt:"2099-07-18T00:00:00.000Z",observedAt:"2099-07-18T00:00:01.000Z"})}return happy(q)};try{await captureU1Campaign(contract(),provider,clock());throw Error("expected invalidation")}catch(e:any){expect(e.custody.reason).toBe("accepted-response-at-or-after-cutoff");expect(e.custody.completePasses).toHaveLength(1);expect(e.custody.acceptedRequests).toHaveLength(2);expect(e.custody.attempts).toHaveLength(2)}});
test("transport retries stop after four attempts with full history/custody",async()=>{try{await captureU1Campaign(contract(),async()=>{throw Error("offline")},clock());throw Error("expected invalidation")}catch(e:any){expect(e.custody.reason).toBe(CAPTURE_EXHAUSTION_INVALIDATION);expect(e.custody.attempts).toHaveLength(4);expect(e.custody.failedCustody).toHaveLength(4);expect(e.custody.failedCustody.every((x:any)=>x.evidence==="unauthenticated-test-provider-error"&&!x.transportReceipt)).toBe(true)}});
test("final validator alias rejection preserves both complete transcripts",async()=>{const provider:AcceptedRequestProvider=async q=>q.kind==="tail-probe"?response(q):response(q,1,[{...item,node_id:`N${q.completePassOrdinal}`}]);try{await captureU1Campaign(contract(),provider,clock());throw Error("expected invalidation")}catch(e:any){expect(e.custody.reason).toBe("final-validator-node-id-alias");expect(e.custody.completePasses).toHaveLength(2);expect(e.custody.acceptedRequests).toHaveLength(4);expect(e.custody.occurrences).toHaveLength(2)}});
test("fetch adapter pins headers/redirect, hides credentials, and binds response URL",async()=>{let init:any;const fetcher=(async(url:any,i:any)=>{init=i;const x=new Response("{}",{status:500,headers:{"content-type":"application/json"}});Object.defineProperty(x,"url",{value:String(url)});return x})as any,adapter=createGitHubFetchProvider(fetcher,"secret-token"),q={attemptId:"a",attemptNumber:1,completePassOrdinal:1,requestPosition:0,parentRequestPosition:null,kind:"tail-probe",url:"https://example.test",requestKey:"k",queryStars:[2000,Number.MAX_SAFE_INTEGER],queryCreated:null}as CaptureQuery,r=await adapter(q);expect(init).toMatchObject({redirect:"error",headers:{Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28",Authorization:"Bearer secret-token"}});expect(r.status).toBe(500);expect(Buffer.from(r.bodyBytes).toString()).toBe("{}");expect(JSON.stringify(r)).not.toContain("secret-token");for(const value of["","https://evil.test"]){const redirected=createGitHubFetchProvider((async()=>{const x=new Response("{}");Object.defineProperty(x,"url",{value});return x})as any);await expect(redirected(q)).rejects.toMatchObject({receipt:{endpoint:"https://example.test",errorClassification:"response-url-mismatch"}})}});

test("rate-limit wait rejection and post-wait cutoff preserve 403 custody",async()=>{const reset=1748737000;for(const mode of["reject","cutoff"]as const){let now="2025-06-01T00:00:00.000Z";const c:CaptureClock={now:()=>"2025-06-01T00:00:00.000Z",peek:()=>now,waitUntil:async()=>{if(mode==="reject")throw Error("timer");now="2100-01-01T00:00:00.000Z"}};try{await captureU1Campaign(contract(),async q=>response(q,0,[],{status:403,headers:{"x-ratelimit-reset":String(reset)}}),c);throw Error("expected invalidation")}catch(e:any){expect(e.custody.reason).toBe(mode==="reject"?"rate-limit-wait-failed":"accepted-response-at-or-after-cutoff");expect(e.custody.failedCustody[0].code).toBe("rate-limit-wait");expect(e.custody.failedCustody[0].response.status).toBe(403)}}});

test("validates 403 chronology before waiting",async()=>{let waited=false;try{await captureU1Campaign(contract(),async q=>response(q,0,[],{status:403,headers:{"x-ratelimit-reset":"1748737000"},startedAt:"broken"}),{...clock(),waitUntil:async()=>{waited=true}});throw Error("expected invalidation")}catch(e:any){expect(e.custody.reason).toBe(CAPTURE_EXHAUSTION_INVALIDATION);expect(e.custody.failedCustody.every((x:any)=>x.code==="malformed-response-schema")).toBe(true);expect(waited).toBe(false)}});

test("accepts only authenticated exact transport receipts",async()=>{for(const valid of[true,false]){const provider:AcceptedRequestProvider=async q=>{const day=String(q.attemptNumber).padStart(2,"0");throw new CaptureTransportError({endpoint:valid?q.url:`${q.url}/wrong`,startedAt:`2025-06-${day}T00:00:00.000Z`,endedAt:`2025-06-${day}T00:00:01.000Z`,errorClassification:"socket-reset"})};try{await captureU1Campaign(contract(),provider,clock());throw Error("expected invalidation")}catch(e:any){expect(e.custody.reason).toBe(CAPTURE_EXHAUSTION_INVALIDATION);expect(e.custody.failedCustody.every((x:any)=>valid?x.transportReceipt?.errorClassification==="socket-reset":x.evidence==="invalid-transport-receipt"&&!x.transportReceipt)).toBe(true)}}});

test("malformed repository names remain inside typed campaign custody",async()=>{const provider:AcceptedRequestProvider=async q=>q.kind==="tail-probe"?response(q):response(q,1,[{...item,full_name:"owner/repo."}]);try{await captureU1Campaign(contract(),provider,clock());throw Error("expected invalidation")}catch(e:any){expect(e.constructor.name).toBe("CaptureCampaignInvalidation");expect([CAPTURE_EXHAUSTION_INVALIDATION,"final-validator-rejection"]).toContain(e.custody.reason)}});

test("malformed response clocks cannot enter terminal attempt custody",async()=>{let calls=0;const c:CaptureClock={now:()=>calls++===0?"2025-06-01T00:00:00.000Z":"malformed",peek:()=>"2025-06-01T00:00:00.000Z",waitUntil:async()=>{}};try{await captureU1Campaign(contract(),async q=>response(q,0,[],{observedAt:"malformed"}),c);throw Error("expected invalidation")}catch(e:any){expect(e.constructor.name).toBe("CaptureCampaignInvalidation");expect(e.custody.attempts).toHaveLength(1);expect(e.custody.attempts.every((a:any)=>/^\d{4}-\d{2}-\d{2}T/.test(a.endedAt)&&a.startedAt<=a.endedAt)).toBe(true)}});
