import { describe, expect, test } from "bun:test";
import { searchCounterfactuals, verifyPlannerCertificate, type Candidate, type CounterfactualOracle, type OracleEvaluation, type PlannerConstraints, type PlannerObjective } from "./organization-counterfactual-planner";

const candidate = (id: string, operations: Candidate["patch"]["operations"], patch: Partial<Candidate> = {}): Candidate => ({ id, patch: { schema: "autonomy.organization-patch.v1", id, operations }, claim: "prediction", targetParameters: [{ name: "worker.service", identifiable: true, confoundedWith: [] }], rationale: `${id} synthetic candidate`, assumptions: ["held-out world is stationary"], risks: ["latency regression"], rollbackTrigger: "p95 latency exceeds 120ms", ...patch });
const baseline = candidate("baseline", []), faster = candidate("faster", [{ kind: "capacity", component: "worker", from: 1, to: 2 }]), cheaper = candidate("cheaper", [{ kind: "routing", route: "worker->review", from: 1, to: .5 }]);
const objectives: PlannerObjective[] = [{ metric: "quality", direction: "maximize", uncertaintyAversion: 1 }, { metric: "cost", direction: "minimize", uncertaintyAversion: 1 }];
const constraints: PlannerConstraints = { allowedSemanticPaths: ["organization.workers"], maximumAuthority: { repo: 1 }, baselineAuthority: { repo: 1 }, budget: 10, requiredApprovals: ["reviewer"], grantedApprovals: ["reviewer"], rolloutMaximumFraction: .2, candidateRolloutFractions: { baseline: 0, faster: .1, cheaper: .1, dangerous: .1, gaming: .1, confounded: .1, uncertain: .1 }, maximumComplexity: 3, minimumMetricCoverage: .9, maximumProxyGap: 0, maximumDistributionShift: .2, maximumBacktestMae: .2, minimumBacktestCoverage: .8 };
const evaluation = (quality: number, cost: number, patch: Partial<OracleEvaluation> = {}): OracleEvaluation => ({ metrics: { quality: { point: quality, uncertainty: .01 }, cost: { point: cost, uncertainty: .1 } }, cost, authority: { repo: 1 }, semanticPaths: ["organization.workers"], proxy: { reportedEscalations: 1, latentFailures: 1, attributedHumanMinutes: 2, actualHumanMinutes: 2, metricCoverage: 1, distributionShift: .1 }, backtest: [{ predicted: quality, interval: [quality - .1, quality + .1], actual: quality }], evidence: ["heldout:synthetic"], ...patch });
class Oracle implements CounterfactualOracle { calls: string[] = []; inspections: string[] = []; constructor(private values: Record<string, OracleEvaluation>) {} inspect(c: Candidate) { this.inspections.push(c.id); const { metrics:_,backtest:__,...inspection } = this.values[c.id]!; return structuredClone(inspection); } evaluate(c: Candidate) { this.calls.push(c.id); return structuredClone(this.values[c.id]!); } }

describe("R26 constraints before scoring", () => {
  test("authority expansion, governance, semantic and rollout violations never reach the oracle", () => { const dangerous = candidate("dangerous", [{ kind: "profile", path: "constitution.authority", from: 1, to: 2 }]), oracle = new Oracle({ baseline: evaluation(.5, 5), faster: evaluation(.8, 4), dangerous: evaluation(1, 0) }); const cert = searchCounterfactuals([baseline, faster, dangerous], "baseline", objectives, constraints, oracle); expect(oracle.calls).toEqual(["baseline", "faster"]); expect(cert.assessments.find((a) => a.candidate.id === "dangerous")).toEqual(expect.objectContaining({ feasible: false, violations: ["semantic:constitution.authority"] })); expect(cert.paretoFront).not.toContain("dangerous"); });
  test("rejects observed authority expansion before objective scoring", () => { const oracle = new Oracle({ baseline: evaluation(.5, 5), faster: evaluation(1, 0, { authority: { repo: 2 } }) }), cert = searchCounterfactuals([baseline, faster], "baseline", objectives, constraints, oracle); expect(cert.assessments.find((a) => a.candidate.id === "faster")?.violations).toContain("authority-expansion:repo"); expect(oracle.inspections).toContain("faster"); expect(oracle.calls).not.toContain("faster"); expect(cert.outcome).toBe("tradeoff"); expect(cert.recommendation).toBeUndefined(); });
  test("refuses causal candidates with non-identifiable/confounded targets before scoring", () => { const confounded = candidate("confounded", [{ kind: "capacity", component: "worker", from: 1, to: 2 }], { claim: "causal", targetParameters: [{ name: "service", identifiable: false, confoundedWith: ["routing"] }] }), oracle = new Oracle({ baseline: evaluation(.5, 5), confounded: evaluation(1, 0) }), cert = searchCounterfactuals([baseline, confounded], "baseline", objectives, constraints, oracle); expect(oracle.calls).toEqual(["baseline"]); expect(cert.assessments[1]!.violations).toContain("causal-nonidentifiable"); });
});

describe("R26 robust Pareto decisions and known optimum", () => {
  test("finds the known synthetic optimum only when it robustly dominates baseline", () => { const oracle = new Oracle({ baseline: evaluation(.5, 5), faster: evaluation(.8, 4) }), cert = searchCounterfactuals([baseline, faster], "baseline", objectives, constraints, oracle); expect(cert.outcome).toBe("recommended"); expect(cert.recommendation).toBe("faster"); expect(cert.paretoFront).toEqual(["faster"]); expect(cert.assessments.find((a) => a.candidate.id === "baseline")?.dominatedBy).toEqual(["faster"]); });
  test("returns the full tradeoff frontier rather than hiding scalar weights", () => { const oracle = new Oracle({ baseline: evaluation(.5, 5), faster: evaluation(.9, 7), cheaper: evaluation(.4, 2) }), cert = searchCounterfactuals([baseline, faster, cheaper], "baseline", objectives, constraints, oracle); expect(cert.outcome).toBe("tradeoff"); expect(cert.recommendation).toBeUndefined(); expect(cert.paretoFront).toEqual(["baseline", "cheaper", "faster"]); });
  test("uncertainty penalty prevents a fragile point-estimate winner", () => { const uncertain = candidate("uncertain", [{ kind: "capacity", component: "worker", from: 1, to: 3 }]), oracle = new Oracle({ baseline: evaluation(.7, 5), uncertain: evaluation(.95, 4, { metrics: { quality: { point: .95, uncertainty: .5 }, cost: { point: 4, uncertainty: 5 } } }) }), cert = searchCounterfactuals([baseline, uncertain], "baseline", objectives, constraints, oracle); expect(cert.recommendation).toBeUndefined(); expect(cert.paretoFront).toContain("baseline"); });
});

describe("R26 adversarial Goodhart and held-out backtests", () => {
  test("rejects suppressed escalation, hidden labor, missing metrics and distribution shift", () => { const gaming = candidate("gaming", [{ kind: "retry", component: "worker", from: 1, to: 0 }]), oracle = new Oracle({ baseline: evaluation(.5, 5), gaming: evaluation(1, 0, { proxy: { reportedEscalations: 0, latentFailures: 3, attributedHumanMinutes: 0, actualHumanMinutes: 10, metricCoverage: .5, distributionShift: .8 } }) }), cert = searchCounterfactuals([baseline, gaming], "baseline", objectives, constraints, oracle), violations = cert.assessments[1]!.violations; expect(violations).toEqual(expect.arrayContaining(["proxy-gaming", "hidden-human-labor", "metric-coverage", "distribution-shift"])); expect(cert.paretoFront).not.toContain("gaming"); });
  test("rejects a candidate whose held-out error or interval coverage fails", () => { const oracle = new Oracle({ baseline: evaluation(.5, 5), faster: evaluation(.9, 4, { backtest: [{ predicted: .9, interval: [.8, 1], actual: .1 }] }) }), cert = searchCounterfactuals([baseline, faster], "baseline", objectives, constraints, oracle); expect(cert.assessments[1]!.violations).toEqual(expect.arrayContaining(["backtest-mae", "backtest-coverage"])); });
});

describe("R26 independent machine-checkable certificates", () => {
  test("recomputes feasibility, robust objectives, Pareto dominance and recommendation", () => { const candidates = [baseline, faster], oracle = new Oracle({ baseline: evaluation(.5, 5), faster: evaluation(.8, 4) }), cert = searchCounterfactuals(candidates, "baseline", objectives, constraints, oracle); expect(verifyPlannerCertificate(cert, candidates, "baseline", objectives, constraints)).toEqual([]); const forged = structuredClone(cert); forged.assessments[1]!.evaluation!.authority.repo = 10; expect(verifyPlannerCertificate(forged, candidates, "baseline", objectives, constraints)).toEqual(expect.arrayContaining(["certificate-digest", "evaluation-recompute:faster"])); });
  test("detects a forged infeasible recommendation even with recomputed outer digest", () => { const dangerous = candidate("dangerous", [{ kind: "profile", path: "constitution.authority", from: 1, to: 2 }]), oracle = new Oracle({ baseline: evaluation(.5, 5), dangerous: evaluation(1, 0) }), cert = searchCounterfactuals([baseline, dangerous], "baseline", objectives, constraints, oracle); const forged = { ...cert, recommendation: "dangerous", outcome: "recommended" as const }; expect(verifyPlannerCertificate(forged, [baseline, dangerous], "baseline", objectives, constraints)).toEqual(expect.arrayContaining(["certificate-digest", "recommendation-not-dominating"])); });
});
