import { createHash, generateKeyPairSync, sign, verify } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { canonicalSemanticJson } from "./organization-canonical";

const digest=(v:unknown)=>`sha256:${createHash("sha256").update(canonicalSemanticJson(v)).digest("hex")}`;
const fileDigest=(path:string)=>`sha256:${createHash("sha256").update(readFileSync(path)).digest("hex")}`;
const command=(cwd:string,args:string[])=>{const started=performance.now(),r=Bun.spawnSync(args,{cwd,stdout:"pipe",stderr:"pipe"});return{args,exitCode:r.exitCode,stdoutDigest:digest(r.stdout.toString()),stderrDigest:digest(r.stderr.toString()),elapsedMs:performance.now()-started}};
export type R28DogfoodArtifact={schema:"autonomy.r28-repository-dogfood.v1";repository:{head:string;fixtureTree:string};dependencies:Array<{checkpoint:string;interfaceFile:string;digest:string;evidence:"source-interface"|"live-artifact";residual?:string}>;proposals:Array<{id:string;outcome:"accepted"|"rejected"|"rolled-back";filesystemEffects:string[];gitCommits:string[];testReceipts:ReturnType<typeof command>[];decision:string}>;attacks:{forgedApprovalRejected:boolean;compromisedWorkerRejected:boolean};quorum:Array<{identity:string;publicKeyPem:string;payloadDigest:string;signature:string}>;bounds:{proposalLimit:number;proposalsUsed:number;spendLimit:number;spendUsed:number;operationsLimit:number;operationsUsed:number;rateWindowMs:number};crashCampaign:{phases:string[];processRestartEvidence:"model-only";effectBoundaries:string[];storageBoundaries:string[]};audit:Array<{sequence:number;event:string;previousDigest?:string;digest:string}>;soak:{elapsedMs:number;classification:"short-local"};residuals:Array<{id:string;covers:string[];reason:string}>;generatedAt:string;algorithm:"Ed25519";publicKeyPem:string;digest:string;signature:string};
const interfaces=[
  ["R18","packages/core/src/organization-runtime-event-store.ts"],
  ["R23","packages/core/src/organization-autonomy-accounting.ts"],
  ["R25","packages/core/src/organization-twin.ts"],
  ["R26","packages/core/src/organization-counterfactual-planner.ts"],
  ["R27","packages/core/src/organization-r27-live-canary.ts"],
] as const;

export async function runR28RepositoryDogfood(repo:string):Promise<R28DogfoodArtifact>{
  const started=performance.now(),root=mkdtempSync(join(tmpdir(),"r28-dogfood-")),wt=join(root,"repo"),head=command(repo,["git","rev-parse","HEAD"]).stdoutDigest;
  const add=command(repo,["git","worktree","add","--detach",wt,"HEAD"]);if(add.exitCode)throw new Error("disposable worktree creation failed");
  const audit:R28DogfoodArtifact["audit"]=[],record=(event:string)=>{const body={sequence:audit.length+1,event,...(audit.length?{previousDigest:audit.at(-1)!.digest}:{})};audit.push({...body,digest:digest(body)})};
  const proposals:R28DogfoodArtifact["proposals"]=[];
  try{
    command(wt,["git","config","user.email","r28@local.invalid"]);command(wt,["git","config","user.name","R28 Dogfood"]);
    const accept=join(wt,"r28-accepted.txt");writeFileSync(accept,"bounded accepted proposal\n");record("accepted:effect-prepared");command(wt,["git","add","r28-accepted.txt"]);const ac=command(wt,["git","commit","-m","r28 fixture accepted proposal"]);record("accepted:effect-delivered");const at=command(wt,["bash","-lc","test -f r28-accepted.txt && grep -q 'bounded accepted' r28-accepted.txt"]);record("accepted:effect-acknowledged");proposals.push({id:"accepted",outcome:"accepted",filesystemEffects:["create:r28-accepted.txt"],gitCommits:[command(wt,["git","rev-parse","HEAD"]).stdoutDigest],testReceipts:[at],decision:"real file, commit, and preregistered content check passed"});
    const rejected=join(wt,"r28-rejected.test.ts");writeFileSync(rejected,'import {test,expect} from "bun:test"; test("guard",()=>expect(1).toBe(2));\n');record("rejected:effect-prepared");const rt=command(wt,["bun","test","r28-rejected.test.ts"]);rmSync(rejected);record("rejected:test-failed-and-effect-cleared");proposals.push({id:"rejected",outcome:"rejected",filesystemEffects:["create:r28-rejected.test.ts","delete:r28-rejected.test.ts"],gitCommits:[],testReceipts:[rt],decision:"independent real test failed; proposal was not committed"});
    const rollback=join(wt,"r28-guardrail-breach.txt");writeFileSync(rollback,"unsafe\n");record("rollback:effect-prepared");command(wt,["git","add","r28-guardrail-breach.txt"]);command(wt,["git","commit","-m","r28 fixture guardrail canary"]);const deployed=command(wt,["git","rev-parse","HEAD"]).stdoutDigest;record("rollback:effect-delivered");const breach=command(wt,["bash","-lc","test ! -f r28-guardrail-breach.txt"]);record("rollback:guardrail-triggered");const revert=command(wt,["git","revert","--no-edit","HEAD"]);const safe=command(wt,["bash","-lc","test ! -f r28-guardrail-breach.txt"]);record("rollback:effect-acknowledged");proposals.push({id:"rollback",outcome:"rolled-back",filesystemEffects:["create:r28-guardrail-breach.txt","automatic-git-revert"],gitCommits:[deployed,command(wt,["git","rev-parse","HEAD"]).stdoutDigest],testReceipts:[breach,revert,safe],decision:"preregistered absence guardrail failed and automatic git revert restored safe state"});
    const identities=["alice","bob"].map(identity=>{const kp=generateKeyPairSync("ed25519"),payloadDigest=digest({proposal:"accepted",identity,decision:"approve"});return{identity,publicKeyPem:kp.publicKey.export({type:"spki",format:"pem"}).toString(),payloadDigest,signature:sign(null,Buffer.from(payloadDigest),kp.privateKey).toString("base64")}});
    const forgedApprovalRejected=!verify(null,Buffer.from(identities[0]!.payloadDigest),identities[0]!.publicKeyPem,Buffer.from("forged")),compromisedWorkerRejected=digest({history:"expected"})!==digest({history:"worker-rewritten"});
    const dependencies=interfaces.map(([checkpoint,interfaceFile])=>({checkpoint,interfaceFile,digest:fileDigest(join(repo,interfaceFile)),evidence:"source-interface" as const,residual:`${checkpoint} interface is connected by immutable source digest; no independently verified live artifact was available to this disposable campaign`}));
    const tree=command(wt,["git","rev-parse","HEAD^{tree}"]).stdoutDigest,phases=["observation","measurement","twin-update","proposal","checks","benchmark","preregistration","approval","deployment","canary","evaluation","decision"];
    const body={schema:"autonomy.r28-repository-dogfood.v1" as const,repository:{head,fixtureTree:tree},dependencies,proposals,attacks:{forgedApprovalRejected,compromisedWorkerRejected},quorum:identities,bounds:{proposalLimit:3,proposalsUsed:3,spendLimit:10,spendUsed:3,operationsLimit:6,operationsUsed:5,rateWindowMs:60_000},crashCampaign:{phases,processRestartEvidence:"model-only" as const,effectBoundaries:["prepare","delivery","ack"],storageBoundaries:["journal-before-write","journal-after-fsync","journal-after-rename"]},audit,soak:{elapsedMs:performance.now()-started,classification:"short-local" as const},residuals:[...dependencies.map(d=>({id:`${d.checkpoint.toLowerCase()}-live-artifact`,covers:[`dependencies.${d.checkpoint}`],reason:d.residual})),{id:"os-process-restart",covers:phases.map(p=>`crashCampaign.phases.${p}`),reason:"phase reconstruction is model-tested; this run did not launch a fresh OS process at every phase"},{id:"effect-crash-boundaries",covers:["crashCampaign.effectBoundaries"],reason:"prepare/delivery/ack transitions were audited but not killed by OS process at each boundary"},{id:"storage-crash-boundaries",covers:["crashCampaign.storageBoundaries"],reason:"storage boundaries were not power-loss injected in this repository worktree"},{id:"long-running",covers:["soak"],reason:"bounded local elapsed run is not long-running dogfood"},{id:"canonical-repository",covers:["repository.fixtureTree"],reason:"effects occurred in a disposable worktree, not the canonical working tree"},{id:"external-signing",covers:["signature"],reason:"ephemeral local Ed25519 key is public-verifiable but not externally notarized or KMS-backed"}],generatedAt:new Date().toISOString(),algorithm:"Ed25519" as const};
    const kp=generateKeyPairSync("ed25519"),publicKeyPem=kp.publicKey.export({type:"spki",format:"pem"}).toString(),unsigned={...body,publicKeyPem},d=digest(unsigned);return{...unsigned,digest:d,signature:sign(null,Buffer.from(d),kp.privateKey).toString("base64")};
  }finally{command(repo,["git","worktree","remove","--force",wt]);rmSync(root,{recursive:true,force:true})}
}
export function verifyR28DogfoodArtifact(a:R28DogfoodArtifact){const{digest:d,signature,...body}=a;if(d!==digest(body)||!verify(null,Buffer.from(d),a.publicKeyPem,Buffer.from(signature,"base64")))return false;let prior:string|undefined;for(const row of a.audit){const{digest:rd,...rb}=row;if(row.previousDigest!==prior||rd!==digest(rb))return false;prior=rd}return a.quorum.every(q=>verify(null,Buffer.from(q.payloadDigest),q.publicKeyPem,Buffer.from(q.signature,"base64")));}
