import{expect,test}from"bun:test";import{buildU5CoverageReport,verifyFrozenU5CoverageReport}from"./organization-u5-coverage-report";import{createU5LedgerTestFixture}from"./organization-u5-disposition-ledger.test";import{authenticateU5SyntheticEvidence,digestU5DispositionLedger,freezeU5DispositionLedger}from"./organization-u5-disposition-ledger";
const args=(z:any)=>[z.u.inventory,z.u.calculus,z.u.sourceRegistry,z.u.trusted,z.attestation??(z.body as any).__attestation,z.policy];
const invoke=(z:any,ledger=z.frozen)=>buildU5CoverageReport(ledger,z.u.inventory,z.u.calculus,z.u.sourceRegistry,z.u.trusted,z.attestation,z.policy);
test("coverage derives only from fully verified authenticated ledger",()=>{const z:any=createU5LedgerTestFixture(),r:any=invoke(z);expect(r.factCount).toBe(17);expect(r.canonical.creditWeight).toBe(r.denominatorWeight);expect(r.dispositions.reduce((n:number,x:any)=>n+x.count,0)).toBe(17);expect(Object.isFrozen(r.dispositions[0])).toBe(true);expect(()=>verifyFrozenU5CoverageReport(r,z.frozen,z.u.inventory,z.u.calculus,z.u.sourceRegistry,z.u.trusted,z.attestation,z.policy)).not.toThrow()});
test("rejects self-digested fake ledger and contributor substitution",()=>{const z:any=createU5LedgerTestFixture(),fake:any=structuredClone(z.frozen);fake.evidenceRegistry[0].payloadDigest="sha256:"+"0".repeat(64);deep(fake);expect(()=>invoke(z,fake)).toThrow(/digest|payload|authentication|semantic/);const r:any=invoke(z),x:any=structuredClone(r);x.dispositions[0].contributorDigest="sha256:"+"0".repeat(64);deep(x);expect(()=>verifyFrozenU5CoverageReport(x,z.frozen,z.u.inventory,z.u.calculus,z.u.sourceRegistry,z.u.trusted,z.attestation,z.policy)).toThrow(/replay|derivation/)});
test("mixed lattice reconciles exact zero-credit products and contributor digests",()=>{const z:any=createU5LedgerTestFixture(),ds=["preserved","derived","lowered","extension","opaque","abstracted","unsupported","inexpressible",...Array(9).fill("preserved")],r:any=invoke(z,remake(z,ds));expect(r.dispositions.filter((x:any)=>!["preserved","derived","lowered"].includes(x.disposition)).every((x:any)=>x.canonicalCreditWeight===0)).toBe(true);expect(r.extensionSubstrata.reduce((n:number,x:any)=>n+x.count,0)).toBe(r.dispositions.find((x:any)=>x.disposition==="extension").count);expect(r.diagnostics.count).toBe(r.dispositions.filter((x:any)=>["unsupported","inexpressible"].includes(x.disposition)).reduce((n:number,x:any)=>n+x.count,0))});
function deep(v:any){const q=[v];while(q.length){const x=q.pop();if(x&&typeof x==="object"&&!Object.isFrozen(x)){q.push(...Object.values(x));Object.freeze(x)}}return v}
test("reports opaque opportunity and complete diagnostic denominators",()=>{const z:any=createU5LedgerTestFixture(),r:any=invoke(z);expect(r.opaqueOpportunity.opportunityCount).toBe(r.factCount);expect(r.opaqueOpportunity.opportunityWeight).toBe(r.denominatorWeight);expect(r.diagnosticAccounting).toEqual({count:r.factCount,weight:r.denominatorWeight,evidenceComplete:true,evidenceInvalid:0});expect(r.canonical.creditWeight+r.zeroCreditReconciliation.weight).toBe(r.denominatorWeight)});
test("report authority and custody receipts are replay-bound",()=>{const z:any=createU5LedgerTestFixture(),r:any=invoke(z);expect(r.authority.ownerId).not.toBe(r.custodian.ownerId);for(const field of ["authorityReceipt","custodyReceipt"]){const x:any=structuredClone(r);x[field]="0".repeat(64);deep(x);expect(()=>verifyFrozenU5CoverageReport(x,z.frozen,z.u.inventory,z.u.calculus,z.u.sourceRegistry,z.u.trusted,z.attestation,z.policy)).toThrow(/replay|derivation/)}});
test("all opaque and all abstracted remain zero canonical with exact denominators",()=>{for(const disposition of ["opaque","abstracted"]){const z:any=createU5LedgerTestFixture(),r:any=invoke(z,remake(z,Array(17).fill(disposition)));expect(r.canonical.count).toBe(0);expect(r.zeroCreditReconciliation.count).toBe(17);expect(r.zeroCreditReconciliation.weight).toBe(r.denominatorWeight)}});
function remake(z:any,ds:string[]){const pairs=z.u.inventory.facts.map((f:any,i:number)=>z.pair(f,ds[i],ds[i]==="extension"?"provider-local":null)),rows=pairs.map((x:any)=>x.row),body={...z.body,evidenceRegistry:pairs.map((x:any)=>x.evidence),ledger:rows,accounting:z.account(rows)};return freezeU5DispositionLedger(body,z.u.inventory,z.u.calculus,z.u.sourceRegistry,z.u.trusted,z.attestation,z.policy)}
test("report chronology and cross-role ownership fail closed",()=>{for(const changes of [{issuedAt:"2026-07-20T00:00:00.000Z"},{authorityOwnerId:"u5-report-owner"}]){const z:any=createU5LedgerTestFixture(),ledger=mutateEvidence(z,changes);expect(()=>invoke(z,ledger)).toThrow(/chronology|separation|binding/)}const z:any=createU5LedgerTestFixture(),r:any=invoke(z),x:any=structuredClone(r);x.authority.keyDigest=x.custodian.keyDigest;deep(x);expect(()=>verifyFrozenU5CoverageReport(x,z.frozen,z.u.inventory,z.u.calculus,z.u.sourceRegistry,z.u.trusted,z.attestation,z.policy)).toThrow(/replay|derivation/)});
function mutateEvidence(z:any,changes:any){const body:any=structuredClone(z.frozen);delete body.digest;const old=body.evidenceRegistry[0],{authorityReceipt:_,custodyReceipt:__,payloadBytes:___,payloadDigest:____,classifierReceipt:_____,...unsigned}=old;void _;void __;void ___;void ____;void _____;body.evidenceRegistry[0]=authenticateU5SyntheticEvidence({...unsigned,...changes});return deep({...body,digest:digestU5DispositionLedger(body)})}
