import { expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { canonicalSemanticJson as C } from "./organization-canonical";
import { createU4AuthenticatedExtractionSpecification } from "./organization-u4-test-fixture";
import { createU4EvidenceExtraction } from "./organization-u4-evidence-extractor";
import { createU4ProbeExtractionBridge, verifyU4ProbeExtractionBridge, createU4BridgeVerifiedTriangulation,verifyU4BridgeQualifiedTriangulation } from "./organization-u4-probe-extraction-bridge";
import {replayInputs,replayVariant,replan,makeRun,creditedExecution} from "./organization-u4-probe-test-fixture";
import {computeU4ProbeMaterialDigest,computeU4SyntheticU3TrustAnchorDigest,freezeU4VerifiedProbeBundle} from "./organization-u4-probe-protocol";

const H=(x:string)=>`sha256:${createHash("sha256").update(x).digest("hex")}`;
function setup(two=false){const x:any=two?replayVariant([{caseId:"case",repetition:0,kind:"credited"},{caseId:"case",repetition:1,kind:"credited"}]):replayInputs(),spec=createU4AuthenticatedExtractionSpecification(x.inventory,x.trusted),extraction=createU4EvidenceExtraction(x.inventory,x.calculus,x.sourceRegistry,x.trusted,spec),args=[x.inventory,x.calculus,x.sourceRegistry,x.trusted,x.probeBundle,extraction,spec] as const,bridge=createU4ProbeExtractionBridge(...args);return{x,spec,extraction,args,bridge}}
function aggregateFor(x:any,cases:any[],stdout:string){const plan=replan(x,cases),run=makeRun(x,plan,cases[0].id,0,"credited",stdout),ce=creditedExecution(x,plan,run),materials=[ce.material],body:any={schema:"open-autonomy.u4-verified-probe-bundle.v1",fixtureKind:"synthetic",denominatorScope:"fixture-local",empiricalRegistration:false,closureClaim:false,inventoryDigest:x.inventory.digest,calculusDigest:x.calculus.digest,u3ContractDigest:x.probeBundle.u3Contract.digest,u3TrustAnchorDigest:computeU4SyntheticU3TrustAnchorDigest(x.probeBundle.u3Contract,ce.material.u3Trusted),materialDigests:materials.map(computeU4ProbeMaterialDigest),plan,executions:[ce.execution]},bundle=freezeU4VerifiedProbeBundle(body,materials,x.inventory,x.calculus,x.probeBundle.u3Contract,x.trusted,x.sourceRegistry);return{bundle,materials,u3Contract:x.probeBundle.u3Contract}}

test("successful public bridge composes into a bridge-qualified triangulation certificate",()=>{const s=setup(),input={adjudications:[],gapDispositions:[]},q=createU4BridgeVerifiedTriangulation(s.bridge,...s.args,input);expect(s.bridge.closureEligible).toBe(true);expect(s.bridge.witnesses).toHaveLength(s.x.inventory.facts.length);expect(q.bridgeDigest).toBe(s.bridge.digest);expect(q.probeBundleDigest).toBe(s.x.probeBundle.bundle.digest);expect(q.triangulation.gapCount).toBe(0);expect(q.triangulation.conflictCount).toBe(0);expect(verifyU4BridgeQualifiedTriangulation(q,s.bridge,...s.args,input)).toEqual(q)});

test("rejects fact permutation observation and pointer reassignment",()=>{for(const attack of [(x:any)=>x.bundle.plan.cases[0].factResultBindings[0].factId=x.bundle.plan.cases[0].factResultBindings[1].factId,(x:any)=>x.bundle.plan.cases[0].factResultBindings[0].observationIds=[],(x:any)=>x.bundle.plan.cases[0].factResultBindings[0].stdoutJsonPointer="/forged"]){const s=setup(),aggregate:any=structuredClone(s.x.probeBundle);attack(aggregate);expect(()=>createU4ProbeExtractionBridge(s.x.inventory,s.x.calculus,s.x.sourceRegistry,s.x.trusted,aggregate,s.extraction,s.spec)).toThrow()}});

test("re-signed bindings enforce bijection and shared-pointer equivalence",()=>{const x:any=replayInputs(),base=structuredClone(x.probeBundle.bundle.plan.cases[0]);for(const attack of [(c:any)=>c.factResultBindings[0].factId=c.factResultBindings[1].factId,(c:any)=>c.factResultBindings.pop(),(c:any)=>c.factResultBindings.push(structuredClone(c.factResultBindings[0])),(c:any)=>c.factResultBindings[0].stdoutJsonPointer="bad",(c:any)=>c.factResultBindings[0].sharedProjectionEquivalenceId=null,(c:any)=>c.factResultBindings[0].sharedProjectionEquivalenceId="other-equivalence"]){const c=structuredClone(base);attack(c);expect(()=>replan(x,[c])).toThrow(/binding|projection|pointer|totality/)}});

test("accepts distinct canonical fact pointers under an exact shared projection equivalence",()=>{const x:any=replayInputs(),c=structuredClone(x.probeBundle.bundle.plan.cases[0]),stdout:any={};c.factResultBindings.forEach((b:any,i:number)=>{b.stdoutJsonPointer=`/v${i}`;b.sharedProjectionEquivalenceId="all-facts-return-same-boolean";stdout[`v${i}`]=true});const aggregate=aggregateFor(x,[c],C(stdout)),spec=createU4AuthenticatedExtractionSpecification(x.inventory,x.trusted),extraction=createU4EvidenceExtraction(x.inventory,x.calculus,x.sourceRegistry,x.trusted,spec),bridge=createU4ProbeExtractionBridge(x.inventory,x.calculus,x.sourceRegistry,x.trusted,aggregate,extraction,spec);expect(bridge.closureEligible).toBe(true);expect(new Set(bridge.witnesses.map(w=>w.stdoutJsonPointer)).size).toBe(x.inventory.facts.length)});

test("rejects stdout-event mismatch extraction candidate mismatch and contradictory repetitions",()=>{const a=setup(),badEvent:any=structuredClone(a.x.probeBundle);badEvent.materials[0].u3Input.source.events[0].payload=false;expect(()=>createU4ProbeExtractionBridge(a.x.inventory,a.x.calculus,a.x.sourceRegistry,a.x.trusted,badEvent,a.extraction,a.spec)).toThrow();const badExtraction:any=structuredClone(a.extraction);badExtraction.candidates.find((c:any)=>c.provenanceKind==="runtime-probe").propositionJson="false";expect(()=>createU4ProbeExtractionBridge(a.x.inventory,a.x.calculus,a.x.sourceRegistry,a.x.trusted,a.x.probeBundle,badExtraction,a.spec)).toThrow();const r=setup(true),contradiction:any=structuredClone(r.x.probeBundle),second=contradiction.materials[1];second.u3Input.source.events.forEach((e:any)=>e.payload=false);expect(()=>createU4ProbeExtractionBridge(r.x.inventory,r.x.calculus,r.x.sourceRegistry,r.x.trusted,contradiction,r.extraction,r.spec)).toThrow()});

test("accounts one noncredit execution as explicit nonclosure gaps",()=>{const x:any=replayVariant([{caseId:"case",repetition:0,kind:"credited"},{caseId:"case",repetition:1,kind:"noncredit"}]),spec=createU4AuthenticatedExtractionSpecification(x.inventory,x.trusted),extraction=createU4EvidenceExtraction(x.inventory,x.calculus,x.sourceRegistry,x.trusted,spec),bridge=createU4ProbeExtractionBridge(x.inventory,x.calculus,x.sourceRegistry,x.trusted,x.probeBundle,extraction,spec);expect(bridge.closureEligible).toBe(false);expect(bridge.gapWitnessIds).toHaveLength(x.inventory.facts.length);expect(()=>createU4BridgeVerifiedTriangulation(bridge,x.inventory,x.calculus,x.sourceRegistry,x.trusted,x.probeBundle,extraction,spec,{adjudications:[],gapDispositions:[]})).toThrow(/noncredit/)});

test("rejects missing surplus witnesses and a consistently redigested forgery",()=>{for(const attack of [(b:any)=>b.witnesses.pop(),(b:any)=>b.witnesses.push(structuredClone(b.witnesses[0])),(b:any)=>b.witnesses[0].factId="forged"]){const s=setup(),b:any=structuredClone(s.bridge);attack(b);const body={...b};delete body.digest;b.digest=H(`${b.schema}\0${C(body)}`);expect(()=>verifyU4ProbeExtractionBridge(b,...s.args)).toThrow(/replay/)}});

test("rejects material invocation join/run and event closure substitutions",()=>{for(const attack of [(a:any)=>{[a.materials[0].invocationId,a.materials[1].invocationId]=[a.materials[1].invocationId,a.materials[0].invocationId]},(a:any)=>{const [l,r]=a.bundle.executions;[l.join,r.join]=[r.join,l.join]},(a:any)=>a.bundle.executions[0].join.sourceEventIds.pop(),(a:any)=>a.bundle.executions[0].join.sourceEventIds.push("event.foreign"),(a:any)=>a.materials[0].u3Input.source.events.push(structuredClone(a.materials[0].u3Input.source.events[0]))]){const s=setup(true),a:any=structuredClone(s.x.probeBundle);attack(a);expect(()=>createU4ProbeExtractionBridge(s.x.inventory,s.x.calculus,s.x.sourceRegistry,s.x.trusted,a,s.extraction,s.spec)).toThrow()}});

test("qualified certificate rejects omission substitution and consistent redigestion",()=>{const s=setup(),input={adjudications:[],gapDispositions:[]},q:any=createU4BridgeVerifiedTriangulation(s.bridge,...s.args,input);for(const attack of [(v:any)=>v.witnessIds.pop(),(v:any)=>v.bridgeDigest=H("other"),(v:any)=>v.probeBundleDigest=H("other"),(v:any)=>v.triangulationDigest=H("other"),(v:any)=>v.triangulation.digest=H("other")]){const v=structuredClone(q);attack(v);const body={...v};delete body.digest;v.digest=H(`${v.schema}\0${C(body)}`);expect(()=>verifyU4BridgeQualifiedTriangulation(v,s.bridge,...s.args,input)).toThrow(/replay/)}});
