import { describe,expect,test } from "bun:test";
import { createU4EvidenceExtraction,createU4ExtractionLocator,signU4ExtractionSpecification,verifyU4EvidenceExtraction,verifyU4ExtractionSpecification } from "./organization-u4-evidence-extractor";
import {createU4AuthenticatedExtractionSpecification,createU4AuthenticatedTestFixture} from "./organization-u4-test-fixture";
const fixture=()=>createU4AuthenticatedTestFixture();
const specification=createU4AuthenticatedExtractionSpecification;
const resign=(s:any,trusted:any)=>{s.receipt=signU4ExtractionSpecification(trusted.authorityKeys.find((x:any)=>x.authorityId==="a-semantic").keyBase64,s);return s};

describe("U4 independently preregistered extraction",()=>{
 test("extracts the full authenticated denominator with one shared semantic slot across four streams",()=>{const f=fixture(),spec=specification(f.inventory,f.trusted),a=createU4EvidenceExtraction(f.inventory,f.calculus,f.sourceRegistry,f.trusted,spec),b=verifyU4EvidenceExtraction(a,f.inventory,f.calculus,f.sourceRegistry,f.trusted,spec);expect(a).toEqual(b);expect(a.candidates).toHaveLength(f.inventory.facts.length*4);for(const fact of f.inventory.facts){const xs=a.candidates.filter(c=>c.factId===fact.id);expect(new Set(xs.map(x=>x.slotId))).toEqual(new Set(["shape","value"]));expect(xs.filter(x=>x.semanticSlot.comparable)).toHaveLength(3);expect(new Set(xs.map(x=>x.provenanceKind))).toEqual(new Set(["native-schema","official-spec","runtime-probe","source-behavior"]));}expect(new Set(a.candidates.filter(c=>c.slotId==="shape").map(c=>c.propositionJson))).toEqual(new Set(['"boolean"']));expect(new Set(a.candidates.filter(c=>c.slotId==="value").map(c=>c.propositionJson))).toEqual(new Set(['true']));expect(a.candidates.every(c=>c.id.length==="locator.".length+64)).toBe(true);expect(a.candidates.find(c=>c.provenanceKind==="official-spec")?.propositionJson).toBe('true')});
 test("rejects cherry-picking, omission, surplus, and semantic-slot remapping even when re-signed",()=>{const f=fixture(),base=specification(f.inventory,f.trusted);for(const attack of [(s:any)=>s.documents.find((d:any)=>d.provenanceKind==="official-spec").allowedLeafPointers.pop(),(s:any)=>s.locators.pop(),(s:any)=>{s.locators[0].slotId="remapped";const{id:_,...body}=s.locators[0];void _;s.locators[0]=createU4ExtractionLocator(body)}]){const s:any=structuredClone(base);attack(s);resign(s,f.trusted);expect(()=>verifyU4ExtractionSpecification(s,f.inventory,f.calculus,f.sourceRegistry,f.trusted)).toThrow(/preregistration|exhaustiveness|totality/)}const s:any=structuredClone(base),extra={...s.locators[0],slotId:"surplus"};delete extra.id;s.locators.push(createU4ExtractionLocator(extra));resign(s,f.trusted);expect(()=>verifyU4ExtractionSpecification(s,f.inventory,f.calculus,f.sourceRegistry,f.trusted)).toThrow(/preregistration|totality/)});
 test("rejects backdated post-evidence re-specification, cross-source substitution, bad signature, and inventory substitution",()=>{const f=fixture(),base=specification(f.inventory,f.trusted);for(const [attack,re] of [[(s:any)=>s.issuedAt="2026-07-18T00:00:00.000Z",/preregistration|chronology/],[(s:any)=>s.locators[0].sourceId="other",/preregistration|identity/],[(s:any)=>s.receipt="00",/receipt/]] as const){const s:any=structuredClone(base);attack(s);if(!/receipt/.test(re.source))resign(s,f.trusted);expect(()=>verifyU4ExtractionSpecification(s,f.inventory,f.calculus,f.sourceRegistry,f.trusted)).toThrow(re)}const x:any=structuredClone(f.inventory);x.digest=x.digest.replace(/.$/,x.digest.endsWith("0")?"1":"0");expect(()=>createU4EvidenceExtraction(x,f.calculus,f.sourceRegistry,f.trusted,base)).toThrow(/inventory digest/);expect(()=>verifyU4ExtractionSpecification(base,x,f.calculus,f.sourceRegistry,f.trusted)).toThrow(/inventory digest/)});
 test("rejects replay mutation, ambiguous identities, false terminal claims, parser mismatch, and resources",()=>{const f=fixture(),base=specification(f.inventory,f.trusted),out:any=structuredClone(createU4EvidenceExtraction(f.inventory,f.calculus,f.sourceRegistry,f.trusted,base));out.candidates[0].slotId="forged";expect(()=>verifyU4EvidenceExtraction(out,f.inventory,f.calculus,f.sourceRegistry,f.trusted,base)).toThrow(/replay mismatch/);const duplicate:any=structuredClone(base);duplicate.locators.push({...duplicate.locators[0]});resign(duplicate,f.trusted);expect(()=>verifyU4ExtractionSpecification(duplicate,f.inventory,f.calculus,f.sourceRegistry,f.trusted)).toThrow(/preregistration|identity/);const falseTerminal:any=structuredClone(base),i=falseTerminal.locators.findIndex((l:any)=>l.provenanceKind==="runtime-probe"),{id:_,...body}=falseTerminal.locators[i];void _;falseTerminal.locators[i]=createU4ExtractionLocator({...body,mode:"terminal",pointer:null,terminal:"opaque"});resign(falseTerminal,f.trusted);expect(()=>verifyU4ExtractionSpecification(falseTerminal,f.inventory,f.calculus,f.sourceRegistry,f.trusted)).toThrow(/preregistration|mode/);const parser:any=structuredClone(base);parser.documents.find((d:any)=>d.provenanceKind==="runtime-probe").traversal="opaque-terminal-only";resign(parser,f.trusted);expect(()=>verifyU4ExtractionSpecification(parser,f.inventory,f.calculus,f.sourceRegistry,f.trusted)).toThrow(/preregistration|exhaustiveness/);const huge:any=structuredClone(base);huge.locators[0].slotId="x".repeat(1_048_577);expect(()=>verifyU4ExtractionSpecification(huge,f.inventory,f.calculus,f.sourceRegistry,f.trusted)).toThrow(/field bound/);const cyclic:any=structuredClone(base);cyclic.loop=cyclic;expect(()=>verifyU4ExtractionSpecification(cyclic,f.inventory,f.calculus,f.sourceRegistry,f.trusted)).toThrow(/cyclic/) });
});
