import{describe,expect,test}from"bun:test";
import type{PaperclipDeploymentObservation,PaperclipDeploymentState,PaperclipReleasePin}from"./organization-paperclip-deployment";
import type{PaperclipEventState}from"./organization-paperclip-events";
import type{PaperclipProviderState}from"./organization-paperclip-live-provider";
import{DiskPaperclipRuntimeJournalStore,MemoryPaperclipRuntimeJournalStore,PaperclipOrganizationRuntime,type PaperclipRuntimeControl,type PaperclipRuntimeEvents,type PaperclipRuntimeJournalStore,type PaperclipRuntimeLifecycle,type PaperclipRuntimeParticipant,type PaperclipRuntimeTrust}from"./organization-paperclip-runtime";
import{mkdtempSync,rmSync}from"node:fs";import{tmpdir}from"node:os";import{join}from"node:path";
const sha=(x:string)=>`sha256:${x.repeat(64).slice(0,64)}`,pin:PaperclipReleasePin={repository:"https://github.com/paperclipai/paperclip.git",commit:"1".repeat(40),treeDigest:sha("2"),lockDigest:sha("3"),executableDigest:sha("4"),builtExecutableDigest:sha("6"),workspaceBuildDigest:sha("7"),workspaceBuildRoots:["server"],dependencyDigest:sha("5"),runtimeExecutable:"node",runtimeVersion:"22",runtimeDigest:sha("8"),runtimeLauncher:"tsx",runtimeLauncherDigest:sha("9"),runtimeEntrypoint:"server/index.ts"};
const trust:PaperclipRuntimeTrust={sign:d=>`sig:${d}`,verify:(d,s)=>s===`sig:${d}`};
function lifecycleState(overrides:Partial<PaperclipDeploymentState>={}):PaperclipDeploymentState{return{schema:"autonomy.paperclip-deployment-state.v1",deploymentId:"r16",sequence:2,fence:1,lifecycleGeneration:1,restoreEpoch:0,processFence:1,status:"running",pin,digest:sha("6"),signature:"signed",...overrides}}
function observed(overrides:Partial<PaperclipDeploymentObservation>={}):PaperclipDeploymentObservation{return{running:true,pid:42,launchFence:1,endpoint:"http://127.0.0.1:3216",dataDir:"/owned/paperclip",pin,healthy:true,...overrides}}
function provider(epoch=0):PaperclipProviderState{return{schema:"autonomy.paperclip-live-state.v1",deploymentId:"r16",sequence:3+epoch,companyId:"company",eventCursor:null,effects:{},issueByEffect:{},digest:sha("7"),signature:"signed"}}
function eventState(epoch=0):PaperclipEventState{return{schema:"autonomy.paperclip-event-state.v1",deploymentId:"r16",companyId:"company",manifestDigest:sha("8"),serverBinding:{gitSha:pin.commit,version:"0.3.1",baseEndpoint:"http://127.0.0.1:3216"},generation:4+epoch,scanCursor:null,seenCursors:{},contiguousSequence:2,observedHighWater:2,events:{},eventDigests:{},works:{},approvals:{},heartbeats:{},activities:[],timeline:[],gaps:[],reconciliations:[],digest:sha("9"),signature:"signed"}}
class Lifecycle implements PaperclipRuntimeLifecycle{calls:string[]=[];state=lifecycleState();observed=observed();done=new Map<string,PaperclipDeploymentState>();initialize(){this.calls.push("initialize");return this.state}start(id:string){return this.once(id,"start")}inspect(){return{state:this.state,observed:this.observed}}restart(id:string){return this.once(id,"restart")}backup(id:string,path:string){const s=this.once(id,"backup");s.backup={id,path,digest:sha("a"),pin,platform:"test",format:"paperclip-physical-v1"};return s}restore(id:string){return this.once(id,"restore",true)}upgrade(id:string,target:PaperclipReleasePin,_path:string){this.state={...this.once(id,"upgrade"),pin:target};return this.state}rollback(id:string,target=pin){this.state={...this.once(id,"rollback",true),pin:target};return this.state}teardown(id:string){this.once(id,"teardown");this.state={...this.state,status:"destroyed"};this.observed=observed({running:false,healthy:false,pid:null})}private once(id:string,kind:string,epoch=false){const old=this.done.get(id);if(old)return old;this.calls.push(`${kind}:${id}`);this.state=lifecycleState({sequence:this.state.sequence+1,fence:this.state.fence+1,lifecycleGeneration:this.state.lifecycleGeneration+1,restoreEpoch:this.state.restoreEpoch+(epoch?1:0)});this.done.set(id,this.state);return this.state}}
class Control implements PaperclipRuntimeControl{calls:string[]=[];epoch=0;invalid=false;deploy(){this.calls.push("deploy");return provider(this.epoch)}health():ReturnType<PaperclipRuntimeControl["health"]>{return{healthy:!this.invalid,residuals:[]}}exportPortableBackup(){this.calls.push("portable");return{schema:"autonomy.paperclip-portable-backup.v1" as const,sourceCompanyId:"company",native:{rootPath:"backup",manifest:{},files:{a:"b"}},digest:sha("b")}}invalidateCheckpoint(id:string,e:number){this.calls.push(`invalidate:${id}`);this.epoch=e;this.invalid=true}rebuildCheckpoint(id:string,e:number){this.calls.push(`rebuild:${id}`);this.epoch=e;this.invalid=false;return provider(e)}checkpoint(){return{epoch:this.epoch,digest:sha("c")}}cleanupOwned(id:string){this.calls.push(`cleanup:${id}`);return sha("d")}}
class Events implements PaperclipRuntimeEvents{calls:string[]=[];epoch=0;initialize(){this.calls.push("initialize");return eventState(this.epoch)}current(){this.calls.push("current");return eventState(this.epoch)}sync(){return eventState(this.epoch)}invalidateCheckpoint(id:string,e:number){this.calls.push(`invalidate:${id}`);this.epoch=e}rebuildCheckpoint(id:string,e:number){this.calls.push(`rebuild:${id}`);this.epoch=e;return eventState(e)}checkpoint(){return{epoch:this.epoch,digest:sha("e")}}cleanupOwned(id:string){this.calls.push(`cleanup:${id}`);return sha("f")}}
class Participant implements PaperclipRuntimeParticipant{calls:string[]=[];epoch=0;constructor(readonly id:string,readonly kind:"sidecar"|"bridge"|"credential"|"artifact"){}invalidateCheckpoint(id:string,e:number){this.calls.push(`invalidate:${id}`);this.epoch=e}rebuildCheckpoint(id:string,e:number){this.calls.push(`rebuild:${id}`);this.epoch=e;return this.checkpoint()}checkpoint(){return{epoch:this.epoch,digest:sha("1")}}cleanupOwned(id:string){this.calls.push(`cleanup:${id}`);return sha("1")}}
function fixture(input:{store?:PaperclipRuntimeJournalStore;afterEffect?:(id:string,step:string)=>void;lifecycle?:Lifecycle;control?:Control;events?:Events;participants?:Participant[]}={}){const lifecycle=input.lifecycle??new Lifecycle(),control=input.control??new Control(),events=input.events??new Events(),participants=input.participants??[new Participant("sidecar","sidecar"),new Participant("bridge","bridge"),new Participant("credential","credential"),new Participant("artifact","artifact")],store=input.store??new MemoryPaperclipRuntimeJournalStore(),runtime=new PaperclipOrganizationRuntime(lifecycle,control,events,{runtimeId:"r16",trust,store,participants,afterEffect:input.afterEffect});return{runtime,lifecycle,control,events,participants,store}}
describe("R16 durable composite Paperclip runtime",()=>{
 test("prepares and replays a paired portable/native backup with stable identity",()=>{const f=fixture(),one=f.runtime.backup("backup","/owned/backup.tgz"),two=f.runtime.backup("backup","/owned/backup.tgz");expect(one).toEqual(two);expect(one).toMatchObject({operation:"backup",nativeBackupDigest:sha("a"),portableBackupDigest:sha("b")});expect(f.runtime.snapshot().operations.backup).toMatchObject({status:"completed",step:5,requestDigest:expect.any(String)}) ;expect(()=>f.runtime.backup("backup","/other")).toThrow(/equivocation/)});
 test("recovers backup after a crash at every side-effect boundary",()=>{for(const boundary of ["portable-backup","native-backup","provider-current","events-current","pair-digests"]){const store=new MemoryPaperclipRuntimeJournalStore(),lifecycle=new Lifecycle(),control=new Control(),events=new Events();let crash=true;const first=fixture({store,lifecycle,control,events,afterEffect:(_id,step)=>{if(crash&&step===boundary){crash=false;throw new Error(`crash:${step}`)}}});expect(()=>first.runtime.backup(`b-${boundary}`,"/owned/b.tgz")).toThrow(/crash/);const resumed=fixture({store,lifecycle,control,events,participants:first.participants});expect(resumed.runtime.backup(`b-${boundary}`,"/owned/b.tgz").operation).toBe("backup");expect(lifecycle.calls.filter(x=>x.startsWith("backup:")).length).toBeLessThanOrEqual(1)}});
 test("restore and rollback establish epochs and invalidate then rebuild every checkpoint",()=>{const f=fixture();for(const [id,action]of[["restore",()=>f.runtime.restore("restore")],["rollback",()=>f.runtime.rollback("rollback",pin)]]as const){const before=f.runtime.snapshot().epoch,receipt=action();expect(receipt.epoch).toBeGreaterThan(before);expect(f.control.calls).toContain(`invalidate:runtime:${id}:invalidate:control`);expect(f.events.calls).toContain(`rebuild:runtime:${id}:rebuild:events`);for(const p of f.participants){expect(p.calls.some(x=>x.startsWith("invalidate:"))).toBe(true);expect(p.checkpoint().epoch).toBe(receipt.epoch)}expect(f.runtime.health().healthy).toBe(true)}});
 test("reports declared assumptions without confusing them with liveness failure",()=>{const f=fixture();f.control.health=()=>({healthy:true,residuals:[{kind:"assumption",id:"manual-recovery",detail:"operator recovery is weaker"}]});f.runtime.deploy("assumptions");expect(f.runtime.health()).toMatchObject({healthy:true,residuals:[{kind:"assumption",id:"manual-recovery"}]})});
 test("recovers an epoch transition after every journal boundary without accepting stale health",()=>{const steps=["lifecycle-transition","epoch-advance","invalidate:control","invalidate:events","invalidate:sidecar:sidecar","invalidate:bridge:bridge","invalidate:credential:credential","invalidate:artifact:artifact","rebuild:control","rebuild:events","rebuild:sidecar:sidecar","rebuild:bridge:bridge","rebuild:credential:credential","rebuild:artifact:artifact","verify-health"];for(const boundary of steps){const store=new MemoryPaperclipRuntimeJournalStore(),lifecycle=new Lifecycle(),control=new Control(),events=new Events(),participants=[new Participant("sidecar","sidecar"),new Participant("bridge","bridge"),new Participant("credential","credential"),new Participant("artifact","artifact")];let crash=true;const a=fixture({store,lifecycle,control,events,participants,afterEffect:(_id,step)=>{if(crash&&step===boundary){crash=false;throw new Error("crash")}}});expect(()=>a.runtime.restore(`r-${boundary}`)).toThrow("crash");const b=fixture({store,lifecycle,control,events,participants});const receipt=b.runtime.restore(`r-${boundary}`);expect(receipt.epoch).toBe(1);expect(b.runtime.health().healthy).toBe(true)}});
 test("upgrade also rebuilds checkpoints because lifecycle may internally roll back",()=>{const f=fixture(),target={...pin,commit:"b".repeat(40)};expect(f.runtime.upgrade("upgrade",target,"/owned/u.tgz").epoch).toBe(1);expect(f.control.epoch).toBe(1);expect(f.events.epoch).toBe(1)});
 test("teardown cleans only enumerated owned resources idempotently and retains a minimal tombstone",()=>{const f=fixture(),receipt=f.runtime.teardown("destroy");expect(receipt.operation).toBe("teardown");expect(f.control.calls.some(x=>x.startsWith("cleanup:"))).toBe(true);expect(f.events.calls.some(x=>x.startsWith("cleanup:"))).toBe(true);for(const p of f.participants)expect(p.calls.filter(x=>x.startsWith("cleanup:")).length).toBe(1);expect(f.lifecycle.calls.some(x=>x==="teardown:runtime:destroy:teardown")).toBe(true);const state=f.runtime.snapshot();expect(state.status).toBe("tombstone");expect(Object.keys(state.operations)).toEqual([]);expect(state.tombstone).toMatchObject({operationId:"destroy",receiptDigest:receipt.digest,receipt});expect(f.runtime.teardown("destroy")).toEqual(receipt);expect(()=>f.runtime.deploy("late")).toThrow(/tombstoned/)});
 test("replays upgrade, rollback, and teardown after every operation-specific crash boundary",()=>{const epochSteps=["lifecycle-transition","epoch-advance","invalidate:control","invalidate:events","invalidate:sidecar:sidecar","invalidate:bridge:bridge","invalidate:credential:credential","invalidate:artifact:artifact","rebuild:control","rebuild:events","rebuild:sidecar:sidecar","rebuild:bridge:bridge","rebuild:credential:credential","rebuild:artifact:artifact","verify-health"];for(const kind of ["upgrade","rollback"]as const)for(const boundary of epochSteps){const store=new MemoryPaperclipRuntimeJournalStore(),lifecycle=new Lifecycle(),control=new Control(),events=new Events(),participants=[new Participant("sidecar","sidecar"),new Participant("bridge","bridge"),new Participant("credential","credential"),new Participant("artifact","artifact")];let crash=true;const a=fixture({store,lifecycle,control,events,participants,afterEffect:(_id,step)=>{if(crash&&step===boundary){crash=false;throw Error("crash")}}});const invoke=(r:PaperclipOrganizationRuntime)=>kind==="upgrade"?r.upgrade(`${kind}-${boundary}`,{...pin,commit:"b".repeat(40)},"/owned/u"):r.rollback(`${kind}-${boundary}`,pin);expect(()=>invoke(a.runtime)).toThrow("crash");expect(invoke(fixture({store,lifecycle,control,events,participants}).runtime).operation).toBe(kind)}const teardownSteps=["cleanup:sidecar:sidecar","cleanup:bridge:bridge","cleanup:credential:credential","cleanup:artifact:artifact","cleanup:events","cleanup:control","lifecycle-teardown","tombstone"];for(const boundary of teardownSteps){const store=new MemoryPaperclipRuntimeJournalStore(),lifecycle=new Lifecycle(),control=new Control(),events=new Events(),participants=[new Participant("sidecar","sidecar"),new Participant("bridge","bridge"),new Participant("credential","credential"),new Participant("artifact","artifact")];let crash=true;const a=fixture({store,lifecycle,control,events,participants,afterEffect:(_id,step)=>{if(crash&&step===boundary){crash=false;throw Error("crash")}}});expect(()=>a.runtime.teardown(`t-${boundary}`)).toThrow("crash");expect(fixture({store,lifecycle,control,events,participants}).runtime.teardown(`t-${boundary}`).operation).toBe("teardown")}});
 test("reconstructs a completed operation through an independent atomic disk journal instance",()=>{const root=mkdtempSync(join(tmpdir(),"oa-r16-runtime-"));try{const lifecycle=new Lifecycle(),control=new Control(),events=new Events(),participants=[new Participant("sidecar","sidecar")],one=fixture({store:new DiskPaperclipRuntimeJournalStore(root),lifecycle,control,events,participants}),receipt=one.runtime.backup("disk-backup","/owned/disk");const before=lifecycle.calls.length,two=fixture({store:new DiskPaperclipRuntimeJournalStore(root),lifecycle,control,events,participants});expect(two.runtime.backup("disk-backup","/owned/disk")).toEqual(receipt);expect(lifecycle.calls.length).toBe(before)}finally{rmSync(root,{recursive:true,force:true})}});
 test("rejects signed journal tampering before replay",()=>{const inner=new MemoryPaperclipRuntimeJournalStore(),f=fixture({store:inner});f.runtime.backup("b","/owned/b");const hostile:PaperclipRuntimeJournalStore={load(id){const s=inner.load(id)!;s.epoch=999;return s},compareAndSwap(){return false}};expect(()=>fixture({store:hostile})).toThrow(/authentication/)})
});
