// Emit autonomy.ir.v1 → a ztrack profile (profile.json + scheduler/schedule.json).
// Substrate = local-loop; harness conventions (skill install paths, run-agent, run.mjs loop)
// are supplied here by the adapter, NOT carried in the IR.
import type { AutonomyIR, CompileOutput, IRWorkflow } from './autonomy-ir';
import type { ZtrackProfile, ZtrackSchedule } from './autonomy-ingest-profile';

/** A `run:` workflow copies its existing script; a `launch:` workflow gets a generated launcher. */
export function workflowScriptPath(w: IRWorkflow, name: string): { path: string; generated: boolean } {
  if (w.run) return { path: w.run, generated: false };
  return { path: `profiles/${name}/scheduler/scripts/${w.name}.mjs`, generated: true };
}

// Inverse of secondsToCron for the simple every-N-minutes cron form the local loop produces.
export function cronToSeconds(cron: string): number {
  const m = /^\*\/(\d+) \* \* \* \*$/.exec(cron.trim());
  return m ? Number(m[1]) * 60 : 900;
}

export function emitProfile(
  ir: AutonomyIR,
  opts: { name?: string } = {},
): { profile: ZtrackProfile; schedule: ZtrackSchedule } {
  const name = opts.name ?? 'app';

  const skills: NonNullable<ZtrackProfile['skills']> = {};
  for (const [role, agent] of Object.entries(ir.agents)) {
    skills[role] = {
      name: `ztrack-${name}-${role}`,
      source: `profiles/${name}/skills/${agent.skill}/SKILL.md`,
      codex: `.agents/skills/ztrack-${name}-${role}/SKILL.md`,
      claude: `.claude/skills/ztrack-${name}-${role}/SKILL.md`,
    };
  }

  // resources split back into the two buckets ztrack distinguishes.
  const readme = ir.resources.find((r) => /readme\.md$/i.test(r));
  const standards = ir.resources.filter((r) => !/readme\.md$/i.test(r));

  // per-agent concurrency → WIP caps.
  const wip: { maxInProgress?: number; maxInReview?: number } = {};
  if (ir.agents.develop) wip.maxInProgress = ir.agents.develop.maxConcurrent;
  if (ir.agents.review) wip.maxInReview = ir.agents.review.maxConcurrent;

  const policy: NonNullable<ZtrackProfile['policy']> = { wip };
  const box = ir.policy.box as Record<string, unknown>;
  if (Array.isArray(box.humanRequiredPaths)) policy.humanRequiredPaths = box.humanRequiredPaths as string[];
  if (Array.isArray(box.humanRequiredTopics)) policy.humanRequiredTopics = box.humanRequiredTopics as string[];

  const scriptPaths = ir.workflows.map((w) => workflowScriptPath(w, name).path);
  const intervalSeconds = ir.workflows[0] ? cronToSeconds(ir.workflows[0].cron) : 900;

  const profile: ZtrackProfile = {
    schema: 'ztrack.profile.v1',
    name,
    preset: name,
    readme,
    scheduler: {
      schedule: `profiles/${name}/scheduler/schedule.json`,
      scripts: [...scriptPaths, `profiles/${name}/scheduler/scripts/run.mjs`],
    },
    scripts: { runAgent: `profiles/${name}/scripts/run-agent.mjs` },
    skills,
    standards,
    policy,
  };

  const schedule: ZtrackSchedule = {
    intervalSeconds,
    env: {},
    scripts: scriptPaths.map((p) => `node ${p}`),
  };

  return { profile, schedule };
}

// --- Full file-tree compile (local-loop substrate, claude+codex harnesses) ---
// Driver/launcher contents are stubs here; the real local driver ships run.mjs / run-agent.mjs.
const LOOP_DRIVER = '// generated by the local-loop driver — reads schedule.json and runs each script on interval\n';
const RUN_AGENT_DRIVER = '// generated by the local-loop driver — launches an agent session (e.g. via termfleet)\n';
const launcherScript = (agent: string) =>
  `// generated launcher — sets ZTRACK_AGENT=${agent} and invokes run-agent\n`;

export function compileLocal(ir: AutonomyIR, opts: { name?: string } = {}): CompileOutput {
  const name = opts.name ?? 'app';
  const base = `profiles/${name}`;
  const { profile, schedule } = emitProfile(ir, { name });

  const generated: Record<string, string> = {
    [`${base}/profile.json`]: JSON.stringify(profile, null, 2),
    [`${base}/scheduler/schedule.json`]: JSON.stringify(schedule, null, 2),
    [`${base}/scheduler/scripts/run.mjs`]: LOOP_DRIVER,
    [`${base}/scripts/run-agent.mjs`]: RUN_AGENT_DRIVER,
  };
  const copies: Array<{ from: string; to: string }> = [];

  // workflows: run → copy the script; launch → generate a launcher
  for (const wf of ir.workflows) {
    const { path, generated: isGen } = workflowScriptPath(wf, name);
    const dest = `${base}/scheduler/scripts/${wf.name}.mjs`;
    if (isGen) generated[dest] = launcherScript(wf.launch as string);
    else copies.push({ from: path, to: dest });
  }

  // skills: source folder in the profile bundle + the two harness installs
  for (const [role, agent] of Object.entries(ir.agents)) {
    const src = `skills/${agent.skill}/SKILL.md`;
    copies.push({ from: src, to: `${base}/skills/${agent.skill}/SKILL.md` });
    copies.push({ from: src, to: `.claude/skills/ztrack-${name}-${role}/SKILL.md` });
    copies.push({ from: src, to: `.agents/skills/ztrack-${name}-${role}/SKILL.md` });
  }

  // resources: readme → README.md; everything else → standards/<basename>
  for (const r of ir.resources) {
    const leaf = r.split('/').pop() ?? r;
    if (/readme\.md$/i.test(r)) copies.push({ from: r, to: `${base}/README.md` });
    else copies.push({ from: r, to: `${base}/standards/${leaf}` });
  }

  return { generated, copies };
}
