#!/usr/bin/env bun
import {createHash,sign as cryptoSign,verify} from 'node:crypto';
import {mkdtemp,mkdir,readFile,rm,writeFile} from 'node:fs/promises';
import {spawnSync} from 'node:child_process';
import {tmpdir} from 'node:os';
import {dirname,join,resolve} from 'node:path';
import {canonicalSemanticJson} from '../packages/core/src/organization-canonical';
import {bindLiveDeploymentInstance,buildDeploymentBundle,promoteDeploymentBundle,signDeploymentBundle,verifyDeploymentBundle,verifyLiveDeploymentInstance,type DeploymentBundleInput} from '../packages/core/src/organization-deployment-bundle';
import {deriveAtomicObligations} from '../packages/core/src/organization-solver';
import {INITIAL_COMPONENT_CATALOG} from '../packages/core/src/organization-component-catalog';
import {createMigrationCutoverController,discoverRealProfileMigrationCorpus,dualCompileMigrationCorpus,signMigrationCutoverEvidence} from '../packages/core/src/organization-migration-cutover';

const digest=(value:unknown)=>`sha256:${createHash('sha256').update(canonicalSemanticJson(value)).digest('hex')}`;
const sha256=(value:string|Uint8Array)=>createHash('sha256').update(value).digest('hex'),sha1=(value:string|Uint8Array)=>createHash('sha1').update(value).digest('hex');
const outputPath='docs/evidence/r9-repository-dogfood.json',publicKeyPath='docs/trust/r9-observer-public.pem';
const discovered=await discoverRealProfileMigrationCorpus({repositoryRoot:'.',profilesDirectory:'profiles'});
const report=await dualCompileMigrationCorpus(discovered.entries,{dispositions:discovered.entries.flatMap(discovered.dispositionsFor),compileV1:discovered.compileV1,compileV2:discovered.compileV2,expectedCompilerDigests:{v1:discovered.legacyCompiler.digest,v2:discovered.v2Compiler.digest},executionVerifier:discovered.executionVerifier});report.assertReadyForShadow();
const entry=discovered.entries.find(candidate=>candidate.id==='self-driving');if(!entry)throw new Error('canonical self-driving profile is absent');
const compiled=await discovered.compileV2(entry) as any,local=compiled.rawOutputs.local,organizationDigest=digest(compiled.organization),nativeOutputDigest=digest(compiled.rawOutputs),certificateDigest=digest(compiled.certificate),instanceId='open-autonomy-self-driving-r9',runtimeDigest=digest(local.generated['scripts/runner.ts']);
const publicKey=await readFile(publicKeyPath,'utf8'),verifyObservation=(observation:any)=>{const bytes=Buffer.from(canonicalSemanticJson(observation.statement));return observation.digest===`sha256:${createHash('sha256').update(bytes).digest('hex')}`&&observation.signer==='repository-r9-observer'&&observation.algorithm==='Ed25519'&&verify(null,bytes,publicKey,Buffer.from(observation.signature,'base64'));};
const canonicalOrganization=JSON.parse(canonicalSemanticJson(compiled.organization)),nativeBytes=new TextEncoder().encode(canonicalSemanticJson({nativeOutputDigest,targets:Object.keys(compiled.rawOutputs).sort()})),manifestContent=INITIAL_COMPONENT_CATALOG['coding-worker-runtime']!,policyContent={id:'v1-profile',rule:canonicalOrganization.policies['v1-profile'].rule},compilerContent={id:discovered.v2Compiler.id,version:'2',generation:discovered.v2Compiler.generation,sourceDigests:discovered.v2Compiler.sourceDigests,catalogDigest:discovered.v2Compiler.catalogDigest,runtimeAbi:discovered.v2Compiler.runtimeAbi},requiredObligations=deriveAtomicObligations(canonicalOrganization).map(value=>value.id),manifestDigest=digest(manifestContent),policyDigest=digest(policyContent),compilerDigest=digest(compilerContent),lock={schema:'autonomy.module-lock.v1' as const,modules:[]};
const bundleInput:DeploymentBundleInput={schema:'autonomy.deployment-bundle-input.v1',canonicalOrganization:compiled.organization,organizationDigest,lock,compiler:{id:compilerContent.id,version:'2',digest:compilerDigest,content:compilerContent,options:{target:'local'}},requiredObligations,selectedManifests:[{id:manifestContent.id,version:manifestContent.version,digest:manifestDigest,content:manifestContent}],loweringCertificates:[{id:'r9-self-driving-local',target:'local',inputDigest:organizationDigest,outputDigest:`sha256:${sha256(nativeBytes)}`,sourceObligations:requiredObligations}],nativeArtifacts:[{path:'targets/local/installation.json',mediaType:'application/json',bytes:nativeBytes}],policies:[{id:'v1-profile',digest:policyDigest,content:policyContent}],secretReferences:[],migrations:[],healthProbes:[{id:'runtime-observed',kind:'command',target:'maintainer',timeoutMs:30000,success:{exitCode:0}}],rollbackPlan:{id:'r9-rollback',triggerObservations:['runtime-unhealthy'],steps:[{operation:'restore',artifact:'targets/local/installation.json'}]},expectedObservations:[{id:'runtime-healthy',subject:'maintainer',predicate:'health',equals:'ready',withinMs:30000},{id:'runtime-unhealthy',subject:'maintainer',predicate:'health',equals:'failed',withinMs:30000}],sbom:{spdxVersion:'SPDX-2.3',SPDXID:'SPDXRef-DOCUMENT',dataLicense:'CC0-1.0',name:'open-autonomy-r9-self-driving',documentNamespace:'https://open-autonomy.example/spdx/r9-self-driving',creationInfo:{created:'2026-07-15T00:00:00Z',creators:['Tool: open-autonomy-r9']},packages:[{name:'open-autonomy-self-driving-runtime',versionInfo:'2',downloadLocation:'NOASSERTION',SPDXID:'SPDXRef-Package-runtime',checksums:[{algorithm:'SHA256',checksumValue:sha256(nativeBytes)}],packageVerificationCode:{packageVerificationCodeValue:sha1(sha1(nativeBytes))}}],files:[{fileName:'targets/local/installation.json',SPDXID:'SPDXRef-File-runtime',checksums:[{algorithm:'SHA256',checksumValue:sha256(nativeBytes)}]}],relationships:[{spdxElementId:'SPDXRef-Package-runtime',relationshipType:'CONTAINS',relatedSpdxElement:'SPDXRef-File-runtime'}]},provenance:{_type:'https://in-toto.io/Statement/v1',subject:[{name:'targets/local/installation.json',digest:{sha256:sha256(nativeBytes)}}],predicateType:'https://slsa.dev/provenance/v1',predicate:{buildDefinition:{buildType:'https://open-autonomy.example/build-types/deployment-bundle/v1',externalParameters:{organizationDigest,lockDigest:digest(lock),compilerDigest},resolvedDependencies:[{uri:`component:${manifestContent.id}@${manifestContent.version}`,digest:{sha256:manifestDigest.slice(7)}},{uri:'policy:v1-profile',digest:{sha256:policyDigest.slice(7)}},{uri:`compiler:${compilerContent.id}@2`,digest:{sha256:compilerDigest.slice(7)}}]},runDetails:{builder:{id:'https://open-autonomy.example/builders/r9'},metadata:{invocationId:'r9-self-driving',startedOn:'2026-07-15T00:00:00Z',finishedOn:'2026-07-15T00:01:00Z'}}}}};
bundleInput.secretReferences.push({id:'runtime-observer-key',provider:'vault',locator:'kv/open-autonomy/r9-observer'});bundleInput.migrations.push({id:'r9-state-cutover',from:'v1',to:'v2',artifactPath:'targets/local/installation.json',healthGate:'runtime-observed',rollback:'r9-rollback'});
bundleInput.canonicalOrganization=canonicalOrganization;
const unsignedBundle=buildDeploymentBundle(bundleInput),bundleDigest=unsignedBundle.digest;
if(process.argv.includes('--check')){
  const evidence=JSON.parse(await readFile(outputPath,'utf8')),envelope={...evidence.deployment.envelope,bundle:{...evidence.deployment.envelope.bundle,bytes:Uint8Array.from(Buffer.from(evidence.deployment.envelope.bundle.bytesBase64,'base64'))}};delete (envelope.bundle as any).bytesBase64;
  const policy={requiredSigners:['repository-r9-observer'],trustedSigners:{'repository-r9-observer':{algorithms:['Ed25519'],verify:(value:string,signature:string)=>verify(null,Buffer.from(value),publicKey,Buffer.from(signature,'base64'))}},rejectUnknownArtifacts:true,rejectSecrets:true};
  if(!verifyDeploymentBundle(envelope as any,policy).valid||!verifyLiveDeploymentInstance(evidence.deployment.instance,evidence.deployment.release,envelope as any,policy).valid)throw new Error('R8 deployment/live-instance verification failed');
  const {digest:recordedDigest,...payload}=evidence;if(recordedDigest!==digest(payload))throw new Error('top-level evidence digest is invalid');
  if(!Array.isArray(evidence.externalObservations)||!evidence.externalObservations.every(verifyObservation))throw new Error('external runtime observation signature is invalid');
  for(const [name,actual] of Object.entries({sourceDigest:entry.provenance.sourceDigest,compilerDigest:discovered.v2Compiler.digest,organizationDigest,certificateDigest,nativeOutputDigest,bundleDigest,releaseDigest:evidence.deployment.release.releaseDigest,instanceId,runtimeDigest,differentialReportDigest:report.digest}))if(evidence.bindings?.[name]!==actual)throw new Error(`${outputPath} has stale ${name}`);
  const identity={subjectBundleDigest:bundleDigest,releaseDigest:evidence.deployment.release.releaseDigest,instanceId,compilerDigest:evidence.deployment.instance.compilerDigest,runtimeDigest,organizationDigest};for(const observation of evidence.externalObservations)for(const [field,value] of Object.entries(identity))if(observation.statement[field]!==value)throw new Error(`signed observation has stale ${field}`);
  const controllerTrust={trustedSigners:{'repository-r9-observer':{algorithms:['Ed25519'],verify:(value:string,signature:string)=>verify(null,Buffer.from(value),publicKey,Buffer.from(signature,'base64'))}}};let replay=createMigrationCutoverController({corpusReport:report,initialRuntime:'v1',ownedState:entry.source.ownedState,publicCommands:Object.values(compiled.commandSurface).flatMap((surface:any)=>surface.agentRunnerCli)});for(const stage of ['shadow','canary','cutover'] as const)replay=replay.transition({to:stage,evidence:evidence.cutover[stage]},controllerTrust);if(canonicalSemanticJson(replay.snapshot())!==canonicalSemanticJson(evidence.cutover.checkpoint))throw new Error('cutover checkpoint or signature chain does not replay');
  if(evidence.cutover.checkpoint.state.activeRuntime!=='v2'||!evidence.externalObservations.some((value:any)=>value.statement.kind==='process')||!evidence.externalObservations.some((value:any)=>value.statement.kind==='effect'&&value.statement.workId==='r9-canonical-live-effect'))throw new Error('canonical v2 runtime process or effect is absent');process.exit(0);
}
const privateKey=process.env.R9_OBSERVER_PRIVATE_KEY;if(!privateKey)throw new Error('R9_OBSERVER_PRIVATE_KEY is required to capture new live evidence');
const privateKeyBytes=await readFile(privateKey),deploymentSigner={id:'repository-r9-observer',algorithm:'Ed25519',sign:(value:string)=>cryptoSign(null,Buffer.from(value),privateKeyBytes).toString('base64')},deploymentTrust={requiredSigners:[deploymentSigner.id],trustedSigners:{[deploymentSigner.id]:{algorithms:[deploymentSigner.algorithm],verify:(value:string,signature:string)=>verify(null,Buffer.from(value),publicKey,Buffer.from(signature,'base64'))}},rejectUnknownArtifacts:true,rejectSecrets:true},envelope=signDeploymentBundle(unsignedBundle,deploymentSigner),release=promoteDeploymentBundle(envelope,deploymentTrust,{environment:'repository-canary',bindings:{'secret:runtime-observer-key':'vault://repository/r9-observer'},signers:[deploymentSigner]}),liveInstance=bindLiveDeploymentInstance(release,envelope,deploymentTrust,{instanceId,tenant:'open-autonomy',observedAt:'2026-07-15T12:00:00Z',signers:[deploymentSigner]}),releaseDigest=release.releaseDigest;
const install=await mkdtemp(join(tmpdir(),'open-autonomy-r9-'));
try{for(const [path,content] of Object.entries(local.generated as Record<string,string>)){await mkdir(dirname(join(install,path)),{recursive:true});await writeFile(join(install,path),content);}for(const copy of local.copies as Array<{from:string;to:string}>){await mkdir(dirname(join(install,copy.to)),{recursive:true});await writeFile(join(install,copy.to),await readFile(join(resolve('profiles/self-driving'),copy.from)));}
  const run=spawnSync(process.execPath,['scripts/runner.ts','launch','maintainer','--DOGFOOD_RUN_ID','r9-canonical-live-effect','--completion','externally-observed'],{cwd:install,encoding:'utf8',env:{...process.env,AUTONOMY_HUMAN_ENGAGE_CMD:''}});if(run.status!==0)throw new Error(`emitted runtime failed: ${run.stderr}`);
  const observer=spawnSync(process.execPath,[resolve('scripts/runtime-r9-observer.ts'),join(install,'.open-autonomy/runner-state/human-sessions.json')],{encoding:'utf8',env:{...process.env,R9_OBSERVER_PRIVATE_KEY:privateKey,R9_DOGFOOD_RUN_ID:'r9-canonical-live-effect',R9_BUNDLE_DIGEST:bundleDigest,R9_RELEASE_DIGEST:releaseDigest,R9_INSTANCE_ID:instanceId,R9_COMPILER_DIGEST:compilerDigest,R9_RUNTIME_DIGEST:runtimeDigest,R9_ORGANIZATION_DIGEST:organizationDigest}});if(observer.status!==0)throw new Error(`external observer failed: ${observer.stderr}`);const externalObservations=JSON.parse(observer.stdout.trim());if(!Array.isArray(externalObservations)||!externalObservations.every(verifyObservation))throw new Error('external observations did not verify');
  const signer={signer:'repository-r9-observer',algorithm:'Ed25519',sign:(value:string)=>cryptoSign(null,Buffer.from(value),privateKeyBytes).toString('base64')},trust={trustedSigners:{'repository-r9-observer':{algorithms:[signer.algorithm],verify:(value:string,signature:string)=>verify(null,Buffer.from(value),publicKey,Buffer.from(signature,'base64'))}}};let controller=createMigrationCutoverController({corpusReport:report,initialRuntime:'v1',ownedState:entry.source.ownedState,publicCommands:Object.values(compiled.commandSurface).flatMap((surface:any)=>surface.agentRunnerCli)});const advance=(to:'shadow'|'canary'|'cutover',payload:Record<string,unknown>)=>{const signed=signMigrationCutoverEvidence({id:`r9:${to}`,corpusDigest:report.corpusDigest,priorStateDigest:controller.stateDigest,from:controller.state.phase,to,payload},signer);controller=controller.transition({to,evidence:signed},trust);return signed;};const shadow=advance('shadow',{differentialReport:report.digest}),canary=advance('canary',{shadowTrace:digest(shadow),fraction:0.1}),cutover=advance('cutover',{canaryTrace:digest(canary),rollbackDrill:'packages/core/src/organization-migration-cutover.test.ts:post-cutover-replay'});
  const {bytes:bundleBytes,...bundleWithoutBytes}=envelope.bundle,serializedEnvelope={...envelope,bundle:{...bundleWithoutBytes,bytesBase64:Buffer.from(bundleBytes).toString('base64')}},bindings={sourceDigest:entry.provenance.sourceDigest,compilerDigest:discovered.v2Compiler.digest,organizationDigest,certificateDigest,nativeOutputDigest,bundleDigest,releaseDigest,instanceId,runtimeDigest,differentialReportDigest:report.digest},evidence={schema:'autonomy.r9-repository-dogfood-evidence.v1',repository:'open-autonomy',profile:{id:entry.id,path:entry.provenance.sourcePath},bindings,deployment:{envelope:serializedEnvelope,release,instance:liveInstance},externalObservations,differentialReport:{profiles:report.profiles,equivalent:report.equivalent,untriagedResiduals:report.untriagedResiduals,digest:report.digest,compilerProvenance:report.compilerProvenance},cutover:{shadow,canary,cutover,checkpoint:controller.snapshot()}};await writeFile(outputPath,`${JSON.stringify({...evidence,digest:digest(evidence)},null,2)}\n`);
}finally{await rm(install,{recursive:true,force:true});}
