#!/usr/bin/env bun
import { writeFileSync } from 'node:fs';
import { ORGANIZATION_SEMANTIC_COVERAGE } from '../packages/core/src/organization-coverage';

const rows = ORGANIZATION_SEMANTIC_COVERAGE.map((entry) =>
  `| \`${entry.interface}\` | ${entry.fields.map((field) => `\`${field}\``).join(', ')} | ${entry.domain} | ${entry.maturity} | ${entry.denotation} |`,
);
const text = `# Organization IR field semantics\n\n` +
  `Generated by \`bun scripts/generate-organization-field-semantics.ts\`; do not edit by hand. The maturity column ` +
  `describes current implementation coverage, not normative optionality or assurance.\n\n` +
  `| Interface | Fields | Domain | Maturity | Denotation |\n|---|---|---|---|---|\n${rows.join('\n')}\n`;
writeFileSync('docs/ORGANIZATION-IR-FIELD-SEMANTICS.md', text);
