import {createNativeLifter,defineAdapter,defineLoweringPass,defineMigration,defineProvider,type ComponentManifestV2,type OperationResult} from '@open-autonomy/sdk';
const evidence={assurance:'conformance-tested' as const,source:{uri:'sdk:test/toy'}};
const manifest:ComponentManifestV2={schema:'autonomy.component.v2',id:'toy-substrate',version:'1.0.0',configuration:{id:'toy.config',version:'1'},facets:{work:{facet:'work',operations:['create','read','transition'],interface:'toy',evidence},event:{facet:'event',operations:['observe'],interface:'toy',evidence}},interfaces:{toy:{id:'toy',version:'1',transport:'function',commands:{create:{id:'toy.create',version:'1'}},observations:{event:{id:'toy.event',version:'1'}}}},state:[{state:'work',authority:'authoritative',consistency:'strong',delivery:'at-least-once',ordering:'per-key',idempotency:'enforced',recovery:'automatic',identity:'stable',evidence}],trust:[{principal:'toy-worker',zone:'toy',enforcedBy:'process boundary',evidence}],failure:{detection:['health probe','operation error'],healthCriterion:'read-after-write succeeds',recovery:['restart and replay'],upgrade:'health before and after',rollback:'restore prior snapshot',evidence},topology:{mode:'standalone',minimumInstances:1,maximumInstances:1,isolation:'process',evidence}};
const result=(criterion:string,status:OperationResult['status']='succeeded'):OperationResult=>({status,criterion,evidence:{toy:'observed'},recoveryRequired:status==='failed'});
const adapter=defineAdapter({schema:'autonomy.adapter.v1',id:'toy-work-bridge',version:'1',direction:'bridge',from:{id:'toy.work',version:'1'},to:{id:'autonomy.work',version:'2'},interfaceMappings:[{from:'toy',to:'portable-work'}],identity:'preserved',causality:'mapped',retry:'translated',conflicts:'serialized',preconditions:['authenticated native request'],postconditions:['portable work identity retained'],losses:['native display color'],reversible:false,evidence});
const pass=defineLoweringPass({id:'toy-emit',version:'1',operation:'emit',input:'execution',output:'native',inputKind:'execution-plan',outputKind:'native-plan',capabilities:{ambient:[],readableInputs:['execution-plan'],writableOutputs:['native-plan']},implementation:'organization.emit'},{sourceObligations:['preserve work identity','emit lifecycle evidence'],losses:['native display color']});
const lifter=createNativeLifter({id:'toy-event-lifter',provider:'toy-substrate',schema:'toy.event',version:'1',portableTypes:['work.started'],map:o=>({schema:'autonomy.event.v2',reducer:'work',id:o.id,type:'work.started',at:o.at,issuer:'toy-substrate',parents:[],epistemic:'observation',provenance:[o.provenance]})});
const migration=defineMigration({id:'toy-config-1-to-2',kind:'component',from:'1',to:'2',migrate(document){const source=document as Record<string,unknown>;return{document:{...source,schemaVersion:'2'},dispositions:[{source:'/',target:'/',disposition:'preserved'},{source:'/schemaVersion',target:'/schemaVersion',disposition:'transformed'}]};}});
export const TOY_PROVIDER=defineProvider({id:'toy-substrate',version:'1.0.0',manifest,adapters:[adapter],passes:[pass],lifters:[lifter],migrations:[migration],health:{check:'health',healthyWhen:'read-after-write',timeoutMs:1000,intervalMs:5000},lifecycle:{provision:'create store',upgrade:'replace version',rollback:'restore snapshot',teardown:'delete store',upgradePrecondition:'healthy',rollbackCriterion:'post-upgrade unhealthy',teardownCriterion:'store absent'},operations:{async provision(){return result('read-after-write');},async health(){return result('read-after-write');},async upgrade(){return result('healthy');},async rollback(){return result('post-upgrade unhealthy');},async teardown(){return result('store absent');}},conformance:{levels:['component','substrate','live-runtime'],operations:['component.describe','runtime.health','substrate.roundtrip'],async invoke(operation){const output=operation==='component.describe'?{id:'worker',facets:['execution']}:operation==='runtime.health'?{healthy:true}:operation==='substrate.roundtrip'?{launched:true,observed:true,cancelled:true}:undefined;if(!output)throw new Error(`unsupported operation '${operation}'`);const evidenceKey=operation==='component.describe'?'component-manifest':operation==='runtime.health'?'live-observation':'lifecycle-transcript';return{output,evidence:{[evidenceKey]:'toy:observed'}};}}});
